### ISSUE TITLE
Middleware Suggestion

### ISSUE THREAD

**Issue by JustJeremy** [archtechx/tenancy#101]
On database selection why not have this actually in your host (framework) database then in your middleware grab the connection info and use that?  You can base the connection on either url/route or tenant name.  With this method you could not only do subdomains, fqdn, and sub folder style tenants.  When I was doing my implementation of a mult-tenant system for Laravel this worked pretty slick.  
I did a admin interface for the tenant system on the host that you can set up new tenants at will and it would create a boilerplate for each new tenant, creation of database connection, model, controller, tenant admin page, generic route, dynamic menu, pages system and new route folder to keep all routes separate from the host and other tenants.
Just a suggestion. Cheers!

**Comment by stancl** [comment]
Hi.

> On database selection why not have this actually in your host (framework) database then in your middleware grab the connection info and use that? You can base the connection on either url/route or tenant name. With this method you could not only do subdomains, fqdn, and sub folder style tenants.

You mean storing information about a database connection in the tenant storage?

**Comment by JustJeremy** [comment]
You would store all database connection info in your tenant table on the host database. Use a middleware on the route to determine all the info you need to connect to another database.  You would need to create a new named connection like "tenant" in your database config file that basically has blank values for driver, host, database, un, pass and then you can set the info from database as values in that connection. 
You wouldn't be limited to using subdomains/domains.  You could then use urls like https://host.example/tenant-1, https://host.example/tenant-2, https://tenant3.host.example, and https://tenant4.example  
Also, you can have multi connections per tenant. So if you are doing a ENV of local/staging/qa/production you can base the connection on the env too.

**Comment by stancl** [comment]
I'm not sure what you mean right now.

The database connection is created using the `tenancy.database.based_on`. If you want to use a custom DB connection for a specific tenant, you can do that with the new event system (docs coming soon).

> You wouldn't be limited to using subdomains/domains.

What's the relationship between database connections and subdomains etc? Sorry, I don't see what you mean right now.
