### ISSUE TITLE
PostgreSQL Database creation error.

### ISSUE THREAD

**Issue by hakanersu** [archtechx/tenancy#112]
#### Describe the bug
When creating tenant whit postgresql database driver im getting ```syntax error at or near "-"``` error. 

When i update PostgreSQLDatabaseManager.php with below my problem fixed;

```php
public function createDatabase(string $name): bool
{
    return DB::statement("CREATE DATABASE \"$name\" WITH TEMPLATE=template0");
}
```

#### Steps to reproduce
```
tenant()->create('tenant-2.myapp.localhost')
```

#### Expected behavior
Creating new tenant

#### Your setup
 - Laravel version 6.0
 - stancl/tenancy version custom fork
 - Storage driver PostgreSQL

**Comment by stancl** [comment]
Hi.

Thanks for reporting this. Will be fixed in 1.8.0.

**Comment by hakanersu** [comment]
By the way, it's work great i migrate my medium size project to your package in minutes.

Thank you.

**Comment by stancl** [comment]
Glad to hear that :)
