### ISSUE TITLE
Store original default DB connection somewhere and make it accessible

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#116]
This could make installation and integration easier.

**Comment by dukenst2006** [comment]
That's will be a cool feature, cause i have some problem installing the 1.8 version, i have this error: InvalidArgumentException Database [multidbsaas] not configured, when i try to visit the home page that's worked well before installing this package. where 'multidbsaas' is the default central database and default DB connection setup on the .env file.
getting stuck there. 
![example](https://user-images.githubusercontent.com/7965394/64476272-e2922080-d15a-11e9-9476-bf23f7b38ba1.jpg)

**Comment by stancl** [comment]
@dukenst2006 Can you share your `config/database.php` and `config/tenancy.php` files?

**Comment by dukenst2006** [comment]
Ok, no problem
`config/database.php`
`<?php

use Illuminate\Support\Str;

return [

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => env('DB_CONNECTION', 'mysql'),

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DATABASE_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],

        'sqlite_testing' => [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ],

        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],

        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer body of commands than a typical key-value system
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'client' => env('REDIS_CLIENT', 'predis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'predis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_CACHE_DB', 1),
        ],

    ],

];
`

`config/tenancy.php`

`<?php

declare(strict_types=1);

return [
    'storage_driver' => 'Stancl\Tenancy\StorageDrivers\DatabaseStorageDriver',
    'storage' => [
        'db' => [ // Stancl\Tenancy\StorageDrivers\DatabaseStorageDriver
            'data_column' => 'data',
            'custom_columns' => [
                'plan',
                'user_id'
            ],
            'connection' => 'multidbsaas',
        ],
        'redis' => [ // Stancl\Tenancy\StorageDrivers\RedisStorageDriver
            'connection' => 'tenancy',
        ],
    ],
    'tenant_route_namespace' => 'App\Http\Controllers',
    'exempt_domains' => [ // e.g. domains which host landing pages, sign up pages, etc
        // 'localhost',
    ],
    'database' => [
        'based_on' => 'mysql', // The connection that will be used as a base for the dynamically created tenant connection.
        'prefix' => 'tenant',
        'suffix' => '',
    ],
    'redis' => [
        'tenancy' => false, // to enable Redis tenancy, you must use phpredis
        'prefix_base' => 'tenant',
        'prefixed_connections' => [
            'default',
            'cache',
        ],
    ],
    'cache' => [
        'tag_base' => 'tenant',
    ],
    'filesystem' => [ // https://stancl-tenancy.netlify.com/docs/filesystem-tenancy/
        'suffix_base' => 'tenant',
        // Disks which should be suffixed with the suffix_base + tenant UUID.
        'disks' => [
            'local',
            'public',
            // 's3',
        ],
        'root_override' => [
            // Disks whose roots should be overriden after storage_path() is suffixed.
            'local' => '%storage_path%/app/',
            'public' => '%storage_path%/app/public/',
        ],
    ],
    'database_managers' => [
        'sqlite' => 'Stancl\Tenancy\TenantDatabaseManagers\SQLiteDatabaseManager',
        'mysql' => 'Stancl\Tenancy\TenantDatabaseManagers\MySQLDatabaseManager',
        'pgsql' => 'Stancl\Tenancy\TenantDatabaseManagers\PostgreSQLDatabaseManager',
    ],
    'queue_database_creation' => false,
    'queue_database_deletion' => false,
    'database_name_key' => null,
    'unique_id_generator' => 'Stancl\Tenancy\UUIDGenerator',
];
`

**Comment by stancl** [comment]
> `'connection' => 'multidbsaas',`

You're telling the package to use the `multidbsaas` database connection, but like the error says, it's not defined in `config/database.php`.

See the [Storage Drivers](https://stancl-tenancy.netlify.com/docs/storage-drivers/#database) page in the documentation.

**Comment by dukenst2006** [comment]
Ok, thanks for your quick response, i created a new connection like mysql and named it multidbsaas
Now it give me error and not yet created any tenant:
`Tenant could not be identified on domain multidbsaas.test`
I think the default home page should be show
Thanks,

**Comment by stancl** [comment]
@dukenst2006 To identify a tenant, you need to create a tenant. Try following the [documentation](https://stancl-tenancy.netlify.com/docs/getting-started/) page by page. It should answer your questions as you go.

**Comment by dukenst2006** [comment]
Thanks for your response and keep this package on, it's useful.
I can't figure out why the tenant route and tenancy midleware load for the home page while the route home page is under the web route.
![1](https://user-images.githubusercontent.com/7965394/64477103-88e32380-d165-11e9-8acc-c55475f72538.jpg)
Best,

**Comment by stancl** [comment]
> I can't figure out why the tenant route and tenancy midleware load for the home page while the route home page is under the web route.

Probably because you have the route also in `tenant.php`. If some domain should have web routes, add it to `tenancy.exempt_routes` config.
