### ISSUE TITLE
Issue with running tests in application

### ISSUE THREAD

**Issue by JoshMoreno** [archtechx/tenancy#117]
I see you touched on it with #54, but there's nothing on the online docs about testing 

[https://stancl-tenancy.netlify.com](https://stancl-tenancy.netlify.com)

I'm currently running into connection problems getting a Tenant model factory going with an in memory sqlite connection. If I extend the default Tenant model and default it back to the `$this->connection` it works.

**app/Tenant.php**
```php
<?php

namespace App;

use App;

class Tenant extends \Stancl\Tenancy\Tenant
{
    public function getConnectionName()
    {
        if (App::runningUnitTests()) {
            return $this->connection;
        }

        return parent::getConnectionName();
    }
}
```

But I'm just getting started with this project and have no idea if this will cause problems for future tests reliant on the tenant's specific database. Perhaps there's a different approach that has to be taken due to multiple databases.

Here's a simplified example below of what I'm running into right now.

```php
use App\User;
use Stancl\Tenancy\Tenant;

// works no problem
factory(User::class)->create();
$this->assertCount(1, User::all());

// doesn't work - Access denied for user 'homestead'@'localhost'
factory(Tenant::class)->create();
$this->assertCount(1, Tenant::all());
```

Any tips would be useful. 

For clarification on sqlite in memory connection I have the following in my **phpunit.xml**
```xml
<env name="DB_DATABASE" value=":memory:"/>
```

**Comment by stancl** [comment]
Hi.

When I'm testing apps which use this package, I create tenants using the TenantManager. I'd prefer if people didn't really use the Tenant model directly, because that's completely untested.

When you want to test your application, I recommend putting this into your `setUp()`:

```php
tenant()->create('test.localhost');
tenant()->init('test.localhost');
```

and then just writing your tests without thinking about tenancy.

Looks like I forgot to add the testing section to the new docs, will fix that.

**Comment by JoshMoreno** [comment]
Thanks for the quick reply!
Do you use sqlite? It's not working for me. Trying to keep my testing databases isolated from the development databases. In memory makes that really easy, but I can't get it working with this package.

Correction to what I have in my phpunit.xml
```xml
<env name="DB_CONNECTION" value="sqlite"/>
<env name="DB_DATABASE" value=":memory:"/>
```

I'll keep trying to figure out a solution

**Comment by stancl** [comment]
What error are you getting? If you're using `:memory:`, the issue is likely that your `tenants` table is missing. Run the migration in your `setUp()`:

```php
protected function setUp(): void
{
    parent::setUp();

    $this->call('migrate', [
        '--path' => database_path('migrations'),
        '--database' => 'sqlite',
    ]);

    tenant()->create('test.localhost');
    tenancy()->init('test.localhost');
}
```

**Comment by stancl** [comment]
Added this page to docs: https://stancl-tenancy.netlify.com/docs/application-testing/

Closing for now. If you're still having issues with this, reach out.

**Comment by JoshMoreno** [comment]
I had to pass a uri string as the second arg in `$this->call`, but otherwise it's unchanged.
```
protected function setUp(): void
{
    parent::setUp();

    $this->call('migrate', '/', [
        '--path' => database_path('migrations'),
        '--database' => 'sqlite',
    ]);

    tenant()->create('test.localhost');
    tenancy()->init('test.localhost');
}
```

```
Illuminate\Database\QueryException : SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: select * from `tenants` where `domain` = test.localhost limit 1)
```

I'm pretty sure the problem is the `Stancl\Tenancy\Tenant::getConnectionName` implementation.  Everything leads back to it and modifying it seems to fix the issue in regards to tenant creation in the main database.

`TenantManager::create` calls `DatabaseStorageDriver::createTenant` which calls `Tenant::create`. And the `Tenant` model overrides `getConnectionName` with

```php
public function getConnectionName()
{
    return config('tenancy.storage.db.connection');
}
```

Changing it to the following fixes the issue, but I still get errors in regards to tenant database creation.
```php
public function getConnectionName()
{
    if (App::runningUnitTests()) {
        return $this->connection;
    }

    return config('tenancy.storage.db.connection');
}
```

So cecause the `Stancl\Tenancy\Tenant` model is hard-coded into the default `DatabaseStorageDriver` I think the only thing I can do until this gets addressed is implement my own storage driver. I was going to have to do this anyways to support both subdomains and custom domains for tenants.


## Tenant Database Error
`DatabaseManager::getDriver` is defaulting to the `tenancy.php` config again and it chooses the mysql driver rather than sqlite driver.

And this class is final so replacing it will be a pain.

```
SQLSTATE[HY000]: General error: 1 near "DATABASE": syntax error (SQL: CREATE DATABASE `tenant01fff1d0-c5eb-11e9-8939-854d9918cb95` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci)
```

Perhaps the best way moving forward is to provide an easy way to override the configuration for testing purposes.

**Comment by stancl** [comment]
I'll take a look at this in the morning.

The reason the Tenant model is hardcoded is because it's not something I want people to change. I even thought about making the Tenant model part of the DB storage driver file. It's hard to add new features in a backwards-compatible way when too much can be modified. For the same reason I made the `TenantManager` a `final` class. Otherwise changing a method's signature would be a breaking change.

**Comment by JoshMoreno** [comment]
The driver is getting picked in `DatabaseManager::createTenantConnection`

```php
$based_on = config('tenancy.database.based_on') ?: config('database.default');
```

**Comment by JoshMoreno** [comment]
Just saw your previous message, I understand. Maybe interfaces can help alleviate the concern?

As far as testing goes, this is a bug in my book. It really only affects dev environments, but there doesn't seem to be a reliable way to have different connections for testing and development. Maybe this only rears it's ugly head when you're mixing connection types like I am (mysql vs sqlite), but it's not uncommon and makes development more enjoyable.

I think tenant identification is a pretty important feature as it can vary per project. Most common ways I've seen are:
- subdomain (e.g. myshop.example.com)
- custom domain (e.g. myshop.com)
- subdomain and a custom domain (e.g. myshop.example.com && myshop.com with a possible redirect from the subdomain to the custom domain)
- route based (e.g. example.com/shop/myshop)

Right now, it's kind of a pain to do this and possibly risky to do this if you're not officially supporting these types of use cases.

I'll have a look over the weekend some more. I may need to just fork it.
Thanks for all your help and hard work! I like this a lot more than hyn. Much simpler.

**Comment by stancl** [comment]
Do I understand correctly that you want the prod/dev DB to be based on mysql and the test DB to be based on sqlite?

You can change the config in setUp().

```php
config(['tenancy.database.based_on' => 'sqlite']);
```

**Comment by stancl** [comment]
@JoshMoreno Did you get it working?

**Comment by JoshMoreno** [comment]
No. I didn't get a chance to try changing config values, though I suspect it would work.

I'm going to roll my own solution for this project though. It will be a good learning experience.
Thanks for your help.

**Comment by devonmather** [comment]
Any updates on this? The testing page in the documentation is a bit scarce on some of the specifics, any advice would be appreciated.

*phpunit.xml* contains the following:
```
<server name="DB_CONNECTION" value="sqlite"/>
<server name="DB_DATABASE" value=":memory:"/>
```

*TestCase.php* contains the following:
```
protected function setUp(): void
{
    parent::setUp();

    // Also this call in the documentation doesn't mention the extra parameters that it needs?
    $this->call('migrate', '/', [
        '--path' => database_path('migrations'),
        '--database' => 'sqlite',
    ]);

    tenancy()->create('test.localhost');
    tenancy()->init('test.localhost');
}
```

*FeatureTest.php* has the following
```
/** @test */
public function a_guest_can_access_the_welcome_screen()
{
    $response = $this->get('/app');

    $response->assertStatus(200);
}
```

and I'm getting the following error:
`1) Tests\Feature\AuthTest::a_guest_can_access_the_welcome_screen
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such table: domains (SQL: select * from "domains" where "domain" = test.localhost limit 1)`

**Comment by stancl** [comment]
@devonmather In the last few days I've had a few people ask me about this. Seems like there is an issue with sqlite :memory: databases. Can you retry with a file DB or a MySQL DB?

**Comment by devonmather** [comment]
Thanks for the prompt response! Yep, using MySQL appears to work. Unfortunately, it adds a lot of databases that need to be deleted? Is there a set way to prevent this in the package until the SQLite memory databases work?

**Comment by stancl** [comment]
Sure, use a `tearDown()` like this to delete all the created DBs: https://github.com/stancl/tenancy/pull/199/files#diff-57668c7e970080317e2e8da18efe12ecR69-R75

**Comment by devonmather** [comment]
Perfect, thank you! To get that working I also had to set the following which I think you mentioned in another issue `'queue_database_deletion' => false,`

**Comment by stancl** [comment]
Ah, right, good point. I'll be sure to cover that on the testing doc page after I resolve the :memory: issue. docs:35

**Comment by devonmather** [comment]
Seems to all be working now, no in-memory functionality but otherwise all good. I've gone ahead and Instantiated the database.sqlite in the TestCase setup and removed in the teardown using the File facade. So from a testing point of view seems to behave the same as if it were using :memory:
