### ISSUE TITLE
Domain aliases

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#119]
See #64 and #12. 

Due to the limitations of the 1.x StorageDriver interface, this should be a implemented using a voluntary method on storage drivers. If the current storage driver does not support this, the method for setting aliases should throw a NotImplemented exception.

**Comment by stancl** [comment]
Will implement unlimited amount of hostnames per tenant in 2.0.0.

**Comment by vahidalvandi** [comment]
Do alias work in v3 ?

**Comment by stancl** [comment]
What?

**Comment by vahidalvandi** [comment]
> What?

How i can use domain aliases in version 3 ?

**Comment by stancl** [comment]
There's a domains page in the docs. Read the docs before opening a million
issues.
