### ISSUE TITLE
[2.x] Drivers in storage configuration

### ISSUE THREAD

**Issue by antonkomarev** [archtechx/tenancy#129]
Wouldn't it be better to have `driver` key in each storage?

Instead of:
```php
'storage_driver' => 'Stancl\Tenancy\StorageDrivers\Database\DatabaseStorageDriver',
'storage' => [
    'db' => [ // Stancl\Tenancy\StorageDrivers\Database\DatabaseStorageDriver
        'data_column' => 'data',
        'custom_columns' => [
            // 'plan',
        ],
        'connection' => null,
        'table_names' => [
            'TenantModel' => 'tenants',
            'DomainModel' => 'domains',
        ],
    ],
    'redis' => [ // Stancl\Tenancy\StorageDrivers\RedisStorageDriver
        'connection' => 'tenancy',
    ],
],
```

Write it like this:
```php
'storage' => 'db',
'storages' => [
    'db' => [
        'driver' => Stancl\Tenancy\StorageDrivers\Database\DatabaseStorageDriver::class,
        'data_column' => 'data',
        'custom_columns' => [
            // 'plan',
        ],
        'connection' => null,
        'table_names' => [
            'TenantModel' => 'tenants',
            'DomainModel' => 'domains',
        ],
    ],
    'redis' => [
        'driver' => Stancl\Tenancy\StorageDrivers\RedisStorageDriver::class,
        'connection' => 'tenancy',
    ],
],
```

And why `table_names` keys are uppercase (`TenantModel`, `DomainModel`)? It's inconsistent.

**Comment by stancl** [comment]
> And why table_names keys are uppercase (TenantModel, DomainModel)? It's inconsistent.

The class base names are `TenantModel` and `DomainModel`.
```php
'tenant' => 'tenants',
```
would look weird, and so would
```php
'tenant_model' => 'tenants',
```

**Comment by drbyte** [comment]
I like the addition of the `driver` name being matched directly to the `::class`, within the array, instead of outside it.

**Comment by stancl** [comment]
@antonkomarev @drbyte If you have any other suggestions regarding the config, please share. I'll be releasing 2.0.0 soon and the config file can't change from that point on.

**Comment by drbyte** [comment]
As to the table-names, TenantModel=>'tenants' ... vs some other approach, I'm indifferent. 
There's only a couple tables involved with the tenancy part of things, so it's not like you'll have a dozen keys to manage in there.

**Comment by stancl** [comment]
![Screenshot from 2019-09-30 18-10-57](https://user-images.githubusercontent.com/33033094/65896534-aba3d900-e3ad-11e9-98a0-9fc65a354e9f.png)


I guess this is better. My only concern is that the `connection` key is on both `db` and `redis` which makes it seem like it's related to the package rather than the actual drivers, but I guess that's not too bad.

**Comment by drbyte** [comment]
Maybe `connection` should be `app_connection`? or something slightly more clarifying of which connection it's meaning?

**Comment by stancl** [comment]
It's really specific to the driver. In the `db` driver's case it's the DB connection and in the `redis` driver's case it's the Redis connection.

**Comment by drbyte** [comment]
Ya, that potential confusion is more a consequence of how Laravel does things, and uses the same word for those different contexts.

I think people who "get" what Laravel does internally will "get" what you mean here.

The point of confusion will probably come down to trying to understand why (the db) one is `null` and the other (redis) is not.

**Comment by stancl** [comment]
People who "just use" the package will understand it because it's covered by the docs. People who develop their own storage driver will have to look at the source code anyway, so they'll understand too I guess.

**Comment by drbyte** [comment]
Agreed. 
This seems sensible to me. Admittedly in my day-to-day I'm unlikely to need to touch this particular part of the package's config.
