### ISSUE TITLE
[2.x] Tenant & system migrations location

### ISSUE THREAD

**Issue by antonkomarev** [archtechx/tenancy#130]
Is there is a way to store tenant migrations in `/database/migrations` & system migrations in `/database/migrations/system`?

I found only the way how to configure tenants migrations location.

**Comment by antonkomarev** [comment]
This is important because most of the migrations will be related to the tenants. If application uses many third party packages there might be an issues when package loads migrations in service provider with `$this->loadMigrationsFrom()` method and doesn't provide any way to ignore them.

**Comment by drbyte** [comment]
> there might be an issues when package loads migrations in service provider with `$this->loadMigrationsFrom()` method and doesn't provide any way to ignore them.

Do you have an example of packages that are doing that instead of offering to publish their migrations?

**Comment by antonkomarev** [comment]
A lot of packages provides this feature. Just used search on GitHub and picked first one from popular vendor:
https://github.com/spatie/laravel-model-status/blob/57bebd45a750baaafceb349ce96e01ce228a1565/src/ModelStatusServiceProvider.php#L12-L14

**Comment by antonkomarev** [comment]
It doesn't mean that package doesn't provide publishing. But if you publish migrations and move them to `/database/migrations/tenants` directory Laravel will ignore them and run migrations loaded from the package vendor directory.

**Comment by stancl** [comment]
What do you think about adding config keys to set this?
```php
'migration_paths' => [
    'tenant' => database_path('migrations/tenant'),
    'system' => database_path('migrations'),
]
```

The migrations directory is already configurable, but it's because I needed it for tests, not because I wanted people to use it. Last time I tried using `database_path()` right in the config file, it blew up. Perhaps we could just do `'tenant' => 'migrations/tenant'` and wrap it in `database_path()` in the package code.

**Comment by antonkomarev** [comment]
It would be great to have those values in config.

**Comment by antonkomarev** [comment]
But we should carefully pick a right name for they keys. If you are calling main service application `Central` - then key should be called `central` in terms of consistency.

**Comment by stancl** [comment]
Adding this in 2.1.0 will not be a breaking change and I want to release 2.0.0 quickly. Configurable tenant migration path will be easy, but I have to find a way to make the Illuminate migration commands use a different path for the central migrations.

**Comment by stancl** [comment]
The central migration path is hardcoded: https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Console/Migrations/BaseCommand.php#L47-L50

So changing this is probably going to be a pain. I'll see if I can make this happen in 2.2.0

**Comment by viezel** [comment]
you can do something like this:

1. make a `migrations_path` helper that points to `database/migrations`. 

2. change config
```php
'migration_paths' => [
    'tenant' => migrations_path('tenant'),
    'system' => migrations_path(),
]
```

3. call migrate with path
```php
Artisan::call('migrate', [
  '--path' => config('tenancy.migration_paths.tenant'),
  '--database' => 'tenant_database',
  '--force' => true
]);
```

**Comment by antonkomarev** [comment]
There is no need to add new `migrations_path` helper, because it will be the same as:
```php 
'migration_paths' => [
    'tenant' => database_path('migrations/tenant'),
    'system' => database_path('migrations'),
]
```

**Comment by stancl** [comment]
FWIW, the tenant migration directory is already configurable: https://github.com/stancl/tenancy/blob/2.x/src/Traits/DealsWithMigrations.php#L15

But I'm still not sure how I'd make the illuminate migrator use a different directory.

**Comment by Surt** [comment]
Sorry for commenting here but I'm still confused.
I'm using many libraries with its own migrations that I want on tenant (example: https://github.com/plank/laravel-mediable) 
How can I make the "vendor packages" migrations execute on tenant?

Edited: I know that it is possible to publish all those migrations but I'm worried that any package updates it's migrations or add more and I did not take care or be aware of publishing them. 

Edited: I'm wondering if it is much work to, having the actual configs for migrations paths etc, changing the library so "central" database is the "exception" I mean, you define your "central" database migrations and let the rest of your application as it is. It would be great to ppl with working applications to not having to change anything or configurate the migration paths, just set the central database migration path. 
Actually I needed to chage my "central migration" using "path=/database/migrations/central" and create a bootstrapper to load my module migrations for the tenants.

**Comment by stancl** [comment]
Can't you just add the path from vendor too?

https://github.com/archtechx/tenancy/blob/3.x/assets/config.php#L186

**Comment by Surt** [comment]
> Can't you just add the path from vendor too?
> 
> https://github.com/archtechx/tenancy/blob/3.x/assets/config.php#L186

Hi @stancl thx for your library,
I don't know which vendors require its own migrations. I know some of them and I can hardcode them in the path but there is always the possibility to add a new library and forget, or to update one and not taking care or something...

Actually all my vendors are used for the tenant application, I have no need of any of them for the "central" application (wich probably will be your saas-boilerplate). I don't know other use cases but it seems to me that your library is "dropped" on existing applications where the migrations etc should not be the exception (adding tenant to migration folder etc). Instead, the "central" application (if needed or used like in your saas boilerplate) is the one that can go to a separate migration path.
Again, this is just my vision of the problem I'm facing.

**Comment by Mo7mud** [comment]
> > Can't you just add the path from vendor too?
> > https://github.com/archtechx/tenancy/blob/3.x/assets/config.php#L186
> 
> Hi @stancl thx for your library, I don't know which vendors require its own migrations. I know some of them and I can hardcode them in the path but there is always the possibility to add a new library and forget, or to update one and not taking care or something...
> 
> Actually all my vendors are used for the tenant application, I have no need of any of them for the "central" application (wich probably will be your saas-boilerplate). I don't know other use cases but it seems to me that your library is "dropped" on existing applications where the migrations etc should not be the exception (adding tenant to migration folder etc). Instead, the "central" application (if needed or used like in your saas boilerplate) is the one that can go to a separate migration path. Again, this is just my vision of the problem I'm facing.

I agree with that.
I'm having a very hard times just to make it work with nWidart modules package, my project became a total mess and nearly I need to redo most of the work.
I'll try another packages for multi tenancy first, maybe they're more friendly with other packages than this one.

**Comment by jvangrouw** [comment]
> > Can't you just add the path from vendor too?
> > https://github.com/archtechx/tenancy/blob/3.x/assets/config.php#L186
> 
> Hi @stancl thx for your library, I don't know which vendors require its own migrations. I know some of them and I can hardcode them in the path but there is always the possibility to add a new library and forget, or to update one and not taking care or something...
> 
> Actually all my vendors are used for the tenant application, I have no need of any of them for the "central" application (wich probably will be your saas-boilerplate). I don't know other use cases but it seems to me that your library is "dropped" on existing applications where the migrations etc should not be the exception (adding tenant to migration folder etc). Instead, the "central" application (if needed or used like in your saas boilerplate) is the one that can go to a separate migration path. Again, this is just my vision of the problem I'm facing.

I prevented hardcoding all the paths by making use of the glob function. This will look for alle vendor packages with database migrations in it. The following solved our issue (we had a lot of packages which make use of loadMigrationsFrom(), and I also wanted to prevent hardcoding all the vendor packages in the settings.
```
    'migration_parameters' => [
        '--force' => true, // This needs to be true to run migrations in production.
        '--path' => array_merge(
                glob(database_path('migrations')),
                glob(base_path('/vendor/**/**/database/migrations')),
        ),
        '--realpath' => true,
    ],
```

**Comment by Surt** [comment]
> > > Can't you just add the path from vendor too?
> > > https://github.com/archtechx/tenancy/blob/3.x/assets/config.php#L186
> > 
> > 
> > Hi @stancl thx for your library, I don't know which vendors require its own migrations. I know some of them and I can hardcode them in the path but there is always the possibility to add a new library and forget, or to update one and not taking care or something...
> > Actually all my vendors are used for the tenant application, I have no need of any of them for the "central" application (wich probably will be your saas-boilerplate). I don't know other use cases but it seems to me that your library is "dropped" on existing applications where the migrations etc should not be the exception (adding tenant to migration folder etc). Instead, the "central" application (if needed or used like in your saas boilerplate) is the one that can go to a separate migration path. Again, this is just my vision of the problem I'm facing.
> 
> I prevented hardcoding all the paths by making use of the glob function. This will look for alle vendor packages with database migrations in it. The following solved our issue (we had a lot of packages which make use of loadMigrationsFrom(), and I also wanted to prevent hardcoding all the vendor packages in the settings.
> 
> ```
>     'migration_parameters' => [
>         '--force' => true, // This needs to be true to run migrations in production.
>         '--path' => array_merge(
>                 glob(database_path('migrations')),
>                 glob(base_path('/vendor/**/**/database/migrations')),
>         ),
>         '--realpath' => true,
>     ],
> ```

Yeah, that's a good solution! Thx (I always try to avoid things that are disk intensive like a glob but in this case it will be used only during migration I hope.
