### ISSUE TITLE
[2.x] Migration runs on wrong connection

### ISSUE THREAD

**Issue by antonkomarev** [archtechx/tenancy#131]
If migration has `mysql` connection definition - tenant migration will be performed not in `tenant` connection.

I'm found an issue with my own private package, but this pattern could be found in Laravel Telescope, so you could try to add telescope migrations to the tenant schemas.

https://github.com/laravel/telescope/blob/c5487364da3f28fd41b631be3193b4751cf10d27/src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php

As you can see `$this->schema` variable contains schema builder with custom connection. This connection defined in configuration file with default value of `mysql`.

So as workaround package's config file could be published and `storage.database.connection` value should be changed to `null`, or make it on the fly: `Config::set('telescope.storage.database.connection', null)`

Do you have other ideas how it could be solved?

**Comment by stancl** [comment]
Do you want the Telescope tables to be in the tenant databases?

**Comment by antonkomarev** [comment]
No, I just provided Telescope as a publicly available example. I have private package which has migrations designed in the same way as Telescope ones.

**Comment by stancl** [comment]
> Do you have other ideas how it could be solved?

Really just setting the configuration key.

If it should be in the `tenant` db, you could set it to `tenant`, but that would be problematic if some tenant uses a different DB connection.

If you really can't change the migration and have tenants with non-`tenant` connections, you could use an event listener for `bootstrapped` and set the config key to the current tenant's connection.

**Comment by drbyte** [comment]
> you could use an event listener for `bootstrapped` and set the config key to the current tenant's connection

This event-listener approach is likely going to be the solution for lots of various end-user questions. 
While the https://tenancy.samuelstancl.me/docs/v2/event-system/ docs already cover how/why to do this in a general sense, I wonder if there will be benefit to showing some specific use-case examples, perhaps in a "common questions" docs page?

**Comment by stancl** [comment]
@drbyte Perhaps also calling them "hooks" would be better? Sounds more like you can hook into the process, rather than just do something on the side after an event is fired.

**Comment by drbyte** [comment]
Fair. I do agree that hooks are more like injecting something into a certain step of the pipeline, rather than a side-effect.
Granted, if the "way" to implement the "hook" is to add an "event listener", then introducing another term ("hooks") may just add more complexity than a quick list of common event-listeners that could be copy-pasted if the use-case warrants.
