### ISSUE TITLE
[2.x] Replace Webpatser UUID with Ramsey UUID

### ISSUE THREAD

**Issue by antonkomarev** [archtechx/tenancy#134]
Laravel uses `"ramsey/uuid": "^3.7",` package. I think it would be better to use it too and not add extra dependency.

**Comment by drbyte** [comment]
I was thinking the same, but haven't had time to look into what's different or why this one was chosen.

**Comment by robmachado** [comment]
Regarding the UUID, Eloquent has a UUID record type when creating tables.
It can be used instead of a string.
For example:

```php
$table->string('tenant_id', 36);
```
can be replaced by

```php 
$table->uuid('tenant_id');
```
And
```php   
$table->string('id', 36)->primary();
```
can be replaced by

```php
$table->uuid('id', 36)->primary();
```
I believe it is a little more readable.

**Comment by stancl** [comment]
@robmachado Like I said in another thread, the ID doesn't *have* to be a uuid. Uuids are just what the package uses as a fallback (when no ID is explicitly set) by default.

I guess the docs should be more clear on the custom ID schemes support.

**Comment by robmachado** [comment]
Very well my friend has now become much clearer to me. Again thank you so much for your great work. :+1:

**Comment by antonkomarev** [comment]
@robmachado here is a PR #142 and detailed explanation from @stancl

**Comment by robmachado** [comment]
Tks, i now see that :+1: 
I have to pay more attention and look more before commenting!
