### ISSUE TITLE
[2.x] Tenant & Domains timestamps

### ISSUE THREAD

**Issue by antonkomarev** [archtechx/tenancy#138]
Why does `tenants` & `domains` database tables doesn't have `created_at` & `updated_at` columns? This information could be very useful.

**Comment by stancl** [comment]
Hmm, good point. I agree, I'll add timestamps.

**Comment by stancl** [comment]
https://github.com/stancl/tenancy/commit/6b103cd2cb8a92c87a061890326e8c3b3f4f9a8a

**Comment by stancl** [comment]
@antonkomarev Actually, this is a bit harder than just making the models use the timestamps. The data should be consistent in all storage drivers, so this functionality should be handled by the TenantManager. I will add this in a future release.

**Comment by stancl** [comment]
This is relatively easy to implement using TenantManger hooks, so it can be implemented easily in the app. But since it's not a big maintenance burden and it can be useful to have a general implementation, I'll make this part of the package as an opt-in Feature.
