### ISSUE TITLE
[2.x] TelescopeTags doesn't have a default callback

### ISSUE THREAD

**Issue by hakanersu** [archtechx/tenancy#147]
#### Describe the bug
When i try to create a tenant through ```php artisan tinker``` i'm getting below error.

```
PHP Error:  Function name must be a string in /application/vendor/stancl/tenancy/src/Features/TelescopeTags.php on line 38
```
Callback returns null. Also even passed that step application not works at all with telescope feature and redirects app to home_url.

It seems in ```src/Features/TelescopeTags.php``` line 30 ```tenant('id')``` call cant resolve Tenant::class in app container.

#### Steps to reproduce
Fresh installation and enable telescope.
Try to create a tenant in tinker with below command.
```
\Stancl\Tenancy\Tenant::new()->withDomains(['tenant1.example.test'])->withData(['plan' => 'free'])->save();
```

#### Expected behavior
Creates given tenant.

#### Your setup
 - Laravel version: 6.*
 - stancl/tenancy version: v2.0.0-rc1
 - Storage driver: redis

**Comment by hakanersu** [comment]
It seems my problem deeper than this issue. I'll dig deeper for real problem

**Comment by stancl** [comment]
Thanks for reporting @hakanersu. Seems like there is no default value for the callback used by `TelescopeTags`.

**Comment by stancl** [comment]
@hakanersu Either way, it calls `$this->callback` on line 38 even if the callback is null. I'll re-test the Telescope integration in an L6 app.

**Comment by hakanersu** [comment]
@stancl 1.x its just works out of the box but i cant migrate my project to 2.x yet. I am trying  to create fresh app but i guess im missing something because i cant get it work yet.

Edit: finally solved my problem, just silly mistake that i just define auth routes in both tenant and web  route.

**Comment by stancl** [comment]
The issue with Telescope should be fixed by https://github.com/stancl/tenancy/commit/dcc9bda7581908fb182c0512f35ea0fc125f7c0e (not part of 2.0.0-rc1)

**Comment by hakanersu** [comment]
@stancl I don't think its fixed.
![cant-resolve](https://user-images.githubusercontent.com/1052467/65896833-a434fd80-e3b6-11e9-9848-c82444f9669b.gif)

**Comment by stancl** [comment]
@hakanersu Are you using `2.x-dev` or `2.0.0-rc1`?

**Comment by hakanersu** [comment]
currently 2.x-dev

**Comment by stancl** [comment]
Okay. I'll test it in a Laravel app with Telescope. I hope I can release `2.0.0-rc2` with this fixed in an hour or so.

**Comment by hakanersu** [comment]
Thank you, i cant figure out why ```app(Tenant::class)->get($key)```  return empty response.

**Comment by stancl** [comment]
Try running `composer update`, I fixed a bug related to tenant storage like an hour ago.

**Comment by stancl** [comment]
(The issue was that the data was not being written during tenant creation, so try setting the data again.)

**Comment by hakanersu** [comment]
Head is now 6cb7f27 it is same.

**Comment by stancl** [comment]
@hakanersu Could you open an issue for that and describe the steps necessary to reproduce this?
