### ISSUE TITLE
[2.1.0] Nova integration

### ISSUE THREAD

**Issue by viezel** [archtechx/tenancy#162]
Given that you already support a vast part of the Laravel ecosystem, it would be a very useful feature to add support for an administration panel powered by Nova. 

Might be a separate package if you want to keep this clean.

**Comment by stancl** [comment]
I was thinking that Nova could work without any changes, but since it has its own migrations and interacts with tenant models, that could be problematic. Alright, I'll look deeper into how it would integrate.

**Comment by viezel** [comment]
For this Feature Request, Nova needs to work in the global environment and not within tenant. 
Imagine a admin panel to CRUD tenants, CRUD subscription plans, view metrics, have mass actions and overall maintain the SaaS application.

**Comment by stancl** [comment]
In 2.1.0 I will make sure Nova works correctly inside the tenant application.

The global environment is a good use case, but I'll have to think about that. Tenants should be created using the `TenantManager`, not using the models, so I'd have to find a way to make that work with Nova.

**Comment by stancl** [comment]
After https://github.com/laravel/nova-issues/issues/2036 is resolved, Nova integration should be possible in 2.1.0.

**Comment by stancl** [comment]
https://github.com/stancl/tenancy-docs/pull/29

**Comment by viezel** [comment]
👏
