### ISSUE TITLE
VerifyCsrfToken middleware on api routes

### ISSUE THREAD

**Issue by franzyke** [archtechx/tenancy#166]
I'm using this library in api "mode" using javascript frontend. In `Stancl\Tenancy\TenantRouteServiceProvider`, the `web` middleware is used. So the VerifyCsrfToken token is called by default which is problematic in my use case since the api calls dont have csrf token.

For now, I disable this by removing `VerifyCsrfToken` from the `web` middleware group in `App\Http\Kernel` as I don't really need it as of now. Is there a better way to do this? 

Would it be practical to remove the web middleware from `Stancl\Tenancy\TenantRouteServiceProvider` and let the end user decide which middleware should be used.

**Comment by stancl** [comment]
Try this: https://tenancy.samuelstancl.me/docs/v2/tenant-routes/#exempt-routes. The API routes/custom route groups section.

Just noticed that the page is a bit poorly structured, so I added another heading.

You should apply the `InitializeTenancy` middleware, not the `tenancy` route group.

**Comment by franzyke** [comment]
Thank you. 

added some routes with `InitializeTenancy` in api.php and it seems to work
