### ISSUE TITLE
Tenant database charset and collation are hardcoded instead of taken from config

### ISSUE THREAD

**Issue by jonagoldman** [archtechx/tenancy#172]
#### Description
`utf8mb4` charset and `utf8mb4_unicode_ci` collation are hardcoded:
https://github.com/stancl/tenancy/blob/7143bce5f9d7e0b4da40d62c9b79a436d6ebdf82/src/TenantDatabaseManagers/MySQLDatabaseManager.php#L21-L24

#### Why this should be added
Database creation should respect the connection configuration.

**Comment by stancl** [comment]
Resolved by #180
