### ISSUE TITLE
How would this work with a VueJS SPA and Laravel as an API only implementation?

### ISSUE THREAD

**Issue by tjhunkin** [archtechx/tenancy#174]
How would this work with a VueJS SPA and Laraval as an API only implementation?

Would you have to send the domain along with each request from VueJS?

**Comment by stancl** [comment]
> Would you have to send the domain

It's the simplest way.

But - if you serve the markup from, say, tenant1.yourapp.com, making an Ajax call to /api/users/all will make the request on that tenant domain. So as long as your API routes are tenant routes, this is isn't really a problem.
