### ISSUE TITLE
How to work with the Eloquent Tenant model

### ISSUE THREAD

**Issue by jonagoldman** [archtechx/tenancy#175]
I'm having trouble understanding how to work with the Eloquent Tenant model. In my usecase, the tenant is an hotel that have relations, getters, setters etc.. I am supposed to have a Hotel model that extends from Tenant? Should I extend something else?

**Comment by stancl** [comment]
The `Tenant` object is completely separate from your tenant app. The actual tenant app is not concerned with the tenant it belongs to, it's sort of unaware of tenancy.

Can you give me more information about why & how you'd need this?

**Comment by jonagoldman** [comment]
I'm building a hotel management system.
The central database holds all the general data like users, permissions and hotels list (tenants).
Then for each hotel I create a separate database with data relevant only to that hotel, for example rooms, bookings, availability etc...

The reason the users are stored in the central database is that one user can manage multiple hotels. For example the user can be the hotel owner who owns multiple hotels, or even a worker that works for more than one hotel. Maybe I want to even create a user for an accauntant so he can look at financial information for multiple hotels at the same time, from a dashboard lets say.

So the user logs in to the central database, and he can switch between hotels with the same credentials. But core information about the hotel is stored in the central database, for example subscription plans, hotel settings like currency, language and address. Maybe also reports generated from multiple hotels.

So there is a relation betwen a user and an hotel (tenant) and a tenant to a report lets say... and so on...

**Comment by stancl** [comment]
I see. So you need a hotel model to define a relationship between a hotel/tenant and a user?

**Comment by jonagoldman** [comment]
I guess I want the Tenant to behave like an Eloquent model, or at least be able to extend from it.

Like when I do `Auth::user()` I get the authenticated Eloquent User.
It would be nice to do `Tenancy::tenant()` and get the current Eloquent Tenant.

**Comment by jonagoldman** [comment]
I can avoid using the tenants table completely, like this: 
![Screenshot from 2019-10-15 17-37-11](https://user-images.githubusercontent.com/1297559/66875019-83ea6e80-ef72-11e9-8c11-f86ce62b1610.png)

But ideally I will 'merge' the `hotels` and `tenants` table and then do things like:
```php
$hotel = tenant(); // or Tenancy::tenant()
$hotel->users()->create([...]); // just an example
```

**Comment by stancl** [comment]
Right. You can rename the `tenants` table to `hotels` in the config, add your custom columns -- name, locale, country, timezone, currency_code ... -- to the config, and create a `Hotel` model in your application. If you want to use that central model in your tenant app, you can use the `CentralConnection` trait on it.

But you still have to use the `Tenant` class to create tenants and set things like timezone and currency_code for the tenant.

**Comment by jonagoldman** [comment]
Now that creation of custom columns is fixed in v2.1.1, it is much easier to use your own Eloquent Model together with the Tenant model. The only thing is you need to manually update the created_at and updated_at models but I think this issue can be closed now.

**Comment by stancl** [comment]
> your own Eloquent Model together with the Tenant model

Can you elaborate on this? The Tenant Eloquent model used by the package is not meant to be used from user land.

**Comment by jonagoldman** [comment]
I don't use TenantModel directly, I create my own Tenant model but they both use the same table. I just take care of not overriding the 'data' column and always use the Tenant facade for actual tenant manipulation. I use my Tenant model for relations and stuff like that.

**Comment by stancl** [comment]
Great, that's the right way. I'm thinking about removing TenantModel and DomainModel and using the `DB` facade instead, to make this less confusing.

**Comment by jonagoldman** [comment]
That's great! I think those models are confusing because you naturally want to work with them directly and extend them. I would personally also remove the domains table entirely and use a json column in the tenants table instead. You can save an extra database query and reduce complexity at the same time! You are already doing a similar thing with the 'data' column so, why not? You can have everything you need to manage a tenant in a single table, much easier. Also for performance reasons it's not recommended to have a table with a `varchar(255)` as primary key.

**Comment by stancl** [comment]
> domains table entirely and use a json column

Two things with that setup:
- I'm not sure if you can find a tenant using a domain at reasonable performance
- You don't have DB-level assurance that one domain can't belong to multiple tenants

**Comment by jonagoldman** [comment]
Uhm, you have 2 good points there, I think you are right.

**Comment by vishalinfyom** [comment]
This may be help : https://infyom.com/blog/how-to-use-multi-tenant-with-single-db
