### ISSUE TITLE
TDD Setup and Tear Down Creates a new DB each time tests run

### ISSUE THREAD

**Issue by drfraker** [archtechx/tenancy#176]
How do you set up and tear down tenants for testing? I can get my tests to work following the documentation. But, each test is creating a new database. Is there a "best practice" way to setup and tear down tests to avoid multiple databases each time? If so can you maybe share a bit of code as to how you are doing this?

**Comment by stancl** [comment]
> But, each test is creating a new database

It's how I do tests for this package.

Is that an issue because of performance or because you're using sqlite and it's bloating your database directory?

If the issue is performance, you could maybe use setUpBeforeClass. If the issue is that it's bloating your database directory, you probably do need a tear down. I'll send some code when I'm on my computer.

**Comment by drfraker** [comment]
I have an idea that might improve testing flow. I’ll submit a pr once I get to work. I’d still like to see an example of how you are doing though. Thank you.

**Comment by stancl** [comment]
I do this:

https://github.com/stancl/tenancy/blob/e98db460ecf8a25a5c5636df082fd7541240a9dc/tests/TestCase.php#L20-L50

and I use sqlite with `:memory:` as the DB driver for tests.

I don't use any `tearDown()`, since sqlite database files aren't an issue for me.

If you want to delete those files, you could do something like this in `tearDown()`:

```php
config(['tenancy.delete_database_after_tenant_deletion' => true]);

tenancy()->all()->each(function (Tenant $tenant) {
    $tenant->delete();
});
```

**Comment by drfraker** [comment]
I tried this in `tearDown()` at first:
```
config(['tenancy.delete_database_after_tenant_deletion' => true]);

tenancy()->all()->each(function (Tenant $tenant) {
    $tenant->delete();
});
```
But Laravel doesn't like it because the method `$this->getPdo()` in Iluminate/Database/Concerns/ManagesTransactions.php line 122 returns `null` and throws an error:
```
Error : Call to a member function beginTransaction() on null
 /*/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:122
```

Here's what I ended up with that seems to be working ok:
```
protected function tearDown(): void
    {
        // Delete all created databases. These are stored in a collection upon tenant creation.
        optional($this->createdDatabaseNames)->each(function ($dbName) {
            DB::statement("DROP DATABASE `$dbName`");
        });

        parent::tearDown();
    }
```

**Comment by stancl** [comment]
> But Laravel doesn't like it because the method $this->getPdo()

Do you have the `queue_database_deletion` config set to true by any chance? Some `getPdo()` errors on deletion are caused by a bug in 2.0.1.

**Comment by drfraker** [comment]
No, I just confirmed that it is set to false.

**Comment by stancl** [comment]
That's weird, looks like a bug. Can you delete tenants outside of the test environment?

**Comment by drfraker** [comment]
Yes that seems to work fine.

**Comment by stancl** [comment]
Is the stack trace in tests longer than just this?

```
 /*/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:122
```

**Comment by drfraker** [comment]
Here's the full stack trace:
```
Error : Call to a member function beginTransaction() on null
 /vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:122
 /vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:106
 /vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:24
 /vendor/stancl/tenancy/src/StorageDrivers/Database/DatabaseStorageDriver.php:136
 /vendor/stancl/tenancy/src/TenantManager.php:88
 /vendor/stancl/tenancy/src/Tenant.php:246
 /tests/TestCase.php:48
 /vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php:176
 /tests/TestCase.php:49
```
