### ISSUE TITLE
Authentication not presisting

### ISSUE THREAD

**Issue by mtctonyhkhk2010** [archtechx/tenancy#179]
#### Describe the bug
After Installed the package, login is no longer persisting. 
I tried to login using the Auth::loginUsingId(id); method, the authentication only persist in just the same request. If I refresh the page, it will be logged out.
Is that a configuration problem at my side? please help.

#### Steps to reproduce
1. Install the package
2. Authentication not persisting

#### Expected behavior
Authentication should persist

#### Your setup
 - Laravel version 6.0.4
 - stancl/tenancy version 2.0.1
 - Storage driver db

**Comment by jonagoldman** [comment]
How is the user authenticated? in a central database or in the tenant database?
Maybe related to this: https://github.com/stancl/tenancy/issues/57#issuecomment-541969091

**Comment by stancl** [comment]
Like @jonagoldman said, does this happen in the central app or the tenant app?

Also, is this in a fresh Laravel application?

**Comment by mtctonyhkhk2010** [comment]
I'm sorry I figured that out now, I set a wrong session domain path.
