### ISSUE TITLE
2.1.0 Tenant routes should be loaded after application routes

### ISSUE THREAD

**Issue by jonagoldman** [archtechx/tenancy#182]
#### Describe the bug
You cannot have conflicting routes like
`xyz.com` <-> `tenant1.xyz.com` or
`xyz.com/login` <-> `tenant1.xyz.com/login` or
`xyz.com/xyz` <-> `tenant1.xyz.com/xyz` ...

#### Expected behavior
I should be able to have `xyz.com` and `tenant1.xyz.com` without any conflict.

#### Proposed Fix
Tenant routes should be loaded **after** main application routes so the central domain will always have priority over the subdomain. Also a route domain must be specified on the main domain `Route::middleware('web')->domain(parse_url(config('app.url'))['host'])` in order for it to work.

#### Disclaimer
I'm not sure this will fix the issue in all scenarios, but there must be a way to avoid conflicts between routes as they are **not** the same, the subdomain is different. https://laravel.com/docs/6.x/routing#route-group-sub-domain-routing

**Comment by stancl** [comment]
This is not a bug, the documentation explains that this is the expected behavior.

Also, this is something Laravel is not built for, so it's quite problematic.

You can't just use domain routing, because it doesn't let you register the route for multiple domains.

Route:list wouldn't work.

You need to make sure you can't access central routes on tenant domains and vice versa.

I'm not aware of a solution with fewer tradeoffs than prefixing your tenant routes with /app.

**Comment by stockhausen** [comment]
only for home route "/"

```php
<?php

/*
|--------------------------------------------------------------------------
| Tenant Routes
|--------------------------------------------------------------------------
|
| Here you can register the tenant routes for your application.
| These routes are loaded by the TenantRouteServiceProvider
| with the tenancy and web middleware groups. Good luck!
|
*/


    Route::get('/', function () {
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });

    Auth::routes();

```

```php
<?php

declare(strict_types=1);

namespace Stancl\Tenancy;

use Illuminate\Foundation\Support\Providers\RouteServiceProvider;
use Illuminate\Support\Facades\Route;

class TenantRouteServiceProvider extends RouteServiceProvider
{
    public function map()
    {
        if (file_exists(base_path('routes/tenant.php'))) {
            Route::middleware(['web', 'tenancy'])
                ->domain(in_array(request()->getHost(), config('tenancy.exempt_domains')) ? null:request()->getHost())
                ->namespace($this->app['config']['tenancy.tenant_route_namespace'] ?? 'App\Http\Controllers')
                ->group(base_path('routes/tenant.php'));
        }
    }
}

```

and  this 

```php
<?php

declare(strict_types=1);

namespace Stancl\Tenancy\Middleware;

use Closure;
use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route as Router;

/**
 * Prevent access from tenant domains to central routes and vice versa.
 */
class PreventAccessFromTenantDomains
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        // If the domain is not in exempt domains, it's a tenant domain.
        // Tenant domains can't have routes without tenancy middleware.
        $isExemptDomain = in_array($request->getHost(), config('tenancy.exempt_domains'));
        $isTenantDomain = ! $isExemptDomain;

        $isTenantRoute = $this->isTenantRoute($request->route());

        if ($isTenantDomain && ! $isTenantRoute) { // accessing web routes from tenant domains
            return redirect(config('tenancy.home_url'));
        }

        
        if ($isExemptDomain && $isTenantRoute && $request->route()->uri !== '/') { // accessing tenant routes on web domains
            abort(404);
        }

        return $next($request);
    }

    public function isTenantRoute(Route $route): bool
    {
        if (in_array('tenancy', $route->middleware(), true)) {
            return true;
        }

        // Loop one level deep and check if the route's middleware
        // groups have a `tenancy` middleware group inside them
        $middlewareGroups = Router::getMiddlewareGroups();
        foreach ($route->gatherMiddleware() as $middleware) {
            if (isset($middlewareGroups[$middleware]) && in_array('tenancy', $middlewareGroups[$middleware], true)) {
                return true;
            }
        }

        return false;
    }
}

```

```shell
+-----------+----------+------------------------+----------------------+------------------------------------------------------------------------+-------------------+
| Domain    | Method   | URI                    | Name                 | Action                                                                 | Middleware        |
+-----------+----------+------------------------+----------------------+------------------------------------------------------------------------+-------------------+
|           | GET|HEAD | /                      |                      | Closure                                                                | web               |
| localhost | GET|HEAD | /                     |                      | Closure                                                                | web,tenancy       |
|           | GET|HEAD | api/companies          |                      | Closure                                                                | api,auth:api      |
|           | POST     | api/companies          |                      | Closure                                                                | api,auth:api      |
|           | GET|HEAD | api/user               |                      | Closure                                                                | api,auth:api      |
|           | GET|HEAD | home                   | home                 | App\Http\Controllers\HomeController@index                              | web               |
|           | GET|HEAD | login                  | login                | App\Http\Controllers\Auth\LoginController@showLoginForm                | web,guest         |
|           | POST     | login                  |                      | App\Http\Controllers\Auth\LoginController@login                        | web,guest         |
| localhost | POST     | login                  |                      | App\Http\Controllers\Auth\LoginController@login                        | web,tenancy,guest |
| localhost | GET|HEAD | login                  | login                | App\Http\Controllers\Auth\LoginController@showLoginForm                | web,tenancy,guest |
|           | POST     | logout                 | logout               | App\Http\Controllers\Auth\LoginController@logout                       | web               |
| localhost | POST     | logout                 | logout               | App\Http\Controllers\Auth\LoginController@logout                       | web,tenancy       |
| localhost | POST     | password/confirm       |                      | App\Http\Controllers\Auth\ConfirmPasswordController@confirm            | web,tenancy,auth  |
| localhost | GET|HEAD | password/confirm       | password.confirm     | App\Http\Controllers\Auth\ConfirmPasswordController@showConfirmForm    | web,tenancy,auth  |
|           | POST     | password/confirm       |                      | App\Http\Controllers\Auth\ConfirmPasswordController@confirm            | web,auth          |
|           | GET|HEAD | password/confirm       | password.confirm     | App\Http\Controllers\Auth\ConfirmPasswordController@showConfirmForm    | web,auth          |
| localhost | POST     | password/email         | password.email       | App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail  | web,tenancy       |
|           | POST     | password/email         | password.email       | App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail  | web               |
|           | POST     | password/reset         | password.update      | App\Http\Controllers\Auth\ResetPasswordController@reset                | web               |
| localhost | POST     | password/reset         | password.update      | App\Http\Controllers\Auth\ResetPasswordController@reset                | web,tenancy       |
| localhost | GET|HEAD | password/reset         | password.request     | App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm | web,tenancy       |
|           | GET|HEAD | password/reset         | password.request     | App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm | web               |
| localhost | GET|HEAD | password/reset/{token} | password.reset       | App\Http\Controllers\Auth\ResetPasswordController@showResetForm        | web,tenancy       |
|           | GET|HEAD | password/reset/{token} | password.reset       | App\Http\Controllers\Auth\ResetPasswordController@showResetForm        | web               |
|           | GET|HEAD | qr                     | home                 | App\Http\Controllers\HomeController@index                              | web               |
|           | GET|HEAD | qr/{token}             | home                 | App\Http\Controllers\HomeController@index                              | web               |
|           | POST     | register               |                      | App\Http\Controllers\Auth\RegisterController@register                  | web,guest         |
|           | GET|HEAD | register               | register             | App\Http\Controllers\Auth\RegisterController@showRegistrationForm      | web,guest         |
| localhost | POST     | register               |                      | App\Http\Controllers\Auth\RegisterController@register                  | web,tenancy,guest |
| localhost | GET|HEAD | register               | register             | App\Http\Controllers\Auth\RegisterController@showRegistrationForm      | web,tenancy,guest |
|           | GET|HEAD | tenancy/assets/{path}  | stancl.tenancy.asset | Stancl\Tenancy\Controllers\TenantAssetsController@asset                | tenancy           |
+-----------+----------+------------------------+----------------------+------------------------------------------------------------------------+-------------------+
```

**Comment by stockhausen** [comment]
this `&& $request->route()->uri !== '/'` is not necessary

**Comment by jonagoldman** [comment]
Laravel is built with a default main url that you must define:

```
// .env
APP_URL=http://xyz.com
```

So similar to what @stockhausen did, for the most common use case where that main domain is used, with additional tenant subdomains (`tenant1.xyz.com`,  `tenant2.xyz.com` ...) here is a simpler solution:

This package will load the routes in `tenant.php` before the main routes here:

```php
// TenantRouteServiceProvider.php
if (file_exists(base_path('routes/tenant.php'))) {
    /...
}
```

So you can delete `tenant.php` and create your own routes with a different file name, for example `app.php` and then manually load it with the tenancy middleware and load the main routes with the **domain specified**:

```php
// RouteServiceProvider.php

// load regular central routes before tenant routes
Route::middleware('web')
    ->domain(parse_url(config('app.url'))['host']) // the host set in .env (xyz.com)
    ->group(base_path('routes/web.php'));

// load tenants routes and apply 'tenancy' middleware
Route::middleware(['web', 'tenancy'])
    ->group(base_path('routes/app.php'));
```

Now you can have have the same path in both routes:

```php
// routes/web.php
Route::get('/', function () {
    return 'Home for: xyz.com';
});
```
```php
// routes/app.php
Route::get('/', function () {
    return 'Home for: ' . tenant('id');
});
```

**Comment by stancl** [comment]
@jonagoldman You can definitely do that. But I don't want to do this inside the package, because I support multiple exempt domains, which would mean registering the central routes for every single exempt (=central) domain using a foreach loop. I don't like that solution.

When I have more time I'll take a look at what @stockhausen suggested.

**Comment by jonagoldman** [comment]
@stancl I agree but I think the tenant routes should not be loaded automatically.
It is super easy to add your own routes and apply the tenancy middleware to them, and that gives you flexibility. You could also remove the `tenant_route_namespace` because that can also be easily defined in the route.

I just don't see why those things are preconfigured when it only takes 2 lines of code to add it yourself:

```php
Route::middleware(['web', 'tenancy'])->group(base_path('routes/tenant.php'));
```

**Comment by stancl** [comment]
In 1.x I think the conflicting routes were working, but there was some ugliness with the route:list and similar things. I believe what we have now (non-conflicting, always-registered routes in separate files) are good defaults that let users get started quickly.

Perhaps we could have a section in documentation about how it's possible to set up domain routing that lets you have conflicting routes? I just don't want that to be the default because of multiple exempt domains support & possible issues with route:list.

**Comment by jonagoldman** [comment]
@stancl I just recently came across this package and I'm very gratuful for it! I'm sure there is a reason for how things are done, probably better than they were before and I find this package really useful! But it's just very strange to me that this is not valid: `xyz.com`, `tenant1.xyz.com` by default.

**Comment by stancl** [comment]
If Laravel domain routing supported multiple domains, I would have registered central routes for `tenancy.exempt_domains` domains. But unfortunately, the only solution that would allow that would be to register all routes for each domain separately, like I said.

So since we can't use domain routing, we have to use path routing to avoid conflicting routes.

I do realize that this isn't ideal, so I'm still very open to suggestions regarding this issue.

**Comment by stockhausen** [comment]
Solution is just to add one Line to class TenantRouteServiceProvider extends RouteServiceProvider and keep all ADN of your package but offre possibilités to have same route un same class without conflict with php artisan route:list

**Comment by ahmedsayedabdelsalam** [comment]
![image](https://user-images.githubusercontent.com/29691074/162813456-c50c8d9f-0b17-40df-bff9-7b9c4c36d015.png)

shouldn't this solve the problem?

**Comment by ahmedsayedabdelsalam** [comment]
also if we want to support custom domains

```php
protected function mapRoutes()
{
    if (file_exists(base_path('routes/tenant.php'))) {
        Route::domain("{domain}")
            ->where(['domain' => '^(?!'. implode('|', config('tenancy.central_domains')) .').*'])
            ->namespace(static::$controllerNamespace)
            ->group(base_path('routes/tenant.php'));
    }
}
```

**Comment by haudv3202** [comment]
> chỉ dành cho tuyến đường về nhà "/"
> 
> ```
> <?php
> 
> /*
> |--------------------------------------------------------------------------
> | Tenant Routes
> |--------------------------------------------------------------------------
> |
> | Here you can register the tenant routes for your application.
> | These routes are loaded by the TenantRouteServiceProvider
> | with the tenancy and web middleware groups. Good luck!
> |
> */
> 
> 
>     Route::get('/', function () {
>         return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
>     });
> 
>     Auth::routes();
> ```
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace Stancl\Tenancy;
> 
> use Illuminate\Foundation\Support\Providers\RouteServiceProvider;
> use Illuminate\Support\Facades\Route;
> 
> class TenantRouteServiceProvider extends RouteServiceProvider
> {
>     public function map()
>     {
>         if (file_exists(base_path('routes/tenant.php'))) {
>             Route::middleware(['web', 'tenancy'])
>                 ->domain(in_array(request()->getHost(), config('tenancy.exempt_domains')) ? null:request()->getHost())
>                 ->namespace($this->app['config']['tenancy.tenant_route_namespace'] ?? 'App\Http\Controllers')
>                 ->group(base_path('routes/tenant.php'));
>         }
>     }
> }
> ```
> 
> và cái này
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace Stancl\Tenancy\Middleware;
> 
> use Closure;
> use Illuminate\Routing\Route;
> use Illuminate\Support\Facades\Route as Router;
> 
> /**
>  * Prevent access from tenant domains to central routes and vice versa.
>  */
> class PreventAccessFromTenantDomains
> {
>     /**
>      * Handle an incoming request.
>      *
>      * @param  \Illuminate\Http\Request  $request
>      * @param  \Closure  $next
>      * @return mixed
>      */
>     public function handle($request, Closure $next)
>     {
>         // If the domain is not in exempt domains, it's a tenant domain.
>         // Tenant domains can't have routes without tenancy middleware.
>         $isExemptDomain = in_array($request->getHost(), config('tenancy.exempt_domains'));
>         $isTenantDomain = ! $isExemptDomain;
> 
>         $isTenantRoute = $this->isTenantRoute($request->route());
> 
>         if ($isTenantDomain && ! $isTenantRoute) { // accessing web routes from tenant domains
>             return redirect(config('tenancy.home_url'));
>         }
> 
>         
>         if ($isExemptDomain && $isTenantRoute && $request->route()->uri !== '/') { // accessing tenant routes on web domains
>             abort(404);
>         }
> 
>         return $next($request);
>     }
> 
>     public function isTenantRoute(Route $route): bool
>     {
>         if (in_array('tenancy', $route->middleware(), true)) {
>             return true;
>         }
> 
>         // Loop one level deep and check if the route's middleware
>         // groups have a `tenancy` middleware group inside them
>         $middlewareGroups = Router::getMiddlewareGroups();
>         foreach ($route->gatherMiddleware() as $middleware) {
>             if (isset($middlewareGroups[$middleware]) && in_array('tenancy', $middlewareGroups[$middleware], true)) {
>                 return true;
>             }
>         }
> 
>         return false;
>     }
> }
> ```
> 
> ```shell
> +-----------+----------+------------------------+----------------------+------------------------------------------------------------------------+-------------------+
> | Domain    | Method   | URI                    | Name                 | Action                                                                 | Middleware        |
> +-----------+----------+------------------------+----------------------+------------------------------------------------------------------------+-------------------+
> |           | GET|HEAD | /                      |                      | Closure                                                                | web               |
> | localhost | GET|HEAD | /                     |                      | Closure                                                                | web,tenancy       |
> |           | GET|HEAD | api/companies          |                      | Closure                                                                | api,auth:api      |
> |           | POST     | api/companies          |                      | Closure                                                                | api,auth:api      |
> |           | GET|HEAD | api/user               |                      | Closure                                                                | api,auth:api      |
> |           | GET|HEAD | home                   | home                 | App\Http\Controllers\HomeController@index                              | web               |
> |           | GET|HEAD | login                  | login                | App\Http\Controllers\Auth\LoginController@showLoginForm                | web,guest         |
> |           | POST     | login                  |                      | App\Http\Controllers\Auth\LoginController@login                        | web,guest         |
> | localhost | POST     | login                  |                      | App\Http\Controllers\Auth\LoginController@login                        | web,tenancy,guest |
> | localhost | GET|HEAD | login                  | login                | App\Http\Controllers\Auth\LoginController@showLoginForm                | web,tenancy,guest |
> |           | POST     | logout                 | logout               | App\Http\Controllers\Auth\LoginController@logout                       | web               |
> | localhost | POST     | logout                 | logout               | App\Http\Controllers\Auth\LoginController@logout                       | web,tenancy       |
> | localhost | POST     | password/confirm       |                      | App\Http\Controllers\Auth\ConfirmPasswordController@confirm            | web,tenancy,auth  |
> | localhost | GET|HEAD | password/confirm       | password.confirm     | App\Http\Controllers\Auth\ConfirmPasswordController@showConfirmForm    | web,tenancy,auth  |
> |           | POST     | password/confirm       |                      | App\Http\Controllers\Auth\ConfirmPasswordController@confirm            | web,auth          |
> |           | GET|HEAD | password/confirm       | password.confirm     | App\Http\Controllers\Auth\ConfirmPasswordController@showConfirmForm    | web,auth          |
> | localhost | POST     | password/email         | password.email       | App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail  | web,tenancy       |
> |           | POST     | password/email         | password.email       | App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail  | web               |
> |           | POST     | password/reset         | password.update      | App\Http\Controllers\Auth\ResetPasswordController@reset                | web               |
> | localhost | POST     | password/reset         | password.update      | App\Http\Controllers\Auth\ResetPasswordController@reset                | web,tenancy       |
> | localhost | GET|HEAD | password/reset         | password.request     | App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm | web,tenancy       |
> |           | GET|HEAD | password/reset         | password.request     | App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm | web               |
> | localhost | GET|HEAD | password/reset/{token} | password.reset       | App\Http\Controllers\Auth\ResetPasswordController@showResetForm        | web,tenancy       |
> |           | GET|HEAD | password/reset/{token} | password.reset       | App\Http\Controllers\Auth\ResetPasswordController@showResetForm        | web               |
> |           | GET|HEAD | qr                     | home                 | App\Http\Controllers\HomeController@index                              | web               |
> |           | GET|HEAD | qr/{token}             | home                 | App\Http\Controllers\HomeController@index                              | web               |
> |           | POST     | register               |                      | App\Http\Controllers\Auth\RegisterController@register                  | web,guest         |
> |           | GET|HEAD | register               | register             | App\Http\Controllers\Auth\RegisterController@showRegistrationForm      | web,guest         |
> | localhost | POST     | register               |                      | App\Http\Controllers\Auth\RegisterController@register                  | web,tenancy,guest |
> | localhost | GET|HEAD | register               | register             | App\Http\Controllers\Auth\RegisterController@showRegistrationForm      | web,tenancy,guest |
> |           | GET|HEAD | tenancy/assets/{path}  | stancl.tenancy.asset | Stancl\Tenancy\Controllers\TenantAssetsController@asset                | tenancy           |
> +-----------+----------+------------------------+----------------------+------------------------------------------------------------------------+-------------------+
> ```

thanks support
