### ISSUE TITLE
Is it possible to set the 'home_url' in option to '/' or ''?

### ISSUE THREAD

**Issue by mtctonyhkhk2010** [archtechx/tenancy#183]
The default option for tenant 'home_url' is '/app', when I try to change it to '/', tenant website will keep redirecting and return 'too many redirects' error. Is it possible to set the 'home_url' in option to '/' or ''?

**Comment by stancl** [comment]
Sure, it can be /, but make sure / doesn't exist as a central route. Those redirects happen when you try to visit a central route on a tenant domain.
