### ISSUE TITLE
Assets for template (js, css, img and fonts)

### ISSUE THREAD

**Issue by paolobattistella** [archtechx/tenancy#184]
My assets for template (js, css, img and fonts) are not in storage path. They are in path /public/assets.
So I use mix('assets/css/app.css') instead of asset('assets/css/app.css') to load all resources needed within template.
The resources loaded by mix must be within mix.manifest.json. So I add this code within webpack.mix.js to update mix-manifest.

```javascript
const fs = require('fs');
const glob = require("glob");

// mix.webpackConfig({});
// mix.js().sass();
// [...]

/*
 * retrieve all files generated by mix in directory "public"
 * and update mix-manifest.json
 */
mix.then(function() {
    let rawdata = fs.readFileSync(__dirname+'/public/mix-manifest.json');
    let manifest = JSON.parse(rawdata);
    let files = glob.sync('@(css|js|fonts|img|vendor)/**', {
        matchBase:true,
        nodir: true,
        cwd: __dirname+'/public/',
    });
    files.forEach(file => {
        if (!manifest.hasOwnProperty('/'+file)) {
            manifest['/'+file] = '/'+file;
        }
    });
    fs.writeFileSync(__dirname+'/public/mix-manifest.json', JSON.stringify(manifest));
});
```

**Comment by stancl** [comment]
Sorry, what exactly is your question?

If you have issues with global assets, try the `global_asset()` helper, `mix(asset(...))`, or `mix(global_asset(...))`

**Comment by stancl** [comment]
`mix('js/app.js')` works correctly. It's probably best to use that for global template-related assets and use `asset()` for tenant data.

**Comment by paolobattistella** [comment]
mix('js/app.js') works fine about files listed into mix-manifest.json.
if you copy files from /resources/assets/img/ to /public/img/ using mix.copy('resources/assets/img', 'public/img') into webpack.mix.js, the file mix-manifest.json doesn't update with all resources of path /resources/assets/img/
Then I create a script to update mix-manifest.json with all resources listed into /public/img/
So I can use mix('img/logo.png').
