### ISSUE TITLE
Make sure sqlite works well with tests in a Laravel app

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#190]
- RefreshDatabase
- Running migrations for tenant databases seems to change the connection, such that the central DB no longer has a `tenants` table

**Comment by stancl** [comment]
`:memory:` is not supported because apparently switching the database to run commands inside a tenant's environment erases the previous `:memory:` database's data.

The docs will be updated to mention this.

**Comment by stancl** [comment]
Neither is `RefreshDatabase` apparently.

I'll leave this issue open because it would be nice to find a way to make these things work in the future.

**Comment by jezzdk** [comment]
Looking forward to this one. I've been having a lot of trouble getting my tests to work (I migrated from Hyn to this).

**Comment by stancl** [comment]
Look at the docs on app testing. You can use an sqlite file and everything will work.

**Comment by jezzdk** [comment]
I actually tried that already but to no avail. I tried all kinds of combinations, but I either get a `no such table: tenants` or a `no such table: users`.

I ended up disabling the package completely in tests, which mean I have to use a different setup if I want to test central only. But I can use the :memory: database which is much faster. This is what I ended up with:

```
use CreatesApplication, RefreshDatabase;

protected function setUp(): void
{
    parent::setUp();

    // We turn off the tenancy middleware, so that its like testing against a single tenant
    $this->withoutMiddleware([
        PreventAccessFromTenantDomains::class,
        InitializeTenancy::class
    ]);
}

/**
 * We overwrite this method to use tenant migrations and seeder
 */
protected function refreshInMemoryDatabase()
{
    $this->artisan('migrate', [
        '--path' => 'database/migrations/tenant',
    ]);

    $this->artisan('db:seed', [
        '--class' => 'TenantSeeder',
    ]);

    $this->app[Kernel::class]->setArtisan(null);
}
```

**Comment by stancl** [comment]
Strange, disabling RefreshDatabase and following the testing docs of this package (running migrations in setUp and using an sqlite file) works for me. I'll revisit this later today.

**Comment by devonmather** [comment]
SQLite is working for me as of 2.2. @jezzdk try removing RefreshDatabase from your tests. I can see it's being used in your last snippet.

**Comment by ravenberg** [comment]
Maybe a little bit off-topic but I would like to share how I use the `RefeshDatabase` trait during my tests.

```php
<?php

namespace Tests\Feature\Tenant

use Illuminate\Foundation\Testing\RefreshDatabase;

class DashboardTest extends Testcase
{
    use RefreshDatabase {
        beginDatabaseTransaction as parentBeginDatabaseTransaction;
    }

    public function beginDatabaseTransaction()
    {
        $tenantFQDN = 'tenant.myapp.test';

        config([
            'app.url' => 'http://' . $tenantFQDN,
            'tenancy.queue_database_creation' => false,
            'tenancy.exempt_domains' => [
                'myapp.test',
            ]
        ]);

        tenancy()->create($tenantFQDN);
        tenancy()->init($tenantFQDN);
        $this->artisan('tenants:migrate');
        $this->parentBeginDatabaseTransaction();
    }

  //... my tests ....
}
```

I basically override the `beginDatabaseTransaction()` method from the trait to setup tenancy right before the the db transaction starts. The caveat is that I only can use one database connection per written test.

This does not fix my issues with SQLite by the way. Instead I use the same DB Engine as I use during development.

**Comment by stancl** [comment]
@ravenberg Looks interesting. Thanks for sharing that. I'll take another look at making the `RefreshDatabase` trait work.

**Comment by antonkomarev** [comment]
My solution looks similar to @ravenberg solution. But I have issues with transactions when trying to run HTTP tests which using `Illuminate\Foundation\Testing\Concerns\MakesHttpRequests` trait.

```php
$user = factory(User::class)->create();

$response = $this->getJson("/users/{$user->id}");

$response->assertStatus(200);
```

I'm creating model in test using factory, and when I'm trying to make debug in FormRequest it looks like database is rolled back already. So transaction rollback starting before the HTTP call. That seems strange for me because all this tests were 100% working in single-tenant application.

**Comment by antonkomarev** [comment]
I've tested it more and found that methods of `FormRequest` in target endpoint executing before `beforeApplicationDestroyed` method, so the problem is hidden in transactions. I found similar issues with Dusk testing: https://github.com/laravel/dusk/issues/110

**Comment by stancl** [comment]
The testing setup is completely new now and there will be traits for transactions in tenant DBs soon.
