### ISSUE TITLE
Filesystem Disks - How to manage public disks?

### ISSUE THREAD

**Issue by radmanz** [archtechx/tenancy#201]
I currently have an issue where im unable to access a tenants files that have been sucessfully uploaded and stored within the _./storage/tenant_id/app/public/_ folder. 
I can upload files fine, and they reside within the _./storage/tenant_id/app/public/_ folder of the project.
My issue is that i cannot access the files from each tenant. I can only access a single tenants files by symlinking the _./storage/tenant_id/app/public/ -> ./public/storage_ . 

Can anyone give me some pointers as to how I am supposed to setup public storage access for each tenant, so as each tenant may continue to use something like the _/storage_ route to access public files. 
Is there a way  for _php artisan storage:link_ to faciliate the automation to symlink stoarge to publicly accessable folders? 

To give further context as to how my filesystem config is setup, please see the following disks array

```php
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```

You support is greafully appreciated 😊

**Comment by stancl** [comment]
Hi,

You can't make a symlink, because the storage directory is variable - it depends on the current tenant's id.

Try using `Storage::disk('public')` to store the files, and `tenant_asset('app/public/...')` to get a link to the asset.

**Comment by radmanz** [comment]
hi @stancl ,
Thanks for the help!
I was using _spatie/laravel-medialibrary_ in the case above which was the most confusing part. I found that tenant_asset() was able to parse the media object created by laravel-medialibary which has resolved my support ticket above.

**Comment by cameroncollector** [comment]
Hey @radmanz 

Would you mind sharing the code of how you were able to render images in blades? I'm having precisely the same issue of being able to easily upload files but unable to get them to display. Also are you retaining the default folder structure of:
Storage-->tenant[insert_id]-->app-->public

    Thanks in advance.

**Comment by stancl** [comment]
`<img src="{{ asset('foo.jpg') }}">` or `<img src="{{ asset('public/foo.jpg') }}">`

**Comment by phuclh** [comment]
> `<img src="{{ asset('foo.jpg') }}">` or `<img src="{{ asset('public/foo.jpg') }}">`

Using `asset` requires a full framework boot. If I have 10 images, that will boot the framework 10 times. Is that correct? Is there any way to access the tenant's image via: `Storage::disk('public')->url(tenant()->id . '/image.jpg');`?

Thank you for your help!

**Comment by stancl** [comment]
Can't find it right now, but there's some issue thread about this (the Storage url approach).

**Comment by andreaverrecchia** [comment]
The private images going under the path storage/app or storage/app/tenant/app?

**Comment by Bottelet** [comment]
@radmanz  @stancl. Is there any more information on this? 

I'm experiencing the same, but using `tenant_asset('app/public/') ` makes a URL looking like: `tenancy/assets/app/public` I am also using Spate image library, but have also tried uploading with `Storage::disk('public')->put("...)`  `asset` does not work either. But I can render images from the `storage/app/public`

**Comment by stancl** [comment]
Try `global_asset()`

**Comment by Bottelet** [comment]
@stancl No luck, I can do `global_asset('storage/'` which gets an image, if I moved it to the non-tenant folder, but I wanna access the images in the tenant storage folder.

**Comment by aroon9002ahmed** [comment]
Hello 
i have same problem with viewing image 
file uploaded on right location 
note: "tenantPTab_saad.sqlite" is my tenant id 
![image](https://github.com/user-attachments/assets/ddeb5842-2e74-4ed6-8ebe-b72604623787)

i'm have tried
{{ Storage::url('images/'.$config->value) }}
{{ asset('storage/images/'.$config->value) }}
{{ asset('app/public/images/'.$config->value) }}

all return 403 (Forbidden) error
![image](https://github.com/user-attachments/assets/038be773-8c25-4556-aeac-a73d08a9dd0a)


i'm using sqlite
