### ISSUE TITLE
Tenants Migrations

### ISSUE THREAD

**Issue by yashiroiori** [archtechx/tenancy#202]
Hi, good job.
I'm testing the package into my core to Erp, the app are modular and i need make migration to tentants all core migrations and after for each module as select user to use and then run migration and your seed from multiples locations depending the module selected, but cmd tenants:migration not take params --path

Command: php artisan tenants:migrate --path=Modules/ModuleName/Database/Migration

![image](https://user-images.githubusercontent.com/17031855/67516619-8a5da200-f666-11e9-9581-209562b07ccf.png)

**Comment by stancl** [comment]
Ah, nice catch. I'll fix that in 2.2.0. Thanks!

**Comment by yashiroiori** [comment]
Excellent, seeders work perfect using class to seeder from multiple locations

**Comment by stancl** [comment]
I'll leave this open so that I can see it in the 2.2.0 milestone.

**Comment by stancl** [comment]
@yashiroiori Could you try doing `composer require stancl/tenancy:dev-add-path-option` and testing if `--path` can be specified?

After you're done, don't forget to go back to the stable version constraint, `^2.1`.

**Comment by yashiroiori** [comment]
Hi.
Can't find dev-path

**Comment by stancl** [comment]
2.2.0 has been released already, so just use the stable version - `^2.2`

**Comment by yashiroiori** [comment]
Excellent work perfect, great job, it's wanderfull this package :+1:
