### ISSUE TITLE
Question regarding multiple route files for tenant based on active products.

### ISSUE THREAD

**Issue by wotta** [archtechx/tenancy#209]
Hello Samuel,

I have a question regarding the usage of multiple route files based on the active products of a tenant.

_Small recap:_
At this moment we use a bootstrapper to load in the route when the tenant has a specific product active.
This kinda works but makes it so that the `URL::signedRoute` function does not work for the routes in that route file. But we can visit the routes that are registered in the route file itself.

So we decided to figure out how the code is running and noticed that what we want is not directly going to work with the default setup for the tenancy service provider.

_Question:_
Would you recommend loading in the extra route files in the `tenant` route file and creating a middleware or do you know of another way to get the route files working correctly while only loading them when a tenant has a specific product?

**Comment by stancl** [comment]
Hi.

You could try to conditionally register the routes in your `RouteServiceProvider` and give them the `'tenancy'` MW group, but that's probably too late in the request lifecycle. I think after the URL generator is built, calling `Route::get()` won't work.

So you probably have to go with the middleware approach. To me, it feels cleaner than conditionally registering the routes anyway.

**Comment by wotta** [comment]
Hello Samuel,

Thanks for your answer. We went for the middleware approach and are making sure the route groups are always included.
I really appreciate your answer!

We got everything working as expected.
