### ISSUE TITLE
Cached tenant db lookup

### ISSUE THREAD

**Issue by viezel** [archtechx/tenancy#215]
#### Description

Today on each request we have 3 queries to the db:
- `select * from domains where domain = ? limit 1`
- `select * from tenants where tenants.id = ? limit 1`
- `select * from domains where tenant_id = ?`

This is quite fine for development, but will become a bottleneck as many request to db does not scale well. Instead using a key value store like redis will scale and can easily withhold this information.

#### Why this should be added
1. use the `globalCache` to store the those values (typically in redis) and add this cache check to the init process.
2. use tagging as Tenants can be changed/deleted and therefore cache invalidation on a specific tag.
3. (optional) - if developers have multiple tables related to the tenant in the "central" database, it could be performant to eager load those relationships and cache those. Hence, create a new config array to specify relationships what will go into a `->with([...])` statement.

**Comment by stancl** [comment]
> Instead using a key value store like redis will scale and can easily withhold this information.

The first solution that comes to mind is to use the provided [RedisStorageDriver](https://github.com/stancl/tenancy/blob/2.x/src/StorageDrivers/RedisStorageDriver.php) instead of the DB driver.

I can also imagine using a non-persistent Redis instance for caching the domain-to-tenant mapping while storing the actual data in a relational database. That could replace the first query.

The second query can't be avoided because you need to get the data.

The third query might be unnecessary, you usually don't need all of the tenant's domains. That data could be retrieved only when an attempt to access the `domains` property on a tenant is made. But I'm not sure if that complexity is worth the one saved database query.

**Comment by viezel** [comment]
I might be a bit old fashioned but I’m not a huge fan of persisting tenant info in redis as main db. 
But again, it’s up to the user of this package. 

I can show you how to avoid all the queries as our SaaS has that functionality. We could do a screen share session if you like? 

I’m interested in this package because it removes a lot of complexity from our app code. I really like this automatic vision :)

**Comment by stancl** [comment]
Since I'm not using Eloquent models for the DB storage driver, I guess I could easily push some of the work into the database layer?

Those 3 queries boil down to "find a tenant using $domain and get a list of his other domains", which I think could be turned into a single query that utilizes `JOIN`.

Would a single query be fine with you, @viezel? I feel like a cache layer can be a pain -- dealing with cache invalidation etc.

**Comment by viezel** [comment]
At scale we cannot handle a db call per request. Cause you cannot handle 300 req/s without buying a very big db server/service. 

I can show you some code of how to cache and handle invalidation effective. 

It can be an optional feature in the package if you want. But we need to pay attention to those extra db queries, due to its a query to global db, then switch connection. To tenant db, then handle any tenant logic and queries. 
It’s quite costly.

**Comment by stancl** [comment]
Hm, makes sense. Merging 3 queries into 1 doesn't solve the main issue of establishing an additional DB connection.

**Comment by viezel** [comment]
What we do is cache a eloquent user model with relations (tenants, features, whatever the app needs) in cache. 

The user lookup is handled once by db, then cached by its global_user_id  I. This cache call we tags the user by:
- tenant
- user_id

If the user is changed or any tenants belonging to the user is changed, or user is added/removed from a tenant, then we invalidate cache with user id and tenant id as cache tags. 

It’s quite effective to guard all those db calls

**Comment by viezel** [comment]
Forget to write that I think those relationships should be in the package config. So the developer can choose how much to put in the tenant/User identification cache

**Comment by viezel** [comment]
To elaborate on the above, ill share a bit of code. 

These below eloquent relations for the tenant are defined in a config file. This can be whatever is needed to run a SaaS. 

```php
/**
 * Tenant Relations that are loaded by default into cache
 */
'tenantRelations' => [
    'owner',
    'subscriptions',
    'additionalFeatures',
    'authSSOProvider',
    'storageProvider',
    'mailConfiguration'
],
```

Then we have a class to handle `GlobalCache` of Tenant identification. 

```php
/**
 * @param string $tenantId
 * @return Tenant|null
 */
protected function getTenantFromCache(string $tenantId): ?Tenant
{
    return $this->cache->tags(self::TENANT_CACHE_TAG)->get($tenantId);
}

/**
 * Get Tenant including all default relations
 * @param string $tenantId
 * @param Tenant|null $Tenant
 * @return void
 */
protected function putTenantToCache(string $tenantId, Tenant $tenant = null): void
{
    if (null !== $tenant) {
        $tenant = MasterDB::perform(function () use ($tenant) {
            return $tenant->load(self::$tenantRelations);
        });
    }

    $this->cache->tags(self::TENANT_CACHE_TAG)->forever($tenantId, $tenant);
}
```

When we run our TenantIdentification (typically within a http middleware), then we cache the results like this:

```php
public function getTenant(string $tenantId = null): ?Tenant
{
    $tenant = $this->getTenantFromCache($tenantId);

    if (null === $tenant) {
        $tenant = $this->getTenantFromDb($domain);
        $this->putTenantToCache($domain, $tenant);
    }

    return $tenant;
}

```


Now, if we refactor the `TenantManager` to handle caching of results and be able to get relations as well, then we can remove those costly db queries on each request. In `TenantManager` i see `find`, `findByDomain` and `findBy` that all could benefit from this cache. 

Another option would be to introduce a `StorageCacheDriver` that caches all `StorageDriver` get requests. 

Just ideas...

**Comment by stancl** [comment]
Seems like the best solution would be to add an interface for cache drivers and make `find`, `findByDomain` and possibly `findBy` look into cache before querying the actual storage driver.

And anything that causes the tenant's data/domains to be updated should probably invalidate the cache.

**Comment by viezel** [comment]
Yep! thats a great plan. 👍

**Comment by stancl** [comment]
I think the 20% solution that provides 80% of benefits will be to just map domains to tenant ids, and maybe tenant ids to tenant objects. Both caches should be relatively easy to invalidate.
