### ISSUE TITLE
Command: Change options tenants default to "none"

### ISSUE THREAD

**Issue by viezel** [archtechx/tenancy#219]
#### Description
Even though I understand the idea and easiness behind the following: 

```php
{--tenants= : The tenant(s) to run the command for. Default: all}
```

Then its a bit unexpected/dangerous to have a behaviour that runs on all tenants by default in production. Imagine with a mistake you ran `tenants:migrate-fresh` on all. 

#### Why this should be added
Change default to none and make it possible to set `--tenants=all` or `--tenants=*`

**Comment by stancl** [comment]
This would be a breaking change so it would be possible only in v3.

You should see a safety check prompt when running `migrate` or `migrate-fresh` in production, so I don't think this is an issue.
