### ISSUE TITLE
Authentication Problem On Tenant

### ISSUE THREAD

**Issue by iazdogar** [archtechx/tenancy#220]
Hi,

I have installed you package on fresh laravel installation.
I want to use authentication on Central and Tenant routes.
but when i implement Auth on both routes Central App Auth Routes works just fine. but Tenant App Routes login doesn't work.

I have separate Users table in Central App and Tenant

**Comment by hakanersu** [comment]
I am using different Model, Guard and different Controller for central app authentication. 
```
app
  - User.php
  - Central\User.php
```

- Central/User.php
```php
<?php

namespace App\Central;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    protected $connection= 'pgsql';

    protected $guard = 'warden';

    use Notifiable;
    ...
```

**Comment by stancl** [comment]
Hi.

The problem with what you're trying to do is that you can't register the same URL twice, so `Auth::routes()` will only work once. Wrapping the call in `Route::prefix('app/')->group(function () { ... });` might work.

In 2.2.0 it will be possible to use the same routes for both the tenant app and the central app.

**Comment by iazdogar** [comment]
Hi,
I have routes/tenant.php 
`Route::prefix('app/')->group(function(){
        Auth::routes();
    });`

And routes/web.php has
`Auth::routes();`

Now Authentication on my central domain works fine.
When i access subdomain it is redirected to login page, but in login form i see form is sending login post data to subdomain.mydomain.com/login instead of app/login
when i change form action on front end to send data to subdomain.mydomain.com/app/login it works fine on subdomain too.

it should check if it is central domain then login route should be central, and if it is subdomain then login route should be prefixed with app in login form

**Comment by stancl** [comment]
Well, you're using named routes and there can only be one route with a given name, so `route('login')` in the form returns `/login`. You could do `Route::prefix('app/')->name('app.')->group(...)` and `route('app.login')`

And then when 2.2 comes out you can refactor to using universal routes.

**Comment by stancl** [comment]
```php
Route::middleware('universal')->group(function () {
    Auth::routes();
});
```

**Comment by dir-clever** [comment]
Hi,
I have fresh Laravel and fresh v3 tenancy package installed. When I try to do authentication through common Laravel post request way by using function in Controller, the app treat central database instead of tenant database. Other thinks work fine, such as domain identification etc, I can retrieve data by User model through post request on tenant url and get data from right tenant database. 
My route in tenant.php:

` Route::post('/authenticate', 'Api\LoginController@authenticate'); `

or

`Route::middleware([
    'api',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::post('/authenticate', 'Api\LoginController@authenticate');
});`
return the same result

My LoginController function:

namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

public function authenticate(Request $request)
    {
        $credentials = $request->only('email', 'password');
        if (!Auth::attempt($credentials)) {
            return response('login failure');
        }else{
        	return response('is authenticated');
        }
    }

**Comment by mvksastry** [comment]
Hi, I have done a fresh installation Laravel 8.x, with Jetstream/Livewire and Stancl/tenancy. i am unable setup the routes and login. My login are returning 419 error. I dug a little bit and noticed when the form is served the encrypted csrf token info is stored in central domain db. At the time of authentication, it is unable to store in tenants db (where the using is trying to login). As a result i am getting 419 error. How to set-up routes and db configurations.. thanks for the hlep

**Comment by acacha** [comment]
> Hi, I have done a fresh installation Laravel 8.x, with Jetstream/Livewire and Stancl/tenancy. i am unable setup the routes and login. My login are returning 419 error. I dug a little bit and noticed when the form is served the encrypted csrf token info is stored in central domain db. At the time of authentication, it is unable to store in tenants db (where the using is trying to login). As a result i am getting 419 error. How to set-up routes and db configurations.. thanks for the hlep

@mvksastry... Same problem here, trying to find a solution...

**Comment by stancl** [comment]
Jetstream + tenancy has some known issues, this has been discussed on our Discord

**Comment by acacha** [comment]
Looking at this issue: https://github.com/stancl/tenancy/issues/344

**Comment by acacha** [comment]
> Jetstream + tenancy has some known issues, this has been discussed on our Discord

Ok I will connect to discord, Thanks

**Comment by fazalm13** [comment]
Hello,

I have the same problem as @iazdogar 
I'm able to login from the central app but not able to login from the tenant app in my local. Infact my tenant login page shows error.

My tenant login page shows the following error:

**Target class [Auth\LoginController] does not exist.** 

I have also configured universal setting from the documentation: https://tenancyforlaravel.com/docs/v3/features/universal-routes/
Also read the issue: #427  
Following Is my tenant route code:
```
Route::group(['middleware'=>['web',InitializeTenancyByDomain::class,PreventAccessFromCentralDomains::class]
],function () {
	Route::middleware(['universal'])->group(function () {
	    Auth::routes();
	});
	
	Route::middleware(['auth'])->group(function () {
	    Route::get('/', function () {
	        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
	    });
	});
});
```
Can you please tell me what am I missing? @stancl

**Comment by kylynangel15** [comment]
> Hi, I have fresh Laravel and fresh v3 tenancy package installed. When I try to do authentication through common Laravel post request way by using function in Controller, the app treat central database instead of tenant database. Other thinks work fine, such as domain identification etc, I can retrieve data by User model through post request on tenant url and get data from right tenant database. My route in tenant.php:
> 
> `Route::post('/authenticate', 'Api\LoginController@authenticate');`
> 
> or
> 
> `Route::middleware([ 'api', InitializeTenancyByDomain::class, PreventAccessFromCentralDomains::class, ])->group(function () { Route::post('/authenticate', 'Api\LoginController@authenticate'); });` return the same result
> 
> My LoginController function:
> 
> namespace App\Http\Controllers\Api; use App\Http\Controllers\Controller; use Illuminate\Http\Request; use Illuminate\Support\Facades\Auth;
> 
> public function authenticate(Request $request) { $credentials = $request->only('email', 'password'); if (!Auth::attempt($credentials)) { return response('login failure'); }else{ return response('is authenticated'); } }

have you resolved this issue? im encountering this passport login issue

**Comment by krlenix** [comment]
I experience the same issue. When logging, application is not doing Auth with Tenant's users table. How can I achieve this?

**Comment by damilareonifade** [comment]
I am also having the issue that whenever I try to authenticate users on my tenant application it's not authenticating the users. It seems it's checking the central database to authenticate the users

**Comment by z41dth3c0d3r** [comment]
> I am also having the issue that whenever I try to authenticate users on my tenant application it's not authenticating the users. It seems it's checking the central database to authenticate the users

Did you find the solution 😢?

**Comment by mvksastry** [comment]
> > I am also having the issue that whenever I try to authenticate users on my tenant application it's not authenticating the users. It seems it's checking the central database to authenticate the users
> 
> Did you find the solution 😢?

The new installation from V3 onwards, the issue settled. I have 4 four such installation and all four working. Check, central domains, tenant domain settings and route service providers. These have changes with respect to frame work. I have done for L8, L9 and L11 (latest). L11 needed lots of tweaks and entries differently as providers changed in L11.
