### ISSUE TITLE
[2.2] ErrorException  : Invalid argument supplied for foreach() TenancyServiceProvider.php:81

### ISSUE THREAD

**Issue by stockhausen** [archtechx/tenancy#222]
Hello, 

When install on a fresh laravel app pb on package discover. 

`php artisan package:discover --ansi`

`ErrorException  : Invalid argument supplied for foreach()`

```
foreach ($this->app['config']['tenancy.global_middleware'] as $middleware) {
    82|             $this->app->make(Kernel::class)->prependMiddleware($middleware);
    83|         }
```

**Comment by stancl** [comment]
I'm unable to reproduce this. Is it really a fresh Laravel app? Does `php artisan config:clear` help?

**Comment by stockhausen** [comment]
ok php artisan config:cleatr help
