### ISSUE TITLE
Best approach for API routes?

### ISSUE THREAD

**Issue by enkota** [archtechx/tenancy#223]
Hey, great package! Was looking to hear your thoughts on API routes with Tenancy.

I see Passport support was moved to 2.3. There are a couple ways I am wondering how this could work.

**Method 1:**
Users access their API data by `https://{tenant}.domain.com/api/{model}/data`
- This would involve adding the routes by group within the tenant. 

Tested the following on `2.2`, but doesn't seem to work with `auth:api`

**_routes/tenant.php_**
```
Route::middleware(['auth:api'])->prefix('api')->group(function () {
    //
    Route::get('test', function () {
        return 'test!';
    });
});
```
**Method 2:**
Users access their API data by `https://domain.com/api/{model}/data
- Believe we would need to make use of `tenancy()->initialize($tenant);` to check the tenant first then retrieve data for that tenant?

Which method would be best in this case? Personally I would love to be able for users to create their passport tokens from the base app then gather data via `Method 2`.

**Comment by stancl** [comment]
Hi. I've never used Passport but it's requested a lot so I'll look into it in the next few days.

Regarding API identification, create your own middleware that does something like `tenancy()->initializeTenancy(tenancy()->find($id))` based on the id coming in the request.

And then in your tenancy config remove the `InitializeTenancy` middleware from the global mw stack and add this one.

For inspiration, check out this middleware: https://github.com/stancl/tenancy/pull/207/files

**Comment by enkota** [comment]
Nice one! Will go see what I can do. Happy to test out some Passport things too!

**Comment by enkota** [comment]
Been playing about with `Method 2` route scenario. Not the cleanest, but something like this kind of works when the authenticated users `team` (in my case) is linked up to the `Tenant` model.

**Route:** `https://domain.com/api/{model}/data`
```
Route::group([
    'middleware' => ['auth:api']
], function () {
  Route::get('mea', function (Request $request) {

    $team = $request->user('api')->team->tenants()->first();

    $tenant = tenancy()->find($team->data['id']);

    tenancy()->initialize($tenant);
      return App\Post::all();
    tenancy()->end();

  });
});
```

Note: I am returning the data ID value here as the tenant()->id seems to return `0` instead of the actual `UUID`. Think this is related to [this issue](https://stackoverflow.com/a/35806332).

**Comment by stancl** [comment]
> Think this is related to this issue.
Are you using your own Tenant model or the one that was part of the package in 2.1.0? Just FYI it was removed in 2.2.0 because it was not intended for external use.

If you use closure routes instead of custom middleware, a refactor suggestion:
```php
return $tenant->run(function () {
    return App\Post::all();
});
```

instead of manually initializing & ending tenancy. Looks cleaner and returns the previous state of tenancy.

**Comment by enkota** [comment]
Perfect!

I created my own Tenant model in `2.1` so that I could reference the `team_id` from the Tenant. I was just reading you can configure so that `Team` for example can be referenced as the model instead which would clean things up?

**Comment by stancl** [comment]
> I created my own Tenant model

Okay.

If `Team` is the "tenant entity" in your app, then yeah, setting `protected $table = 'tenants'` on that model is ideal.

**Comment by enkota** [comment]
I think I will go ahead with `Method 2` so users can access the API via `https://domain.com/api/{model}/data`

In terms of performance, do you see accessing each tenant DB through the central domain first an issue, or should I go with `Method 1` by access API data via their subdomain?

**Comment by stancl** [comment]
Method 2 should be okay. Nothing really happens when you visit a central domain so there shouldn't be any extra queries I think (but feel free to verify this in Telescope or Debugbar).

The main benefit that I see in going with method 1 is that your frontend is simpler. You just send a request to `/api/foo` and don't have to deal with any explicit tenant id stuff.

**Comment by enkota** [comment]
Okay, thanks for the feedback! Yeah, that's true... I guess the downside to `Method 1` means I need to look at Passport auth from the central store anyway. Will follow along with the Passport updates. Cheers!

**Comment by stancl** [comment]
Closing this, Passport-related updates will be posted to #200

**Comment by enkota** [comment]
Closing this, Passport-related updates will be posted to #200 ...


👍
