### ISSUE TITLE
Support Impersonation

### ISSUE THREAD

**Issue by viezel** [archtechx/tenancy#224]
#### Description
Being able to impersonate a user.
Since this is a multi tenancy - multi domain package, we need to add a specific version of Impersonation, as a user can belong to multiple tenants.

### Use case
A system admin wants to impersonate a user from a tenant (e.g. to offer support). By impersonating the user, the system admin will:

1. Impersonate the user
2. Be redirected to the tenant domain

## Requirements

- [ ] User->canImpersonate()
- [ ] User->impersonate()
- [ ] User->isImpersonating()
- [ ] User->stopImpersonating()
- [ ] Store current tenant and user id in session in order to come back

## Example code

```php
public function impersonate(User $currentUser, Tenant $tenant, User $user)
{
    session()->flush();
    session()->put('tenancy:impersonator', [
        'id' => $currentUser->id,
        'tenant' => $tenant->id
    ]);

    // switch domain if needed
    if (! tenancy()->isCurrent($tenant)) {
        tenancy()->switchToTenant($tenant);
    }

    Auth::login($user);

    return redirect()->route('/')->tenant($tenant->getDomain());
}

public function stopImpersonating()
{
    if (! session()->has('tenancy:impersonator')) {
        Auth::logout();

        return redirect('/');
    }

    $impersonator = session()->pull('tenancy:impersonator');
    session()->flush();

    $tenant = tenancy()->FindById($impersonator->tenant);
    Auth::login(tenancy()->user()->findOrFail($impersonator->id));

    return redirect()->route('/')->tenant($tenant->getDomain());
}
```

**Comment by viezel** [comment]
Icing on the cake would be an simple way to access these methods. Something like 

tenancy()->user->isImpersonating();

**Comment by stancl** [comment]
So the goal is to impersonate *any* user in a tenant's database?

**Comment by viezel** [comment]
yeah, thats the goal. In a SaaS you often get a customer support message, like "When I do this, then an error occurs". Then we use impersonation to see how the exact user does. Its super helpful to resolve customer support cases.

**Comment by viezel** [comment]
First time we built it, we started by allowing to impersonate only the tenant owner. but actually it was the exact same implementation to support any user. 😄

**Comment by stancl** [comment]
> By impersonating the user, the system admin will:
> 1. Impersonate the user
> 2. Be redirected to the tenant domain

This can be implemented in two ways.

One would be to have global identifiers for users and use that (in some central admin panel). And the other is to just specify the tenant id and user id.

**Comment by stancl** [comment]
> - User->canImpersonate()
> - User->impersonate()
> - User->isImpersonating()
> - User->stopImpersonating()
> - Store current tenant and user id in session in order to come back

This sounds unnecessarily complex. Why not just have one route that redirects you to the tenant's domain, signed in as a specific user?

Also the redirect can't be automatic, it can't know what domain to use.

**Comment by viezel** [comment]
sure @stancl. All features come in various sizes. do the MVP first. :)

**Comment by stancl** [comment]
I'm starting to feel like this is very specific to the application and easy to implement. There's so many ways this can be done. Redirect from some central admin panel to a route on a tenant domain, impersonate a user from a tenant database in some other code, etc. I'm putting this off and if someone can give me example use cases, I can work on this again.

**Comment by masterix21** [comment]
A solution could be a command "tenants:login <id|email>" to generate a signed URL that login.

**Comment by stancl** [comment]
That would work for some implementation. The logic could be taken from here: https://github.com/stancl/tenancy/issues/194#issuecomment-552500495

**Comment by stancl** [comment]
Done in v3.
