### ISSUE TITLE
Extend Eloquent Model instead of just ArrayAccess

### ISSUE THREAD

**Issue by viezel** [archtechx/tenancy#225]
#### Description
Change Stancl\Tenancy\Tenant to extend Illuminate\Database\Eloquent\Model  instead of ArrayAccess. 

#### Why this should be added
In order to use the Tenant model for various patterns in the Laravel framework like: Observer, guards, eloquent builder, then it must extend the Illuminate\Database\Eloquent\Model. 
Laravel ecosystem tools like Scout and Nova relies on Illuminate\Database\Eloquent\Model classes.

**Comment by stancl** [comment]
I might refactor the DB storage driver to use models (in 2.2.0 I refactored *away* from that solution because it was very messy). But `Stancl\Tenancy\Tenant` definitely can't be a model because it's independent of the underlying storage. Also it would introduce a lot of bloat and messiness.
