### ISSUE TITLE
How to install it on laravel nova

### ISSUE THREAD

**Issue by techguydev** [archtechx/tenancy#228]
Hello, thanks a lot for sharing this package.

I've tried to follow  all the steps to install this software when using Laravel Nova but I can not get it to work properly.

I am able to create new tenants and access the proper url, when showing the nova login screen I can not login, how can I create users specific for a tenant?

I've tried to run  ' php artisan nova:user ' but it just try to add it to the central  app

Thanks ahead

**Comment by stancl** [comment]
Hi,

You can try doing something like this:

```php
$tenant->run(function () {
    Artisan::call('nova:user', [
        // args
    ]);
});
```

If you want to do this from the console, `php artisan tenants:run --tenants=<tenant_id> nova:user`

**Comment by techguydev** [comment]
> Hi,
> 
> You can try doing something like this:
> 
> ```
> $tenant->run(function () {
>     Artisan::call('nova:user', [
>         // args
>     ]);
> });
> ```
> 
> If you want to do this from the console, `php artisan tenants:run --tenants=<tenant_id> nova:user`

Fantastic!, I will test it!, thanks a lot for sharing this wonderful package!, it open endless possibilities.

**Comment by techguydev** [comment]
@stancl  I have tried your recommendation and it works like a charm, I have been able to install the Role and permission package for nova and it works nicely, I will try to make a video soon to share with the community the setup, thanks ahead for sharing this wonderful package.

**Comment by stancl** [comment]
Glad to hear that.

> I will try to make a video soon to share with the community

Sounds great, thanks!
