### ISSUE TITLE
Cache store does not support tagging (Laratrust)

### ISSUE THREAD

**Issue by Qwans** [archtechx/tenancy#231]
I tried to install Laratrust for roles and permission.
But when I add the "LaratrustUserTrait" to my User Model it gives me an error:
"This cache store does not support tagging"

More details: [https://flareapp.io/share/DPyGVJ59#F69](url)

How could I solve this? I read on google people suggest to change CACHE_DRIVER in ENV to array, but this doesn't work for me.

**Comment by stancl** [comment]
Hi. If you want your cache to be tenant-aware, you need to use a driver that supports tagging, e.g. Redis.

If you don't need tenant-aware cache, comment out the CacheTenancyBootstrapper in your tenancy.php config file.

**Comment by Qwans** [comment]
Thanks I commented out the CacheTenancyBootstrapper and that solved it. Will look into Redis in the future!

**Comment by stancl** [comment]
Glad it works :)

If you ever need to use caching in your app, Redis is a really good option.

It's extremely performant and it requires practically zero configuration. Just install it and set the cache driver to Redis.

And if you want to learn about using Redis yourself, not just through Laravel's cache, I recommend this course on Laracasts: https://laracasts.com/series/learn-laravel-and-redis-through-examples
