### ISSUE TITLE
facade/ignition-contracts should be part of require instead of require-dev

### ISSUE THREAD

**Issue by lbausch** [archtechx/tenancy#232]
#### Describe the bug

My Laravel project does not have `facade/ignition` installed, so some exceptions thrown by `stancl/tenancy` end with 

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Interface 'Facade\IgnitionContracts\ProvidesSolution' not found
```
This is because `facade/ignition-contracts` is only part of `require-dev` not `require` in `composer.json`

#### Steps to reproduce
Remove `facade/ignition` from project and trigger exception, e.g. `TenantCouldNotBeIdentifiedException`

#### Expected behavior
See the real exception `TenantCouldNotBeIdentifiedException` instead of `Interface 'Facade\IgnitionContracts\ProvidesSolution' not found`

This works if `facade/ignition-contracts` is installed manually.

#### Your setup
 - Laravel version: 6.5.2
 - stancl/tenancy version: 2.2.0
 - Storage driver: database

**Comment by stancl** [comment]
Hi,

thanks for reporting this. Fixed in https://github.com/stancl/tenancy/commit/4e477b472feff93fdfe6d4a23963b5e295171dc9.

After tests in CI pass, I'll tag 2.2.1. So in about 10 minutes, running `composer update` should fix this.

**Comment by lbausch** [comment]
awesome! :+1:
