### ISSUE TITLE
Laravel Spark integration

### ISSUE THREAD

**Issue by mick340** [archtechx/tenancy#233]
Hi, is there any support for Laravel Spark? Im using laravel spark for teams so if somebody is going to register a new team i want a tenancy for that team. 

So for example if i create a new team called Test, i want a test.mydomain.com tenanct. 

I hope this will be added soon or if someone could help me that would be nice.

**Comment by stancl** [comment]
Hi. Documenting Spark integration is planned, but it's not of high priority at the moment.

The exact thing you're describing sounds like you want to listen to a "team was created" event and do `Tenant::new()` with the tenant's data and domains.

**Comment by BeniSt** [comment]
Hi, would it be possible with for example financial support to give this feature a higher priority? ;)

**Comment by mick340** [comment]
> Hi. Documenting Spark integration is planned, but it's not of high priority at the moment.
> 
> The exact thing you're describing sounds like you want to listen to a "team was created" event and do `Tenant::new()` with the tenant's data and domains.

That is what im trying to do, but also de routing isnt working because of the tenancy routes

**Comment by stancl** [comment]
To mark the routes as tenant routes, apply the `'tenancy'` middleware group to Spark routes.

I think this should be somewhat similar to Nova integration: https://tenancy.samuelstancl.me/docs/v2/nova/

**Comment by mick340** [comment]
> To mark the routes as tenant routes, apply the `'tenancy'` middleware group to Spark routes.
> 
> I think this should be somewhat similar to Nova integration: https://tenancy.samuelstancl.me/docs/v2/nova/

Oke thankyou i will give it a try

**Comment by mick340** [comment]
> Hi. Documenting Spark integration is planned, but it's not of high priority at the moment.
> 
> The exact thing you're describing sounds like you want to listen to a "team was created" event and do `Tenant::new()` with the tenant's data and domains.

I guess I have to do this before a team is registered? Because all of the team stuff isn't in the apps DB anymore this will be in the tenant right?

**Comment by stancl** [comment]
I hope to look into Spark soon. Right now I'm sorry, but I don't know enough about Spark to help with that.

You need to decide what should be in the central database and what should be in the tenant databases. If teams = tenants, then teams should be in the central database.

I recommend reading through this package's docs. They might help with these things.

**Comment by stancl** [comment]
@BeniSt

> Hi, would it be possible with for example financial support to give this feature a higher priority? ;)

That would be very much appreciated. Though I don't have a Spark license and I can't promise if I can realistically get to this soon, so I don't want to get donations for a feature that I'm not sure I can make happen. Maybe I could help you integrate this package into a Spark app and then document the process?

**Comment by mick340** [comment]
> @BeniSt
> 
> > Hi, would it be possible with for example financial support to give this feature a higher priority? ;)
> 
> That would be very much appreciated. Though I don't have a Spark license and I can't promise if I can realistically get to this soon, so I don't want to get donations for a feature that I'm not sure I can make happen. Maybe I could help you integrate this package into a Spark app and then document the process?



> To mark the routes as tenant routes, apply the `'tenancy'` middleware group to Spark routes.
> 
> I think this should be somewhat similar to Nova integration: https://tenancy.samuelstancl.me/docs/v2/nova/

Sadly for Spark there is no such thing as a config file like Nova has, so can't place the tenancy middleware. Could be cool if we can figure this out together

**Comment by stancl** [comment]
Isn't there a `SparkServiceProvider` or something?

**Comment by BeniSt** [comment]
@stancl I will of course give you access to a new and empty spark installation. It would be fantastic, if you will have a look how to integrate this.

**Comment by stancl** [comment]
@BeniSt Could you contact me on [Telegram](https://t.me/samuelstancl) or Discord?

**Comment by stancl** [comment]
Decided to not do this. Spark is too old.

**Comment by jetwes** [comment]
What's up with spark next?
