### ISSUE TITLE
HTTPS certificates

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#236]
It would be nice if the package could help with issuing HTTPS certificates when using the `yourapp.client1.com` model.

The idea is that the client should be able to just add an `ALIAS` record in their DNS and the app would take care of the rest.

I originally opened an issue for this in January: #11 

There are multiple ways to solve this:
- use an ACME PHP library to generate the certificates using the HTTPS challenge
  - use the nginx lua module to load certificates ([`ssl_certificate_by_lua_block`](https://github.com/openresty/lua-nginx-module#ssl_certificate_by_lua_block))
- create vhost, let certbot take care of the certificates, call `service nginx reload` from PHP
  - probably the simplest solution, though reloading nginx from PHP feels ugly
- CloudFlare
- Traefik
- [SNA certs](https://tighten.co/blog/serving-multiple-ssl-encrypted-domains-from-one-application-in-nginx) - but this means doing an ACME challenge for all existing domains when adding a new one and still reloading the webserver from PHP, so this is just more complexity at no benefit

Feedback from anyone who has experience with this would be very much appreciated.

**Comment by viezel** [comment]
This can be used https://certbot.eff.org/ and this guide: https://medium.com/@omerkarabacak/generate-wildcard-ssl-certificate-with-letsencrypt-and-use-at-nginx-6fe41ff346bd

but it might be outside of the scope of this project as there are many ways to host a website. 🤷🏻‍♂️

**Comment by ssatz** [comment]
could you please check out this package [https://github.com/GUI/lua-resty-auto-ssl](https://github.com/GUI/lua-resty-auto-ssl) .

Here Redis storage adapters can be used to query the host name and save the certificates. 
I haven't tried  but am considering it for one of my project.

**Comment by stancl** [comment]
@viezel When you can use wildcard certs, this is basically a non-issue. I'm talking about the yourapp.client1.com model (I fixed this in my original comment).

@ssatz I will take a look at that. Thanks for sharing.

**Comment by iulit** [comment]
Just checking this package and saw this issue.

A while ago I did a multi-tenant app that also had to generate certificates (and renew them automatically) and I ended up using https://github.com/yourivw/LEClient. Might be helpful.
