### ISSUE TITLE
tenant_route() helper method should accept mixed $parameters

### ISSUE THREAD

**Issue by seanmtaylor** [archtechx/tenancy#241]
#### Describe the bug
The `tenant_helper()` method has a `$parameters` parameter.

This is currently set to accept an `array`.

It should be left as mixed to allow for non-arrays to be used, just like the `route()` helper method.

#### Steps to reproduce
1. `tenant_route('foo', $bar)`

#### Expected behavior
Using `tenant_route('foo', $bar)` should work in the same way that `route('foo', $bar)` would work.

#### Your setup
 - Laravel version: 6.6.0
 - stancl/tenancy version: 2.2.2
 - Storage driver: Database

**Comment by stancl** [comment]
Hi, thanks for reporting. Nice catch.

Can you make a PR that removes the typehint?

**Comment by stancl** [comment]
Fixed.

**Comment by seanmtaylor** [comment]
That was quick, thanks @stancl :+1:
