### ISSUE TITLE
Override tenancy assets

### ISSUE THREAD

**Issue by t-prod** [archtechx/tenancy#246]
Hi,

For admin routes I would like to avoid tenancy assets. Is this possible and how can I do ?

**Comment by stancl** [comment]
Hi,

If the assets are JS/CSS, you can use Laravel Mix's `mix()` helper. If you don't use mix, you can use `global_asset()`.

See here: https://tenancy.samuelstancl.me/docs/v2/central-app/#central-assets

**Comment by t-prod** [comment]
Hi and thanks for your answer. global_asset() is the perfect answer I close the support issue ;)
