### ISSUE TITLE
Error in urls when uploading images to Trix field in Nova

### ISSUE THREAD

**Issue by buzkall** [archtechx/tenancy#248]
When using Nova and Trix field, if an image is uploaded to public disk the preview shows correctly and it's stored in the nova_pending_trix_attachments. But when saving the resource, the line in nova_pending_trix_attachments is moved to nova_trix_attachments and linked to the resource, but the url of the asset it's not correct (it's like: http://domain/storage/filename), so it gets added to the resource incorrectly.

I've tried to override the attach function in the Nova resource with no success.
I'm creating the resource like this:

            Trix::make(__('body'), 'body')
                ->withFiles('public')
                ->hideFromIndex()
                ->rules('required'),

I'm using the latests versions of Laravel, Nova and Stancl/Tenancy

![error](https://user-images.githubusercontent.com/5702/70976617-8d946d80-20ac-11ea-8dd5-8f50291fc4d9.png)

**Comment by stancl** [comment]
Hi,

Hmm, that's a bit hard to debug for me. Do you think you could give me read access to the repository?

You can also DM me on Telegram [@samuelstancl](https://t.me/samuelstancl).

**Comment by phuclh** [comment]
Temporary fix for that: Create a disk and don't add it in the tenancy config file.

```
Trix::make('Description')
                    ->withFiles('app-public')
                    ->path('tenant/products/' . tenant()->id),
```

**Comment by Dontorpedo** [comment]
this worked for me:

Adding to AppServiceProvider.php

```
        config(['filesystems.disks.public.root' => storage_path('/app/public'),]);
        config(['filesystems.disks.public.url' => asset('/tenancy/assets'),]);
```

**Comment by sicaboy** [comment]
> this worked for me:
> 
> Adding to AppServiceProvider.php
> 
> ```
>         config(['filesystems.disks.public.root' => storage_path('/app/public'),]);
>         config(['filesystems.disks.public.url' => asset('/tenancy/assets'),]);
> ```

That works for me. Thanks

**Comment by stancl** [comment]
Nova support will no longer be a primary feature and will soon be replaced with [Lean](http://lean-admin.dev/), which will focus on working with this package perfectly.
