### ISSUE TITLE
Initialize tenancy outside tenant routes

### ISSUE THREAD

**Issue by mcsystemen** [archtechx/tenancy#251]
Hi there,

I was hoping someone can help me out with the following.

I'm using tenancy in combination with Nova to manage multiple customers. All those customers have their own database with only 1 table in it. In nova I made a resource to manage this data, but when loading this resource it is only displaying the data from the default database.

Is it possible to initialize a tenant database based on for example some prameter data from the visited url. Or to choose from a dropdown select which contains all of the tenant options available.

I hope my question makes sense.

Thanks

**Comment by stancl** [comment]
Hi,

Maybe this can help? https://tenancy.samuelstancl.me/docs/v2/tenancy-initialization/#tenancy-initialization

And if you want to initialize tenancy just for a few commands, you can use `$tenant->run()`: https://tenancy.samuelstancl.me/docs/v2/tenants/#run
