### ISSUE TITLE
Home route for both tenants and central

### ISSUE THREAD

**Issue by Flerex** [archtechx/tenancy#252]
Hello,

I just installed the package and after reading the documentation I think I fell in love with it.

However, I'm trying to make a site where its tenants will be public, so I need to both the tenant and the central to have a `/` route. I have read in the documentation that there cannot be collisions between routes, but I think it's kind of strange that, especially on my case, this is not possible.

Am I missing something? Is there a way to do what I'm trying to do?

**Comment by stancl** [comment]
Hi,

Admittedly it might be somewhat poorly placed in the documentation, but conflicting routes are documented here: https://tenancy.samuelstancl.me/docs/v2/tenant-routes/#conflicting-routes

**Comment by Flerex** [comment]
Oh, right. I did read that but I was understanding another thing. Sorry for this. 😂

Thank you!

**Comment by stancl** [comment]
No worries :) Hope everything works now.
