### ISSUE TITLE
How to make it work with nWidart/laravel-modules

### ISSUE THREAD

**Issue by coding-sunshine** [archtechx/tenancy#255]
Hi I am using https://github.com/nWidart/laravel-modules
in my projects and want to use stancl/tenancy along with that, how can I make stancl/tenancy aware of Modules database migrations?

**Comment by stancl** [comment]
You could dynamically change the `tenancy.migrations_directory` config - see this: https://github.com/stancl/tenancy/issues/130#issuecomment-568178508

**Comment by Mo7mud** [comment]
> You could dynamically change the `tenancy.migrations_directory` config - see this: [#130 (comment)](https://github.com/archtechx/tenancy/issues/130#issuecomment-568178508)

What changes should we do?
I'm having very difficult time trying to use these two packages together

**Comment by a-di-ez** [comment]
@coding-sunshine @EgyptianM any solution?

**Comment by Mo7mud** [comment]
> @coding-sunshine @EgyptianM any solution?

Unfortunately no and the support is very bad for this library.

**Comment by MusheAbdulHakim** [comment]
One way is to make use of the **glob** function. Modify tenancy config file **migration_parameters**

```
/**
     * Parameters used by the tenants:migrate command.
     */
    'migration_parameters' => [
        '--force' => true, // This needs to be true to run migrations in production.
        '--path' =>array_merge(
            glob(database_path('migrations')),
            glob(base_path('/Modules/**/database/migrations/tenant')),
        ),
        '--realpath' => true,
    ],
```

With this, **php artisan tenants:migrate** will migrate all migration files under 'tenant' folder of your module
