### ISSUE TITLE
Exception thrown when adding middleware closure

### ISSUE THREAD

**Issue by hakanersu** [archtechx/tenancy#256]
#### Describe the bug
When we use middleware closure in controller an exception is thrown. Exception is;
```
Illegal offset type in isset or empty 
```
Throwns in 
```php
PreventAccessFromTenantDomains.php:63
...
if (isset($middlewareGroups[$inner]) && in_array($middleware, $middlewareGroups[$inner], true)) 
```

Example middleware

```php
public function __construct()
{
      $this->middleware(function ($request, $next) {
          return $next($request);
      });
}
```

```$inner``` variable returns a Closure
#### Steps to reproduce
Add a middleware closure to a controller.

#### Expected behavior
Middleware must be working as expected.

#### Your setup
 - Laravel version: 6.7.0
 - stancl/tenancy version: 2.2.3
 - Storage driver: DB

**Comment by stancl** [comment]
Could you try if replacing this line:

https://github.com/stancl/tenancy/blob/fed8c0f9d11c26c03c66809e815b4b04e6b257f9/src/Middleware/PreventAccessFromTenantDomains.php#L58

with

```php
if (isset($middlewareGroups[$inner]) && is_array($middlewareGroups[$inner]) && in_array($middleware, $middlewareGroups[$inner], true)) {
```

fixes this?

**Comment by hakanersu** [comment]
Sorry it isn't fixes. Because $inner variable is a closure. Dump of the $inner variable
![image](https://user-images.githubusercontent.com/1052467/71487651-ac71cd00-282d-11ea-9540-c13a3bc57a41.png)

**Comment by stancl** [comment]
I see. So it probably has to be:

```php
if (! $inner instanceof \Closure && isset($middlewareGroups[$inner]) && in_array($middleware, $middlewareGroups[$inner], true)) {
```

**Comment by hakanersu** [comment]
Yes it fixes. :+1:

**Comment by stancl** [comment]
I'll tag v2.2.5 in a few minutes.
