### ISSUE TITLE
Question: How to implement Google login with socialite?

### ISSUE THREAD

**Issue by code-reflex** [archtechx/tenancy#258]
If we are going to have tenant wise users (i.e., users table is moved under tenant), how can we implement socialite based google auth? We need to specify a callback/redirect URL and we will have a different URL for each tenant (because of the subdomain - tenant1.example.com, tenant2.example.com...)

This callback/redirect URL need to be added into Google's portal & hence I dont see any way to handle wildcards (unless Google supports wildcards for subdomain) due to this.

A possible solution will be to use IP address (since all subdomains too are served by the same IP:port) in the callback URL that we specify in Google, but I was wondering if
a) we can have a more elegant solution here for multi tenant setups  & (or)
b) Is it a mistake to move the users table to tenant folder itself?

**Comment by stancl** [comment]
Hi.

> Is it a mistake to move the users table to tenant folder itself?

Definitely not, that's how most apps do this.

As for a more elegant solution, assuming your [`redirect` configg(https://laravel.com/docs/6.x/socialite#configuration) has the right (tenant-specific) URL and the only issue is adding the URL to Google's portal, I think you have two options:
- Hook into the `tenant.created` event and use some sort of Google API to add this host
- Just use the IP address.

Honestly if Google is fine with an IP address, I'd just go with that.
