### ISSUE TITLE
Make asset() tenancy optional

### ISSUE THREAD

**Issue by lasselehtinen** [archtechx/tenancy#259]
Hi,

I am having somewhat issues including Horizon and the documentation is not quite clear. What I have done is installed Horizon and added the "universal" middleware on config/horizon.php. But when I try to load /horizon the js and css assets are referenced to the tenant instead of globally.

`http://hostaname/tenancy/assets/vendor/horizon/app.js?id=f41217b645f8cd9ffacc`

The [Horizon blade layout is using asset() helper](https://github.com/laravel/horizon/blob/3.0/resources/views/layout.blade.php#L14) so shouldn't it call it from the /vendor/horizon instead of the tenancy assets?

**Comment by stancl** [comment]
Hi,

I see. `asset()` is a bit problematic. My idea is that you'd use `asset()` for things like images, which should be tenant-specific, and `mix()` for global assets like JS and CSS.

There is also a `global_asset()` that's always global and a `tenant_asset()` helper that's always tenant-specific.

If you can modify the Horizon view somehow, you could use `global_asset()` or `mix()`.

I'll add a config option to disable `asset()` tenancy.

**Comment by lasselehtinen** [comment]
Hi,

Thanks. Because modifying the views would mean forking the horizon package and of course it would be nice if it would work out of the box.

Another question though, should Horizon even be tenant aware or global?

**Comment by stancl** [comment]
It should be purely global because queued jobs live in the central database.

**Comment by lasselehtinen** [comment]
That makes sense. I am not sure how the internals work, so just an idea. Since you are overriding the asset helper, would it be possible to detect where it is called? For example if was called outside the application directory it would use the global assets. Then all these vendor packages layouts would work currently.

**Comment by stancl** [comment]
@lasselehtinen Does disabling `FilesystemTenancyBootstrapper` in your `config/tenancy.php` file help? If yes, I'll just add a config option to disable parts of it and that should fix this.

**Comment by lasselehtinen** [comment]
@stancl Sorry for the late reply. Yes after I disabled it, Horizon seems to work just fine. I guess without the changes disabling it will also mean that the other filesystem related tenancies are disabled as well?

**Comment by stancl** [comment]
I'll add a config key to disable just the `asset()` tenancy.
