### ISSUE TITLE
Problem with Laravel facades on PHPUnit tests

### ISSUE THREAD

**Issue by lasselehtinen** [archtechx/tenancy#260]
Hi,

I have packages that use Laravel facades like Cache and Config. I am getting the following error when trying to access those inside phpunit tests. This happens with Cache and Config at least. They work fine everywhere else. The tests are setup like in the documentation, I am initializing tenant the the TestCase. 

```php
<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;
use Illuminate\Support\Facades\Config;

class SomeTest extends TestCase
{
    public function testGettingSomething()
    {
        $this->assertSame('UTC', Config::get('app.timezone'));
    }
}
```

`RuntimeException: A facade root has not been set.`

With the config helper I get a different error:

`Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist.`

The facades work just fine when running normally.
```
Psy Shell v0.9.12 (PHP 7.3.13-1+ubuntu18.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> Config::get('app.timezone');
=> "UTC"
```

**Comment by stancl** [comment]
You're extending the PHPUnit test case instead of the Laravel test case.

**Comment by lasselehtinen** [comment]
Äsh, of course. Thanks for the help!
