### ISSUE TITLE
tenant_route method does not use the correct domain

### ISSUE THREAD

**Issue by SamuelNitsche** [archtechx/tenancy#262]
#### Describe the bug
When I manually initialize tenancy, the `tenant_route()` method does use the tenant domain. Instead, the route is generated by the global `APP_DOMAIN` environment variable.

#### Steps to reproduce
1. Manually initialize tenancy in tinker
2. Use `tenant_route()` to generate a route

#### Expected behavior
The correct tenant domain should be used to generate the url.

#### Your setup
 - Laravel version: 6.9.0
 - stancl/tenancy version: 2.2.4

**Comment by stancl** [comment]
`tenant_route()` is not meant to be used with tenancy initialization. It's to get a route with tenant domain name from central context.

Your tenants can have an unlimited amount of domains. How would the helper know which one to use?

**Comment by SamuelNitsche** [comment]
Hmm, I see what you mean. Seems like there is no way to implement my expected behaviour. Thank you anyway!

**Comment by stancl** [comment]
There definitely is. Tell me where & how you're initializing tenancy and what you need the route for.

**Comment by SamuelNitsche** [comment]
I am generating QR codes in an application based on the tenant url. This works perfectly fine using the `tenant_route()` method in a controller. Tenancy gets initialized using the domain and just works.

Now I want to generate a code programmatically. Therefore I wanted to manually initialize tenancy. My code look like this.

```
$tenant = tenancy()->all()->first();
tenancy()->initializeTenancy($tenant);
```

```
QrCodeGenerator::format('png')
            ->size(250)
            ->generate(tenant_route('qrCode.redirect', $id);
```

Does this help you?

**Comment by stancl** [comment]
First of all I think you don't need to initialize tenancy for this unless you're also persisting the data into tenant storage. In which case, I suggest using 

```php
$tenant->run(function ($tenant) {
    // runs inside that tenant's environment
});
```
instead of manually initializing tenancy.

If you only use one domain for your tenants, you could do something like `tenant_route('qrCode.redirect', $id, $tenant->domains[0])`.

**Comment by SamuelNitsche** [comment]
> If you only use one domain for your tenants, you could do something like `tenant_route('qrCode.redirect', $id, $tenant->domains[0])`.

Yes, I use only one domain. I think this works for me. Thank you!

**Comment by stancl** [comment]
You're welcome :)
