### ISSUE TITLE
Multiple database settings

### ISSUE THREAD

**Issue by NatachaH** [archtechx/tenancy#263]
Hi,

I'm not sure to understand how I should implement the multiple database connection for my project.
For each tenant I have to set a different "database_name", "database_username" and "database_password". The other settings like "database_host" are the same.

Should I insert them in the config database.php and copy the connections.mysql for each tenant ? Or there is an easier way ?

Thanks in advance for your answer :)

**Comment by stancl** [comment]
Hi,

You could try doing something like this if the DB config is dynamic and you don't want to store a connection for each tenant:

```php
// Make new tenants use your connection "template"
Tenant::new()->withData([
    '_tenancy_db_connection' => 'someTenantConnectionTemplate',
]);

// Make tweaks to the connection before bootstrapping tenancy
tenancy()->hook('bootstrapping', function ($tenantManager) {
    config(['database.connections.someTenantConnectionTemplate.name' => $tenantManager->tenant['database_name']]);
    config(['database.connections.someTenantConnectionTemplate.password' => $tenantManager->tenant['database_password']]);
    config(['database.connections.someTenantConnectionTemplate.host' => $tenantManager->tenant['database_host']]);
});
```

**Comment by NatachaH** [comment]
Thank you for the explanation :)

**Comment by suleodu** [comment]
Oh! thanks greatly i will put that to test tonight  so can i  also add database_username like ?
`tenancy()->hook('bootstrapping', function ($tenantManager) {
    config(['database.connections.someTenantConnectionTemplate.name' => $tenantManager->tenant['database_name']]);
    config(['database.connections.someTenantConnectionTemplate.password' => $tenantManager->tenant['database_password']]);
    config(['database.connections.someTenantConnectionTemplate.host' => $tenantManager->tenant['database_host']]);
config(['database.connections.someTenantConnectionTemplate.username' => $tenantManager->tenant['database_userame']]);
});`

**Comment by stancl** [comment]
You can add anything you want, look at what the code does. It modifies the config. You can modify the config any way you want.

**Comment by suleodu** [comment]
Is it posible i create the tenant and pass all the dB param like 
`// Make new tenants use your connection "template"
Tenant::new()->withData([
    'database_name' => 'my_tenant_db_name',
   'database_host' => 'my_tenant_db_host_or_ip_address_to_host',
   'database_password' => 'my_tenant_db_password',
    'database_user_ame' => 'my_tenant_db_user_name',
]);`

rather than saving it to config file ....

I am sorry  for the too much question

**Comment by stancl** [comment]
You are supposed to set that during tenant creation, and then use the hook to overwrite those keys in the connection config.

**Comment by suleodu** [comment]
Okay now i get it thanks so much for the support

**Comment by suleodu** [comment]
i got this error 
 Symfony\Component\Debug\Exception\FatalThrowableError  : Cannot access protected property Stancl\Tenancy\TenantManager::$tenant

  at /Users/adedayo/Sites/stackapi/app/Providers/AppServiceProvider.php:29
    25|      */
    26|     public function boot()
    27|     {
    28|         tenancy()->hook('bootstrapping', function ($tenantManager) {
  > 29|             config(['database.connections.mysql.username' => $tenantManager->tenant['database_username']]);
    30|             config(['database.connections.mysql.name' => $tenantManager->tenant['database_name']]);
    31|             config(['database.connections.mysql.password' => $tenantManager->tenant['database_password']]);
    32|             config(['database.connections.mysql.host' => $tenantManager->tenant['database_host']]);
    33|         });

  Exception trace:

  1   App\Providers\AppServiceProvider::App\Providers\{closure}(Object(Stancl\Tenancy\TenantManager), Object(Stancl\Tenancy\Tenant))
      /Users/adedayo/Sites/stackapi/vendor/stancl/tenancy/src/TenantManager.php:449

  2   Stancl\Tenancy\TenantManager::Stancl\Tenancy\{closure}([], Object(Closure))
      [internal]:0

**Comment by stancl** [comment]
Right, that should be $tenantManager->getTenant('database_name') etc

**Comment by stancl** [comment]
You posted that message three times.
