### ISSUE TITLE
Using laravel-activitylog on the Tenant model

### ISSUE THREAD

**Issue by johans** [archtechx/tenancy#264]
Has anyone managed to get `laravel-activitylog` to record changes on the tenants and domains table? I've tried adding the `LogsActivity`-trait to the `Tenant`-class but it's not working because the package isn't using Eloquent Models for this I think?

**Comment by stancl** [comment]
It isn't using Eloquent Models, because it doesn't force you to store tenants in the DB.

You might be able to use [hooks](https://tenancy.samuelstancl.me/docs/v2/hooks/) like `tenant.updated` to log some things, but you can't use Eloquent to record changes to tenants.

**Comment by johans** [comment]
@stancl That makes sense, thanks.
