### ISSUE TITLE
Where in the code the tenant's config is applied?

### ISSUE THREAD

**Issue by tamkeen-tms** [archtechx/tenancy#265]
Thanks for this great library, looking through its code is quite fun! 

I was wondering at what exact point in the code the tenant's dynamic config changes (mapping) is applied to Laravel's config? I looked through the TenantConfig feature, but applying the config is simply done by setting the `config` property? How and where it's actually applied to Laravel, using Config::set?

**Comment by stancl** [comment]
The `config()` helper does the same as `Config::set`. `config('foo')` gives you the value for `foo`, but `config(['foo' => 'bar'])` sets `foo` to `bar`.

**Comment by stancl** [comment]
Ah sorry, just realized the class injects a `Config\Repository` dependency. It's a reference to the same class used by the `config()` helper and `Config` facade, so making changes to `$this->config` in `TenantConfig` makes changes to the global config you access via that helper & facade.

**Comment by TamkeenLMS** [comment]
Great, I get that, but looking through the code, I cannot pin down exactly where (what file?) the tenant config is overrides the app config? I hope I am explaining myself correctly.

**Comment by tamkeen-tms** [comment]
Aha, now I get it. So, if I want, say, store the tenant's config (as json, in the data column) and apply it after bootstrapping, the following would work?

```php
// AppServiceProvider
function boot(Repository $config){
tenancy()->hook('bootstrapped', function($manager, $tenant) use($config){
// Update $config with $tenant->config
});
}
```

**Comment by stancl** [comment]
Yes, that would work.

The `TenantConfig` feature works like this:

The `bootstrap()` method is called by `TenantManager`. It adds a hook that changes the app config after tenancy is bootstrapped.

https://github.com/stancl/tenancy/blob/5ebb68e860119b4508d86f2150d2dd7ce4696bd5/src/Features/TenantConfig.php#L29-L33

Then the `setTenantConfig()` method, called by that hook, copies keys from the tenant's data to `$this->config` which is the `Config\Repository` used by the framework.

https://github.com/stancl/tenancy/blob/5ebb68e860119b4508d86f2150d2dd7ce4696bd5/src/Features/TenantConfig.php#L40-L48

**Comment by tamkeen-tms** [comment]
Awesome. And yes, I found the TenantConfig feature. But, I don't want to do the mapping thing. I want to store a "config" for each tenant (as json on the tenants table), and just apply it in the bootstrapping process, this way I get to add/edit/delete from each tenant's config separately, and also wont need to update the mapping everytime, ... it would get too long after time, and I would need to `config:cache` after each change, which would be kinda painful. What do you think?

**Comment by stancl** [comment]
I see your reasoning, sounds good. Just json decode the property and loop through the key/value pairs and apply them to the app config.

**Comment by tamkeen-tms** [comment]
Great! Thanks for the help, great work.
