### ISSUE TITLE
Conflicting routes

### ISSUE THREAD

**Issue by oxidand** [archtechx/tenancy#267]
I guess I don't understand this part of documentation <https://tenancy.samuelstancl.me/docs/v2/tenant-routes/#conflicting-routes>

In my `web.php` I have:

```php
Route::get('/', 'RegisterController@create')->name('app.index');
```

and in my `tenant.php`:

```php
Route::get('/', 'DashboardController@index')->name('dashboard.index');
```

Even with `->domain($domain)` option in `mapWebRoutes()` tenant routes still overwrite `GET /` and `app.index` route is not available (because tenant routes are loaded for all domains, including those listed in `exempt_domains` and it overwrite web routes).

For now I added the condition `if ($extempt_domain === $current_domain) return;` in `routes/tenant.php`, but maybe I can do it without such hack?

**Comment by stancl** [comment]
Tenant routes should be loaded on non-exempt domains only. Can you try clearing your config cache?

**Comment by oxidand** [comment]
sorry for not replying, it was a busy month. I'll run the tests again today
when I tested it the last time I cleared everything: config and routes included

**Comment by EdwardNavarro** [comment]
Hi @curious-jim, you solve yet?

**Comment by oxidand** [comment]
Sorry again, I completely forgot about it
When I posted the issue, it wasn't working, so I created a hack and the app was working as it should be
Since then we updated to newer version of tenancy and laravel, but the hack was still there
I now tried to disable the hack and everything works just fine without it
So the issue is resolved

**Comment by stancl** [comment]
I think I may have added a feature that makes sure tenant routes are loaded after central routes, so that could be it.
