### ISSUE TITLE
How scheduling is handled?

### ISSUE THREAD

**Issue by tamkeen-tms** [archtechx/tenancy#269]
I am trying to understand how Scheduling is handled by this library. In the `app/Console/Kernel.php` I have 7 jobs that gets dispatched and queued for execution, when the `artisan queue:work` is hit by cron, how these tasks are made tenant-aware in the CLI environment?

I think these tasks now should be called for each tenant separately? Should I loop through the tenants, and initiate them one by one to execute the tasks?

Thanks in advance for the help, I dont' seem to understand this part.

**Comment by stancl** [comment]
Tenancy is not automatically initialized in the app (it has to be initialized by a middleware or something like that), so the schedule will run centrally. If you want to run a job for all tenants, you're best off keeping it a normal, central job and doing something like this inside the job:

```php
$tenants = tenancy()->all();

foreach ($tenants as $tenant) {
    $tenant->run(function () {
        // ...
    });
}
```

**Comment by tamkeen-tms** [comment]
Great, this is what I initially expected, but wanted to be sure. Thanks for the help.

**Comment by aminraeisi** [comment]
> ```
> $tenants = tenancy()->all();
> 
> foreach ($tenants as $tenant) {
>     $tenant->run(function () {
>         // ...
>     });
> }
> ```

@stancl When I do this and inside the run closure I run `dispatch(new UpdateRentStatus());` it runs it every time with success but if I do it with `$schedule->job(new UpdateRentStatus)->everyMinute();` inside the closure, it fails most of the time. I tried to echo the tenant id inside one of my jobs and sometimes It return the id of the tenant when I do echo `tenant('id')` but most of the time in the same job it just return blank.

**Edit:**
I forgot to mention that when the jobs fail it tries to add the failed jobs to my central database and throws an error that the table is not there. but when (sometimes) the same job passes it applies the job to the correct tenant.

**Comment by stancl** [comment]
Can you show me the code of the job?

**Comment by aminraeisi** [comment]
Thanks for the quick response! Here are the files:

```php
// App\Console\Kernel.php

protected function schedule(Schedule $schedule)
    {
        $tenants = Tenant::get();

        foreach ($tenants as $tenant) {
            $tenant->run(function () use ($schedule) {

                // Sometimes works but when it fails, it tries to write to central DB
                $schedule->job(new GenerateInvoices)->everyMinute();

                // Always works
                dispatch(new GenerateInvoices());
            });
        }
    }
```

```php
// App\Jobs\GenerateInvoices;

class GenerateInvoices implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $recurringInvoiceId;

    public function __construct($recurringInvoiceId = null)
    {
        $this->recurringInvoiceId = $recurringInvoiceId;
    }

    public function handle()
    {
        if ($this->recurringInvoiceId) {
            RecurringInvoice::where('id', $this->recurringInvoiceId)
                ->where('start_date', '<=', now()->addDays(7))->get()
                ->each->generateInvoices();
        } else {
            RecurringInvoice::where('status', RecurringInvoiceStatus::ACTIVE)
                ->where('start_date', '<=', now()->addDays(7))->get()
                ->each->generateInvoices();
        }
    }
}

```

**Comment by stancl** [comment]
Right. Scheduled jobs always run centrally. So `$schedule->job(new GenerateInvoices)->everyMinute();` won't work.

**Comment by tamkeen-tms** [comment]
@aminraeisi The loop you made through the tenants should be done inside the job instead, instead of inside the kernel.php file.

**Comment by aminraeisi** [comment]
@stancl But why sometimes it picks up the correct tenant with the `schedule`? Is this an issue to be fixed or the package does not intend to have it at all?

@tamkeen-tms I will try that when I get back to the same task. Hopefully it works. If I do the loop inside each job, then there will be a repeating code getting all the users for each job. I will try to pass list of users from the Kernel to each job. 

Thanks for the reply. 👍

**Comment by stancl** [comment]
It's not an issue with the package because it's not intended to be used like this precisely because it's so unpredictable.

Just use a loop inside a scheduled job. Don't pass anything from kernel.

**Comment by stancl** [comment]
Or, you can pass *some* things from the kernel, but only do the tenancy loop inside the job.

**Comment by tamkeen-tms** [comment]
@aminraeisi  Yes, the same code should run for each tenant, separately. This is the idea anyway, think about it. The keyword here is Scope; anything related to the tenant (and not the central app) should run inside THAT tenant's scope. So, in your case, yes, you must loop through the users FOR EACH TENANT, inside EACH TENANT'S SCOPE.

**Comment by aminraeisi** [comment]
@tamkeen-tms Thanks for explaining. I think if I add the loop inside each job, it won't look good when I want to track the queues using tags for specific tenant or see which tenant had a problem inside the queue. The loop will add all the tenants to one job which will make the job to take more time to process for all the tenants and all their users.
Please correct me if I am wrong.

The way I want to go with now is to have a simple loop inside the kernel which sends the id of the tenant to the job. Inside the job's handle, before running anything, I will initialize the tenant so that the scope is for that specific tenant.

Here is what the code looks like now:

```php
// App\Console\Kernel.php

protected function schedule(Schedule $schedule)
    {
        $tenants = Tenant::get();

        foreach ($tenants as $tenant) {
            $schedule->job(new GenerateInvoices($tenant->id))->everyMinute();
        }
    }
```

```php
// App\Jobs\GenerateInvoices;

class GenerateInvoices implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tenant;

    public function __construct($tenantId = null)
    {
        $this->tenant = Tenant::findOrFail($tenantId);
    }

    // I can even use tags for each tenants job now
    public function tags()
    {
        $tags = [
            'GenerateInvoices',
            $this->tenant ? 'Tenant' : 'Central',
        ];

        if ($this->tenant) {
            $tags[] = 'tenant:' . $this->tenant->id;
        }

        return $tags;
    }

    public function handle()
    {
        if ($this->tenant) {
            tenancy()->initialize($this->tenant);

            RecurringInvoice::where('id', $this->recurringInvoiceId)
                ->where('start_date', '<=', now()->addDays(7))->get()
                ->each->generateInvoices();
        }
    }
}

```

Please let me know if this way is good because I don't know if there will be any side effects.

**Comment by aminraeisi** [comment]
And of course because I am `dispatching` this specific job inside the app as well, I can have a condition to ignore the `initialize` part when I dispatch it within a tenant domain.

**Comment by stancl** [comment]
This is wrong.

![Screen Shot 2020-08-13 at 14 45 57](https://user-images.githubusercontent.com/33033094/90135945-b53ef100-dd73-11ea-8861-96b4aced5078.png)

Tenants are something that can change very often. Like I said **do a loop inside the job**.

**Comment by aminraeisi** [comment]
> Tenants are something that can change very often.

Can you please elaborate on this because I don't get this point 🤔 .

From my understanding, this is a loop that goes through each tenant and schedules a job with the tenant's ID and the job can run later for the correct tenant.

**Comment by stancl** [comment]
At what point in the lifecycle is `App\Console\Kernel.php` executed?

Will it know that there are new tenants?

It seems far more reasonable to me to just loop inside the job.

**Comment by aminraeisi** [comment]
@stancl Thanks for explaining. I get your point now. And for sure won't do it in cases that will affect my app.

But for this app that I am building, I am dispatching the jobs on users actions as well. For example generating rent invoices that are due happens in the cron every 30 minutes but I also dispatch the job when a user creates a rent (I don't want them to wait for the next 30 minutes).

But yeah if I was just relying on the cron, I should loop inside the job to make sure every tenant is included.  

Thanks a lot @stancl and @tamkeen-tms for your help.

**Comment by aneeskhan47** [comment]
for those who want to run their custom artisan command tenant aware (for each tenant):

@tamkeen-tms 
@aminraeisi 

![image](https://user-images.githubusercontent.com/30714223/133605659-7b15e088-31fc-4f9d-857b-bcf36f44e56a.png)
