### ISSUE TITLE
Document setting custom tenant ids during creation

### ISSUE THREAD

**Issue by knash94** [archtechx/tenancy#275]
#### Description
It would be helpful to be able to have more flexibility when it comes to filesystem suffixing, similar to the way you can customise database names by using the `_tenancy_db_name` key on the tenants data. This will help to make the file structure a lot more readable.

Example:
```
Tenant::new()
    ->withDomains(['company-a.yourapp.com', 'tenant1.com'])
    ->withData(['_tenancy_filesystem_suffix' => 'tenant_company-a'])
    ->save();
```

The above would then result in the tenancy suffix being `tenant_company-a` rather than an unrecognisable UUID.

I'm more than happy to implement the above changes if you agree with them. Also, great work on the package, I'm really impressed with how well maintained it is!

**Comment by stancl** [comment]
Might be useful, but before we consider adding this feature, wouldn't setting the id work too in your case?

People generally want clean paths when they have a few tenants they add manually, which means that you can set the ID yourself.

```php
Tenant::new()
    ->withDomains(['company-a.yourapp.com', 'tenant1.com'])
    ->withData(['id' => 'company-a'])
    ->save()
```

And if you set `tenancy.filesystem.suffix_base` to `tenant_`, you will get a suffix of `tenant_company-a`.

**Comment by knash94** [comment]
You're right, I never considered that it would be possible to override the id on a tenant and that seems to have worked fine. I think the original feature might be a nice to have though, it adds that extra layer of flexibility if it's ever needed

**Comment by stancl** [comment]
I agree that it's a nice-to-have, but I specifically try to adding those, unless there are actual use cases. When someone shows me their use case for this (custom suffix, but not custom id), I will be happy to add this.

But part of maintaining a project is fighting feature creep to keep the codebase from becoming too complex.

I'll make sure the custom id during tenant creation is better covered by the docs, though :)

**Comment by suleodu** [comment]
Hello is there a way i cant specify my tenant database host, user_name, passwors and database name during teneant creation ...i want a situation where i can host my tenant database on my tenant server ...
A scenario, i want my Saas app to be hosted on my server while each of my client may either want to host their database on my server or their saver why my app can still connect to it

**Comment by stancl** [comment]
https://tenancyforlaravel.com/docs/v3/customizing-databases
