### ISSUE TITLE
Specifying Database host and other db parameter during tenant creation

### ISSUE THREAD

**Issue by suleodu** [archtechx/tenancy#277]
#### Description

Hello is there a way i cant specify my tenant database host, user_name, password and database name during tenant creation ...

#### Why this should be added

I want a situation where i can host my tenant database on my tenant separate server ...
i want my Saas app file will  hosted on my server while each of my client(tenant) may either want to host their database on my server or on their respective saver . this may allow tenant that want to discontinue using my service can be easily shot down and still have assess to her company record with out even making request to me

**Comment by stancl** [comment]
Does this help? https://github.com/stancl/tenancy/issues/263#issuecomment-573674683

**Comment by stancl** [comment]
Resolved: https://github.com/stancl/tenancy-docs/commit/6bcc5cdd88c851f05bbf41ac247ba986cf7a3d02

**Comment by suleodu** [comment]
When i try this 
`tenancy()->hook('bootstrapping', function ($tenantManager) {
            //dd($tenantManager);
            config(['database.connections.mysql.username' => $tenantManager->tenant['database_username']]);
            config(['database.connections.mysql.name' => $tenantManager->tenant['database_name']]);
            config(['database.connections.mysql.password' => $tenantManager->tenant['database_password']]);
            config(['database.connections.mysql.host' => $tenantManager->tenant['database_host']]);
            dd(config(['database']));
        });`

i got this error when i run php artisan tenants:migrate

Symfony\Component\Debug\Exception\FatalThrowableError  : Cannot access protected property Stancl\Tenancy\TenantM
anager::$tenant

  at /Users/adedayo/Sites/stackapi/app/Providers/AppServiceProvider.php:30
    26|     public function boot()
    27|     {
    28|         tenancy()->hook('bootstrapping', function ($tenantManager) {
    29|             //dd($tenantManager);
  > 30|             config(['database.connections.mysql.username' => $tenantManager->tenant['database_username']]);
    31|             config(['database.connections.mysql.name' => $tenantManager->tenant['database_name']]);
    32|             config(['database.connections.mysql.password' => $tenantManager->tenant['database_password']]);
    33|             config(['database.connections.mysql.host' => $tenantManager->tenant['database_host']]);
    34|             dd(config(['database']));

  Exception trace:

  1   App\Providers\AppServiceProvider::App\Providers\{closure}(Object(Stancl\Tenancy\TenantManager), Object(Stancl\Tenancy\Tenant))
      /Users/adedayo/Sites/stackapi/vendor/stancl/tenancy/src/TenantManager.php:449

  2   Stancl\Tenancy\TenantManager::Stancl\Tenancy\{closure}([], Object(Closure))
      [internal]:0

  Please use the argument -v to see more details.

**Comment by stancl** [comment]
Please don't spam, you already posted the same two messages twice in different threads.
