### ISSUE TITLE
Custom Database Connections 

### ISSUE THREAD

**Issue by suleodu** [archtechx/tenancy#279]
can the doc be more elaborate when i tried this 
tenancy()->hook('bootstrapping', function ($tenantManager) {
    config(['database.connections.someTenantConnectionTemplate.name' => $tenantManager->tenant['database_name']]);
    config(['database.connections.someTenantConnectionTemplate.password' => $tenantManager->tenant['database_password']]);
    config(['database.connections.someTenantConnectionTemplate.host' => $tenantManager->tenant['database_host']]);
});

within my app service provider i got the bellow erorr when i run php artisan tenants:migrate 

 Symfony\Component\Debug\Exception\FatalThrowableError  : Cannot access protected property Stancl\Tenancy\TenantM
anager::$tenant

  at /Users/adedayo/Sites/stackapi/app/Providers/AppServiceProvider.php:31
    27|     public function boot()
    28|     {
    29|         tenancy()->hook('bootstrapping', function ($tenantManager) {
    30|             //dd($tenantManager);
  > 31|             config(['database.connections.mysql.username' => $tenantManager->tenant['database_username']]);
    32|             config(['database.connections.mysql.name' => $tenantManager->tenant['database_name']]);
    33|             config(['database.connections.mysql.password' => $tenantManager->tenant['database_password']]);
    34|             config(['database.connections.mysql.host' => $tenantManager->tenant['database_host']]);
    35|             dd(config(['database']));

  Exception trace:

  1   App\Providers\AppServiceProvider::App\Providers\{closure}(Object(Stancl\Tenancy\TenantManager), Object(Stancl\Tenancy\Tenant))
      /Users/adedayo/Sites/stackapi/vendor/stancl/tenancy/src/TenantManager.php:449

  2   Stancl\Tenancy\TenantManager::Stancl\Tenancy\{closure}([], Object(Closure))
      [internal]:0

  Please use the argument -v to see more details.

**Comment by stancl** [comment]
Like I [answered 2 hours before you opened this issue](https://github.com/stancl/tenancy/issues/263#issuecomment-579092229), replace `->tenant[...]` with `->getTenant(...)`.

**Comment by stancl** [comment]
Fixed https://github.com/stancl/tenancy-docs/commit/6cb9deb08e1dfc875dce72243662b5db91659cb6
