### ISSUE TITLE
Tenant permissions

### ISSUE THREAD

**Issue by kamilkozak** [archtechx/tenancy#280]
How to manage tenant permission (spatie) if there is no Tenant model? I do not want to grant permissions to the user only the tenant.

**Comment by stancl** [comment]
If you need a tenant model, create one. Though I don't see why you'd want to use that permission package with tenant entities.

**Comment by kamilkozak** [comment]
Each tenant can create their users. And I would have to give each one permission separately.

**Comment by stancl** [comment]
Can you elaborate? Tenants are the units that separate your clients' applications. You probably mean that a superuser within that tenant database can create users. I don't see why you need to use permissions on the `tenants` table.
