### ISSUE TITLE
Apply middleware tenancy and auth:api

### ISSUE THREAD

**Issue by samo29** [archtechx/tenancy#282]
Hi, I'm trying to use middleware auth:api with tenancy in a group of routes, works just using tenancy, but if I add auth:api don't work. How can I solve this?

This work
`Route::middleware('tenancy')->group(function(){
	Route::prefix('tenant')->group(function(){
		Route::post('login', 'Tenant\AuthenticationController@login')->name('login');
		Route::get('test', 'TestController@index');	
	});
});`

But this don't
`Route::middleware(['auth:api','tenancy'])->group(function(){

	Route::prefix('tenant')->group(function(){
		Route::get('test', 'TestController@index');
	});

});`

**Comment by stancl** [comment]
> But this don't

Can you explain what exactly doesn't work?

Also be sure to read this: https://tenancy.samuelstancl.me/docs/v2/tenant-routes/#custom-groups

**Comment by samo29** [comment]
Sorry, but work now. I was ignoring the Bearer word in authorization header in postman where i'm doing test. Thanks for your time.
