### ISSUE TITLE
Storage error while using Real Time Facades

### ISSUE THREAD

**Issue by pdrolima** [archtechx/tenancy#283]
Hi there!

I'm getting an error when I try to use real time facades, but I don't understand why...it's looks is associated with Tenant Storage settings.

```
file_put_contents(/mnt/c/Users/pedro/Projects/cool-saas/storage/tenante594198d-3a8f-47cc-8f62-5eb53f3eb391/framework/cache/facade-4e0fa087d60f28713ef2f7c1a97f99e8e2a731c0.php): failed to open stream: No such file or directory 
```

Am I missing some configuration? 🤔

**Comment by stancl** [comment]
What realtime facades are you trying to use?

Also try `artisan cache:clear`.

**Comment by pdrolima** [comment]
I'm using my own class. I did some research, and It's looks is a Windows WSL issue (damn Windows...). I'll try to find a solution and write here in case someone got a similar issue.

**Comment by pdrolima** [comment]
Hi,

I was taking a look in [tenancy docs](https://tenancy.samuelstancl.me/docs/v2/filesystem-tenancy/) and I see that I need to create tenant specific storage folder, but since Laravel's caches Real-Time Facades and the folders weren't there, this "error" was being triggered.

**Comment by quaidesbalises** [comment]
Hi, I had the same problem which is fixed with the creation of the tenant storage folder. This is what i did : 

```php
        // Storage
        $storage_path = 'storage/board-'.$tenant->id;

        mkdir($storage_path);
        mkdir("$storage_path/app");
        mkdir("$storage_path/app/public");
        mkdir("$storage_path/framework");
        mkdir("$storage_path/framework/cache");
        mkdir("$storage_path/framework/sessions");
        mkdir("$storage_path/framework/testing");
        mkdir("$storage_path/framework/views");
        mkdir("$storage_path/logs");

```

Would it be a common way to achieve it ?  Why not include it by default if we are on the local disk ?  Just a simple question to be curious  😉

**Comment by stancl** [comment]
Was your problem also related to real time facades or something else? I think those folders should get created automatically.

**Comment by quaidesbalises** [comment]
Yes it concerns real time facades too

**Comment by stancl** [comment]
Can you give me some code that I can use to reproduce this?

**Comment by quaidesbalises** [comment]
For sure :  

**1.** Create a ```app/Test.php``` class : 

```php

namespace App;

class Test {

   public function foo()
   {
      return 'bar';
   }
	
}

```

**2.** Go to ```routes/tenant.php``` file and put this route : 

```php

use Facades\App\Test;

Route::get('test', function() {
   echo Test::foo();
});

```


**3.** You'll get this file_put_contents **ErrorException** : 

```php
ErrorException
file_put_contents(/Users/francois.dusautoir/Code/databoard/storage/board-fcbf85e0-1f55-4ca5-b38e-25af8251ae72/framework/cache/facade-d6dc2dfdf9ed62fa0c35ef530c42f68b1a73ac56.php): failed to open stream: No such file or directory
```

Then the error is solved by created **the board-...** folder in the storage folder.

**Comment by quaidesbalises** [comment]
Do you plan to include this issue in the next 2.3.0 release ?

**Comment by stancl** [comment]
If this issue exists for more things than realtime facades, then yes. If it exists only for realtime facades, then I'll focus on this after 2.3.0 is released and fix it in 2.3.1 or something.

There are more important things to be done and I personally don't believe realtime facades have any use so I'm not going to make this my main priority.

**Comment by stancl** [comment]
Will try to get this added to tenant creation somehow https://github.com/stancl/tenancy/issues/283#issuecomment-596210846

**Comment by stancl** [comment]
Moved to #462
