### ISSUE TITLE
implementing graphql server with   nuwave/lighthouse  and stancle/tenancy 

### ISSUE THREAD

**Issue by suleodu** [archtechx/tenancy#285]
Hello, 
I tried to create a graphql server with nuwave/lighthouse on my tenant application after setting up with this documentaion  [Lighthouse](https://lighthouse-php.com/4.8/the-basics/schema.html)  it was successful but when i run it trough my tenenat url i got this error 
`[{"errors":[{"message":"Syntax Error: Unexpected <EOF>","extensions":{"category":"graphql"},"locations":[{"line":1,"column":1}]}]}]`

Can i get some help on this

**Comment by suleodu** [comment]
I have actualy solved this..  All i did was add `Stancl\Tenancy\Middleware\InitializeTenancy::class,`
to the middleware arrary in the `app/config/lighthouse.php` file ...

**Comment by stephenjason89** [comment]
@suleodu I am still having difficulties integrating it with lighthouse with v3 tenancy.
Can you please elaborate more?
I added 
            \Stancl\Tenancy\Middleware\InitializeTenancyByDomainOrSubdomain::class,
on my lighthouse.php but it is giving me an error

![image](https://user-images.githubusercontent.com/3810177/131742531-89716a11-249c-49db-a556-24bfa640baa6.png)

Not adding a middleware makes lighthouse query the original db not the tenant db
