### ISSUE TITLE
Example tests

### ISSUE THREAD

**Issue by Silver343** [archtechx/tenancy#288]
Hi Im struggling with some basic test,

when i try to complete a get or post request in phpunit it is visiting the localhost, and I havent been able to get it to visit a subdomain, I think I have correctly followed the example testcase in the docs.

**Comment by stancl** [comment]
Can you share some test code?

Does this not work?
```php
$response = $this->post('tenant1.localhost/foo');
```

**Comment by Silver343** [comment]
Here is the test:

<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;

class ExampleTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp();

        tenancy()->create('test.sas-online.test');
        tenancy()->init('test.sas-online.test');
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $this->withoutExceptionHandling();

        $response = $this->get('test.sas-online.test/app');

        $response->assertStatus(200);
    }


    public function tearDown(): void
    {
        parent::tearDown();
    }
}

and it returns the error:

1) Tests\Feature\ExampleTest::testBasicTest
Symfony\Component\HttpKernel\Exception\NotFoundHttpException: GET http://localhost/sas-online.test/test.sas-online.test/app

Im using laragon for windows which may be effecting the test.

**Comment by stancl** [comment]
Yes, it looks like `test.sas-online.test` is not available during the test.

**Comment by Silver343** [comment]
Here is the test:

`<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;

class ExampleTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp();

        tenancy()->create('test.sas-online.test');
        tenancy()->init('test.sas-online.test');

    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $this->withoutExceptionHandling();

        $response = $this->get('test.sas-online.test/app');

        $response->assertStatus(200);
    }


    public function tearDown(): void
    {
        parent::tearDown();
    }
}
`

which returns the error:

1) Tests\Feature\ExampleTest::testBasicTest
Symfony\Component\HttpKernel\Exception\NotFoundHttpException: GET http://localhost/test.sas-online.test/app

**Comment by stancl** [comment]
Like I said, your phpunit can't access `test.sas-online.test`. Running `tenancy()->create()` will create a tenant for you, but it will not configure your webserver. I suggest using `.localhost` domains for this reason.

**Comment by tobyhage** [comment]
Hello,

Is it possible that you provide a complete working example of 

phpunit.xml
Testcase.php
BasicTest.php (an example test which changes the database)
.env file

with a sqlite database and for test.localhost. I'am trying for two hours now with all kind of combinations (and different error messages) and reading topics on github and it is still not working and reading all topics i think i'am not the only one :-). I think the documentation contains inconsistencies.

Thank you very much.

**Comment by Silver343** [comment]
I have had some success by using the full url in the test:

for example  

> $response` = $this->get('http://test.myapp.local/app');

this seems to work without changing the host file or the app url.

**Comment by tobyhage** [comment]
Thank you for your reply. I think that's working because of your development environment.
I use laradock with nginx and mysql. For testing i have created a empty database/test.sqlite.

I have following files:

phpunit.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false" backupStaticAttributes="false" bootstrap="vendor/autoload.php" colors="true" convertErrorsToExceptions="true" convertNoticesToExceptions="true" convertWarningsToExceptions="true" processIsolation="false" stopOnFailure="false">
    <testsuites>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>

        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
    <php>
        <server name="APP_ENV" value="testing"/>
        <server name="BCRYPT_ROUNDS" value="4"/>
        <server name="CACHE_DRIVER" value="array"/>
        <server name="MAIL_DRIVER" value="array"/>
        <server name="QUEUE_CONNECTION" value="sync"/>
        <server name="SESSION_DRIVER" value="array"/>
        <server name="DB_CONNECTION" value="sqlite"/>
        <server name="DB_DATABASE" value="/home/toby/projects/pim/frontend/database/test.sqlite"/>
    </php>
</phpunit>
```

tests/Feature/BasicTest.php
url: 'test.localhost/test' is a simple test function

```php

<?php

namespace Tests\Feature;

use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp();
        tenancy()->create('test.localhost');
        tenancy()->init('test.localhost');
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $this->withoutExceptionHandling();

        $response = $this->get('test.localhost/test');

        $response->assertStatus(200);
    }

    public function tearDown(): void
    {
        config([
            'tenancy.queue_database_deletion' => false,
            'tenancy.delete_database_after_tenant_deletion' => true,
        ]);
        tenancy()->all()->each->delete();
        
        parent::tearDown();
    }
}
```

tests/Feature/Testcase.php

```php
<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public function setUp(): void
    {
        parent::setUp();

        $this->artisan('migrate:fresh');

        config([
            'tenancy.queue_database_creation' => false,
        ]);

        config(['tenancy.exempt_domains' => [
            '127.0.0.1',
            'localhost',
        ]]);
    }
}
```

env.testing

```
APP_NAME="Fysio123"
APP_ENV=local
APP_KEY=base64:MqrCz4bFSD3D/N/zznfdshjkfhsdjkhVT10mZZq+ZMkKPO0cZ52/G4qc=
APP_DEBUG=true
APP_URL=http://localhost
LOG_CHANNEL=stack

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
```

When i run the test i get following error:

> Executing task: /home/toby/projects/pim/frontend/vendor/bin/phpunit "/home/toby/projects/pim/frontend/tests/Feature/BasicTest.php" --configuration /home/toby/projects/pim/frontend/phpunit.xml <

1) Tests\Feature\ExampleTest::testBasicTest
Illuminate\Database\QueryException: could not find driver (SQL: select exists(select * from `tenants` where `id` = 846f20c2-e1b7-4945-b280-ddaa691bb9c7) as `exists`)

I don't know why it is using SQL and i don't know why he could not find driver.

**Comment by stancl** [comment]
Did you solve this or do you still need help?

**Comment by Silver343** [comment]
Sorry forgot to close this. I have solved it by moving to homestead and vagrant.
