### ISSUE TITLE
Generating client keys manually in DB seeder - Passport integration

### ISSUE THREAD

**Issue by enkota** [archtechx/tenancy#290]
Hi,

Just getting round to trying the new [passport support](https://tenancy.samuelstancl.me/docs/v2/passport/). Following your docs, I am confused as to how you generate the shared keys in a seeder when the tenant is created?

Does anyone have any examples they could share to explain this step?

Much appreciated :)

**Comment by stancl** [comment]
Create a database seeder class, configure that seeder as the tenant seeder, and use `Artisan::call('passport:client')` in the seeder. With arguments like this: https://github.com/laravel/passport/blob/8.x/src/Console/InstallCommand.php#L33

Does this help?

**Comment by YoussF** [comment]
Hi,

I just tried `Artisan::call('passport:client')` in my TenantsDatabaseSeeder.php and when i run the seeder with `php artisan tenants:seed --class=TenantsDatabaseSeeder` the console got stuck after printing the tenant ID `Tenant: d79e487d-afe6-4509-a95d-453b0187fb93`. I tried the same `Artisan::call('passport:client')` on tinker and the console also got stuck infinitely (with no error msg)

**Comment by webard** [comment]
You need run `passport:client` command with `--no-interaction` flag set.

**Comment by YoussF** [comment]
it returned `Illuminate/Database/QueryException with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null`

After adding the `--name` flag it worked. Also for my use case i need a Password Grant Client. So i also added `--password` flag as following:
```
Artisan::call('passport:client',[
'--no-interaction'=>true,
'--name'=>'Tenant Password Grant Client',
'--password' => true
]);
```
@webard thank you for the hint ;)

**Comment by enkota** [comment]
Awesome that worked @YoussF thanks for the help guys!
