### ISSUE TITLE
Tenant Config And GoogleTagManager

### ISSUE THREAD

**Issue by tobyhage** [archtechx/tenancy#291]
Hello,

Thanks for this great library :-)
I want to use the TenantConfig Feature to store the google tag manager id per tenant.
So i have added the "google_tagmanager_id": "GTM-XXXX" to the data column in the tenants table.

In tenancy.php i have

`   
    'features' => [     
        Stancl\Tenancy\Features\TenantConfig::class,
    ],
    'storage_to_config_map' => [ // Used by the TenantConfig feature
        'google_tagmanager_id' => 'googletagmanager.id',
        'postmark_token' => 'services.postmark.token'
    ],`

I use this library for google tag manager: https://github.com/spatie/laravel-googletagmanager.
But when i run a view i get an error message that google_tagmanager is not set.

I see that config repository is set correct with google_tagmanager_id.

Probably the reason is that google_tag_manager library is reading config before the mapping.

I'am right and how can i solve this :-)

Thank you.

**Comment by stancl** [comment]
> But when i run a view i get an error message that google_tagmanager is not set.

What error specifically and what does the view do?

Note that here you're saying `google_tagmanager` but you're setting a `googletagmanager.id` config - without an underscore.

**Comment by tobyhage** [comment]
You can see the error on: https://fysio123.tobeontheweb.nl/
googletagmanager.id is correct. I have also added some dump data in the debug tab.

**Comment by stancl** [comment]
Right, the dumped tag manager instance does not have an id set. So the id gets injected before the config is changed.

![Screenshot from 2020-02-09 14-27-51](https://user-images.githubusercontent.com/33033094/74102967-71f79180-4b48-11ea-9d92-408ec8608362.png)

Use a `bootstrapped` event hook to set the id:

```php
use Spatie\GoogleTagManager\GoogleTagManagerFacade as GoogleTagManager;

// AppServiceProvider::boot()
tenancy()->hook('bootstrapped', function (TenantManager $tenantManager) {
    GoogleTagManager::setId($tenantManager->getTenant('google_tagmanager_id');
});
```

**Comment by tobyhage** [comment]
Thank you for the suggestion.
It is not working. I have added code below. But i see no dump and still same error.
Is there something else i have to do...

`
        tenancy()->hook('boostrapped', function (TenantManager $tenantManager) {
            dump($tenantManager->getTenant('google_tagmanager_id'));
            GoogleTagManager::setId($tenantManager->getTenant('google_tagmanager_id'));
        });
`

**Comment by stancl** [comment]
Sorry, typo. It should be `tenancy()->hook('bootstrapped')`.

**Comment by tobyhage** [comment]
Ah. Thank you :-)
