### ISSUE TITLE
Tenant Migrate-Refresh Force

### ISSUE THREAD

**Issue by jeverington** [archtechx/tenancy#292]
When running tenants:migrate-fresh I'm finding that it's hanging on the migrating step and not going any further. Is it possible to force this as you would in normal laravel?

**Comment by stancl** [comment]
If you add `--force => true` here, does it help? 
https://github.com/stancl/tenancy/blob/95ee295da1527e280dea94d50054de90c754f7c0/src/Commands/MigrateFresh.php#L47-L49

You can find this file in `vendor/stancl/tenancy/src/Commands/`.

**Comment by jeverington** [comment]
Thanks @stancl, i'll give that a try.

**Comment by stancl** [comment]
@jeverington Did it help? If yes, I will add the flag to that call in the package.

**Comment by stancl** [comment]
@jeverington I will be releasing 2.3.0 soon. Did it help and should I add it to package source code?

**Comment by jeverington** [comment]
@stancl my initial problem was fixed due to a problem with a migration that was being swallowed. I feel that adding force by default would fix more problems than it would cause. 
Sorry for the slow reply, I wasn't paying attention to my notifications.

**Comment by stancl** [comment]
> fix more problems than it would cause

Sounds right, also you never use migrate fresh in production, so `--force` probably makes sense.

**Comment by stancl** [comment]
I'll keep this open to see it in the milestone though.

**Comment by stancl** [comment]
Resolved in https://github.com/stancl/tenancy/commit/d0bd8f2ad88d154fe448f5ed93c18ab8749e272f
