### ISSUE TITLE
How to cache static assets for tenants for Nginx

### ISSUE THREAD

**Issue by tobyhage** [archtechx/tenancy#293]
Hello,

I want to cache static assets like images for tenants in Nginx.
When i use:

```
   location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg)$ {
        access_log off;
        expires 365d;
        add_header Cache-Control "public";
    } 
```

in my site config it is not working (for images i get 404 error). My url's are https://www.example.com/tenancy/assets/img.jpg

How can i make this working?

**Comment by stancl** [comment]
Hi,

Take a look at this. Would it perhaps help? https://github.com/stancl/tenancy/issues/7#issuecomment-575715998

**Comment by tobyhage** [comment]
Yes. Thank you!
