### ISSUE TITLE
Passport shared keys

### ISSUE THREAD

**Issue by kevin-ian** [archtechx/tenancy#294]
Hi,

I followed the passport integration (https://tenancy.samuelstancl.me/docs/v2/passport/#passport-integration) and I would like to use the same public and private key for all tenants.

So instead of using `passport:install`, and I just used `passport:keys` as described, then I created a client in the tenant's database oauth_table.

I added `Passport::routes(null, ['middleware' => 'tenancy']);` in my AppServiceProvider.php.

When I try to call `http://user1.localhost:81/oauth/token`, I get the error below

```
"Key path \"file:///var/www/storage/tenant9006664f-ace0-49e5-aecf-75b438d15c76/oauth-private.key\" does not exist or is not readable",
```

Looks like it's trying to load the private key within a folder. Am I missing something? What could be the issue?

Note: If I create a folder named `tenant9006664f-ace0-49e5-aecf-75b438d15c76` and dropped in they keys inside, then everything works fine

How can we use shared keys?

**Comment by kevin-ian** [comment]
Hmmm turns out it's not related to this package. It's a problem in my code. I suggest we keep this open, until I find out the real issue

**Comment by kevin-ian** [comment]
Ok I think we can close this.

For future developers with same problem, here's what I missed.. I had to manage routing conflicts.. I had to add this

```
protected function mapApiRoutes()
{
    foreach (config('tenancy.exempt_domains', []) as $domain) {
        Route::prefix('api')
            ->middleware('api')
            ->domain($domain)
            ->namespace($this->namespace)
            ->group(base_path('routes/api.php'));
    }
}
```

**Comment by sushiljic** [comment]
Sorry for commenting on the closed thread.
@kevin-ian 
Could you please share your code for

> So instead of using passport:install, and I just used passport:keys as described, then I created a client in the tenant's database oauth_table.

I are trying to integrate passport in API but failed with passport.

Thanks in advance.

**Comment by k-ian** [comment]
@sushiljic 

The `passport:keys` is an artisan command.

If I am not mistaken, you can also create a a client using artisan command. No specific code at this point
