### ISSUE TITLE
Create invoice based on tenantbased data

### ISSUE THREAD

**Issue by centiveo** [archtechx/tenancy#295]
I want my central app to create invoices for each tenant(customer) based on the amount of users in a tenant-usertable. What is the best aproach to achieve this?

**Comment by stancl** [comment]
Use `tenancy()->all()` to get all tenants and [Tenant Run](https://tenancy.samuelstancl.me/docs/v2/tenants/#run) to run code inside the tenant's environment.

```php
use Stancl\Tenancy\Tenant;

$tenants = tenancy()->all();

$invoices = $tenants->map(function (Tenant $tenant) {
    $invoice = $tenant->run(function (Tenant $tenant) {
        // whatever is your domain logic for creating invoices
        $userCount = User::count();
        return (new CreateInvoiceAction)($tenant, $userCount);
    });

    return $invoice;
});
```

**Comment by centiveo** [comment]
Thanks!
