### ISSUE TITLE
Stancl/tenancy net::ERR_CONNECTION_CLOSED with React.js and Laravel

### ISSUE THREAD

**Issue by ghost** [archtechx/tenancy#298]
Hi there, I'm implementing the tenancy package into an existing react.js/laravel project of mine and I'm getting the following issues whenever I try to go to the tenants domain: 

GET https://test.localhost:8080/tenancy/assets/css/app.css?v=1 net::ERR_CONNECTION_CLOSED,
GET https://test.localhost:8080/tenancy/assets/js/app.js net::ERR_CONNECTION_CLOSED,
(index):51 GET https://test.localhost:8080/tenancy/assets/images/logo.png net::ERR_CONNECTION_CLOSED,
:8080/tenancy/assets/images/favicon.ico:1 GET https://test.localhost:8080/tenancy/assets/images/favicon.ico net::ERR_CONNECTION_CLOSED

All I've done is install the second version of this package to allow me to use passport. I created a tenant with the URL test.localhost and tried to npm run development and php artisan serve and it just gives me those errors. I haven't changed any code. Does anyone have any suggestions for me?

**Comment by stancl** [comment]
I think your css/js assets should use mix() or global_asset() instead of asset()

**Comment by ghost** [comment]
I should probably mention that I have no non-tenant routes. Essentially all the routes in the project need to apply to all tenants. There is no dashboard or tenant registration. The tenants will be added manually for now but all the routes that were in web.php need to be in tenant.php so I've moved them all over

**Comment by stancl** [comment]
I think you want to load these assets centrally though. That way your webserver can just cache the files instead of having to make a full PHP request, DB call to identify tenant, etc just to serve a file used on all pages.

**Comment by ghost** [comment]
Do you have an example of where to specify assets to be global, this project is a collaboration and react is also fairly new to me. Would it be done in the webpack.mix.js?

**Comment by ghost** [comment]
Don't worry the mix worked, the logos still don't load but I have an idea for those at a later stage. One more thing I wanted to ask is with passport. I've added:
 
Passport::ignoreMigrations();
Passport::routes(null, ['middleware' => 'tenancy']); 

to my AppServiceProvider and I've run php artisan passport:keys. But I'm not entirely sure how to generate the client for the individual tenants, or even use a the same keypair for all tenants. I did: 

1. Uncomment the TenantConfig line in your tenancy.features config
2. Add these keys to your tenancy.storage_to_config_map config:
'storage_to_config_map' => [
    'passport_public_key' => 'passport.public_key',
    'passport_private_key' => 'passport.private_key',
],

but when I tried to register a user I get the error: 

Key path "file://C:\Users\...\storage/tenantf7c0a137-ab25-48db-a6c6-5235fde78c41\oauth-public.key" does not exist or is not readable"

**Comment by stancl** [comment]
Hmm, sounds like the config is loaded by Passport before it is changed by that event listener.

**Comment by ghost** [comment]
Any suggestions on how to fix this? 😁

**Comment by stancl** [comment]
I have never used Passport so I can source dive it but I can't test anything I come up with.

**Comment by ghost** [comment]
I think the easiest way would be to change where the package looks for the key, I have the public key stored under /storage/oauth-public.key, is there a way to change the location from storage/tenantf7c0a137-ab25-48db-a6c6-5235fde78c41\oauth-public.key to just storage/oauth-public.key

**Comment by stancl** [comment]
Seems like the config is loaded here:

https://github.com/laravel/passport/blob/32c3a43686a4214855bd7e67e773a5acbcde7a4b/src/PassportServiceProvider.php#L245

I think you'd have to call that service provider again in the event listener, so maybe something like this:

```php
app()->register(new PassportServiceProvider($this));
```

**Comment by ghost** [comment]
Okay awesome thank you so much

**Comment by ghost** [comment]
Hey man, adding the service provider didn't help but I found a very sneaky work around. In the Crypkey.php construct method for passport I created a method that removes everything after storage in the keypath up until the first "\\" if the keypath contained /tenant. This forces passport to look in the \storage directory for the keys regardless of the tenant. The tenants still have their own passport clients but the keys are shared this way.

**Comment by stancl** [comment]
This is related to the Passport docs, which seem to be out of date anyway. There's a note in the docs and I'll let someone who uses Passport fix that page.
