### ISSUE TITLE
Maintenance mode doesn't work on tenant domains

### ISSUE THREAD

**Issue by tamkeen-tms** [archtechx/tenancy#301]
#### Describe the bug
As per Laravel's code:
```php
    public function isDownForMaintenance()
    {
        return file_exists($this->storagePath().'/framework/down');
    }
```
The check for the "down" file is done in the app storage path, which at this point, will be pointing to the tenant's storage path, which wont have the "down" file. 

So, when the app is taken down, only the central app will be down, not the tenants.

**Comment by stancl** [comment]
Does putting
```php
\App\Http\Middleware\CheckForMaintenanceMode::class,
```
at the very top of your [`$middlewarePriority`](https://github.com/laravel/laravel/blob/6.x/app/Http/Kernel.php#L73) fix this?

**Comment by stancl** [comment]
Hmm, seems like that does not work. I'll see what I can do.

**Comment by stancl** [comment]
This is a bug but I'm removing it from the 2.3.0 milestone to ship the release faster.

**Comment by stancl** [comment]
Fixed in v3.
