### ISSUE TITLE
Tenant based on Session

### ISSUE THREAD

**Issue by Qwans** [archtechx/tenancy#302]
Hi Stancl,

Your package is great! However I am wondering if it is possible to create a multi tenant app with it by just using 1 domain and without path identification.

Example:
app.example.com/home <- default db connection
user creates a company (tenant)

redirect to new company route:
app.example.com/tenant/{company} -> tenantSwitchController puts tenant_id into session and redirect to /dashboard (in routes/tenant.php)
add middleware to all routes/tenant.php something like SetTenant where we resolve the tenant by his tenant_id from session.
_(concept is from Alex from codecourse.com, with his multi tenant tutorial)_

I would like to create a clean URL for all tenants and without requiring a tenant ID or Name in the url all the time.

I hope you get the concept what I am trying to describe. Is something like this possible with your package, or could it be?

**Comment by stancl** [comment]
Sure. Just don't use `routes/tenant.php`, use `routes/web.php` and use custom middleware to [initialize](https://tenancy.samuelstancl.me/docs/v2/tenancy-initialization/#tenancy-initialization) tenancy based on any data you want.
