### ISSUE TITLE
Using Local & Remote Database Connections At The Same Time

### ISSUE THREAD

**Issue by cupcakedream** [archtechx/tenancy#306]
Hey All - 

I'm new to this package and have a question about how it works. I'm assuming this package allows you to create multiple databases within a single instance of MySQL or whatever you're using by default. Is it possible to also use a remote or multiple remote database servers and scale an app horizontally using this package? I'm thinking I might want 40-50 tenants per server, and then will need to add more database servers from there. Is it possible to do something like this?

Thanks,

Mike

**Comment by stancl** [comment]
Sure. You probably want to define each server as a database connection in your `config/database.php` file and then during tenant creation select that connection:

```php
$tenant = Tenant::new()->withData([
    '_tenancy_db_connection' => 'server1',
    // ...
])->save();
```

Or if you don't want to add a connection to your config for every server, you can have a "template" connection and just change the, e.g. host, based on some value in the tenant storage - see [this](https://tenancy.samuelstancl.me/docs/v2/custom-db-connections/#custom-database-names).

**Comment by cupcakedream** [comment]
Great, thanks! So the idea is I would just define additional connections as I create new servers?

**Comment by stancl** [comment]
Yeah. And then store the current connection you want to assign to latest tenant in some config and read from that during tenant creation, to set the connection for the tenant.

**Comment by mreduar** [comment]
Hi! How can I do this for version 3?
