### ISSUE TITLE
Seeder parameters class not use in tenants:seed command

### ISSUE THREAD

**Issue by quaidesbalises** [archtechx/tenancy#307]
Hi,

Thanks for this great package.
When we specify a seeder class in **seeder_parameters** and we turn on the **seed_after_migration** in the **config/tenancy.php** file, that works well. For example :

```php
'seeder_parameters' => [
        '--class' => 'Seeds\Tenant\DatabaseSeeder'
]
```

But after this, if we run ```php artisan tenants:migrate-fresh``` then  ```php artisan tenants:seed```it ignores our class parameters and takes the default laravel DatabaseSeeder.

Obviously, we can override it passing our class in parameter : ```php artisan tenants:seed --class='Seeds\Tenant\DatabaseSeeder'```. It works but it would be cool if it would consider by default the class parameters define in the **config/tenancy.php** file.

**Comment by stancl** [comment]
Hi. The original intention of seeder_params was that they should be used by the automatic seeder but it probably makes sense for the tenant seeder to always use them.

I'll fix this in 2.3.0.

**Comment by stancl** [comment]
@quaidesbalises could you please test my patch?

Run this:
```
composer require stancl/tenancy:dev-use-seeder-params-by-seeder
``` 
and see if `tenants:seed` respects the parameters specified in `config/tenancy.php`.

Thank you.

**Comment by quaidesbalises** [comment]
Just test it. This what I get : 

```
php artisan tenants:seed
Tenant: fe6bf4cc-5fab-489b-9451-c7e359c73b50


  The "--class" option does not exist.

```

**Comment by quaidesbalises** [comment]
Just test it. This what I get : 

```
php artisan tenants:seed
Tenant: fe6bf4cc-5fab-489b-9451-c7e359c73b50


  The "--class" option does not exist.

```

Also, to udpate with the patch broke the application, I don't know if that was normal at this point. It seems like the ```tenancy()->hook('bootstrapped', ...)``` was the issue. I got an **BindingResolutionException** : 

```Target class [cache] does not exist.```

Reinstall the 2.2.8 solved the issue.

**Comment by stancl** [comment]
@quaidesbalises Could you please try again? I pushed a change.

Btw to return to the normal 2.2.8 version you can just run `composer require stancl/tenancy:^2.2`

**Comment by quaidesbalises** [comment]
That is ok :)

```php artisan tenants:seed
Tenant: f1dcbff2-c18f-4557-9fb3-73c9ae5f99c6
Seeding: Seeds\Tenant\UsersTableSeeder
Utilisateur gbecker@example.net crée
Seeded:  Seeds\Tenant\UsersTableSeeder (0.06 seconds)
Database seeding completed successfully.
```

Btw, steel need to remove ```tenancy()->hook('bootstrapped', ...)```in **AppServiceProvider** to make this release works. Is it normal ?

**Comment by stancl** [comment]
2.2.8 works fine but this patch doesn't? Can you show me your AppServiceProvider code?

**Comment by quaidesbalises** [comment]
```php

<?php

namespace App\Providers;

use Illuminate\Support\Facades\Session;
use Illuminate\Support\ServiceProvider;
use Inertia\Inertia;
use Spatie\Permission\PermissionRegistrar;
use Stancl\Tenancy\TenantManager;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->registerInertia();
        $this->registerTenancy();
    }

    private function registerInertia()
    {
        Inertia::version(function () {
            return md5_file(public_path('mix-manifest.json'));
        });
    }

    private function registerTenancy()
    {
        tenancy()->hook('bootstrapped', function (TenantManager $tenantManager) {

            // Spatie - Permission
            PermissionRegistrar::$cacheKey = 'spatie.permission.cache.tenant.'.
            $tenantManager->getTenant('id');

            // Inertia - Variables
            Inertia::share([
                'app_name' => config('app.name'),
                'locale' => config('app.locale'),
                'tenant' => collect($tenantManager->getTenant('data'))->except('id')
            ]);

            Inertia::share([
                'flash' => function () {
                    return [
                        'success' => Session::get('success'),
                        'error' => Session::get('error'),
                    ];
                },
                'errors' => function () {
                    return Session::get('errors')
                        ? Session::get('errors')->getBag('default')->getMessages()
                        : (object) [];
                },
            ]);



        });
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        
    }
}
```

Yes exactly. In 2.2.8, all is ok. If I test the patch, app doesn't work until I remove the ```tenancy()->hook('bootstrapped', ...)```in **AppServiceProvider**

**Comment by stancl** [comment]
And if you remove the hook, the app works fine?

**Comment by stancl** [comment]
Also could you show me the whole exception please? I wonder what is the cause of the issue, if it could be the newly added caching layer for tenant identification.

**Comment by quaidesbalises** [comment]
Yes for sure : 

<img width="1017" alt="Capture d’écran 2020-03-15 à 13 49 15" src="https://user-images.githubusercontent.com/25004867/76701729-feefb680-66c3-11ea-97f2-cb4a944c3c7b.png">

<img width="1437" alt="Capture d’écran 2020-03-15 à 13 49 36" src="https://user-images.githubusercontent.com/25004867/76701735-0747f180-66c4-11ea-88f9-e77aef4050a8.png">

**Comment by stancl** [comment]
Thanks for sharing that. Could you also share the exception via Flare so that I can inspect the stack trace? It would help me a lot.

**Comment by quaidesbalises** [comment]
I don't know why but as you can see on the screenshot, the share Flare tab does not appear on this error. On others errors exception I have it but not there.

**Comment by stancl** [comment]
Alright. Could you then test registering the hook, but leaving the function empty? I need to know if the issue is that you register the hook, or the logic that happens inside the closure.

I feel like this part is the most likely to cause the exception:

![Screenshot from 2020-03-15 16-20-33](https://user-images.githubusercontent.com/33033094/76704401-0b323e80-66d9-11ea-9634-c33fba036925.png)

**Comment by quaidesbalises** [comment]
Already tested it but always have the issue (with and without the TenantManager class pass in the closure) : 

<img width="995" alt="Capture d’écran 2020-03-15 à 16 24 40" src="https://user-images.githubusercontent.com/25004867/76704461-7f6ce200-66d9-11ea-9ded-d939563c2002.png">

<img width="1408" alt="Capture d’écran 2020-03-15 à 16 24 35" src="https://user-images.githubusercontent.com/25004867/76704463-84ca2c80-66d9-11ea-97b6-a63a89c5d6de.png">

**Comment by stancl** [comment]
Alright, that makes it pretty easy to reproduce for me. I'll try to fix that today.

Thanks a lot for all the help!

You can revert to 2.2.8 now:

```
composer require 'stancl/tenancy:^2.2'
```

**Comment by quaidesbalises** [comment]
okay no problem. Thanks for your time. :)

**Comment by stancl** [comment]
@quaidesbalises Could you try moving those events hooks to your `boot` method in `AppServiceProvider`? `register()` is for registering things into the service container and `boot()` is for adding behavior and configuration.

**Comment by quaidesbalises** [comment]
@stancl  That's working, thanks
