### ISSUE TITLE
Problem with DB::beginTransaction()

### ISSUE THREAD

**Issue by fmiqbal** [archtechx/tenancy#310]
Using vanilla config, I try to create a tenancy, and because this flow is coupled with `Institution` (the tenancy object)  I always use `DB::transaction()` to make sure and for testing, but using `DB::transaction()` alone only rollback the `Institution` model, not the `Tenant`.

1. Not working
```
DB::transaction(function () use ($request, $institution){
    $institution->fill($request->toArray());

    $domain = $request->get('domain') . '.edu.facade.test';

    $tenant = Tenant::new()
        ->withDomains($domain)
        ->save();

    $institution->forceFill([
        'tenant_id' => $tenant->id
    ]);

    $institution->save();

    throw new \Exception('Failed oi');
});
```

2. using beginTransaction() also didn't work
3. I try to use 
`DB::on(Tenant::new()->getConnectionName())->beginTransaction()` but still didnt work
4. Filling the config for `tenancy.storage_drivers.db.connection` and using `DB::on('mysql_tenant')->beginTransaction()` (`mysql_tenant` being my new connection copied from vanilla config.database mysql) seems to work

I have tried searching `Transaction` on both documentation and this issue, but doesn't get answer I was hoping for, is this a feature, a bug ? or did I miss something ?

**Comment by stancl** [comment]
Strange. Transactions should work out of the box. Are you trying to run the transaction inside the tenant app on the central DB?

Does this work?
```php
use Stancl\Tenancy\StorageDrivers\Database\DatabaseStorageDriver;

DatabaseStorageDriver::getCentralConnection()->beginTransaction(function () {
    // ...
});
```

Or are you trying to run the transaction on the central DB, inside the central app? That should just work. Maybe the issue is that transactions don't let you create databases, like `Tenant::new()->save()` does?

**Comment by fmiqbal** [comment]
Hmm, I used this on my central app, the route is in web.php as described in 
```
Route::group([
    'middleware' => 'auth',
], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('institutions', 'InstitutionController')
        ->only(['create', 'store', 'destroy']);
});
```

> Does this work?

sadly its not

on another strange behaviour, 
```
beginTransaction
-> do instituion save
-> do tenant save
-> rollback()
```

make my instituion not getting rollbacked, meanwhile

```
beginTransaction
-> do instituion save
-> rollback

beginTransaction
-> do tenant save
-> rollback()
```
did make institution getting rollbacked, tho the tenant still saved

**Comment by fmiqbal** [comment]
oh thanks for your concern anyway, I am not into development yet, just trying to set my foot on what I want to build, so, don't concern it much, probably I setted this up wrongly somewhere, your package's rock anyway, it really did out of the box :+1:

**Comment by stancl** [comment]
I think the issue is what I said:

> Maybe the issue is that transactions don't let you create databases, like `Tenant::new()->save()` does?
