### ISSUE TITLE
how can i redirect from tenant to central

### ISSUE THREAD

**Issue by laracodedeveloper** [archtechx/tenancy#311]
I try to redirect page from tenant page to the central page please can you help me?

**Comment by stancl** [comment]
Where do you need to make the redirect happen? Can you show some code?

If you need to redirect from a tenant domain to a central domain using `return redirect()`, you could just use [Tenant Redirect](https://tenancy.samuelstancl.me/docs/v2/features/tenant-redirect/#tenant-redirect) and use the central domain.

**Comment by laracodedeveloper** [comment]
> Where do you need to make the redirect happen? Can you show some code?
> 
> If you need to redirect from a tenant domain to a central domain using `return redirect()`, you could just use [Tenant Redirect](https://tenancy.samuelstancl.me/docs/v2/features/tenant-redirect/#tenant-redirect) and use the central domain.


Thank you so much, yup this working for me:
return redirect()->route('dashboard')->tenant($domain);

**Comment by stancl** [comment]
Glad to hear that.
