### ISSUE TITLE
Hostname header

### ISSUE THREAD

**Issue by rayleroux** [archtechx/tenancy#320]
Hi,

I use the Tenancy package on a micro-service which receives requests via internal network from an API gateway.

At the moment the API gateway is receiving the request and adding a header to it called "hostname" containing the domain used.

I've then modified ../src/Middleware/InitializeTenancy.php with the following code.

Before:
`
tenancy()->init($request->getHost());
`

After:
`
if($request->header('hostname')){
	tenancy()->init($request->header('hostname'));
} else {
	tenancy()->init($request->getHost());
}
`

Is there a better way to do this without having to reapply the change on every update?

Cheers,
Ray

**Comment by stancl** [comment]
Hi,

Sure. Create your own middleware class and replace [this](https://github.com/stancl/tenancy/blob/2.x/assets/config.php#L114) with your class.
