### ISSUE TITLE
Creation without DB

### ISSUE THREAD

**Issue by VConsulting** [archtechx/tenancy#324]
Is it possible to create a Tenants by specifying the name of a DB that already exists?
exemple :
`
$domains = ['site3.test'];
        Tenant::create($domains, [
            'plan' => 'free',
            '_tenancy_db_name' => 'nameDB',
            '_tenancy_db_create' => 0
        ]);
`

**Comment by stancl** [comment]
Could you please describe the use case for this?

**Comment by VConsulting** [comment]
Example:
- host or creation of DB is not permitted by programming.
therefore creation by another reach of the DB, upstream to then add a tenant.
- integration of temat with another already existing application whose DBs already exist.
...

**Comment by stancl** [comment]
Apparently I already added this feature. See https://github.com/stancl/tenancy/pull/299

It will be available shortly in 2.3.0.

**Comment by VConsulting** [comment]
I'm using version 2.3.0

I still want to link the tenant to the database that already exists. It would therefore be necessary to create the tenant and configure with the database indicated.

> Stancl \ Tenancy \ Exceptions \ TenantDatabaseAlreadyExistsException: the tenant cannot be created. Reason: the database already exists.

I get the error "The database already exists." it always seems to be trying to create the database instead of ignoring the creation, or am I making a mistake when requesting the creation?

`
        $domains = ['site3.test'];
        Tenant::create($domains, [
            '_tenancy_db_name' => 'DB_site3',
            '_tenancy_create_database' => false
        ]);
`

**Comment by stancl** [comment]
Hmm, maybe the "database exists" check runs even if DB creation is disabled. I'll look into it.

**Comment by stancl** [comment]
https://github.com/stancl/tenancy/commit/df99e3e7116265ba8540111ccbbef08f122bbab1

**Comment by travnettech** [comment]
I am facing the same issue. I freshly migrated the database and still it is showing **### Stancl\Tenancy\Exceptions\TenantDatabaseAlreadyExistsException: Tenant cannot be created. Reason: Database  already exists.**
this error. Can you please tell me how to solve it?

**Comment by thomas-tahmasebi** [comment]
> I am facing the same issue. I freshly migrated the database and still it is showing **### Stancl\Tenancy\Exceptions\TenantDatabaseAlreadyExistsException: Tenant cannot be created. Reason: Database already exists.** this error. Can you please tell me how to solve it?

Hi,
It was the same problem for me, I deleted all databases that were related to my multi-tenancy, and I re-ran migrate and seed, and it is working now.
There is already a database that you are trying to create.

**Comment by ali635** [comment]
> I am facing the same issue. I freshly migrated the database and still it is showing **### Stancl\Tenancy\Exceptions\TenantDatabaseAlreadyExistsException: Tenant cannot be created. Reason: Database already exists.** this error. Can you please tell me how to solve it?

do solve problem ? 
I am facing the same issue.

**Comment by ali635** [comment]
exception
: 
"Stancl\\Tenancy\\Exceptions\\TenantDatabaseAlreadyExistsException"

: 
"Tenant cannot be created. Reason: Database tenantcf49dbc7-8d3d-4d05-9dc1-7232b60657ef already exists."

**Comment by gotzsys** [comment]
**Summary**
Tenant creation runs as a queued pipeline (create DB, migrate, seed, post-setup jobs).
If a later step fails, the queue retries the pipeline from the beginning.
On retry, the create DB step runs again and fails because the tenant database was already created in the first attempt.

**Root cause**
The first pipeline step was not idempotent.
Retries re-executed database creation and raised TenantDatabaseAlreadyExistsException.

**Proposed fix**
Make the first step idempotent: if the database already exists during retry, log and continue the pipeline.

**Expected result**
Retries no longer fail on “database already exists”
Migrations/seed/follow-up jobs can complete on retry
Fewer manual delete/recreate operations

**Proposed code**

Idempotent create-database job

```php
<?php

declare(strict_types=1);

namespace App\Jobs\Tenants;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\DatabaseManager;
use Stancl\Tenancy\Events\CreatingDatabase;
use Stancl\Tenancy\Events\DatabaseCreated;
use Stancl\Tenancy\Exceptions\TenantDatabaseAlreadyExistsException;

class CreateDatabaseIfNotExistsJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /** @var TenantWithDatabase|Model */
    protected $tenant;

    public function __construct(TenantWithDatabase $tenant)
    {
        $this->tenant = $tenant;
    }

    public function handle(DatabaseManager $databaseManager)
    {
        event(new CreatingDatabase($this->tenant));

        // Keep compatibility with Stancl's create_database internal flag behavior.
        if ($this->tenant->getInternal('create_database') === false) {
            return false;
        }

        $this->tenant->database()->makeCredentials();

        try {
            $databaseManager->ensureTenantCanBeCreated($this->tenant);
            $this->tenant->database()->manager()->createDatabase($this->tenant);

            event(new DatabaseCreated($this->tenant));

        } catch (TenantDatabaseAlreadyExistsException $exception) {
            Log::warning('Tenant database already exists during pipeline retry. Continuing.', [
                'tenant_id' => $this->tenant->getTenantKey(),
                'database' => $this->tenant->database()->getName(),
                'job' => static::class,
            ]);
        }
    }
}
``` 

Use this job as the first step in TenantCreated pipeline

```php
Events\TenantCreated::class => [
  JobPipeline::make([
  \App\Jobs\Tenants\CreateDatabaseIfNotExistsJob::class,
  Jobs\MigrateDatabase::class,
  Jobs\SeedDatabase::class,
  ])->send(function (Events\TenantCreated $event) {
  return $event->tenant;
  })->shouldBeQueued(true),
],
```

**Comment by stancl** [comment]
> Tenant creation runs as a queued pipeline (create DB, migrate, seed, post-setup jobs).
> If a later step fails, the queue retries the pipeline from the beginning.
> On retry, the create DB step runs again and fails because the tenant database was already created in the first attempt.

Already addressed by CreateDatabase::$ignoreExisting in v4.

**Comment by gotzsys** [comment]
Thanks, Samuel — I’ve left the proposed solution in place for those still using the older version.
