### ISSUE TITLE
Seed with nwidart.com/laravel-modules each tenant

### ISSUE THREAD

**Issue by t-prod** [archtechx/tenancy#326]
Hi,

I'm using your fantastic package to develop a SAAS app. I'm using https://nwidart.com/laravel-modules/ and would like to seed every module foreach tenants. How can I do ?

Seeders are in each Modules/module_name/ Seeds/MySeed.php so how can I configure from your module ?

Thanks again

Regards

**Comment by stancl** [comment]
Hi,

I've never used that package and I unfortunately don't have the time to look into it now, so I can't really help.

I'll keep this open though, if someone has done this and can help.

**Comment by laracodedeveloper** [comment]
I think i have found a solution about this - tenant_route('home', [], $domain); its working perfect

**Comment by t-prod** [comment]
Hi,

@laracodedeveloper do you have a more precise example ? Do you tell me that you redirect the route to do the seed ?

**Comment by stancl** [comment]
I think they're just confused and meant to answer in this thread https://github.com/stancl/tenancy/issues/325

**Comment by t-prod** [comment]
Thanks stancl maybe we can override the seed to it in different namespaces ? Is there a way to do it ? Maybe a loop for each tenant and a seed by changing the database connection ?

**Comment by stancl** [comment]
Again, I have no clue and I don't have the time to focus on this right now. I suggest looking into the source code of this package and that module package.

**Comment by rajakhoury** [comment]
@t-prod I'm interested why is this an issue? I haven't used both packages a lot but I think you can call your modules seeders from a master seeder just like you normally do

**Comment by t-prod** [comment]
Hi,

When you are developing Modules with Nwidart you have the ability to seed in Modules/Database/Seeders. If you have the tenancy package is useless cause the tenant database is unknown ;) Indeed the solution it's to centralize all the seeders in the classical way database\seeds\DatabaseSeeder.php

**Comment by t-prod** [comment]
I would like it will be in each Module for a better organization ;)

**Comment by stancl** [comment]
> I would like it will be in each Module for a better organization

Why not call each module's seeder from the central seeder? How is that bad organization?

**Comment by t-prod** [comment]
If you have a lot of Modules you will have to comment Seeder for each module is active or not.
It's same thing for migrations. Maybe I'm wrong but it would be easier not to centralize all of them.

For instance, if you want to migrate and seed one module when you have more of 6.

**Comment by rajakhoury** [comment]
I feel your frustration as I tend to spend hours structuring things myself but you may be overthinking it here. 
This package has an artisan command `tenants:run` and a callback that you could use to run your own migration logic or use the built-in nWidart `modules:seed`  - if don't intend to publish your app so people can extend it you maybe you do not need the modules package at all ( [here ](https://github.com/invoiceninja/invoiceninja) is nice usage of nWidart package ) alternatively do it the laravel [way](https://laravel.com/docs/master/packages) and structure your app into modules where each module could have its own Providers, Migrations, Routes, Lang ect..
I recommend you watch this [video](https://youtu.be/T-gHOXFpZvg) as there's an interesting question at the end how to handle migrations and he suggests to provision all databases in advance which could make sense if your expecting alot of users or want to make sure everything is order.
I personally would create separate repositories and a core library that shares all the business logic ( Models, Repositories, Contracts.. ) for example a) Tenant app b) Tenant manager ( my own admin panel ) c) Marketing website / Logins / Registrations 
There are many ways to do this, what I am trying to say is don't rely entirely on any package and those checks you mention you need to do them eventually - I think this package is flexible giving you the choice on how to do it.
To answer you question you can do both method centralize all migrations / seeders or keep it seperate.

**Comment by yashiroiori** [comment]
> If you have a lot of Modules you will have to comment Seeder for each module is active or not.
> It's same thing for migrations. Maybe I'm wrong but it would be easier not to centralize all of them.
> 
> For instance, if you want to migrate and seed one module when you have more of 6.

I make a command to run migration and seeder for each modulo with this package

Need {Module name}[are folder name into folder Modules] {tenand_id} and {--seed} flag to run seeder
I use the namespace to run using path into migration and --class to run seeder

![image](https://user-images.githubusercontent.com/17031855/79804179-1f490b80-8329-11ea-96c3-712b2e3b190b.png)

**Comment by t-prod** [comment]
Thanks for sharing, we have the same problem and your solution looks great ;)

**Comment by thamibn** [comment]
@yashiroiori thanks for your solution i will try that because i want to use nwidart/laravel-modules with this package i was also wondering how it will work with the migrations and seeders.

but this means i can no longer use the automatic migration config after creating a tenant right?.

@t-prod thanks for opening the issue i was about to ask the same thing too.

**Comment by stancl** [comment]
You can dynamically set `tenancy.migration_parameters`.

https://github.com/stancl/tenancy/blob/2.x/assets/config.php#L103

```php
'--path' => [
    'path1',
    'path2',
],
```
should work

**Comment by thamibn** [comment]
@stancl oh wow nice!!,

 so basically that will solve the problem with nwidart/laravel-modules by simple configuring stancl/tenancy and tell it where the migrations are located for each module still need to try that.

thanks.

**Comment by lucassmacedo** [comment]
```
<?php

if (!function_exists('modules_directoires_migration')) {
    /**
     * set modal info
     *
     * set the title, message, and any fields for the modal
     *
     */
    function modules_directoires_migration()
    {
        $path        = base_path('Modules');
        $directories = [];
        foreach (new \DirectoryIterator($path) as $file) {
            if ($file->isDot()) continue;

            if ($file->isDir() && !$file->isDot()) {
                $directories[] = $path . DIRECTORY_SEPARATOR . $file->getFilename() . DIRECTORY_SEPARATOR . config('modules.paths.generator.migration.path');
            }

        }

        return $directories;
    }
}
```

**Comment by lucassmacedo** [comment]
tenancy.php
```
    'migration_parameters' => [
        '--force'    => TRUE, // This needs to be true to run migrations in production.
        '--path'     => modules_directoires_migration(),
        '--realpath' => TRUE,
    ],
```

**Comment by NerdSnipe** [comment]
## Migrate and Seed Laravel Modules (nwidart)
Not sure if anyone else could use this but here is a solution that handles the migration and seeding of modules from within the JobPipeline.

### Modify the location of module migration files.
* To prevent the module's migrations from being run on the main (central) database, modify the ```config/modules.php``` file by adding 'tenant' to the path as in the example below.

```php
        /*
        |--------------------------------------------------------------------------
        | Generator path
        |--------------------------------------------------------------------------
        | Customise the paths where the folders will be generated.
        | Set the generate key to false to not generate that folder
        */
        'generator' => [
           // ...
            'migration' => ['path' => 'Database/Migrations/tenant', 'generate' => true], // modify this line
          // ...
        ]

```

* Move module migration files to the ```Modules/{ModuleName}/Database/Migrations/tenant``` folder.

### Set the module migration path(s)
* Using the earlier ([thread](https://github.com/archtechx/tenancy/issues/326#issuecomment-695043660)) suggestion add the following to your helpers file

```php
if (!function_exists('modules_directories_migration')) {
    /**
     * set modal info
     *
     * set the title, message, and any fields for the modal
     *
     */
    function modules_directories_migration(): array
    {
        $path        = base_path('Modules');
        $directories = [];
        foreach (new \DirectoryIterator($path) as $file) {
            if ($file->isDot()) continue;

            if ($file->isDir() && !$file->isDot()) {
                $directories[] = $path . DIRECTORY_SEPARATOR . $file->getFilename() . DIRECTORY_SEPARATOR . config('modules.paths.generator.migration.path');
            }

        }

        return $directories;
    }

}
```
### Migrate and Seed as part of the Tenant creation process
* Create two new Jobs ```MigrateModules``` and ```SeedModules```, I will attach examples below.
* Add the Jobs to the JobPipeline (TenancyServiceProvider::events)

```php
use App\Jobs\MigrateModules;
use App\Jobs\SeedModules;
```

```php
 JobPipeline::make([
                    Jobs\CreateDatabase::class,
                    Jobs\MigrateDatabase::class,
                    MigrateModules::class, // NEW JOB
                    SeedModules::class, // NEW JOB
                    // ... 
             ]);
```

```App/Jobs/SeedModules.php```

```php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Config;
use Stancl\Tenancy\Contracts\TenantWithDatabase;

class SeedModules implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /** @var TenantWithDatabase */
    protected TenantWithDatabase $tenant;

    public function __construct(TenantWithDatabase $tenant)
    {
        $this->tenant = $tenant;
    }


    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {

        $modules = \Nwidart\Modules\Facades\Module::toCollection();

        foreach( $modules as $module ){

            $path =  $module->getExtraPath('Database/Seeders');
            $className = $path.'\\'.$module->getStudlyName().'DatabaseSeeder';
            $className = str_replace(base_path(),'', $className);
            $className = str_replace('/','\\', $className);

            $params =   [
                '--class' => $className,
                '--force' => true,
            ];

            Config::set('tenancy.seeder_parameters', $params );
            Artisan::call('tenants:seed', [
                '--tenants' => [$this->tenant->getTenantKey()],
            ]);

        }

    }
}
```

```App/Jobs/MigrateModules.php```

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Config;
use Stancl\Tenancy\Contracts\TenantWithDatabase;

class MigrateModules implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;


    /** @var TenantWithDatabase */
    protected TenantWithDatabase $tenant;

    public function __construct(TenantWithDatabase $tenant)
    {
        $this->tenant = $tenant;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $params =  [
            '--force'    => TRUE, // This needs to be true to run migrations in production.
            '--path'     => modules_directories_migration(),
            '--realpath' => TRUE,
        ];

        Config::set('tenancy.migration_parameters', $params );

        Artisan::call('tenants:migrate', [
            '--tenants' => [$this->tenant->getTenantKey()],
        ]);

    }
}

```

**Comment by yashiroiori** [comment]
> ## Migrate and Seed Laravel Modules (nwidart)
> Not sure if anyone else could use this but here is a solution that handles the migration and seeding of modules from within the JobPipeline.
> 
> ### Modify the location of module migration files.
> * To prevent the module's migrations from being run on the main (central) database, modify the `config/modules.php` file by adding 'tenant' to the path as in the example below.
> 
> ```
>         /*
>         |--------------------------------------------------------------------------
>         | Generator path
>         |--------------------------------------------------------------------------
>         | Customise the paths where the folders will be generated.
>         | Set the generate key to false to not generate that folder
>         */
>         'generator' => [
>            // ...
>             'migration' => ['path' => 'Database/Migrations/tenant', 'generate' => true], // modify this line
>           // ...
>         ]
> ```
> 
> * Move module migration files to the `Modules/{ModuleName}/Database/Migrations/tenant` folder.
> 
> ### Set the module migration path(s)
> * Using the earlier ([thread](https://github.com/archtechx/tenancy/issues/326#issuecomment-695043660)) suggestion add the following to your helpers file
> 
> ```
> if (!function_exists('modules_directories_migration')) {
>     /**
>      * set modal info
>      *
>      * set the title, message, and any fields for the modal
>      *
>      */
>     function modules_directories_migration(): array
>     {
>         $path        = base_path('Modules');
>         $directories = [];
>         foreach (new \DirectoryIterator($path) as $file) {
>             if ($file->isDot()) continue;
> 
>             if ($file->isDir() && !$file->isDot()) {
>                 $directories[] = $path . DIRECTORY_SEPARATOR . $file->getFilename() . DIRECTORY_SEPARATOR . config('modules.paths.generator.migration.path');
>             }
> 
>         }
> 
>         return $directories;
>     }
> 
> }
> ```
> 
> ### Migrate and Seed as part of the Tenant creation process
> * Create two new Jobs `MigrateModules` and `SeedModules`, I will attach examples below.
> * Add the Jobs to the JobPipeline (TenancyServiceProvider::events)
> 
> ```
> use App\Jobs\MigrateModules;
> use App\Jobs\SeedModules;
> ```
> 
> ```
>  JobPipeline::make([
>                     Jobs\CreateDatabase::class,
>                     Jobs\MigrateDatabase::class,
>                     MigrateModules::class, // NEW JOB
>                     SeedModules::class, // NEW JOB
>                     // ... 
>              ]);
> ```
> 
> `App/Jobs/SeedModules.php`
> 
> ```
> namespace App\Jobs;
> 
> use Illuminate\Bus\Queueable;
> use Illuminate\Queue\SerializesModels;
> use Illuminate\Queue\InteractsWithQueue;
> use Illuminate\Contracts\Queue\ShouldQueue;
> use Illuminate\Foundation\Bus\Dispatchable;
> use Illuminate\Support\Facades\Artisan;
> use Illuminate\Support\Facades\Config;
> use Stancl\Tenancy\Contracts\TenantWithDatabase;
> 
> class SeedModules implements ShouldQueue
> {
>     use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
> 
>     /** @var TenantWithDatabase */
>     protected TenantWithDatabase $tenant;
> 
>     public function __construct(TenantWithDatabase $tenant)
>     {
>         $this->tenant = $tenant;
>     }
> 
> 
>     /**
>      * Execute the job.
>      *
>      * @return void
>      */
>     public function handle()
>     {
> 
>         $modules = \Nwidart\Modules\Facades\Module::toCollection();
> 
>         foreach( $modules as $module ){
> 
>             $path =  $module->getExtraPath('Database/Seeders');
>             $className = $path.'\\'.$module->getStudlyName().'DatabaseSeeder';
>             $className = str_replace(base_path(),'', $className);
>             $className = str_replace('/','\\', $className);
> 
>             $params =   [
>                 '--class' => $className,
>                 '--force' => true,
>             ];
> 
>             Config::set('tenancy.seeder_parameters', $params );
>             Artisan::call('tenants:seed', [
>                 '--tenants' => [$this->tenant->getTenantKey()],
>             ]);
> 
>         }
> 
>     }
> }
> ```
> 
> `App/Jobs/MigrateModules.php`
> 
> ```
> <?php
> 
> namespace App\Jobs;
> 
> use Illuminate\Bus\Queueable;
> use Illuminate\Queue\SerializesModels;
> use Illuminate\Queue\InteractsWithQueue;
> use Illuminate\Contracts\Queue\ShouldQueue;
> use Illuminate\Foundation\Bus\Dispatchable;
> use Illuminate\Support\Facades\Artisan;
> use Illuminate\Support\Facades\Config;
> use Stancl\Tenancy\Contracts\TenantWithDatabase;
> 
> class MigrateModules implements ShouldQueue
> {
>     use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
> 
> 
>     /** @var TenantWithDatabase */
>     protected TenantWithDatabase $tenant;
> 
>     public function __construct(TenantWithDatabase $tenant)
>     {
>         $this->tenant = $tenant;
>     }
> 
>     /**
>      * Execute the job.
>      *
>      * @return void
>      */
>     public function handle()
>     {
>         $params =  [
>             '--force'    => TRUE, // This needs to be true to run migrations in production.
>             '--path'     => modules_directories_migration(),
>             '--realpath' => TRUE,
>         ];
> 
>         Config::set('tenancy.migration_parameters', $params );
> 
>         Artisan::call('tenants:migrate', [
>             '--tenants' => [$this->tenant->getTenantKey()],
>         ]);
> 
>     }
> }
> ```

Excelente let me try 👍
