### ISSUE TITLE
Login by select tenant database user table

### ISSUE THREAD

**Issue by laracodedeveloper** [archtechx/tenancy#328]
Can help me, someone, how can log in by select tenant database user table to log in?

**Comment by stancl** [comment]
Please elaborate on your question.

**Comment by Jorgedev** [comment]
View this issues 

https://github.com/stancl/tenancy/issues/224

**Comment by stancl** [comment]
Maybe also this. https://github.com/stancl/tenancy/issues/194#issuecomment-552500495

I have no clue what the question is.
