### ISSUE TITLE
Relationship between central domain and tenant db

### ISSUE THREAD

**Issue by laracodedeveloper** [archtechx/tenancy#330]
First sorry for my English, I need to make the relationship between the central user table and tenant db table,

This Model is related with central database table
```php
class Employer extends Authenticatable
{
    use Notifiable, HasRoles;

    protected $guard = 'employer';

    protected $connection = 'mysql';

    protected $table = 'employer';

    public function invoices()
    {
        return $this->hasMany(Invoices::class,'user_id');
    }

```

But this Model is related with tenant database table
```php
class Ivoices extends Model
{
    protected $table = 'invoices';

}

```

How can I make a relationship between models

**Comment by laracodedeveloper** [comment]
Anyone can help me please?

**Comment by stancl** [comment]
Eloquent is not made for cross-database relationships.
