### ISSUE TITLE
Run command for each tenants

### ISSUE THREAD

**Issue by t-prod** [archtechx/tenancy#332]
Hi,

I have developed a command in a module Module/Report/Console/MyCommand.php.
It's registered in the Kernel/Console.php like this :

$schedule->command('report:seedorders')->twiceDaily(0,12);

How can I run it for each tenants ?

Thanks for your help

**Comment by stancl** [comment]
https://tenancy.samuelstancl.me/docs/v2/tenant-aware-commands/#tenant-aware-commands

**Comment by devonmather** [comment]
I just tried to open a PR for an issue related to this with Laravel 7.0. Unfortunately I had a bit of a hard time setting up the package for testing. I kept getting errors related to "Error: Class 'Redis' not found" 

However the issue in the package with Laravel 7 seems to be the `Traits/TenantAwareCommand::execute()` method needs to return a positive boolean.

https://github.com/stancl/tenancy/pull/331/commits/d2df9a9866f3a3f4412b2400eaa4b55b390abb22

I would be super grateful if there was a CONTRIBUTION.md file or something to that effect that had a bit of of info in regards to setting the package and running tests 😇

**Comment by stancl** [comment]
> Unfortunately I had a bit of a hard time setting up the package for testing
> I would be super grateful if there was a CONTRIBUTION.md

There is 😃. See this: https://github.com/stancl/tenancy/blob/2.x/CONTRIBUTING.md#running-tests

It's just that you should run the tests using the bash scripts that run phpunit in Docker, rather than running it on whatever setup your OS has.

**Comment by devonmather** [comment]
Wow I'm actually blind, sorry. Will work on test and re-open PR if I can isolate a test for the change.

**Comment by stancl** [comment]
No worries. Thanks for contributing!

**Comment by t-prod** [comment]
> https://tenancy.samuelstancl.me/docs/v2/tenant-aware-commands/#tenant-aware-commands

Sorry for that I have looked to the documentation but not anywhere ;)
That's perfect thank you
