### ISSUE TITLE
I get a TenantCouldNotBeIdentifiedException when surfing to a non-existing tenant

### ISSUE THREAD

**Issue by tomdevos** [archtechx/tenancy#334]
Hi,

I have a question. I've set up some tenants, which is working fine. I want to make the application also elegant when surfing tot a non-existing subdomain. When I surf to a subdomain that is not linked to a specific tenant, I get a 500 error with a Stancl\\Tenancy\\Exceptions\\TenantCouldNotBeIdentifiedException. Instead, I would like to redirect to the top domain or give a 403. Is this possible?

Stack Trace:
{
    "message": "Tenant could not be identified on domain xxx.xxx.xxx",
    "exception": "Stancl\\Tenancy\\Exceptions\\TenantCouldNotBeIdentifiedException",
    "file": "/vendor/stancl/tenancy/src/StorageDrivers/Database/DatabaseStorageDriver.php",
    "line": 78,
    "trace": [
        {
            "file": "/vendor/stancl/tenancy/src/TenantManager.php",
            "line": 217,
            "function": "findByDomain",
            "class": "Stancl\\Tenancy\\StorageDrivers\\Database\\DatabaseStorageDriver",
            "type": "->"
        },
        {
            "file": "/vendor/stancl/tenancy/src/TenantManager.php",
            "line": 178,
            "function": "findByDomain",
            "class": "Stancl\\Tenancy\\TenantManager",
            "type": "->"
        },
        {
            "file": "/vendor/stancl/tenancy/src/Middleware/InitializeTenancy.php",
            "line": 37,
            "function": "init",
            "class": "Stancl\\Tenancy\\TenantManager",
            "type": "->"
        },
        {
            "file": "/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Stancl\\Tenancy\\Middleware\\InitializeTenancy",
            "type": "->"
        },
        {
            "file": "/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}

**Comment by stancl** [comment]
See this: https://tenancy.samuelstancl.me/docs/v2/middleware-configuration/#customizing-the-onfail-logic

Alternatively you can catch the exception in your Exception Handler and do some logic.

**Comment by tomdevos** [comment]
Great, thanks a lot! Awesome package by the way!
