### ISSUE TITLE
Allow array values in `storage_to_config_map`

### ISSUE THREAD

**Issue by Neophen** [archtechx/tenancy#335]
#### Describe the feature
When trying to use an Array value in `storage_to_config_map` in tenancy.php config, you get an error.

![tenancy_config](https://user-images.githubusercontent.com/6092928/77330106-8920c600-6d27-11ea-92c7-b583a2d220ca.png)

in `tenancy.php` config:
use an array value to set multiple configs for example:
```php
    'storage_to_config_map' => [ // Used by the TenantConfig feature
        'locale' => [
            'app.locale',
            'app.fallback_locale',
            'translatable.fallback_locale'
        ],
    ],
```

#### Expected behavior
Allow to use Array values in `storage_to_config_map`

**Comment by stancl** [comment]
I told you to open an issue for this *feature*. This is not a bug. This is you trying to do something that can't be done yet.

I will either add this in 2.3.1 or in 2.4.0.

**Comment by Neophen** [comment]
ahh sorry my bad :)

**Comment by Neophen** [comment]
Here is the fix, replace the construct function in `src/Features/TenantConfig.php`
```php
    public function __construct(Repository $config)
    {
        $this->config = $config;

        foreach ($this->getStorageToConfigMap() as $key => $configKey) {
           if (is_array($configKey)) 
           {
                foreach ($configKey as $originalConfigKey) {
                    $this->originalConfig[$originalConfigKey] = $this->config[$key];
                }
            } else {
               $this->originalConfig[$configKey] = $this->config[$configKey];
            }
        }
    }
```

**Comment by stancl** [comment]
Added in v3.
