### ISSUE TITLE
seperation of database users pr tenant when using database as storage driver

### ISSUE THREAD

**Issue by morloderex** [archtechx/tenancy#337]
#### Description
When a new tenant is created and the given application is configured to use the database storage driver we currently still use the same tenant use to connect to the tenant's database. I would like to propose a feature. Which (when opted-in) automatically creates a new seperated database user and when switching to that tenant it's database specific user should then be used to connect to the given database.

#### Why this should be added
Connecting with the same tenant database user for different databases can be quite dangerous for a security standpoint. Think of it like using the same **api token** or **password** for every single website you use. 

One benefit besides the security concern is that for many RDBM's a database user's can have different permissions. We could then configure each tenant's database user so that it for instance cannot delete other databases and anything alike.

On a side note both `tenancy/multi-tenant` and `tenancy/tenancy` comes with this feature build-in.

**Comment by stancl** [comment]
I guess we could store the username and (hashed?) password in tenant storage (`tenants` table) for each tenant and copy that into the DB connection when connecting?

And when creating database, we'd use some connection that has a user who can create databases, create users and assign those users to databases?

**Comment by morloderex** [comment]
@stancl That's exactly what i had in mind. The central database user most have the ability to create databases, grant permissions, create users.. etc.

But we should not hash the password but instead encrypt it. Because we can't get the originial value out if it's hashed. (hashing is a one-way street)

So here is the flows i am talking about:

#### Create tenant database flow: 
1. Check if feature is enabled
2. Generate strings for username and password (optional host should could provided).
3. Create database user with the strings from 2.
4. Create database normally
5. Assign database user to the created database with any provided permissions (should be configurable in the package settings)
6. Lastly encrypt all the generated strings from 1. and store them in the database.

#### Switching tenant database
1. Check if feature is enabled
2. Decrypt database settings
3. Override the tenant database configuration within `database.connections.tenant` with the new values leaving out (driver)
4. Switch connection normally.

**Comment by stancl** [comment]
Sounds reasonable. I did not go down this path by default because setting up DB users and permissions can be a pain and I see people struggle with this when using hyn/multi-tenant.

But as an optional feature this is definitely good. This shouldn't be hard to add so I'll try to make it happen in 2.4.0.

**Comment by stancl** [comment]
Added in v3.
