### ISSUE TITLE
Non-existing domain redirect not working

### ISSUE THREAD

**Issue by swashman** [archtechx/tenancy#339]
Hello,
I am getting a strange issue when trying to implement the non-existent tenant redirect.

My central app route file only contains the basic welcome page route, and my tenant routes directs the app/ through a controller to a basic hello world page. The controller has a auth middleware in its construct to force a login.
This all works as expected with a registered tenant.
When I try to access a non-existent tenant I get the expected error page, when i added the redirect code into the appserviceprovider boot and try to redirect to my base localhost.com, it seems as though the auth logic overrides this somehow and takes me to the tenant login page instead of redirecting to the central site. 

As I was typing this out, I realized I should just try and remove the auth logic and see what happens, however the result was the same and it still tried to load the main tenant page.

**Comment by stancl** [comment]
Can you show me your routes and AppServiceProvider code?

**Comment by swashman** [comment]
my appserviceprovider
```
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;
use Stancl\Tenancy\Middleware\InitializeTenancy;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
        Schema::defaultStringLength(191);
        $this->app->bind(InitializeTenancy::class, function ($app) {
    return new InitializeTenancy(function ($exception) {
        echo "i am broken";
         return redirect()->away('https://www.google.com');
    });
});
    }
}
```

my tenant routes
```

/*
|Main Page
*/
Route::group(['namespace' => 'Tenant', 'prefix' => 'app'], function()
{
    Route::get('/', 'MainController@show')->name('mainpage'); //matches the app/
});


/*
|
|
|  TENANT LOGIN
|
|
*/
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
Route::post('password/confirm', 'Auth\ConfirmPasswordController@confirm');
```

in trying to trace the issue i added the random echo to the app service provider and the echo does show up on the generated login page, so it does properly run the code however it seems the redirect is not firing.

**Comment by swashman** [comment]
Also just tried to move the redirect further along on the process and if i put it in place of my main page controller the redirect works, so it appears its just not working in this particular location.

**Comment by swashman** [comment]
AH issue resolved i believe!
`
return redirect()->away('https://www.google.com');
`
needs to be `redirect()->away('https://www.google.com')->send();`

not a 1 to 1 comparison but resolution was found here
[https://stackoverflow.com/questions/28527202/redirect-in-route-service-provider](url)
