### ISSUE TITLE
How to redirect to global domain if no tenant is found on subdomain?

### ISSUE THREAD

**Issue by devonmather** [archtechx/tenancy#340]
By default if say a user navigates to test.domain.com they get a 500 error. As the docs note I should customize the onFail logic like so. https://tenancy.samuelstancl.me/docs/v2/middleware-configuration/

```
$this->app->bind(InitializeTenancy::class, function ($app) {
    return new InitializeTenancy(function ($exception) {
        // return redirect('https://www.google.com/'); // => test.domain.com/app
        // return redirect()->route('welcome'); // => test.domain.com/app
        return redirect(env('APP_URL')); // => test.domain.com/app
    });
});
```

I have also disabled all use of https://tenancy.samuelstancl.me/docs/v2/tenant-routes/#prevent-access-middleware but that hasn't changed the end result?

I have also enabled and disabled Stancl\Tenancy\Features\TenantRedirect::class in the config but didn't get the results I was looking for.

Any help would be appreciated 🙏🏻

**Comment by stancl** [comment]
```php
redirect(...)->tenant('central.domain');
```

It's called `tenant()` but it actually means "host".

Note that for this you need the TenantRedirect feature enabled.

**Comment by devonmather** [comment]
Hmm still getting same results with `return redirect()->route('welcome')->tenant('domain.com');` 

In my case domain.com is an env variable like env('TENANT_BASE_URL') = appname.com

I've also enabled the TenantRedirect featured, and tried with and without PreventAccessFromTenantDomains middleware enabled.

**Comment by stancl** [comment]
Same result? Show me the requests in dev tools

**Comment by devonmather** [comment]
So i have the following;

* TenantRedirect feature enabled
* PreventAccessFromTenantDomains enabled
* Welcome route is not universal and only on web.php
* TENANT_BASE_URL = betafashion-app.test
* and also no tenant with a sub domain of "test"

```
$this->app->bind(InitializeTenancy::class, function ($app) {
        return new InitializeTenancy(function ($exception) {
            return redirect()->route('welcome')->tenant(env('TENANT_BASE_URL'));
        });
 });
```

Here's the requests in dev tools;
<img width="1221" alt="Screenshot 2020-03-31 at 21 56 44" src="https://user-images.githubusercontent.com/3239389/78069781-f3c2a900-739a-11ea-9343-4e50db49125e.png">
<img width="1217" alt="Screenshot 2020-03-31 at 21 56 54" src="https://user-images.githubusercontent.com/3239389/78069777-f0c7b880-739a-11ea-90bd-efe2439097b0.png">

The above code actually behaves quite odd as I can access Nova dashboard etc on a domain like 123456789.app.com and it prompts me to login. Despite no tenant existing at 123456789.

**Comment by stancl** [comment]
Seems like you visit a central route on a non-central domain, get redirected to /app and then get error 500 that the tenant does not exist?

No, you get 404. That's strange. What domains are in your exempt domains?

**Comment by devonmather** [comment]
Sorry for the hassle on this. This is in my tenancy config.

```
'exempt_domains' => [ // e.g. domains which host landing pages, sign up pages, etc
    env('TENANT_BASE_URL'),
],
```

Are you able to redirect to google.com if a tenant isn't found?

**Comment by stancl** [comment]
This is strange. Are you sure the changes in your service provider are taking place? If you're using `artisan serve` you need to restart the server. Also try clearing config cache and stuff like that.

**Comment by devonmather** [comment]
Yea so, if i put an exit statement in the service provider binding it reaches it. I've just cleared all cached, routes, config etc. but no effect :/

Just to be clear to narrow scope of issue a bit, is it possible if a tenant wasn't found on the subdomain to redirect to an external URL like google.com? If so what would that look like and does it work in your environment?

**Comment by stancl** [comment]
And the environment variable works for sure? Once I get a chance I will test this in my environment.

**Comment by devonmather** [comment]
Yep in the context of the binding I've dumped the value and it exists. Also just tried a hardcoded value in the config but no change in behaviour either. Let me know how you go with it when you test it 🙏🏻

**Comment by zmj888** [comment]
I got this problem too. Please fix it.

**Comment by stancl** [comment]
Open `InitializeTenancy` in your vendor directory and add this `return`. Does it fix the problem for you too? It did for me. If yes, I'll make a new release.

![Screenshot from 2020-04-05 12-38-36](https://user-images.githubusercontent.com/33033094/78472582-62f12200-773a-11ea-8f07-0ef42799fc4e.png)

**Comment by jonagoldman** [comment]
> I got this problem too. Please fix it.

chill

**Comment by zmj888** [comment]
> Open `InitializeTenancy` in your vendor directory and add this `return`. Does it fix the problem for you too? It did for me. If yes, I'll make a new release.
> 
> ![Screenshot from 2020-04-05 12-38-36](https://user-images.githubusercontent.com/33033094/78472582-62f12200-773a-11ea-8f07-0ef42799fc4e.png)

Thanks, It works for me.

**Comment by devoncmather** [comment]
Works for me too, thanks 👍🏻

**Comment by stancl** [comment]
Fixed in https://github.com/stancl/tenancy/commit/4f5ef6fc5602ea2d1caa31942e89166546f8f244

**Comment by coblyox** [comment]
Hi, it fixes redirects but it breaks at other point. For example, InitializeTenancy doesn't return anything response breaks and gives an error: 
`Call to a member function send() on null` at index.php `($response->send();)`

**Comment by coblyox** [comment]
Eg.
`$this->app->bind(InitializeTenancy::class, function ($app) {
                return new InitializeTenancy(function ($exception) {
                    // do nothing
                });
            });`

**Comment by stancl** [comment]
@niunisas Would the middleware passing `$request` and `$next` to the closure, letting you do `return $next($request);` work for you?

**Comment by coblyox** [comment]
@stancl Yea, it would be great. Since kinda building app with both standalone and tenancy modes. At some point if standalone is enabled, I just need to skip Initialization. Maybe other suggestions? (can't do exempt domain)

**Comment by stancl** [comment]
Alright, once the tests pass I'll tag 2.3.3.

Can you describe your use case a bit more? Also maybe DM me on Telegram (`@samuelstancl`) or on the Laravel Discord (also `@samuelstancl`) or create a new issue, to avoid sending notifications to the other people in this thread.
