### ISSUE TITLE
Reusing tables in both central/tenant apps

### ISSUE THREAD

**Issue by Neophen** [archtechx/tenancy#342]
When you want to reuse tables/migrations in both central/tenant apps. you need to change the table class as well as name.

For egzample:

You have in central:
in `database/migrations`
`<date>_create_users_table.php` with name `CreateUsersTable`
and you want to have a tenant users table, you can't just duplicate the migration file, you need to do the following:
in `database/migrations/tenant`
`<date>_create_tenant_users_table.php` with name `CreateTenantUsersTable`

- `create_tenant_users_table`: you can name it whatever just not a duplicate of any files in migrations
- `CreateTenantUsersTable` **has to match** `create_tenant_users_table` just with different casing.

**Comment by stancl** [comment]
Think this is documented in the new docs.
