### ISSUE TITLE
How to use global assets (css,js,less) for every tenant

### ISSUE THREAD

**Issue by utpal93** [archtechx/tenancy#343]
My tenant's are not loading css and js files can i use the global assets in every tenant rather then creating assets for every tenant . Please help me on this.

**Comment by stancl** [comment]
What's unclear? Global assets are documented. What do you mean "creating assets for every tenant"? Just compile them into public/

**Comment by utpal93** [comment]
@stancl  I have my assets in public folder only but when i visit the tenant site it was unable to load the assets(css n js files)

**Comment by stancl** [comment]
Then maybe show some code

**Comment by christophheich** [comment]
> @stancl I have my assets in public folder only but when i visit the tenant site it was unable to load the assets(css n js files)

It works fine, if you have a folder structure like /public/assets/backend/css/file.css you can use it like this:

`<link type="text/css" href="{{ global_asset('assets') }}/backend/css/file.css" rel="stylesheet">`

**Comment by utpal93** [comment]
@christophheich thanks for the help it works..
