### ISSUE TITLE
dependency injection causes table doesn't exist?

### ISSUE THREAD

**Issue by tobyhage** [archtechx/tenancy#345]
Hello,

Can you help me with following issue? Did i something wrong or is it a bug?

I have a command 

```
namespace App\Console\Commands;

use App\Features\PullProductsFromDbFeature;
use Illuminate\Console\Command;

class PullProductsFromDbCommand extends Command
{
    protected $pullProductsFromDbFeature;

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'pim:products:pull-db {feedID=null}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Pull products from feed(s) tables to import_products table';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct(PullProductsFromDbFeature $pullProductsFromDbFeature)
    {
        $this->pullProductsFromDbFeature = $pullProductsFromDbFeature;
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $feedID = $this->argument('feedID');
        $this->pullProductsFromDbFeature->execute($feedID);
    }
}

```

class PullProductsFromDbFeature

```
    public function __construct(PullProductsFromDbJob $pullProductsFromDbJob)
    {
        $this->pullProductsFromDbJob = $pullProductsFromDbJob;
    }

    /**
     * @param string $feedID
     *
     * @return void
     */
    public function execute(string $feedID): void
    {
        $this->pullProductsFromDbJob->execute($feedID);
    }
```

class pullProductsFromDbJob

```
    public function __construct()
    {
        $this->categories = Category::all();
   }
```

When i execute command with:

```
php artisan tenants:run pim:products:pull-db --tenants=<site>
```

i get message central.categories table doesn't exist.
So on this moment the code is not Tenant aware. How can i fix this?

regards,

Toby.

**Comment by stancl** [comment]
Show me more code & the output of the command.

**Comment by tobyhage** [comment]
hereby the output of the command. Which code you want to see? I think i gave you the most important code.

```
   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'central.categories' doesn't exist (SQL: select * from `categories`)

  at /var/www/pim/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   App\Domains\Feed\Jobs\PullProductsFromDbJob::__construct()
      [internal]:0

  2   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'central.categories' doesn't exist")
      /var/www/pim/frontend/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63

```

**Comment by stancl** [comment]
Is that the full output? If you used the `tenants:run` command, you should see the tenant ID printed. https://github.com/stancl/tenancy/blob/2.x/src/Commands/Run.php#L37

**Comment by tobyhage** [comment]
Yes this is the full output, no tenant id
I have changed the first post with the full code of the command. Maybe you see the problem....

**Comment by stancl** [comment]
Well, seems like the issue happens before my command's `handle()` is executed then. I wanted to see the full source code because you may be overriding `execute` in the command or forgetting to call some parent constructor.

**Comment by tobyhage** [comment]
I had placed the full code of the command in the first post. Is this
enough?

Op wo 8 apr. 2020 14:22 schreef Samuel Štancl <notifications@github.com>:

**Comment by stancl** [comment]
I have no idea what's the issue then.

**Comment by tobyhage** [comment]
What do you mean? With this code i get the error

Op wo 8 apr. 2020 14:58 schreef Samuel Štancl <notifications@github.com>:

**Comment by stancl** [comment]
I have no idea what is causing the issue. The tests for `tenants:run` pass so the issue is probably somewhere in your code. Also it would be better to make that command a tenant-aware command rather than running it with tenants:run, since there is no way it can work when run against the central database. See the docs for tenant-aware commands.

**Comment by tobyhage** [comment]
That's a pitty. I made the command Tenant-aware but no difference.

**Comment by tobyhage** [comment]
With this code all my php artisan commands are failing :-(

**Comment by stancl** [comment]
That's a problem with your code, not the package. Sorry, I can't help with that. I think tenant aware commands are pretty well documented.
