### ISSUE TITLE
Telescope tags are broken

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#346]
#### Describe the bug

This line should check for `'universal'` too (combined with a check if tenancy is initialized)

https://github.com/stancl/tenancy/blob/2.x/src/Features/TelescopeTags.php#L33

**Comment by jny986** [comment]
This update has broken the package and causes the following error:

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Stancl\Tenancy\Middleware\PreventAccessFromTenantDomains::routeHasMiddleware() must be an instance of Illuminate\Routing\Route, null given, called in /home/vagrant/vinteract/vendor/stancl/tenancy/src/Features/TelescopeTags.php on line 34 and defined in /home/vagrant/vinteract/vendor/stancl/tenancy/src/Middleware/PreventAccessFromTenantDomains.php:48
Stack trace:
#0 /home/vagrant/vinteract/vendor/stancl/tenancy/src/Features/TelescopeTags.php(34): Stancl\Tenancy\Middleware\PreventAccessFromTenantDomains::routeHasMiddleware()
#1 [internal function]: Stancl\Tenancy\Features\TelescopeTags->Stancl\Tenancy\Features\{closure}()
#2 /home/vagrant/vinteract/vendor/laravel/telescope/src/Telescope.php(255): call_user_func()
#3 /home/vagrant/vinteract/vendor/laravel/telescope/src/Telescope.php(342): Laravel\Telescope\Telescope::record()
#4 /home/vagrant/vinteract/vendor/laravel/telescope/src/Watchers/ExceptionWatcher.php(52): Laravel\Telescope\Telescope::recordException()
#5 /home/v in /home/vagrant/vinteract/vendor/stancl/tenancy/src/Middleware/PreventAccessFromTenantDomains.php on line 48
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Stancl\Tenancy\Middleware\PreventAccessFromTenantDomains::routeHasMiddleware() must be an instance of Illuminate\Routing\Route, null given, called in /home/vagrant/vinteract/vendor/stancl/tenancy/src/Features/TelescopeTags.php on line 34 and defined in /home/vagrant/vinteract/vendor/stancl/tenancy/src/Middleware/PreventAccessFromTenantDomains.php:48
Stack trace:
#0 /home/vagrant/vinteract/vendor/stancl/tenancy/src/Features/TelescopeTags.php(34): Stancl\Tenancy\Middleware\PreventAccessFromTenantDomains::routeHasMiddleware()
#1 [internal function]: Stancl\Tenancy\Features\TelescopeTags->Stancl\Tenancy\Features\{closure}()
#2 /home/vagrant/vinteract/vendor/laravel/telescope/src/Telescope.php(255): call_user_func()
#3 /home/vagrant/vinteract/vendor/laravel/telescope/src/Telescope.php(342): Laravel\Telescope\Telescope::record()
#4 /home/vagrant/vinteract/vendor/laravel/telescope/src/Watchers/ExceptionWatcher.php(52): Laravel\Telescope\Telescope::recordException()
#5 /home/v in /home/vagrant/vinteract/vendor/stancl/tenancy/src/Middleware/PreventAccessFromTenantDomains.php on line 48
Script @php artisan optimize:clear handling the post-autoload-dump event returned with error code 255`

**Comment by stancl** [comment]
@jny986 Thanks for reporting. Can you try if adding:

```php
if (! request()->route() {
    return $tags;
}
```

to this line fixes the problem? https://github.com/stancl/tenancy/blob/2.x/src/Features/TelescopeTags.php#L33

**Comment by jny986** [comment]
Thanks

That fixes the issues thanks

**Comment by stancl** [comment]
Alright, will make a new release. Thanks for letting me know :)
