### ISSUE TITLE
Database connections, users, etc.

### ISSUE THREAD

**Issue by rmsj** [archtechx/tenancy#351]
Am I understanding this correct?
The setting database.based_on will be used not as a base, but be copied with same DB user name and password for all tenants. There are no new database users being created but the same one with permission for all databases.

Also, this needs to be someone with global privileges right?

**Comment by stancl** [comment]
Yes, that's correct.

But we're working on a feature that will let you create a DB user for each tenant. Should be added in the next few weeks.

**Comment by rmsj** [comment]
That sounds great. Thanks for the quick response.
Would it be a good idea to wait or could I hook into the `database.creating` and do something like that?

**Comment by stancl** [comment]
At what stage is your app? If it's still in development, I would just use a root user and then once the feature comes out, you can use it.

And yeah, if I were to "hack" this feature together in my app, I would use `database.creating` to run a create user query before the create database query is executed (or maybe after the DB is created, so that we can assign it permissions to that DB?), and I would put the username into the tenant's storage. Then, I'd use `bootstrapping` event or something to set the DB connection user before tenancy is initialized.

**Comment by rmsj** [comment]
Thanks very much.
Do you have a ticket number we can follow up.

Our app is under development but soon to be released.
Just as a side note, a big side note, your package is awesome. Thanks for releasing this.

**Comment by stancl** [comment]
@morloderex is working on the PR. I think we can get it done in 1-2 weeks.

**Comment by rmsj** [comment]
What would be a good place to add my 'bootstraping' hook code?

**Comment by rmsj** [comment]
Ok, I've endup extending the `Stancl\Tenancy\TenantDatabaseManagers\MySQLDatabaseManager` class as a quick way to create and delete users. In my case, for specific reasons to my app, they have select access to the central database.
 
Then I've used a service provider boot method to hook into the bootstraping event.
If you have time, let me know what you think.
This could be easily extended into settings, were you can tell what are the permissions, if any, of tenant db users into central db, etc.

Password could be on settings as well - like: what is the password generator for db users for tenants. Then this could be saved into data field or something like that.

Example of what I've done:


`class DatabaseTenancyManager extends MySQLDatabaseManager
{
    /**
     * Creates DB user for tenant
     *
     * @param string $dbName
     * @return bool
     */
    public function createUser(string $dbName): bool
    {
        $userName = tenant_username($dbName);
        $password = self::password($userName);

        $centralDb = env('DB_DATABASE');

        if ($this->database()->statement("GRANT ALL PRIVILEGES ON `$dbName`.* TO '$userName'@'%' IDENTIFIED BY '$password';")) {
            return $this->database()->statement("GRANT SELECT ON `$centralDb`.* TO '$userName'@'%';");
        }

        return false;
    }

    /**
     * Creates database for tenant
     * @param string $name
     * @return bool
     */
    public function createDatabase(string $name): bool
    {
        if (parent::createDatabase($name)) {
            return $this->createUser($name);
        }

        return false;
    }

    /**
     * Drop database and user
     *
     * @param string $name
     * @return bool
     */
    public function deleteDatabase(string $name): bool
    {
        $userName = tenant_username($name);
        if ($this->database()->statement("DROP USER $userName;")) {
            return parent::deleteDatabase($name);
        }
        return false;
    }

    /**
     * Password on the fly generation
     * @param $source
     * @return string
     */
    public static function password($source)
    {
        return Hash::make($source . " _ " . $source);
    }
}
`

**Comment by rmsj** [comment]
That creates an issue for the migrations.
It should now run under the new tenant specific db user. But still needs the user with global powers.
Which is OK for now.
