### ISSUE TITLE
Registering a new tenant user

### ISSUE THREAD

**Issue by konrad-ch** [archtechx/tenancy#352]
Hello, I'm making register form for a new user (tenant). What I've done so far:
1. create central route for ```/register``` form
2. register method in ```RegisterController``` which creates a new Tenant

And now I want to save new user data in ```users``` table in new tenant database, but the problem is that this new table exists in tenant database and not in current (central) connection.

Is there any recommended way of dealing with this?

**Comment by stancl** [comment]
Once you have the tenant object, you could do

```php
$tenant->run(function ($tenant) {
    User::create(...);
});
```

**Comment by konrad-ch** [comment]
Thanks, works great! (sorry, should have read docs more carefully... :) By the way, this package is awesome! It's so much better than the hyn alternative which is a bit of a mess in my opinion... It is a pity that I did not come across it in the first place.
