### ISSUE TITLE
Exception: get_class() expects parameter 1 to be object, null given

### ISSUE THREAD

**Issue by jonagoldman** [archtechx/tenancy#353]
I'm using the [Laravel IDE Helper](https://github.com/barryvdh/laravel-ide-helper) package.
I get the exception in the issue title when I run `artisan ide-helper:generate` 

It can be fixed in `Stancl\Tenancy\Facades\TenantFacade` doing this:

```php
class TenantFacade extends Facade
{
    protected static function getFacadeAccessor()
    {
        // return Tenant::class;

        // return hardcoded string instead of getting the name from the class
        return '\Stancl\Tenancy\Tenant';
    }
    // ...
}
```

But I'm not sure whats going on...

#### Setup
 - Laravel version: 7.5.2
 - stancl/tenancy version: 2.3.4
 - Storage driver: MySQL

**Comment by stancl** [comment]
Can I see the exception?

**Comment by jonagoldman** [comment]
The exception is thrown by `Barryvdh\LaravelIdeHelper\Alias` and the stacktrace doesn't contain any reference to the Tenancy package, but while debugging I see that it occurs when `get_class()` is called in `Stancl\Tenancy\Facades\TenantFacade`.


```
ErrorException(code: 0): get_class() expects parameter 1 to be object, null given at /xxx/vendor/barryvdh/laravel-ide-helper/src/Alias.php:274
# 0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
# 1 /xxx/vendor/barryvdh/laravel-ide-helper/src/Alias.php(274): get_class()
# 2 /xxx/vendor/barryvdh/laravel-ide-helper/src/Alias.php(61): Barryvdh\\LaravelIdeHelper\\Alias->detectRoot()
# 3 /xxx/vendor/barryvdh/laravel-ide-helper/src/Generator.php(207): Barryvdh\\LaravelIdeHelper\\Alias->__construct()
# 4 /xxx/vendor/barryvdh/laravel-ide-helper/src/Generator.php(228): Barryvdh\\LaravelIdeHelper\\Generator->getValidAliases()
# 5 /xxx/vendor/barryvdh/laravel-ide-helper/src/Generator.php(84): Barryvdh\\LaravelIdeHelper\\Generator->getAliasesByExtendsNamespace()
# 6 /xxx/vendor/barryvdh/laravel-ide-helper/src/Generator.php(74): Barryvdh\\LaravelIdeHelper\\Generator->generatePhpHelper()
# 7 /xxx/vendor/barryvdh/laravel-ide-helper/src/Console/GeneratorCommand.php(113): Barryvdh\\LaravelIdeHelper\\Generator->generate()
# 8 [internal function]: Barryvdh\\LaravelIdeHelper\\Console\\GeneratorCommand->handle()
# 9 /xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
# 10 /xxx/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
# 11 /xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
# 12 /xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
# 13 /xxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
# 14 /xxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
# 15 /xxx/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
# 16 /xxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
# 17 /xxx/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run()
# 18 /xxx/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
# 19 /xxx/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
# 20 /xxx/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
# 21 /xxx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
# 22 /xxx/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
# 23 {main}
```

**Comment by stancl** [comment]
@jonagoldman I think the cause of that is that `Tenant` sometimes resolves to null. You can inject it as a dependency to get the current tenant, but when tenancy is not initialized, it's null. But I wonder why changing it to string helps, it should be literally the same. PHP should change `Tenant::class` to `'Stancl\Tenancy\Tenant'`.

**Comment by jonagoldman** [comment]
Yes, the difference is in the `\` global namespace.
`Tenant::class` resolves to `'Stancl\Tenancy\Tenant'` but I changed to `'\Stancl\Tenancy\Tenant'`.

**Comment by stancl** [comment]
That shouldn't matter though. `\` is only necessary with the `::class` syntax. Strings are automatically considered to be in the global namespace.

**Comment by jonagoldman** [comment]
Yes, I find that strange, but lots of different  packages use facades so I'm trying to find out why it fails here but not in others.
In general I found that most facades just return simple strings like `'sentry'` or `'event-sourcing'` or `'cache'`. And also don't add additional functionality like the `create()` method I see.
I guess I'm just asking myself if there is something I'm not understanding or if the facade implementation should be different.

**Comment by stancl** [comment]
A string is a string, it shouldn't make a difference. The reason I go with the fully namespaced `Tenant` class is that I don't want to bind it twice into the container, and when we use a class name, we can inject it.

Would you be so kind to test this in a fresh Laravel app? I don't use ide-helper. If not, I can just install it myself I guess.

Should be quick:
```sh
laravel new test
cd test
nano .env # comment DB_CONNECTION
touch database/database.sqlite
composer require stancl/tenancy
php artisan tenancy:install
# ... whatever are the installation steps for installing ide-helper
php artisan ide-helper:generate
```

**Comment by jonagoldman** [comment]
Sure I will do it. Im not giving it too much importance is just to generate an ide helper file at the end of the day. I will give it a try.

**Comment by stancl** [comment]
Right. It's a weird bug though. And if the package improves the experience of developers using this package, I'll do my best to fix it.

**Comment by jonagoldman** [comment]
Ok, so I can confirm this issue is happening on a clean Laravel installation:

![Screenshot from 2020-04-14 16-25-13](https://user-images.githubusercontent.com/1297559/79275918-ad764b00-7e6c-11ea-9e52-c80246bf1e57.png)

Exception and stacktrace are the same.

_By the way, I was also going report the bug in the IDE Helper repo, but they have more than 300 open issues so I will post it there only if we find that the problem is related to that package._

**Comment by stancl** [comment]
I'd like to resolve this so I'll leave this open, but I'm removing the bug label as it doesn't break anything and isn't really that high priority.

**Comment by jonagoldman** [comment]
Sure, I'll try to dig deeper if I can. I just don't have enough knowledge of how both packages work.

**Comment by stancl** [comment]
If you want to do that, sure would be helpful.

Some suggestions from my side would be trying some verbose mode for the ide helper command, then doing some dd()ing in the place of the exception.

With regards to my package, the only "weird" thing is that the Tenant object sometimes resolves to null and not an object, and it seems like the ide helper is executing the facade for some reason. Might be because it tries to generate `@method` annotations based on what's available on the object, except there's no `Tenant` object available?

You could try creating a tenant and doing `php artisan tenants:run ide-helper:generate`, to see if running the command with initialized tenancy would help.

**Comment by jonagoldman** [comment]
The issue is that `TenantFacade::getFacadeRoot()` returns `null` so `get_class(null)` throws an exception.

From what I see, the root instance name is `"Stancl\Tenancy\TenantManager"` but `TenantFacade::getFacadeAccessor()` returns `"Stancl\Tenancy\Tenant"` instead, so the instance can't be found in `$app[$name]` and `null` is returned.

I think the instance name comes from the binding in `Stancl\Tenancy\TenancyServiceProvider`

```php
$this->app->bind(Tenant::class, function ($app) {
   return $app[TenantManager::class]->getTenant();
});
```

---

This is the flow when IDE Helper tries to get the facade root:

1) In `Barryvdh\LaravelIdeHelper\Alias` 
```php
protected function detectRoot()
{
    // "\Stancl\Tenancy\Facades\TenantFacade"
    $facade = $this->facade;

    try {
        if (method_exists($facade, 'getFacadeRoot')) {
            $root = get_class($facade::getFacadeRoot());
        }
        // ....
    }
    // ....
}
```
2) In `Stancl\Tenancy\Facades\TenantFacade`:
```php
public static function getFacadeAccessor()
{
    // "Stancl\Tenancy\Tenant"
    return Tenant::class;
}

public static function getFacadeRoot()
{
    return static::resolveFacadeInstance(static::getFacadeAccessor());
}

protected static function resolveFacadeInstance($name)
{
    // false
    if (is_object($name)) {
        return $name;
    }
    // false
    if (isset(static::$resolvedInstance[$name])) {
        return static::$resolvedInstance[$name];
    }
    // true
    if (static::$app) {
        // ✗ static::$app["Stancl\Tenancy\Tenant"] doesn't exist
        // ✔ static::$app["Stancl\Tenancy\TenantManager"] does exist
        return static::$resolvedInstance[$name] = static::$app[$name];
    }
}
```

**Comment by stancl** [comment]
Thanks for the detailed write-up, appreciate it!

Seems like it's not really a bug with either package.

IDE helpers should take the class name from `getFacadeAccessor()` in my case, but it uses `get_class()` on the resolved object because facades can use non-class strings as keys for the underlying objects.

And the way I use the facade is probably not fully "correct", since there are cases when the facade root resolves to null.

The only solution I see would be ide-helper skipping the instance resolution & `get_class()` if `getFacadeAccessor()` returns a class string. I think `is_class($facade::getFacadeAccessor())` would work.

**Comment by stancl** [comment]
They have a ton of open PRs, but I submitted the fix anyway: https://github.com/barryvdh/laravel-ide-helper/pull/916

**Comment by jonagoldman** [comment]
Just tried https://github.com/barryvdh/laravel-ide-helper/pull/916/commits/9817b95511190b7f34b35195e6ecb288e31ade8d and I'm getting a different exception now:

```
RuntimeException(code: 0):
A facade root has not been set. at /xxx/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:258)
# 0 /xxx/vendor/barryvdh/laravel-ide-helper/src/Alias.php(276): Illuminate\\Support\\Facades\\Facade::__callStatic()
# 1 /xxx/vendor/barryvdh/laravel-ide-helper/src/Alias.php(61): Barryvdh\\LaravelIdeHelper\\Alias->detectRoot()
# 2 /xxx/vendor/barryvdh/laravel-ide-helper/src/Generator.php(207): Barryvdh\\LaravelIdeHelper\\Alias->__construct()
# 3 /xxx/vendor/barryvdh/laravel-ide-helper/src/Generator.php(228): Barryvdh\\LaravelIdeHelper\\Generator->getValidAliases()
# 4 /xxx/vendor/barryvdh/laravel-ide-helper/src/Generator.php(84): Barryvdh\\LaravelIdeHelper\\Generator->getAliasesByExtendsNamespace()
# 5 /xxx/vendor/barryvdh/laravel-ide-helper/src/Generator.php(74): Barryvdh\\LaravelIdeHelper\\Generator->generatePhpHelper()
# 6 /xxx/vendor/barryvdh/laravel-ide-helper/src/Console/GeneratorCommand.php(113): Barryvdh\\LaravelIdeHelper\\Generator->generate()
# 7 [internal function]: Barryvdh\\LaravelIdeHelper\\Console\\GeneratorCommand->handle()
# 8 /xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
# 9 /xxx/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
# 10 /xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
# 11 /xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
# 12 /xxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
# 13 /xxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
# 14 /xxx/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
# 15 /xxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
# 16 /xxx/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run()
# 17 /xxx/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
# 18 /xxx/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
# 19 /xxx/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
# 20 /xxx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
# 21 /xxx/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
# 22 {main}
```

**Comment by stancl** [comment]
The tenant facade is removed in v3. Little use case for it anyway.
