### ISSUE TITLE
installation of package

### ISSUE THREAD

**Issue by rogerad** [archtechx/tenancy#355]
my application was working until i tried to install the package .
i get  Migrating: 2019_09_15_000010_create_tenants_table
Migrated:  2019_09_15_000010_create_tenants_table (0.63 seconds)
Migrating: 2019_09_15_000020_create_domains_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `domains` add primary key `domains_domain_primary`(`domain`))

  at C:\xampp\htdocs\LARAVEL69\vendor\laravel\framework\src\Illuminate\Database\Connection.php:665
    661|         // If an exception occurs when attempting to run a query, we'll format the error
    662|         // message to include the bindings with SQL, which will make this exception a
    663|         // lot more helpful to the developer instead of just the database's errors.
    664|         catch (Exception $e) {
  > 665|             throw new QueryException(
    666|                 $query, $this->prepareBindings($bindings), $e
    667|             );
    668|         }
    669|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
      C:\xampp\htdocs\LARAVEL69\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:123

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
      C:\xampp\htdocs\LARAVEL69\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:121

i have already placed   public function boot()
    {
        //
        schema::defaultStringLength(191);  in appserviceprovider
 **this error should not occur**
i have upgraded to laravel 6 framework

**Comment by rogerad** [comment]
i just fixed this if anyone else has problem this is the solution from google   justicenode commented on Mar 8, 2019

i think the problem is that by default laravel uses the utf8mb4 charset which uses more space than the utf8 charset. You can either change the mysql settings to allow for bigger keys or just change the charset to utf8 and the collation to utf8_general_ci in config/database.php under the mysql section. Had this problem more than once and not just with laravel.
@Saibamen
Author
Saibamen commented on Mar 9, 2019

So documentation need to be updated

**Comment by stancl** [comment]
What needs to be updated in the documentation?

**Comment by Saibamen** [comment]
I think @rogerad copy pasted too much text from here: https://github.com/laravel/framework/issues/27806#issuecomment-470745850

**Comment by stancl** [comment]
Ah I see, makes sense. Thanks @Saibamen.

**Comment by rogerad** [comment]
Hi just tell people how to fix it if they get that error
