### ISSUE TITLE
Morph relationship not working

### ISSUE THREAD

**Issue by rmsj** [archtechx/tenancy#359]
#### Describe the bug

Morph relationship does not execute in the context of tenancy.

#### Steps to reproduce
Create a morph relationship on laravel and try to save it using $model->morphRelationname->create([data_here])

It does work when using the save method.
Note: save accepts an instance of the morph relationship, while create takes an array.

#### Expected behavior
I expect the data to be saved on the database for that tenant.

#### Your setup
 - Laravel version: [e.g. 7.6.2]
 - stancl/tenancy version: [e.g. 2.1.0]
 - Storage driver: [DB]

**Comment by stancl** [comment]
$model->morphRelationname

I think this should have () at the end of the call, you're trying to get a builder instance, not resolve a collection.

**Comment by rmsj** [comment]
That was just a typo when reporting the problem, sorry. 
I will try to provide example code.
