### ISSUE TITLE
Can I connect to a central database from a tenant?

### ISSUE THREAD

**Issue by socloccoc** [archtechx/tenancy#361]

**Comment by stancl** [comment]
Yes, create a dedicated connection for the central DB and use `DB::connection('...')` to make the calls, or `use CentralConnection;` on the model (and import it with the full namespace).

**Comment by socloccoc** [comment]
Thank you for the quick response
I'm a beginner, could you please give me a specific piece of code?

**Comment by stancl** [comment]
Piece of code for what? Add a connection named `'central'`, like this: https://github.com/laravel/laravel/blob/master/config/database.php#L46

Set this to `'central'`: https://github.com/stancl/tenancy/blob/2.x/assets/config.php#L14

And use it like `DB::connection('central')->table('foo')->...`, or do

```php
use Stancl\Tenancy\StorageDrivers\Database\CentralConnection;

class Foo extends Model
{
    use CentralConnection;

    // ...
}
```

**Comment by socloccoc** [comment]
Thank you so much!

**Comment by stancl** [comment]
No problem :)

**Comment by sn003bjr** [comment]
Hi! Is there a way to connect to a specific Tenant database from Central Domain?

**Comment by stancl** [comment]
See the manual initialization section in the docs. Also visit our Discord, support questions belong there.

**Comment by sn003bjr** [comment]
Found it! Thank you!
