### ISSUE TITLE
I build an web but?

### ISSUE THREAD

**Issue by turkidkil** [archtechx/tenancy#364]
When registering a new dealer
_Do I do the following \\_

**Comment by stancl** [comment]
> Is there a way to move between databases?

Yes, you can make cross-database queries, for example. Or you can loop through tenants and use `$tenant->run()` to execute some logic.

If you want to access a tenant's admin panel directly, you need an account in that tenant's app and you visit his domain.

**Comment by turkidkil** [comment]
> > Is there a way to move between databases?
> 
> Yes, you can make cross-database queries, for example. Or you can loop through tenants and use `$tenant->run()` to execute some logic.

**Was this explained in the documents? 
https://tenancyforlaravel.com/docs/v2/**

> If you want to access a tenant's admin panel directly, you need an account in that tenant's app and you visit his domain.
okay understood

but How can I access the entire system control panel?
administrator.domain.test

### I have 1,000 tenants
**In the future, I wanted to add a new field to the product table
How is it without Empty the table?**

**Comment by stancl** [comment]
> Was this explained in the documents?

Yes. https://tenancyforlaravel.com/docs/v2/tenants/#run

> How can I access the entire system control panel?
> administrator.domain.test

what? Do you mean this? https://tenancyforlaravel.com/docs/v2/central-app/

> In the future, I wanted to add a new field to the product table
> How is it without Empty the table?

It's literally the same as adding a new field to any table in Laravel. Just create a migration. https://laravel.com/docs/7.x/migrations#creating-columns

Please read documentation of both Laravel and this package.

**Comment by turkidkil** [comment]
### Thank you very much
### You are a wonderful person


> > How can I access the entire system control panel?
> > administrator.domain.test
> 
> what? Do you mean this? https://tenancyforlaravel.com/docs/v2/central-app/

Yes, I have read all the documents
Including this
https://tenancyforlaravel.com/docs/v2/central-app/

But what I meant
I have two control panels
One for the full site administrator
The second is for the tenant
I want to enter Nova through the central domain
To manage the entire system

**_domain.test/nova
not working!_**

How do I tell nova this subdomain
**admin.domain.test**
or
**domain.test/nova**
It is special for administrator

and this subdomain for tenants
**nova_tenants.domain.test**
