### ISSUE TITLE
Laravel Permission Roles (User is not logged in)

### ISSUE THREAD

**Issue by JonathanMMann** [archtechx/tenancy#365]
Hey, I’m having an issue with laravel-permission. When I'm trying to visit api routes with role middleware. When I'm visiting routes that aren't protected by the role middleware they work fine, but when I visit any route with that middleware it's saying that the user isn't logged in.

error:

	message: "User is not logged in."
	exception: "Spatie\Permission\Exceptions\UnauthorizedException"

kernel.php

    protected $middlewarePriority = [
        Tenancy\PreventAccessFromTenantDomains::class,
        Tenancy\InitializeTenancy::class,
    ];	
    protected $middlewareGroups = [
    'web' => [
        Tenancy\PreventAccessFromTenantDomains::class,
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\Session\Middleware\AuthenticateSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\VerifyCsrfToken::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
        \Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,
    ],

    'api' => [
        Tenancy\PreventAccessFromTenantDomains::class,
        'throttle:150,1',
        'bindings',
    ],

api.php

	Route::middleware('tenancy')->group(function () {
	    Route::group(['middleware' => ['role:super-admin|admin|partner', 'auth:api'], 'prefix' => 'admin'], function () {
			Route::get('/dashboard', 'AdminDashboardController@index');
		});
	});

I’ve installed the package and moved over my migrations:

```
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"
mv database/migrations/*_create_permission_tables.php database/migrations/tenant
```

AppServiceProvider:

	public function boot()
    {
        tenancy()->hook('bootstrapped', function (TenantManager $tenantManager) {
            \Spatie\Permission\PermissionRegistrar::$cacheKey = 'spatie.permission.cache.tenant.' . $tenantManager->getTenant('id');
        });
    }
    
 Any thoughts on why this might be happening?

**Comment by stancl** [comment]
Could you share the full stack trace, for example via Flare?

**Comment by JonathanMMann** [comment]
Apparently I don't have ignition workin on the tenancy app. ;) Heres a link to it in codebeautify. Tree view will show it a bit cleaned up:

https://codebeautify.org/jsonviewer/cb3fc6bc

**Comment by stancl** [comment]
That's strange. Maybe applying the `auth:api` middleware *before* the Permissions middleware would help?

**Comment by JonathanMMann** [comment]
Haha. That worked. I've been trying to wrap my head around this for 3 days ... thanks so much!

**Comment by stancl** [comment]
Glad to help :)

**Comment by farshadff** [comment]
> That's strange. Maybe applying the `auth:api` middleware _before_ the Permissions middleware would help?

so wierd but this worked  :D
