### ISSUE TITLE
Calling all(), when using the RedisStorageDriver class, throws error: strlen() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by mattyh88** [archtechx/tenancy#366]
#### Describe the bug
I'm writing my own custom driver, which uses this package DatabaseStorageDriver and RedisStorageDriver. This is because I like to cache tenant data, but mainly store my tenant in my MySQL database. 

Now, when I call the all() function from the RedisStorageDriver, I get this error: 

`strlen() expects parameter 1 to be string, null given`

#### Steps to reproduce
1. Add new custom driver.
2. Inject DatabaseStorageDriver & RedisStorageDriver classes into the new custom driver.
3. Call the RedisStorageDriver's all() method.
4. Configure config/tenancy.php (storage_driver => cache, storage_drivers => add CacheDriver)
5. It's worth mentioning that I've setup a custom Redis connection with these params: 

`'cache' => [
    'host' => env('REDIS_HOST', '127.0.0.1'),
    'password' => env('REDIS_PASSWORD', null),
    'port' => env('REDIS_PORT', '6379'),  
     'database' => env('REDIS_CACHE_DB', '5'),
],`
6. I've also set the connection param of the RedisStorageDriver to this connection in config/tenancy.php

#### Expected behavior
I should get an (empty) array of cached tenants.

#### Your setup
 - Laravel version: v6.14.0
 - stancl/tenancy version: v2.2.7
 - Storage driver: Custom 'Cache' Driver, that uses both DatabaseStorageDriver & RedisStorageDriver

Thanking you in advance.

**Comment by stancl** [comment]
> This is because I like to cache tenant data, but mainly store my tenant in my MySQL database.

This feature is not documented *yet*, but you can do this already. Look at the latest releases: https://github.com/stancl/tenancy/releases/tag/v2.3.0

https://github.com/stancl/tenancy/blob/2.x/assets/config.php#L19

It's also well explained in #348

**Comment by mattyh88** [comment]
Thank you! :)
