### ISSUE TITLE
Filesystem Suffixing Writes In Wrong Folder

### ISSUE THREAD

**Issue by watercayman** [archtechx/tenancy#369]
Thank you for this wonderful package.

I'm having trouble with **writing** files to tenant disks.  As on the filesystem help page, writes go to a suffix folder inside the disk folder, rather than top level.  So, from your docs example, I'm writing to the first, when I want the second:

`/path_to_your_application/storage/clientUploads/tenant1e22e620-1cb8-11e9-93b6-8d1b78ac0bcd/`

`/path_to_your_application/storage/tenant1e22e620-1cb8-11e9-93b6-8d1b78ac0bcd/clientUploads/`

When I go to READ the files, I get an error, since the file is not where tenancy expects it to be.  However, the error is looking for the file in the _correct_ (2nd) directory.  So - reads look to the correct directory - writes/deletes are going to the wrong directory.

I have tried `php artisan config:clear` and `php artisan cache:clear`.  I have tweaked various parts of the `tenancy` file, but I can not get it to write with the top-level tenant.suffix folder.

Here is my **filesystem config**:

`'disks' => [

        'local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
        ],
        'clientUploads' => [
            'driver' => 'local',
            'root'   => storage_path() . '/clientUploads',
        ],`

Here is my **tenancy config**:

`'filesystem' => [ // https://tenancy.samuelstancl.me/docs/v2/filesystem-tenancy/

        'suffix_base' => 'tenant',
        'suffix_storage_path' => true, // Note: Disabling this will likely break local disk tenancy. Only disable this if you're using an external file storage service like S3.
        'asset_helper_tenancy' => false, // should asset() be automatically tenant-aware. You may want to disable this if you use tools like Horizon.
        // Disks which should be suffixed with the suffix_base + tenant id.
        'disks' => [
            'local',
            'clientUploads',
            // 's3',
        ],
        'root_override' => [
            // Disks whose roots should be overriden after storage_path() is suffixed.
            'local' => '%storage_path%/app/',
            'public' => '%storage_path%/app/public/',
        ],
    ],`

Here is an example of how I write to disk:

`\Storage::disk('clientUploads')->put($filename, file_get_contents($file))`

Probably I'm missing something silly.  Appreciate any help please.

**Comment by stancl** [comment]
Can you see https://github.com/stancl/tenancy/issues/308? I tried to reproduce this but it worked for me.

**Comment by watercayman** [comment]
Yes, I read that as well.  I just tried updating the package and it did update from v2.3.4 => v2.3.5, but no luck.  It still writes to the wrong place, and tries to read from the correct place.

**Comment by stancl** [comment]
Hmm, do you maybe see something different in what you're doing and what I'm doing? I'd love to fix this but like I said, I didn't manage to reproduce it.

**Comment by watercayman** [comment]
I understand.  I don't see anything unusual, and I've been poking around for hours.  I'm going to tear down the server and try from scratch.  I will let you know if anything changes.  Thank you again.

**Comment by stancl** [comment]
Thank you! Much appreciated.

**Comment by watercayman** [comment]
I rebooted the server - no change.  I then created a new server from scratch, VMWare vs VBox this time, and cloned my current project.  No change, unfortunately.

I did notice one clue: in both cases, upon Laravel booting (regardless of page or tenant), Laravel immediately created the wrong folders.  So without loading or downloading a file, on the first page I visited on the new server, it created `storage/clientUploads`.  It created a folder for each of my disks (from `filesystems.php`).   Something on the create/write side is bypassing the tenancy replacement folder.  

I don't know Laravel well enough to know where this happens, or why.  Only other thing I can say is that it is Laravel 7.5, but I have been upgrading this app for a very long time (5.something).  Though - the new server installed everything from scratch, so I can't imagine the vendor files would be old versions.  Perhaps another package is interfering?

Any thoughts?  If not, I will try building a Laravel app from scratch tomorrow, add Tenancy, and see what happens.

**Comment by stancl** [comment]
Ah! Just noticed you don't use root_override at all for your two custom disks. It's a bit confusing, but this should help: https://tenancyforlaravel.com/docs/v2/filesystem-tenancy/#filesystem-tenancy

**Comment by watercayman** [comment]
HA!  YES!  That's fantastic, and it is now working perfectly.  Thank you very much for catching that - I was going to spend my day re-inventing the wheel lol.

For dummies like me, may I suggest a slight update to that document?  I read it quite a few times but I didn't understand that the disk needed to be entered in **both** places for this to work correctly (notwithstanding a non-local disk like S3).  I was thinking I needed to add my disks in the `disks` section, but I thought the `root_override` was just for the base folder and not the disks as well.  I realize it does say this, but I didn't follow correctly.  Perhaps add an explicit example outside of the normal Laravel disks inside both areas to highlight? 

Totally my mistake - Tenancy seems to be working fantastically!!  Thank you again.

**Comment by stancl** [comment]
Nice, glad to hear that. Yeah, the filesystem stuff is a bit poorly documented. I've already rewritten the page once but will need to set some time aside for that again. Since root_override works for both me & you, I'm closing #308.
