### ISSUE TITLE
Spatie hasPermissionTo Always return true in tenant

### ISSUE THREAD

**Issue by iazdogar** [archtechx/tenancy#374]
Hi,
I have followed your documentation about spatie permissions,
i have this problem
when i check user has specific permission it always return true even the user doesn't have the permission.
need a little help please

**Comment by stancl** [comment]
That isn't specific enough for me to help you and sounds more like a problem with your code.

**Comment by iazdogar** [comment]
i have removed spatie permissions package, and wrote my own user roles and permissions,
i have another question.
my script is working on central domain.
now i want to define Gates in AuthServiceProvider. How can i make it tenant aware ?
as it is returning central app permissions even i am logged in subdomain.
1. i want to load permissions table entries from central domain if central domain is accessed.
2. i want to load permissions from subdomain when site is accessed.

**Comment by iazdogar** [comment]
I have removed Spatie permissions package and created user roles and permissions myself.
Now i have a problem. 
1. i want to register Gate in AuthServiceProvider for central app and tenant.
2. i have added roles and permissions table migration in central and tenant folder, when i migrate i get error  Symfony\Component\Debug\Exception\FatalErrorException  : Cannot declare class CreateRolesTable, because the name is already in use
