### ISSUE TITLE
Nova Image Field doesn't show the preview

### ISSUE THREAD

**Issue by phuclh** [archtechx/tenancy#375]
#### Steps to reproduce
Add an image field and upload an image, but when you come back the field doesn't show the uploaded image (preview file)

```
Image::make('Logo', 'logo')
    ->rules('dimensions:max_width=400,max_height=300')
    ->disableDownload()
```

#### Your setup
 - Laravel version: 7.6
 - stancl/tenancy version: 2.3
 - Storage driver: public (default)

<img width="555" alt="Screen Shot 2020-04-27 at 5 57 52 PM" src="https://user-images.githubusercontent.com/6707194/80435380-33ed4c80-88b1-11ea-8ee3-aebda4c673d7.png">

**Comment by stancl** [comment]
Sounds like a storage issue, related to #248

**Comment by phuclh** [comment]
> Sounds like a storage issue, related to #248

Yes, the same error. How can I fix it? I don't see any solution in there. Thank you!

**Comment by stancl** [comment]
I haven't gotten to fixing that. Too much other work to do, so "bugs" related to integrating with other packages aren't really a priority right now.

**Comment by sicaboy** [comment]
Meet the same issue. Any idea to solve it?

**Comment by nilsE** [comment]
would need that, too...

**Comment by stancl** [comment]
Nova support will no longer be a primary feature and will soon be replaced with [Lean](http://lean-admin.dev/), which will focus on working with this package perfectly.

**Comment by nilsE** [comment]
very bad. i bought the package mainly because of the nova support. i will stop my support then, sorry.

**Comment by stancl** [comment]
No problem. Nothing is getting removed, Nova support is just no longer a priority because at this point I don't even have time for more important projects.

**Comment by nevishs** [comment]
@stancl, is there an update on this task? I know it has low priority but assuming it has passed 1.5 years till now ....
