### ISSUE TITLE
Access the central database instead of tenant database in constructor function.

### ISSUE THREAD

**Issue by phuclh** [archtechx/tenancy#378]
#### Describe the bug
I tried to get an API key from the database in the constructor functions of a independences injection class, something like that:

```
class BoxmeInventoryAdapter implements InventoryInterface {

    private $apiUrl;

    private $httpClient;

    /**
     * BoxmeInventoryAdapter constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->apiUrl = $this->determineEnvironment();

        $apiKey = nova_get_setting('boxme_api_key');

        if (!$apiKey) throw new \Exception('Boxme API Key is invalid!');

        $this->httpClient = Http::withToken($apiKey);
    }
...
```

#### Expected behavior
I expected it will pull out the database from tenant's database, but it pulled from central database instead of.

#### Your setup
 - Laravel version: 7.6
 - stancl/tenancy version: 2.3
 - Storage driver: DB

**Comment by stancl** [comment]
This is not a bug, this is just that you instantiate the class somewhere before the package can possibly initialize tenancy. Show me more and I may be able to help.

**Comment by phuclh** [comment]
> This is not a bug, this is just that you instantiate the class somewhere before the package can possibly initialize tenancy. Show me more and I may be able to help.

I loaded the service provider in config/app.php. Where should I load it to make sure it initialize after tenancy?

**Comment by stancl** [comment]
Loading the service provider is fine, but you have to make sure it doesn't *instantiate* (which causes dependencies to be injected) the class in it. Use closure binding:

```php
$this->app->bind(Foo::class, function ($app) {
    return new Foo(...);
});
```

and make sure no class that's instantiated before tenancy is initialized depends on that class - it would also instantiate it.

**Comment by phuclh** [comment]
I did try, but It didn't work. Here is my service provider:

```
<?php namespace App\Services\Inventories;

use App\Services\ProviderFinder;
use Illuminate\Support\ServiceProvider;

class InventoryServiceProvider extends ServiceProvider {

    /**
     * Register any inventory services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(InventoryRegistry::class, function ($app) {
            return new InventoryRegistry;
        });
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    public function boot()
    {
        (new ProviderFinder('inventory'))->discovery();
    }
}
```

`InventoryRegistry` class:

```
<?php namespace App\Services\Inventories;

class InventoryRegistry {

    /**
     * Inventory providers.
     *
     * @var array
     */
    protected $inventories = [];

    /**
     * @param $name
     * @param InventoryInterface $instance
     * @return $this
     */
    public function register($name, InventoryInterface $instance)
    {
        $this->inventories[ $name ] = $instance;

        return $this;
    }

    /**
     * @param $name
     * @return InventoryInterface
     * @throws \Exception
     */
    public function get($name): InventoryInterface
    {
        if (array_key_exists($name, $this->inventories))
        {
            return $this->inventories[ $name ];
        }

        throw new \Exception("Invalid inventory provider.");
    }
}
```

**Comment by stancl** [comment]
I'd assume the issue is caused by `(new ProviderFinder('inventory'))->discovery();` being executed before tenancy is initialized.

Both register and boot are executed before the middleware that initializes tenancy.

**Comment by phuclh** [comment]
Awesome! Thank you so much!!!
