### ISSUE TITLE
How can I run seeder seperatly for Tenants and Central app

### ISSUE THREAD

**Issue by phuclh** [archtechx/tenancy#379]
Right now, both command `php artisan db:seed` and `php artisan tenants:seed` are using the same class `DatabaseSeeder` for running the child seeders. How can I separate the seeders for tenants and central app?

I did try to use the option `--class` in `tenancy` config, but it just said the class was not found.

Thank you for the great package!

**Comment by lokreybe** [comment]
You need to create a new Seeder for the tenants. I have created a seeder TenantDatabaseSeeder at then you must to modify the tenancy.php .
`    'seed_after_migration' => false, // should the seeder run after automatic migration
    'seeder_parameters' => [
        '--class' => 'TenantDatabaseSeeder', // root seeder class, e.g.: 'DatabaseSeeder'
        // '--force' => true, // force database seeder
    ],`

**Comment by rami1973** [comment]
Target class [Database\Seeders\TenantDatabaseSeeder] does not exist.

**Comment by vahidalvandi** [comment]
'seeder_parameters' => [
        '--class' => 'TenantDatabaseSeeder', // root seeder class
        '--force' => true,
    ],

not run /database/seeders/**TenantDatabaseSeeder.php**  it run default **DatabaseSeeder.php**
