### ISSUE TITLE
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value

### ISSUE THREAD

**Issue by phuclh** [archtechx/tenancy#384]
`SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value`. 

I got this error when I uncomment `Stancl\Tenancy\Features\Timestamps::class`

Here is my custom columns config:

```
'custom_columns' => [
                'plan_id',
                'customer_id',
                'created_at',
                'updated_at'
            ],
```

It seems like the Storage Driver (Database) uses the wrong DateTime format for Laravel 7.

**Comment by stancl** [comment]
What type is that column? You can customize the format used by that Feature, look into the source code.
