### ISSUE TITLE
Auth Login\Registration example

### ISSUE THREAD

**Issue by vaskomichal** [archtechx/tenancy#385]
Hi! do you have an example of authentication? How to use it? How is necessary to set routes when I want to use ui:auth? After installation login and registration page is not accessible

Thanks!

**Comment by stancl** [comment]
If you want auth in your central app, add `Auth::routes()` to web routes. If you want it in the tenant app, add it to tenant routes. Also move your auth migrations to tenant/ if you want auth in the tenant app.
