### ISSUE TITLE
If-clause in CacheManager generates an unexpected Redis key

### ISSUE THREAD

**Issue by mattyh88** [archtechx/tenancy#395]
#### Describe the bug
The if-clause in CacheManager generates an unexpected Redis key.

I have a (Nova) admin panel where I can CRUD a certain resource. Besides storing this resource in my MySQL database, I like to have it in cache (Redis) too. I'm using tagged cache, as described here: https://laravel.com/docs/6.x/cache#cache-tags
All this is working as expected and is just to give a bit of context. **Please note that this (Nova) admin panel isn't behind this package's Tenant middleware.**

Now, when I navigate to a tenant subdomain, this package sets it's own CacheManager in the Service container, to be used as the parent of Laravel's CacheManager. This means that every Cache request (using the global Cache helper) will use tagged cache. 
The Stancl CacheManager generates another key for tenant ID x, than when I generate a key in my CRUD (Nova) admin panel (remember that the admin panel isn't behind the Tenant middleware). 

I found out that the Stancl CacheManager generates a different key, because it's creating an array of tags with two items (this array holds the same key twice, instead of once) when using the 'tags' method in my application.

#### Steps to reproduce
1. Create tagged cache in part of the application, that isn't behind the Tenant Middleware (in my case this is the Nova admin panel). 

    $tags = [config('tenancy.cache.tag_base') . $tenantId];

    return Cache::tags($tags)  
        ->rememberForever(  
            $this->getCacheKey($tenantId),  
                function () use ($tenantId) {  
                    return parent::getByTenantId($tenantId);  
                }
        );

2. Try to fetch the tagged cache when navigating to a tenant subdomain in your browser. (obviously a part of the application that is behind the Tenant Middleware)
If you run this code again (with the same cache key as step 1), it won't be able to find the tagged cache record as the key is generated in a different way, because of Stancl's CacheManager.

    $tags = [config('tenancy.cache.tag_base') . $tenantId];

    return Cache::tags($tags)  
        ->rememberForever(  
            $this->getCacheKey($tenantId),  
                function () use ($tenantId) {  
                    return parent::getByTenantId($tenantId);  
                }
        );

#### Expected behavior
Stancl's CacheManager should generate the same key, as the Laravel default. 

#### Your setup
 - Laravel version: 6.14.0
 - stancl/tenancy version: 2.3.4
 - Storage driver: DB

**Comment by mattyh88** [comment]
Found out that the Stancl CacheManager can simply be disabled if you don't like to use tagged caching, by disabling the bootstrapper in the tenancy config file.

**Comment by stancl** [comment]
Is this still relevant?

**Comment by mattyh88** [comment]
For me it's not, as I disabled this package's CacheManager :)

**Comment by codeinfo** [comment]
@mattyh88 How to disable？

**Comment by stancl** [comment]
Disable the cache bootstrapper
