### ISSUE TITLE
Tenant creation silently gets stuck in production when migrate_after_creation set to true

### ISSUE THREAD

**Issue by lasselehtinen** [archtechx/tenancy#399]
#### Describe the bug
In production I have set migrate_after_creation to true but I did not have migration_parameters --force set. When trying to create a tenant in production, it would be just stuck forever, I guess waiting for the answer the the console command confirmation to say Y. This can be fixed of course by adding --force.

#### Steps to reproduce

1. Set migrate_after_creation to true and do not add migration_parameters --force 
2. Set APP_ENV to production
3. Try to create a new tenant with Tenant::new()

#### Expected behavior
When migrate_after_creation is set to true and application environment in production, provide some kind of meaningful error message when trying to create tenant and it cannot run the migrations?

#### Your setup
 - Laravel version: 6.18.14
 - stancl/tenancy version: 6.18.14
 - Storage driver: DB

**Comment by stancl** [comment]
Not sure if I added it in v2 or only v3, but the config now has --force
with a comment that it's necessary for running the migrations in
production. Might be that you have an outdated config file if I added it in
v2.

This is not a bug. Just something that should be better documented.

Dne ne 17. kvě 2020 10:42 uživatel Lasse Lehtinen <notifications@github.com>
napsal:
