### ISSUE TITLE
Add more database-related artisan commands

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#4]
Perhaps some of these?

- [x] ~migrate:fresh     Drop all tables and re-run all migrations~
- [ ] migrate:install   Create the migration repository
- [ ] migrate:refresh   Reset and re-run all migrations
- [ ] migrate:reset     Rollback all database migrations
- [ ] migrate:status    Show the status of each migration

**Comment by stancl** [comment]
I don't think we need these.

**Comment by drbyte** [comment]
Agreed: I'm not sure these are critical. 
Perhaps in a dev environment they may be useful, or for "stepped debugging", but not for normal use.
I find `tenancy:migrate-fresh` is enough.

**Comment by chrillep** [comment]
@stancl would be nice to see the status when developing, so i can check if any tenant failed a migration

**Comment by chrillep** [comment]
@stancl @drbyte by the way shouldnt tenancy:migrate-fresh be tenancy:migrate:fresh with a ":" to keep parity with laravels default migrate:fresh command? :) 


```sh
migrate
  migrate:fresh                           Drop all tables and re-run all migrations
  migrate:install                         Create the migration repository
  migrate:refresh                         Reset and re-run all migrations
  migrate:reset                           Rollback all database migrations
  migrate:rollback                        Rollback the last database migration
  migrate:status                          Show the status of each migration
 ```
 
 ```sh
 tenancy
  tenancy:install                         Install stancl/tenancy.
 tenants
  tenants:list                            List tenants.
  tenants:migrate                         Run migrations for tenant(s)
  tenants:migrate-fresh                   Drop all tables and re-run all migrations for tenant(s)
  tenants:rollback                        Rollback migrations for tenant(s).
  tenants:run                             Run a command for tenant(s)
  tenants:seed                            Seed tenant database(s).
  ```

**Comment by chrillep** [comment]
then i could run make command
```make
.PHONY: migrate-status ## migrate status central tenants and elastic
migrate-status:
	@printf "Central migration status:\n"
	@php artisan migrate:status
	@printf "Tenants migration status:\n"
	@php artisan tenants:migrate:status
	@printf "Elastic migration status:\n"
	@php artisan elastic:migrate:status
```

**Comment by stancl** [comment]
I think if it were `tenancy:migrate:fresh`, artisan would create another namespace for `tenancy:migrate`, which isn't what we want.

**Comment by chrillep** [comment]
> I think if it were `tenancy:migrate:fresh`, artisan would create another namespace for `tenancy:migrate`, which isn't what we want.

aaah ok to bad nvm then for `tenancy:migrate:fresh` :) 
still would like status tho :)

**Comment by eskayamadeus** [comment]
I would like status also
