### ISSUE TITLE
Tenant Config is not available in Command constructor

### ISSUE THREAD

**Issue by lasselehtinen** [archtechx/tenancy#402]
Hi,

I just noticed that the Tenant Config is not available on the __construct method of the command. I would like to do the following. In the handle the config works fine. Is there any way to initialize the tenant config for the constructor?

```php
    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        $woocommerce = new Client(
            config('woocommerce.api.url'),
            config('woocommerce.api.consumer_key'),
            config('woocommerce.api.consumer_secret'),
            [
                'version' => 'wc/v3',
            ],
        );

        $this->woocommerce = $woocommerce;

        parent::__construct();
        $this->specifyParameters();
    }
```

**Comment by stancl** [comment]
Tenancy is initialized between the constructor and the `handle()` method, so unfortunately there's no way to do this in the constructor.
