### ISSUE TITLE
Tenant could not be identified on domain 127.0.0.1

### ISSUE THREAD

**Issue by NithMario** [archtechx/tenancy#404]
#### Your setup
 - Laravel version: [e.g. 6.2.0]
 - stancl/tenancy version: [e.g. 2.1.0]
 - Storage driver: [e.g. DB]

**Comment by stancl** [comment]
1. Read the documentation.
2. Don't open bug reports when you haven't read the documentation. This is a support question.
3. Fill out issue templates if you want any help at all.
