### ISSUE TITLE
How to redirect subdomain to domain.

### ISSUE THREAD

**Issue by phuclh** [archtechx/tenancy#406]
In the tenant app, when a tenant has more than 1 domain. How can I redirect 301 the subdomain to  domain? Because if 2 domains serve the same content, it causes a penalty from Google.

Thank you.

**Comment by stancl** [comment]
I'd add a concept of a primary domain to your app, and then use a middleware to redirect users from tenant domains to the primary tenant domains.

**Comment by phuclh** [comment]
Thank you for the quick response.

Where should I apply the middleware? In `$middlewareGroups` in Kernel.php?

**Comment by stancl** [comment]
@phuclh Doesn't matter. Even just wrapping all of your routes in tenant.php in a route group with middleware will work.
