### ISSUE TITLE
Issue implementing Tenant Config Feature

### ISSUE THREAD

**Issue by JonathanMMann** [archtechx/tenancy#407]
Hey there!

I'm working on implementing the storage_to_config_map to set my mail_from_name from tenant storage. Even though I can dump my config() and see that the mail_from_name has been set to the tenants mail_from_name in the database, the emails still send from the Laravel default from name.

Here's the code:
config/tenancy

`'features' => [
        // Features are classes that provide additional functionality
        // not needed for tenancy to be bootstrapped. They are run
        // regardless of whether tenancy has been initialized.

        // Stancl\Tenancy\Features\Timestamps::class,
        Stancl\Tenancy\Features\TenantConfig::class,
        // Stancl\Tenancy\Features\TelescopeTags::class,
        // Stancl\Tenancy\Features\TenantRedirect::class,
    ],
    'storage_to_config_map' => [ // Used by the TenantConfig feature
        'mail_from_name' => 'mail.from.name',
        'mail_from_address' => 'mail.from.address'
    ],`

DB Record:
`'f6d15f05-fe43-45a6-9c92-0fb52f24c751', '{\"id\": \"f6d15f05-fe43-45a6-9c92-0fb52f24c751\", \"mail_from_name\": \"Jonathan Mann\"}'`

Config Mail Dump:
```
"mail" => array:10 [▼
      "driver" => "smtp"
      "host" => "smtp.mailtrap.io"
      "port" => "2525"
      "from" => array:2 [▼
        "address" => "hello@example.com"
        "name" => "Jonathan Mann"
    ]
```

As you can see above this sets properly in the config, but when I send emails even after clearing the cache they still send with the default Laravel from.name. Any thoughts? Am I just using this feature incorrectly?

**Comment by stancl** [comment]
Sorry for the late response, apparently I forgot to click Comment when I replied.

The issue is likely that some part of your application reads from this config *before* you change it.

**Comment by JonathanMMann** [comment]
Ah you are correct. I tested it in a fresh Laravel installation and it worked. I'll debug my application and close this request. Thanks!
