### ISSUE TITLE
404 on Nova Routes after integration

### ISSUE THREAD

**Issue by Dontorpedo** [archtechx/tenancy#410]
Hi, i followed the doecumentation on integration with nova, but after that, the nova routes return 404, am i doing something wrong?

thanks
Denis

**Comment by stancl** [comment]
Are you accessing Nova on a central domain or a tenant domain?

**Comment by Dontorpedo** [comment]
i acces them on the central domain, i added my domain to the tenancy.exempt_domains config.

i am working on laragon, could be this the issue?

**Comment by stancl** [comment]
So do you want to use Nova to manage tenants or to manage resources inside tenant databases?

The Nova integration guide in the docs states that it's for using Nova inside the tenant app.

<img width="865" alt="Screenshot 2020-05-25 at 14 54 53" src="https://user-images.githubusercontent.com/33033094/82814589-bf013880-9e97-11ea-88e2-f7f0352b9d4b.png">
<img width="362" alt="Screenshot 2020-05-25 at 14 55 05" src="https://user-images.githubusercontent.com/33033094/82814595-c0cafc00-9e97-11ea-9d69-38f98c189535.png">

**Comment by Dontorpedo** [comment]
oh ok, i misunderstood this.. 

my app uses nova as a backend for tenants.. so i need it for both tenant and also to manage tenants.. i should use universal route right?

**Comment by stancl** [comment]
You can't use Nova to manage tenants in v2 -- you can do that in v3 which is coming soon.

And I don't think you can use Nova inside the tenant app and to manage tenants at the same time. Or you could, but it would be terribly hacky. Different resources.

**Comment by Dontorpedo** [comment]
sorry, than i misunderstood the whole concept, haha.. have to read about it again, not a native speaker so i have many language barriers..

my usecase was:

i have exisiting app made with nova as backend which i want to offer as saas.

so i need problably a clean installation of laravel with whatever backend to manage the tenants separately with all the subscription forms etc. to work as a central app.

from this central app i create the tenants with configured migrations.. sorry for the stupid question as i am not experienced, but do i have to copy the models, controllers etc from my existing app to the new tenant folders or how does it work?

or maybe i will wait for the v3 to have a look into the  example SaaS application :S

**Comment by stancl** [comment]
> i have exisiting app made with nova as backend which i want to offer as saas.
> 
> so i need problably a clean installation of laravel with whatever backend to manage the tenants separately with all the subscription forms etc. to work as a central app.

That's correct. Follow the Nova integration guide, but use something else for managing tenants.

> but do i have to copy the models, controllers etc from my existing app to the new tenant folders

No, you don't have to move anything

> or how does it work?

Like this: https://tenancyforlaravel.com/docs/v2/getting-started/#how-does-it-work

Meaning, you don't have to move anything except migrations and routes.

**Comment by Dontorpedo** [comment]
ok, thank you!
