### ISSUE TITLE
Where to host (multi-DBs for 1 app support)?

### ISSUE THREAD

**Issue by JurajG007** [archtechx/tenancy#411]
Hi,
I have a problem to find a hosting which could allow multi-databases for 1 application/user.
Can you recommend us some? 
Regards,
Juraj

**Comment by stancl** [comment]
Any major cloud will work. DigitalOcean, AWS, GCP.

**Comment by JurajG007** [comment]
Thanks a lot.
Now I realized every hosting which is supporting cPanel is able to provide requested feature.
