### ISSUE TITLE
Referencing tenant config in another config

### ISSUE THREAD

**Issue by lasselehtinen** [archtechx/tenancy#413]
I would need tenant aware variables referenced in another config. Namely the config/filesystem.php for a disk systems user credentials. I have tried the following:

1. Using tenant aware config and referencing them with config('variable'). Seems like tenant is not available in another config. They are returned as null. Initializing the tenant and accessing the same config variable works fine everywhere else.

2. tenant()->get('variable); in the config returns Target [Stancl\Tenancy\Contracts\StorageDriver] is not instantiable while building [Stancl\Tenancy\Tenant].

How to solve this?

**Comment by stancl** [comment]
Why would you call `tenant()` in the config? Config can be cached, you can't generate it dynamically.

You can change it dynamically at runtime, see https://tenancyforlaravel.com/docs/v2/features/tenant-config/

**Comment by lasselehtinen** [comment]
Hi,

Aah now I see. I will just override the configuration values on runtime just before the disk is accessed. Thanks!
