### ISSUE TITLE
Delete schema in postgres don't  work

### ISSUE THREAD

**Issue by dilsonbeltran** [archtechx/tenancy#414]
Hi,

I found this bug, the Drop schema don't work, if you have relations inside the schema. you could solve that with DROP SCHEMA "$name" **CASCADE**  in the next line:

https://github.com/stancl/tenancy/blob/c239225bc6f08d9f6324ad96fe19d9af128df4e7/src/TenantDatabaseManagers/PostgreSQLSchemaManager.php#L40

**Comment by stancl** [comment]
Is this a bug with the package or not if you closed the issue?

**Comment by dilsonbeltran** [comment]
> Is this a bug with the package or not if you closed the issue?

Yes is a bug, sorry for close.
