### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by saurabh2k1** [archtechx/tenancy#415]
I am using v2, After using universal middleware on Auth::routes(), 
When I try to open login route on subdomain, no resource is coming,  no app.css, no layout etc. 
Please show the example how a tenant user authenticate. I am using separate users table in tenant DB.

**Comment by stancl** [comment]
The only example I have time to work on is the upcoming saas boilerplate.

**Comment by saurabh2k1** [comment]
atleast guide how I authenticate tenant users Please

**Comment by stancl** [comment]
I don't have the resources to provide anything more than the docs for v2 at this point.
