### ISSUE TITLE
Cannot declare class CreateUsersTable, because the name is already in use

### ISSUE THREAD

**Issue by phuclh** [archtechx/tenancy#417]
I have set up the TestCase for my testing. I have 2 migration files for creating `users` table for my tenant app and central app (one located in app/database and another is app/database/tenant).

Here is my TestCase:

```
<?php

namespace Tests;

use Illuminate\Foundation\Mix;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase {

    use CreatesApplication;

    protected $tenancy = false;

    protected function setUp(): void
    {
        parent::setUp();

        // Swap out the Mix manifest implementation, so we don't need
        // to run the npm commands to generate a manifest file for
        // the assets in order to run tests that return views.
        $this->swap(Mix::class, function () {
            return '';
        });

        $this->artisan('migrate:fresh');

        config([
            'tenancy.queue_database_creation' => false,
        ]);

        config(['tenancy.exempt_domains' => [
            '127.0.0.1',
            'localhost',
        ]]);

        // Initializing tenancy
        if ($this->tenancy)
        {
            $this->initializeTenancy();
        }
    }

    public function initializeTenancy($domain = 'test.localhost')
    {
        tenancy()->create($domain, [
            'customer_id' => 1,
            'plan_id'     => 1,
        ]);

        tenancy()->init($domain);
    }

    public function tearDown(): void
    {
        config([
            'tenancy.queue_database_deletion'               => false,
            'tenancy.delete_database_after_tenant_deletion' => true,
        ]);
        tenancy()->all()->each->delete();

        parent::tearDown();
    }
}
```

When I run a test, I get this error: `PHP Fatal error:  Cannot declare class CreateUsersTable, because the name is already in use in`

```
In 2014_10_12_000000_create_users_table.php line 7:
Cannot declare class CreateUsersTable, because the name is already in use
```

I tried to make both files name are difference but It's still not working.

**Comment by stancl** [comment]
Rename both the file names and the class names.

**Comment by phuclh** [comment]
> Rename both the file names and the class names.

I got this error when I rename both the file names to `2018_01_02_000000_create_central_action_events_table` and the class name to `CreateCentralActionEventsTable`

```
SQLSTATE[HY000]: General error: 1 table "action_events" already exists (SQL: create table "action_events" ("id" integer not null primary key autoincrement, "batch_id" varchar not null, "user_id" integer not null, "name" varchar not null, "actionable_type" varchar not null, "actionable_id" integer not null, "target_type" varchar not null, "target_id" integer not null, "model_type" varchar not null, "model_id" integer null, "fields" text not null, "status" varchar not null default 'running', "exception" text not null, "created_at" datetime null, "updated_at" datetime null))
```

**Comment by stancl** [comment]
Show me a screenshot of your migrations/ file tree.

**Comment by phuclh** [comment]
Here is it:

<img width="532" alt="Screen Shot 2020-06-01 at 8 16 46 AM" src="https://user-images.githubusercontent.com/6707194/83423719-3ecf5b80-a3e0-11ea-9f0e-4c0a2383951b.png">

**Comment by stancl** [comment]
I'd guess that's because Nova is adding the migrations from the package even though you have them in your `migrations` directory. Make Nova not add migrations.

**Comment by phuclh** [comment]
> Make Nova not add migrations

Yes, it prevents the Nova add the `action event` migration but it cannot prevent add migration of a Nova custom tool. I have installed a tool name Nova Settings and it throws the same error:

`General error: 1 table "nova_settings" already exists (SQL: create table "nova_settings" ("key" varchar not null, "value" varchar null, primary key ("key")))`

My code:
```
if ($this->app->runningUnitTests()) {
            Nova::ignoreMigrations();
        }
```

**Comment by stancl** [comment]
If you're using a third-party package that we don't have an integration tutorial for then I can't really help with that, sorry. I might be able to take a look at these things, but definitely not in the next couple of weeks.

**Comment by phuclh** [comment]
> If you're using a third-party package that we don't have an integration tutorial for then I can't really help with that, sorry. I might be able to take a look at these things, but definitely not in the next couple of weeks.

Thank you, I understand that. I just manually removed `loadMigrationsFrom` method from that tool, and that error was fixed, but I got the new error. It seems the `tenants` table was not created.

`General error: 1 no such table: tenants (SQL: select * from "tenants" where "id" in (b90b6e9b-3a58-4ca9-9141-a8e7cdfca2c2))`

**Comment by phuclh** [comment]
@stancl can you help me this error?

**Comment by stancl** [comment]
Do you think that I can help with such a generic error with no other context?

**Comment by phuclh** [comment]
> Do you think that I can help with such a generic error with no other context?

I just don't know why `tenants` table doesn't exist when run `php artisan test`.

**Comment by stancl** [comment]
Because you messed something up with the central migrations.

**Comment by alfligno** [comment]
I stumbled on this error, base on my diagnosis this error comes out when creating tenant, is there any way to fix this?
`Tenant::create()`
![image](https://user-images.githubusercontent.com/69491106/130209077-6fc4551e-0539-4b15-9f0f-5eb808887c6b.png)
