### ISSUE TITLE
Database seperate to servers

### ISSUE THREAD

**Issue by laracodedeveloper** [archtechx/tenancy#419]
Hi, 
Thank you for your awesome work first, my question is it possible to create each tenancy different database servers or separate my app from the tenancy database with this package?

**Comment by stancl** [comment]
Hi,

sure.

**v2**
```php
Tenant::new()->withData([
    '_tenancy_db_connection' => 'some-specific-connection',
])->save();
```

Note that you need to create the connection in `config/database.php`.

**v3** (recommended)
```php
Tenant::create([
    'tenancy_db_connection' => 'some-specific-connection',
]);
```

or, you can specify parts of the connection details, e.g. the hostname
```php
Tenant::create([
    'tenancy_db_hostname' => 'foo',
]);
```
