### ISSUE TITLE
Question: does this work  without involving Sessions?

### ISSUE THREAD

**Issue by alinmiron** [archtechx/tenancy#421]
In a REST-API only configuration ?

**Comment by stancl** [comment]
In v2, yes with some changes. I recommend using v3 (beta) if you're just starting. You can read about tenant identification, including using request data, for v3 here: https://www.notion.so/Tenant-identification-dbfb4aec83224de9aa8c06dc6fe4dc56

**Comment by alinmiron** [comment]
great, I'll dive in.
Another question:
Is it possible to have nested tenants?
I mean something like:

> Landlord->Tenant1->SubTenant1 
.................................->SubTenant2      
................->Tenant2->SubTenant1 
............................... ->SubTenant2

**Comment by stancl** [comment]
With some work on your part, yes. Why do you need that?

**Comment by alinmiron** [comment]
the 

> With some work on your part, yes. Why do you need that?

On a project there is this idea:
If a multinational company has a main office worldwide, then, for each country has a Tenant, for each county in that country a SubTenant

**Comment by stancl** [comment]
You can use single-db tenancy inside multi-db tenancy pretty easily

**Comment by brenjt** [comment]
@stancl I am exploring this sub tenant idea. You say it could be done pretty easily. Do you have a minute to explain how you think it could resolve and bootstrap those subtenants in the single-db? I guess I can't wrap my head around how you'd structure the tenant resolution
