### ISSUE TITLE
Using in a hybrid application

### ISSUE THREAD

**Issue by a21ns1g4ts** [archtechx/tenancy#423]
I have one question: I will implement a tenancy application with one user account belongs to many tenancy. 
We have support ?

**Comment by stancl** [comment]
I don't understand the question.

**Comment by a21ns1g4ts** [comment]
we have the single database and multi database architecture. My question is: There's a possibilities to implementing these two concepts using stancl tenancy in one application ? sharing the users table for all tenancy

**Comment by stancl** [comment]
You can use single-db tenancy inside multi-db tenancy with v3

**Comment by a21ns1g4ts** [comment]
v3 can auto create database ?

**Comment by stancl** [comment]
Yes https://github.com/stancl/tenancy/blob/3.x/assets/TenancyServiceProvider.stub.php#L23-L25
