### ISSUE TITLE
Tenant specific routes

### ISSUE THREAD

**Issue by bsolutionscv** [archtechx/tenancy#424]
Hi.
I search on Google and here in Github, but I was unable to find an answer.
Is possible to have tenant specific route file? And is possible to override a route only for specific tenants?

**Comment by stancl** [comment]
You can do pretty much everything, it just might be a bit complex. There's no built-in feature for this but it should be achievable one way or another.

**Comment by bsolutionscv** [comment]
Thanks for your replay.
