### ISSUE TITLE
Use eloquent create record central from tenant domain.

### ISSUE THREAD

**Issue by daominhtu245** [archtechx/tenancy#425]
I want access central from tenant domain? 
Example: I want create 1 record at central from tenant domain, but i must use eloquent not querybuilder. 

is there any way of handling central part data like use:  initialize($tenant) - endTenancy()

**Comment by stancl** [comment]
Use this trait on the model https://github.com/stancl/tenancy/blob/3.x/src/Database/Concerns/CentralConnection.php

v2: https://github.com/stancl/tenancy/blob/2.x/src/StorageDrivers/Database/CentralConnection.php
