### ISSUE TITLE
Hard coded controllers namespace

### ISSUE THREAD

**Issue by gpassarelli** [archtechx/tenancy#426]
#### Describe the bug
On **TenancyServiceProvider**,  the namespace of the controllers is hardcoded assuming all controllers would be under `App/Httt/Controllers` namespace, and sometimes you may want to keep the controller on a different organization. So instead of hard coding the namespace, some option would be to set the namespace in a config or just like Laravel `RouteServiceProvider` that uses `->namespace($this->namespace)`

https://github.com/stancl/tenancy/blob/0378f142ec06360347b5e63578e2eec749280c71/assets/TenancyServiceProvider.stub.php#L123

#### Steps to reproduce
Create a controller on a different namespace, and try to use it on tenant.php file

#### Expected behavior
Should be able to specify the namespace for the controllers used on tenant routes

#### Your setup
 - Laravel version: [7.0.0]
 - stancl/tenancy version: [2.3.0]
 - Storage driver: [DB]

**Comment by stancl** [comment]
What version are you on actually? The code you sent is for v3.

That service provider is published, it's in your `app/Providers` directory. For that reason there is no longer a config key. You can edit it right in the provider.

And in v2 there's a config key.

**Comment by gpassarelli** [comment]
I guess I looked at the wrong file then, but I'm using version 2 and I'm having the following error when I try to access my tenants.php routes:
`Target class [App\Http\Controllers\App\PriceLists\Controllers\PriceListsController] does not exist.
`

**Comment by gpassarelli** [comment]
My bad, I just saw the option under the config file.

**Comment by stancl** [comment]
See your config file
