### ISSUE TITLE
how i can use universal in v3

### ISSUE THREAD

**Issue by vahidalvandi** [archtechx/tenancy#429]
**Target class [universal] does not exist.**

in routes/tenant.php
```
Route::middleware('universal')->group(function () {
    Auth::routes();
});
```

**Comment by stancl** [comment]
Enable the feature in config

**Comment by vahidalvandi** [comment]
i removed comment but Still 
**Illuminate\Contracts\Container\BindingResolutionException
Target class [universal] does not exist.**
```
    'features' => [
        // Stancl\Tenancy\Features\UserImpersonation::class,
        // Stancl\Tenancy\Features\TelescopeTags::class,
         Stancl\Tenancy\Features\UniversalRoutes::class,
        // Stancl\Tenancy\Features\TenantConfig::class, // https://tenancy.samuelstancl.me/docs/v2/features/tenant-config/
        // Stancl\Tenancy\Features\CrossDomainRedirect::class, // https://tenancy.samuelstancl.me/docs/v2/features/tenant-redirect/
    ],
```

**Comment by stancl** [comment]
https://tenancyforlaravel.com/docs/v3/features/universal-routes

**Comment by vahidalvandi** [comment]
@stancl in document https://tenancyforlaravel.com/docs/v3/routes section universal in empty .
please add this to this section https://tenancyforlaravel.com/docs/v3/features/universal-routes

**Comment by vahidalvandi** [comment]
after use 
```
Route::group([
    'middleware' => ['universal', InitializeTenancyByDomain::class],
], function () {
    Auth::routes();
});

```
in login page return 
**Undefined variable: errors (View: /var/www/html/gandomplus/resources/views/auth/login.blade.php)**
but if comment universal route . and add 
Auth::routes();
in web.php
work fine ! 
please help me

**Comment by stancl** [comment]
Yes, that's planned
