### ISSUE TITLE
queue does not load tenant when queue driver is redis/database

### ISSUE THREAD

**Issue by hardikdangar** [archtechx/tenancy#430]
#### Describe the bug
queue does not load the tenant when queue driver is redis/database.

#### Steps to reproduce
1. Install laravel with --auth option
2. Add tenancy package
3. Add Job class like https://gist.github.com/hardikdangar/6ef3106b6fb642641dc1ff3f5f0208f2
4. Create two domains tenant1.local, tenant2.local
5. add job call to tenant.php routes file like https://gist.github.com/hardikdangar/bed289f0d5cc88d131d66b4defb65cc7
6. change QUEUE_CONNECTION=database or QUEUE_CONNECTION=redis
6. run php artisan queue:work
7. from tenant1.local/sendqueue will not log any tenant detail. it will return empty array.

#### Expected behavior
in step 7 it should give us tenant context.

#### Your setup
 - Laravel version: 7.15.0
 - stancl/tenancy version: 3.x-dev
 - Storage driver: DB
 - PHP VERSION : 7.3

**Comment by hardikdangar** [comment]
In debugging here is what i have found,

in vendor/stancl/tenancy/src/Bootstrappers/QueueTenancyBootstrapper.php

if i add Log::info('in constructor'); in constructor in log it is fired.

so i added another log info into 

```
$this->event->listen(JobProcessing::class, function ($event) {
Log::info('in event listen');
....
});
```
it never logs. So i thought may be Laravel's Queue events are not working. to test it i added following code in appserviceprovider.php boot method,

```
        Queue::before(function (JobProcessing $event) {
            Log::info('from job processing event');
        });
```

But it fires so Laravel's event is working but same code in QueueTenancyboostrapers constructor does not work.

So i am stumped here. Do you know what could be issue ?

**Comment by hardikdangar** [comment]
So from code it seems you are loading bootstrapers when tenancy is initialised but JobProcessing::class needs to be registered on appserviceprovider.php or tenancyserviceprovider.php. I am not sure how to hook into tenancy when we hook into laravel's queue in appserviceprovider.php

**Comment by stancl** [comment]
I see. In v2, I had that listener in the service provider, because I couldn't get it working in the QueueTenancyBootstrapper job. I thought I found a way to make it work in v3 but apparently not.

Will try to write a regression test and fix it.

Thanks!

**Comment by hardikdangar** [comment]
with latest commit this is fixed :)
