### ISSUE TITLE
auth in central and use tenant

### ISSUE THREAD

**Issue by vahidalvandi** [archtechx/tenancy#431]
hi . i I got confused in auth system , i decide  use of path after login with user central db  list all my tenants (  i understand  this simple auth::routes() in web.php routes ) very simple
**https://app.example.com/home**

after click each rediret to it like bellow (do i need sync user ? in central db and tenant db ??) 
https://app.example.com/9ea7df2b60799df158161f3f4d7c3ebfy1/dashboard 

**schema central**
users >> email , password ,...
domain 
...
**schema tenant** 
users >> email , password ,...
...

top schema is correct ?

i cant find complete tutorial for this work , **PLEASE create sample project in github repositry**

**Comment by stancl** [comment]
You can have a `users` table both in central DB and in tenant DB.

> PLEASE create sample project in github repositry

Soon the SaaS boilerplate will be released.

**Comment by vahidalvandi** [comment]
thank you.
owner in register in example.com and login the dashboard , ok then create a tenant (plan,domain ...) then owner How can login the tenant ?? 
do i need copy owner in central users to tenant ?
