### ISSUE TITLE
table tenant_users 

### ISSUE THREAD

**Issue by vahidalvandi** [archtechx/tenancy#432]
in table tenant_users , What users are included? all users in all tenants ? or just owner tenants ?

**Comment by vahidalvandi** [comment]
i undrestand must all users in all tenants first add in central db then each user need global_id then for update user in tenant sync to central ?? do it correct ?
global_id in docu is string , i need to set uuid for each user for global_id ?

**Comment by stancl** [comment]
Resource syncing is optional, few apps need it. You only need it if you want e.g. shared users between tenants.

**Comment by vahidalvandi** [comment]
thank you
