### ISSUE TITLE
wrong in document

### ISSUE THREAD

**Issue by vahidalvandi** [archtechx/tenancy#434]
**https://tenancyforlaravel.com/docs/v3/synced-resources-between-tenants**

i think you must change TenantUser to **User** because  you not define TenantUser
 
// Create the same user in tenant DB
$user = **TenantUser**::create([
    'global_id' => 'acme',
    'name' => 'John Doe',
    'email' => 'john@localhost',
    'password' => 'secret',
    'role' => 'commenter', // unsynced
]);

**Comment by stancl** [comment]
fixed
