### ISSUE TITLE
Global variable that can store settings fetched from database

### ISSUE THREAD

**Issue by SebastianBotez** [archtechx/tenancy#435]
Hello and thank you for this great package. I really appreciate your hard work. Tried many tenancy packages but this is the best.

Just a question regarding the performance of the app. Is there any recommendation from you of where to store a global variable that will keep a tenant settings fetched from database?
Tried to search the documentation but I didn't find anything helpful (correct me if I'm wrong).

Note that this global variable needs to be declared after tenancy logic bootstraping. Thank you.

**Comment by stancl** [comment]
Once the tenant is identified, it's stored in the service container. The `tenant()` helper will retrieve it.

Also, there's "cached tenant lookup" in the docs. This lets you get the tenant from e.g. Redis rather than having to make a DB query.
