### ISSUE TITLE
Create database and run migrations when a new tenant is created

### ISSUE THREAD

**Issue by blimundo** [archtechx/tenancy#437]
Hi @stancl. 

This is pretty simple, I guess, but I can't find a answer anywhere. 

How I can create a database and run migration when a new tenant is created? The package do this automaticaly or I have to do this myself?

And if I have to do manually, is trough events?

Currently i am doing this to create tenants:
`
$tenant = Tenant::create(['name' => 'test']);
 $tenant->domains()->create(['domain' => 'test.myapp.test']);
`

I am using V3.

**Comment by stancl** [comment]
The package does it automatically, as per your event mapping in `TenancyServiceProvider`. If you registered it in your `config/app.php` providers, that is.

**Comment by blimundo** [comment]
Thanks for quick reply. 

I miss that. I registered App\Providers\TenancyServiceProvider in config\app. Now work fine.
