### ISSUE TITLE
URL for resources inside tenant specific folder

### ISSUE THREAD

**Issue by izshreyansh** [archtechx/tenancy#438]
Hi, I'm really sorry for opening another issue.

If there's a resource within tenant specific storage folder:
`project/storage/tenant46a4edef-7593-4a0d-961c-403473ea5117/app/public/products/1.png`

How can we generate links to these resources?

The symlink is created in `public/storage` to `storage/app/public`. So i'm confused about how to get links for resources in tenant's folder `project/storage/tenant46a4edef-7593-4a0d-961c-403473ea5117/app/public/products/1.png`

__Do we have to create new symlink in public for each tenant?__
eg: `project/public/tenant46a4edef-7593-4a0d-961c-403473ea5117` to `project/storage/tenant46a4edef-7593-4a0d-961c-403473ea5117/app/public/`

ps: I'm actually trying to integrate [Spatie Media Library](https://github.com/spatie/laravel-medialibrary). And for that i'm saving product images in tenant specific folder. But i'm unable to create links to these product images.

**Comment by stancl** [comment]
Hey.

The way this works is that the `asset()` helper is replaced by a function that generates URLs to this package's controller. https://github.com/stancl/tenancy/blob/3.x/src/Controllers/TenantAssetsController.php

So no, you won't need to create a new symlink for each tenant. See the v2 docs for filesystem tenancy: https://tenancyforlaravel.com/docs/v2/filesystem-tenancy/

I think this might be helpful too: https://github.com/stancl/tenancy/issues/396#issuecomment-636707407

**Comment by fulopattila122** [comment]
As an alternative solution, one can instruct nginx to look assets in another folder:

```nginx
server {
    // ...
    set $assetsFolder /var/www/vhosts/yourapp/storage/$host/public;
    if ( $host = 'your.central.domain' ) {
        set $assetsFolder /var/www/vhosts/yourapp/public;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|ttf|eot|svg|woff|woff2|pdf|swf|flv|fla|mp3|css|js)$ {
        alias $assetsFolder;
        add_header Access-Control-Allow-Origin *;
        try_files $uri =404;
    }
    // ...
}
```

**Comment by izshreyansh** [comment]
Thank you @stancl,
This answer seems to do the trick: https://github.com/stancl/tenancy-docs/issues/78#issuecomment-636707407
