### ISSUE TITLE
conditional use of domains

### ISSUE THREAD

**Issue by Dontorpedo** [archtechx/tenancy#439]
hi,

in my usecase i have two packages, lets say standard and premium, only the premium package has the need of domains, i would like to identify the users on standard package by id or something.. 

is it possible?

**Comment by stancl** [comment]
> i would like to identify the users on standard package by id or something

How would this ID be sent?

**Comment by Dontorpedo** [comment]
i use a normal user model on my central app, when the user pays for a package i create the database, do migrations and seed the created user in central app also to the tenants database.

the domain to the tenants app is shown inside the profile of the user..

so maybe i could do something after the payment.. but no clue

**Comment by stancl** [comment]
I can't help with your application's design.

I'm just saying that if you don't want to let them use domains with some plan, then it's your responsibility to send the tenant id from your front end in some way.
