### ISSUE TITLE
Another Sanctum config for all tenants

### ISSUE THREAD

**Issue by zorca** [archtechx/tenancy#442]
I need to change the path to the Sanctum API for all tenancies. I would be grateful for an example of implementation. I read the documentation for TenancyConfig, but I didn't figure out how to make exactly my case.

**Comment by zorca** [comment]
Central App already has Sanctum with /sanctum path and I need /tenant-api path for all tenants. If I change global config, then it conflicts with existing code.

**Comment by dotmbf** [comment]
Sanctum allows to be configured to disable routes,
```php
protected function defineRoutes()
{
    if ($this->app->routesAreCached() || config('sanctum.routes') === false) {
        return;
    }

    Route::group(['prefix' => config('sanctum.prefix', 'sanctum')], function () {
        Route::get(
            '/csrf-cookie',
            CsrfCookieController::class.'@show'
        )->middleware('web');
    });
}
```
If you add:
```php
'routes' => false
```
To your `config/sanctum.php`, you'll be able to define your own routes for each individual context (Central / Tenant)

Or you can hook onto one of the events in `app/Providers/TenancyServiceProvider.php` and update the config `sanctum.prefix` accordingly.

As explained by @stancl :

> code never reads env directly
> on framework boot, env is read and stored in config
> when you make a call to change a config value, it only happens in memory, within that one request
> all requests have 100% isolated state

**Comment by stancl** [comment]
There's an existing issue for Sanctum - #327, so I'm closing this.
