### ISSUE TITLE
Unable to access tenant() from within model

### ISSUE THREAD

**Issue by Reached** [archtechx/tenancy#444]
Hi there,

Big fan of the package, great job!

I am trying to implement tenant aware searching with Algolia (using Laravel scout), but I am unable to access the current tenant to get the id for the index within my model: 

```
public function searchableAs()
{
    return tenant()->id . '_customers_index';
}
```

Tenant is null, which is why the call to get the id fails. So my guess is that the middleware is somehow not applied in this context, is there any way to force this?

**Comment by stancl** [comment]
Hey,

If `tenant()` is null, then the app is in the tenant context (tenancy hasn't been initialized).

Try looking into Scout's config file for some middleware config and add the relevant middleware from this package.

**Comment by Reached** [comment]
Unfortunately it seems that there is no configuration that allows for this. Is it possible to resolve the tenant manually by the domain? Then I could write my own trait that overrides the searchableAs method and injects the current tenant that way :)

**Comment by Reached** [comment]
Find an extremely hacky way to do this in case anyone stumbles upon the same thing in the future:

I created a new model for the tenant called SelfConfig, in the corresponding table I created a "own_domain", where I store the domain, I then look up the domain and get the tenant from that, it works but feels gross 👎 

```
public function searchableAs()
    {
        $ownDomain = SelfConfig::first()->own_domain;
        $tenantId = Domain::where('domain', $ownDomain)->first()->tenant->id;
        return $tenantId . '_customers_index';
    }
```

**Comment by stancl** [comment]
> Is it possible to resolve the tenant manually by the domain

You can access any domain's `tenant` property.

Also, you can access the current domain (static property in the `DomainTenantResolver`) and the boilerplate has a Tenant hasOne PrimaryDomain setup.
