### ISSUE TITLE
Implementing with Algolia (using Laravel scout)

### ISSUE THREAD

**Issue by Reached** [archtechx/tenancy#445]
Hi there,

I am trying to implement Algolia in my multi tenancy application, however when trying to run the scout:import command, it's trying to execute the command from the "central" database and not the tenant one, do you have any experience getting Laravel scout to work with your package? :)

**Comment by stancl** [comment]
Try `php artisan tenants:run --tenant=... scout:import`

**Comment by Reached** [comment]
Omg, could have sworn I tried that! It worked!

Thanks :)

**Comment by andreasmatuszewski** [comment]
Hi, 
same issue:
`php artisan tenants:run --tenants=name scout:import "App\Models\Product"`
results into 
`Too many arguments to "tenants:run" command, expected arguments "commandname".`

`php artisan scout:import "App\Models\Product"` works.

Could you help with this. It would be great, if this was in the documentation.

**Comment by stancl** [comment]
https://tenancyforlaravel.com/docs/v3/console-commands#run

**Comment by andreasmatuszewski** [comment]
Thank you! 

For others: `php artisan tenants:run scout:import --tenants=name --argument="model=App\Models\Product"`

**Comment by Surt** [comment]
Do you need a customized bootstrapper for scout to be tenant aware? is this implemented?

**Comment by firrae** [comment]
> Do you need a customized bootstrapper for scout to be tenant aware? is this implemented?

This is something I’m curious on as well @stancl. Does the package also handle creating a search index for each tenant or do we need to set `searchableAs` in the models ourselves?

**Comment by andreaspabst** [comment]
+1 :-) just a friendly reminder on how is it with the tenant aware searching?

**Comment by andreasmatuszewski** [comment]
Should we open a new issue on tenant aware searching?

**Comment by Reached** [comment]
@stancl

**Comment by stancl** [comment]
If there's a concrete problem, you can open a new issue yeah

**Comment by dekts** [comment]
> Thank you!
> 
> For others: `php artisan tenants:run scout:import --tenants=name --argument="model=App\Models\Product"`

@andreasmatuszewski 

I tried below command but it thorws me error.

php artisan tenants:run send:reminder

No arguments expected for "tenants:run" command, got "send:reminder".

**Comment by Surt** [comment]
```php
<?php

namespaceMyNamespace;

use Stancl\Tenancy\Contracts\TenancyBootstrapper;
use Stancl\Tenancy\Contracts\Tenant;

class ElasticTenancyBootstrapper implements TenancyBootstrapper
{
    public function bootstrap(Tenant $tenant)
    {
        $id = tenant()->getTenantKey();
        $prefix = config('scout.prefix');
        $prefix_scout = $prefix.$id.'_';

        app()['config']['scout.prefix'] = $prefix_scout;
        app()['config']['elastic.migrations.prefixes.index'] = $prefix_scout;
        app()['config']['elastic.migrations.prefixes.alias'] = $prefix_scout;

        config(['scout.prefix' => $prefix_scout]);
        config(['elastic.migrations.prefixes.index' => $prefix_scout]);
        config(['elastic.migrations.prefixes.alias' => $prefix_scout]);
    }

    public function revert()
    {
        $prefix = env('SCOUT_PREFIX');

        app()['config']['scout.prefix'] = $prefix;
        app()['config']['elastic.migrations.prefixes.index'] = $prefix;
        app()['config']['elastic.migrations.prefixes.alias'] = $prefix;

        config(['scout.prefix' => $prefix]);
        config(['elastic.migrations.prefixes.index' => $prefix]);
        config(['elastic.migrations.prefixes.alias' => $prefix]);
    }
}
```

I did some time ago a bootstrapper for my elasticsearch scout, it works like a charm, so, yes, it needs a bootstrapper.

**Comment by techguydev** [comment]
Thanks a lot Surt, it has worked perfectly for me.
