### ISSUE TITLE
Nova Password Reset Link has Central Route (APP_URL) Rather Than Tenant's URL

### ISSUE THREAD

**Issue by MikeCraig418** [archtechx/tenancy#447]
Hello -

I'm running Tenancy v2.3.9 and Nova ^3.0.

Thanks again for the great package. Everything has run pretty smoothly, but today I noticed the password reset link in the email belongs to the landlord and not the tenant.

**My Steps:**

1. Go to the tenant's Nova Password Reset Page https://tenant.myapp.com/nova/password/reset
2. Request a password reset email
3. Email received, but password reset link is https://myapp.com/nova/password/reset/xyz

I reviewed https://tenancyforlaravel.com/docs/v2/nova and it looks like everything is setup correctly here.

Any ideas?

Thanks!

Mike

**Comment by stancl** [comment]
I've seen some other issues with Nova in the tenant app. I wrote the integration guide back in v2 times (both for Nova and stancl/tenancy), so maybe things have changed a bit.

I'll try to get Nova to work in the tenant app in v3 and update the guide 👍

**Comment by agusesetiyono** [comment]
same issue here,

the password reset link become http://tenant_domain.com/central_domain.com/dashboard/password/reset/

please help

**Comment by stancl** [comment]
Can some sponsor check if this happens with even with this setup? https://sponsors.tenancyforlaravel.com/universal-central-and-tenant-nova

**Comment by renege** [comment]
@stancl Yes, it also happening when set up like that part of the documentation 

When you request a password reset via the Nova part of a tenant, you get a mail with a link to the main domain for changing the password. You can change the URL manually to the correct subdomain, but that's not pretty.

**Comment by glarbdev** [comment]
I solved this problem by putting the following in the TenancyServiceProvide boot() method:

`
ResetPassword::toMailUsing(function ($notifiable, $token) {

            $url = url(route('tenant.password.reset', [
                'token' => $token,
                'email' => $notifiable->getEmailForPasswordReset(),
            ], false));

            return (new MailMessage)
                ->subject(Lang::get('Reset Password Notification'))
                ->line(Lang::get('You are receiving this email because we received a password reset request for your account.'))
                ->action(Lang::get('Reset Password'), $url)
                ->line(Lang::get('This password reset link will expire in :count minutes.', ['count' => config('auth.passwords.'.config('auth.defaults.passwords').'.expire')]))
                ->line(Lang::get('If you did not request a password reset, no further action is required.'));
        });
`

You can do this for verify and other ones as well although they will slightly differ.  The issue seems to be that the route is hard coded into Laravel so you need to override.

**Comment by Jaspur** [comment]
@sscodex  PR this?

**Comment by stancl** [comment]
Nova support will no longer be a primary feature and will soon be replaced with [Lean](http://lean-admin.dev/), which will focus on working with this package perfectly.

**Comment by eugenefvdm** [comment]
Thanks @sscodex !

I struggled for days with both Nova 3 & 4.

> The issue seems to be that the route is hard coded into Laravel so you need to override

Part of the reason I struggled so much! There is so much abstraction when it comes to the password reset broker in Laravel.

On my system I also had to change:

`resources/views/tenant/auth/passwords/reset.blade/php`

```php
{{ route('password.update') }}
```

to

```php
{{ route('tenant.password.update') }}
```

Confirmed working with Nova 4.
