### ISSUE TITLE
TenantCouldNotBeIdentifiedOnDomainException on central domain

### ISSUE THREAD

**Issue by mahdi29** [archtechx/tenancy#454]
#### Describe the bug
PreventAccessFromCentralDomains is not initialised first, instead InitializeTenancyByDomain is fired. This causes TenantCouldNotBeIdentifiedOnDomainException on central domain.

#### Solution
Change From 

`            $this->app[\Illuminate\Contracts\Http\Kernel::class]->prependToMiddlewarePriority($middleware);
`

To 

`            $this->app[\Illuminate\Foundation\Http\Kernel::class]->prependToMiddlewarePriority($middleware);
`

In TenancyServiceProvider solves the issue.

#### Your setup
Laravel version: ^7.0
stancl/tenancy version: ^3.1

**Comment by stancl** [comment]
This works for everyone else.

Also that change from contract to an instance is wrong. Your app is using a custom Http Kernel.

**Comment by percymamedy** [comment]
Facing the same issue.

I had to change:

```
$this->app[\Illuminate\Contracts\Http\Kernel::class]->prependToMiddlewarePriority($middleware);
```

To

```
$this->app[\Illuminate\Foundation\Http\Kernel::class]->prependToMiddlewarePriority($middleware);
```

And then

```
Route::middleware([
    'web',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::get('/', function () {
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });
});
```

To

```
Route::middleware([
    'web',
    PreventAccessFromCentralDomains::class,
    InitializeTenancyByDomain::class,
])->group(function () {
    Route::get('/', function () {
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });
});
```

Setup 

Laravel 6.x
stancl/tenancy version: ^3.1

**Comment by stancl** [comment]
Are you using a fresh Laravel install? I don't have any issues with this nor do the boilerplate users

**Comment by percymamedy** [comment]
No am not using a Fresh Laravel install. Integrating with an existing project. Am also using Single DB setup.

**Comment by percymamedy** [comment]
FYI we don't really need to use prependToMiddlewarePriority method, I've just added it to $middlewarePriority in app/Http/Kernel.php and that works fine for me.

```php

    /**
     * The priority-sorted list of middleware.
     *
     * This forces non-global middleware to always be in the given order.
     *
     * @var array
     */
    protected $middlewarePriority = [
        // Tenancy Middleware takes priority.
        \Stancl\Tenancy\Middleware\PreventAccessFromCentralDomains::class,
        \Stancl\Tenancy\Middleware\InitializeTenancyByDomain::class,
        \Stancl\Tenancy\Middleware\InitializeTenancyBySubdomain::class,
        \Stancl\Tenancy\Middleware\InitializeTenancyByDomainOrSubdomain::class,
        \Stancl\Tenancy\Middleware\InitializeTenancyByPath::class,
        \Stancl\Tenancy\Middleware\InitializeTenancyByRequestData::class,

        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\Authenticate::class,
        \Illuminate\Routing\Middleware\ThrottleRequests::class,
        \Illuminate\Session\Middleware\AuthenticateSession::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
        \Illuminate\Auth\Middleware\Authorize::class,
    ];
```

**Comment by stancl** [comment]
Yes, but then you need to do that manually. `prependToMiddlewarePriority()` lets you do this programmatically.

If you can reproduce this in a fresh app, I'll reopen.

I don't have this issue (nor do many other people using the package) so I'm closing this.

**Comment by sarmenb** [comment]
What i did is in the Providers/TenancyServiceProvider in the boot method i put this and it works like a charm.

```
InitializeTenancyByDomain::$onFail = function ($exception, $request, $next) {
            return redirect('http://my-domain.com');
};
```

**Comment by sarmenb** [comment]
What i did is in the Providers/TenancyServiceProvider in the boot method i put this and it works like a charm.

InitializeTenancyByDomain::$onFail = function ($exception, $request, $next) {
            return redirect('http://my-domain.com');
};

**Comment by thomsontochi** [comment]
I am currently facing the sae issue, I have tried it all, nothing works , please what I am doing wrong , but when I tried this 

`InitializeTenancyByDomain::$onFail = function ($exception, $request, $next) {
            return redirect('http://my-domain.com');
};` I was getting a 404, I am probably redirecting to a wrong page, what request am I to return to.

**Comment by TilsonM17** [comment]
> #### Describe the bug
> PreventAccessFromCentralDomains is not initialised first, instead InitializeTenancyByDomain is fired. This causes TenantCouldNotBeIdentifiedOnDomainException on central domain.
> 
> #### Solution
> Change From
> 
> ` $this->app[\Illuminate\Contracts\Http\Kernel::class]->prependToMiddlewarePriority($middleware);`
> 
> To
> 
> ` $this->app[\Illuminate\Foundation\Http\Kernel::class]->prependToMiddlewarePriority($middleware);`
> 
> In TenancyServiceProvider solves the issue.
> 
> #### Your setup
> Laravel version: ^7.0 stancl/tenancy version: ^3.1

This work for me, thanks alot
