### ISSUE TITLE
Single-database: issues with third-party packages

### ISSUE THREAD

**Issue by KoenLav** [archtechx/tenancy#455]
We are considering using this package for our new boilerplate, but would like to have some more insights into the limitations of a single-database implementation.

In the docs it is mentioned that it will be more difficult to integrate with third-party packages, could you provide some examples?

Background/Context:
We are creating a boilerplate based on React, Apollo, GraphQL and Laravel (using Lighthouse PHP) and are aiming for a recursive tenant structure (where Tenants can have parents/children, and as such be top-level, mid-level or bottom-level), which will eventually allow top-level Tenants to have access to (at least) aggregated data of their children (and their children, and so on), hence a multi-database setup would probably over-complicate things.

**Comment by stancl** [comment]
When you use multi-database tenancy & the automatic mode (automatic DB switching in the background), you get the benefit of extremely simple package integration. You can, for example, use Laravel Nova inside the tenant app, to manage data inside tenant databases, with only a few changes to the config.

Single-database tenancy makes some of these things harder. When a package uses internal models, you can switch the default DB connection, but you cannot force a single-db scope/trait on it.

Sometimes it's not an issue though. For example when you're in control of the models. So Nova inside the tenant app would probably work fine with single-db.

> (where Tenants can have parents/children, and as such be top-level, mid-level or bottom-level), which will eventually allow top-level Tenants to have access to (at least) aggregated data of their children (and their children, and so on), hence a multi-database setup would probably over-complicate things.

One idea I've been playing with is "multi-tier" tenancy. For example, single-database tenancy (`tenant_id` columns) inside a multi-database setup. It should be pretty straightforward with v3 and I'd be open to help with that.

**Comment by KoenLav** [comment]
Thanks for the quick reply.

I think in the end it all comes down to how we want to model the Tenant entity.

In our applications we've seen that:
- Tenants are usually Organizations (which are linked to a Plan (billing), where Users may be part of multiple Organizations);
- Tenants end up being multi-tier (for which, in my opinion, the best 'conceptual model' is to use recursion, since you never know when you'll need another tier, but it's bound to happen some time);
- Sometimes the Tiers/Levels end up having types assigned to them (top, middle, bottom, or even more in between), which dictate certain behavior and/or allow their Users certain actions.

Good to hear you think it might not be so much of an issue, because we have extensive experience with single-database multi-tier (recursive) tenant architectures and have yet to run into significant issues and/or pitfalls (aside from scaling, which in my opinion should be done at the database level using sharding).

We'll be playing around a little for the next weeks and will definitely let you know if we need any help and/or can contribute some code :)

**Comment by stancl** [comment]
Hint with regards to multi-tier tenancy: Create multiple instances of `Stancl\Tenancy\Tenancy`, bind them to the container as singletons (they hold the tenancy state related to the specific tier) and update the query scopes to read from the correct `Tenancy` instance.
