### ISSUE TITLE
One user, many tenants - How to actually set that up?

### ISSUE THREAD

**Issue by molteber** [archtechx/tenancy#456]
Hello

I'm trying to setup a tenancy application where the concept is 1 user can have multiple tenants. I'm doing this with the single-database approach.

To start off, i did the Quickstart tutorial in the documentation with some modifications related to single-database approach.
I've createt a `tenant_user` table which for now only has `tenant_id` and `user_id`.

Now, to connect the users model to tenants model, I have used the `BelongsToPrimaryModel` trait and specified a BelongsToMany relationship to the tenants model.

During the testing face in the bottom of your tutorial, you simple lists the tenants users. Went ahead to try that only to find out it showed **all** users, which was connected to a tenant. `dd(User::all());`

Not quite how I wanted that to work, being on a identified tenant domain. So i did some digging and found my way to the `ParentModelScope` where i we're simply calling a whereHas on the specified relation in `BelongsToPrimaryModel`.

Wouldn't it be more correct to do it like this? To make sure the relation is actually a part of that tenant?

```php
$builder->whereHas(
  $builder->getModel()->getRelationshipToPrimaryModel(),
  function (Builder $query) {
    $query->where(BelongsToTenant::$tenantIdColumn, tenant()->getTenantKey());
  }
);
```

Or would that not be quite the meaning of `BelongsToPrimaryModel` /`ParentModelScope` and should probably be added to a other scope? 

Do you have any other suggestions on how to do this with your package?

**Comment by stancl** [comment]
> 1 user can have multiple tenants

What's the point of that?

The scopes/traits are for when 1 tenant has multiple e.g. users.

**Comment by molteber** [comment]
Basically like saying the user is a part of a team, but only needs to know 1 user credential.

> The scopes/traits are for when 1 tenant has multiple e.g. users.

Alright, I guess I can make a custom scope which specifies that a model is indeed a part of the active tenant.

**Comment by wittwerch** [comment]
@molteber We have the exact same case. Would you mind sharing your solution here?

**Comment by vishalinfyom** [comment]
this may be help : https://infyom.com/blog/how-to-use-multi-tenant-with-single-db
