### ISSUE TITLE
Is "delete_database_after_tenant_deletion" coming to 3.x?

### ISSUE THREAD

**Issue by smnmmnn** [archtechx/tenancy#460]
Is there a way to automatically delete the database after deleting the tenant in 3.x?

**Comment by smnmmnn** [comment]
Just realised the default of `$tenant->delete()` also deletes the database.

**Comment by stancl** [comment]
It doesn't do it directly. It fires an event. And there's a listener registered in `TenancyServiceProvider`

Take a look at the Event System page of docs.

**Comment by smnmmnn** [comment]
@stancl Got it, thank you. Is there a helper overview for 3.x?

**Comment by stancl** [comment]
What do you mean by helper overview?

**Comment by smnmmnn** [comment]
like `delete()`, `tenant()`, `end()` …

**Comment by stancl** [comment]
Right, the `tenant()` and `tenancy()` helpers might not be documented too well, not sure.

As for `delete()`, `Tenant` is a model so that's pretty self-evident. A lot of people ask about that though so I'll see how well this is explained in docs.

**Comment by smnmmnn** [comment]
Yes, I can see it for `tenant->run` for example. Is there a reverse equivalent for that (running commands in the central context)?
