### ISSUE TITLE
Unable to upload conflict with Livewire and tenancy

### ISSUE THREAD

**Issue by t-prod** [archtechx/tenancy#462]
Hi,

Just handling multiples files as the docs described it : https://laravel-livewire.com/docs/file-uploads#multiple-files
I'm using Stancl Tenancy package and I think there's a conflict when trying to upload in local. I think there's a conflict with routes or an injection of the tenant ID. Note that I'm in version 2.3 and not the last version.

`file_put_contents(C:\Users\titin\Documents\laragon\www\saas\storage/tenant2afa6d6d-562b-4b4a-b2b4-292f77bdd8ee\framework/cache/facade-c2f53e2d655810ac111b48d42b34b209861bb985.php): failed to open stream: No such file or directory`

The file where the problem is vendor\livewire\livewire\src\WithFileUploads.php
and this function GenerateSignedUploadUrl::forLocal()

![image](https://user-images.githubusercontent.com/1824638/87907847-aa8b8780-ca65-11ea-872b-9a415fa268fc.png)

`$this->emitSelf('upload:generatedSignedUrl', $name, GenerateSignedUploadUrl::forLocal()); //<-- here`
If you see the error screenshot I think there's tenant id injection here but I don't know how can I make it work ;)

![image](https://user-images.githubusercontent.com/1824638/87907547-220ce700-ca65-11ea-966a-c5b8edb6a4b5.png)

Any ideas ?

**Comment by stancl** [comment]
Create the framework directory for the tenant when he's created (using a hook) https://github.com/stancl/tenancy/issues/283#issuecomment-596210846

(`$storage_path` above is `storage_path()` in tenant context)

I'll document this for v3. v2 won't be getting updates.

**Comment by stancl** [comment]
https://tenancyforlaravel.com/docs/v3/realtime-facades/

**Comment by gmanikandan-dev** [comment]
I have received this issue. 
**Class "Facades\Livewire\GenerateSignedUploadUrl" not found**
**Solution :**
 1. Go to the "vendor/livewire/livewire/src/**WithFileUploads**.php" file.
 2. You should use "**use Livewire\GenerateSignedUploadUrl**" instead of  "use Facades\Livewire\GenerateSignedUploadUrl".
 3. Go to the "vendor/livewire/livewire/src/**GenerateSignedUploadUrl**.php".
 4. **Add static**  
 ```
public static function forLocal()
    {
        return URL::temporarySignedRoute(
            'livewire.upload-file', now()->addMinutes(FileUploadConfiguration::maxUploadTime())
        );
    }
```
**instead of**
```
 public function forLocal()
    {
        return URL::temporarySignedRoute(
            'livewire.upload-file', now()->addMinutes(FileUploadConfiguration::maxUploadTime())
        );
    }
```

**Comment by GarethSomers** [comment]
Incase anyone is coming to this issue from a Laravel Vapor perspective; instead of hooking into the TenantCreated event as per the documentation [here](https://tenancyforlaravel.com/docs/v3/realtime-facades/)... you can instead use this `TenancyBootstrapped`.
