### ISSUE TITLE
Command execution with tenants:run 

### ISSUE THREAD

**Issue by TheOneWhoKnokks** [archtechx/tenancy#465]
#### Describe the bug
Hello, 

when i try to launch a command with tenants:run, the job is precessed successfully : 
```
[2020-07-24 09:55:50][11] Processing: Illuminate\Foundation\Console\QueuedCommand
"handle function"
"handle function"
[2020-07-24 09:55:50][11] Processed:  Illuminate\Foundation\Console\QueuedCommand
```
There is one queued command but there is 2 handle function executed. The two "handle function" match with my 2 created domains. So if i a have 5 domains, there will be 5 times "handle function is executed" for only one job. 

I try with a new fresh laravel project and with a custom driver i got the same result

#### Steps to reproduce
Create two domains
Create a command FooBar with dump or log info in handle function to show a message.
Add 2 traits "TenantAwareCommand" and "HasATenantArgument"
Create a specific route url with with content inside : 
```
$tenantId = tenancy()->getTenant('id');
Artisan::queue("tenants:run", [
     "commandname" => "foo:bar",
      "--argument" => ["tenant=$tenantId"],
]);
```
Use redis for queue connection and launch php artisan queue:listen for listening queue.

To go to your created route and the console result will be : 
```
[2020-07-24 09:55:50][11] Processing: Illuminate\Foundation\Console\QueuedCommand
"handle function"
"handle function"
[2020-07-24 09:55:50][11] Processed:  Illuminate\Foundation\Console\QueuedCommand
```

#### Expected behavior
Correct me if i'm wrong but i think it must be only one "handle function" when there is one tenant id whatever the domain quantity no ?

#### Your setup
 - Laravel version: 7.21.0
 - stancl/tenancy version: 2.3.12
 - Storage driver: db (mysql)

**Comment by stancl** [comment]
Why are you using both `tenants:run` and the command traits?

**Comment by TheOneWhoKnokks** [comment]
Ah it's an error indeed, I had misread the doc, I thought that the two could work together, sorry: /

**Comment by stancl** [comment]
If you're writing the commands yourself, use the traits. If you're executing some third party commands, the `tenants:run` command is useful.

Hope that helps.
