### ISSUE TITLE
Cannot get data from api when using sanctum. when you put a middleware it does work.if you dont put a middleware it works. what might be the problem

### ISSUE THREAD

**Issue by Dickorir** [archtechx/tenancy#469]
#### Describe the bug

Cannot get data from api when using sanctum. when you put a middleware it does work.if you dont put a middleware it works. what might be the problem
#### Your setup
 - Laravel version: [e.g. 6.2.0]
 - stancl/tenancy version: [e.g. 2.1.0]
 - Storage driver: [e.g. DB]
 - Laravel Sanctum

**Comment by SergeyMiracle** [comment]
No good description or code examples

It looks like you have problems with sanctum, not tenancy

**Comment by stancl** [comment]
Sanctum is not tenancy, so please don't open bug reports when this is completely unrelated to the package.
