### ISSUE TITLE
Undefined class constant 'OPT_PREFIX' on a new Installation of Laravel 5.8

### ISSUE THREAD

**Issue by clizaola** [archtechx/tenancy#47]
I was trying to test this package in a brand new Laravel 5.8 app, I went as far as 
https://github.com/stancl/tenancy#creating-a-new-tenant
and in the next step, I got the error of
 Symfony\Component\Debug\Exception\FatalThrowableError  : Undefined class constant 'OPT_PREFIX'
on
/vendor/stancl/tenancy/src/StorageDrivers/RedisStorageDriver.php:75

Thanks

**Comment by stancl** [comment]
Do you have phpredis installed?

Phpredis is required because predis can't do prefixes.

If you run `\Redis::OPT_PREFIX` in `php artisan tinker` it should return `2`.

**Comment by clizaola** [comment]
yes I do, this is my composer.json

`
"require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "predis/predis": "^1.1",
        "stancl/tenancy": "^1.3"
    },
`

**Comment by stancl** [comment]
> `"predis/predis": "^1.1"`

That's the issue. Like I said, this package requires **phpredis** and does not support **predis**.

---

I see that I should have mentioned this at the top of the readme rather than in the *Redis* section. I fixed that. https://github.com/stancl/tenancy/blob/1.x/README.md#requirements

**Comment by clizaola** [comment]
Sorry, I see now, thanks

**Comment by stancl** [comment]
No problem. Thanks for opening this issue though, I didn't notice that I forgot to mention phpredis in the installation part of readme.
