### ISSUE TITLE
laravel-websockets support?

### ISSUE THREAD

**Issue by hizone** [archtechx/tenancy#470]
any one know if supporting 
https://github.com/beyondcode/laravel-websockets ?

**Comment by raymiec** [comment]
Works just fine, had a slight issue with the broadcast route to get the token for private channels but other than that all is good

**Comment by a-ssassi-n** [comment]
@raymiec how did you solve the broadcast auth route issue?

While using a private channel, the `/broadcasting/auth` route always connects to the central database rather than connecting to the tenant database.

Is there a way to solve this?

**Comment by raymiec** [comment]
Move it in your routes files so it's getting loaded with the tenant.

**Comment by a-ssassi-n** [comment]
Ya, I thought so and create a custom route and it's working fine now. Thanks.

**Comment by rymesaint** [comment]
i'm still getting trouble with broadcasting auth on tenant, i still got 403 error, how to resolve this?

```
Broadcast::routes(['middleware' => ['web', 'auth:sanctum']);

Route::post('/broadcasting/auth', function(Request $request) {
    Broadcast::auth($request);
})->withoutMiddleware([VerifyCsrfToken::class]);
```

**Comment by lucabecchetti** [comment]
did you solve it?

**Comment by stancl** [comment]
In v3 you'd need to manually register channels prefixed with the tenant's ID, in v4 we have an integration for this.
