### ISSUE TITLE
Route::prefix('api')  is omitted 

### ISSUE THREAD

**Issue by victorelec14** [archtechx/tenancy#476]
#### Describe the bug

seems like tenancy ignores routes with api prefix and give 404 Error.

#### Steps to reproduce

tenant.php
```php
Route::middleware([
    'api',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
  
    Route::get('hello', function () {
        return 'test api' . tenant('id');
    });
});
```

#### Your setup
 - Laravel version: 7.0
 - stancl/tenancy version: 3.1

---------------

> php artisan route:list
> php artisan tenants:run route:list

![image](https://user-images.githubusercontent.com/543450/89643209-8f1dda80-d8b5-11ea-856f-2bf3aa373524.png)

RouteServiceProvider.php
```

 protected function mapApiRoutes()
    {      
        foreach ($this->centralDomains() as $domain) {
            Route::prefix('api')
                ->domain($domain)
                ->middleware('api')
                ->namespace($this->namespace)
                ->group(base_path('routes/api.php'));
        }
    }

```

Urls:
{tenacy}.domain.dev/api/hello -> 404
{tenacy}.domain.dev/hello -> data

change route "Route::get('hello') to Route::get('api/hello')  : 
{tenacy}.domain.dev/api/hello -> data

It will too ignore if I change the API prefix to some other .

Thanks !

**Comment by stancl** [comment]
routes/tenant.php is unrelated to `mapApiRoutes()`. I don't see what's the problem

**Comment by victorelec14** [comment]
> routes/tenant.php is unrelated to `mapApiRoutes()`. I don't see what's the problem

The same happens in the api.php.

tenancy doesn't support /api/xxxx ?  or need set the route with "/api/xxx" in the api.php

**Comment by stancl** [comment]
What? Don't use `api.php`. That's a central route. Your routeserviceprovider literally registers it only on the central domain.

If you want a tenant `/api` route, go to `tenant.php` and create a route that starts with `/api`. How does that not work?

**Comment by Neve12ende12** [comment]
I tried this and it worked for me.

https://{tenant}.domain.local -> Returns the tenant id
https://{tenant}.domain.local/api//users -> Returns the tenants users

routes/tenant.php
```
Route::prefix('api')->middleware([
    'api',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::resources([
        'users' => UserController::class
    ]); 
});

Route::middleware([
    'web',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::middleware(['web'])->group(function () {
        Route::get('/', function () {
            return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
        });
    });
});
```

**Comment by xBigDaddyx** [comment]
i still getting error 404, and already place my route on tenant.php

```
Route::middleware([
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->prefix('api')->group(function () {
    Route::middleware(['api'])->group(function () {
        // Route::get('auth/login', function () {
        //     return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
        // });
        Route::post('auth/register', [\App\Http\Controllers\Api\AuthController::class, 'register'])->name('accuracy.api.register');
        Route::post('auth/login', [\App\Http\Controllers\Api\AuthController::class, 'login'])->name('accuracy.api.login');
    });
});
```
