### ISSUE TITLE
Multi-Domain Support

### ISSUE THREAD

**Issue by UniSoftTeam** [archtechx/tenancy#478]
#### Description

Hi, I wonder if I can use this awesome package to admin multi domain tenant system?
like this one https://github.com/gecche/laravel-multidomain

**Comment by jonagoldman** [comment]
Yes, the documentation is a good place to check all the features. See [Domains](https://tenancyforlaravel.com/docs/v3/domains) .

**Comment by vahidalvandi** [comment]
Do I need change apache setting for domain park 
?
