### ISSUE TITLE
Test compatibility with Lumen

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#48]

**Comment by stancl** [comment]
Lumen is not supported.

```

In TenancyServiceProvider.php line 36:
                                                           
  Call to undefined function Stancl\Tenancy\config_path()  
                                                           
```

**Comment by moazam1** [comment]
Hi, just checking if you have added lumen support in v2.0?

**Comment by stancl** [comment]
It's certainly still unsupported, but I'll revisit this and see if I can add Lumen support without introducing too much complexity.

**Comment by moazam1** [comment]
Thanks!

**Comment by stancl** [comment]
Decided to ignore this again. Lumen shouldn't be used for many things anyway.

**Comment by lengjunbin-trec** [comment]
@stancl How about now?Do you hava any plan to support lumen

**Comment by stancl** [comment]
No plans. Laravel has no plans for it either, they're only keeping it alive.

There's no reason to choose Lumen for new applications nowadays and supporting it is difficult.

**Comment by lengjunbin-trec** [comment]
> No plans. Laravel has no plans for it either, they're only keeping it alive.
> 
> There's no reason to choose Lumen for new applications nowadays and supporting it is difficult.

Thanks for reply
