### ISSUE TITLE
Inconsistency in __callStatic method doc blocks causing red error in my IDE while doing Getting Started tutorial

### ISSUE THREAD

**Issue by isaackearl** [archtechx/tenancy#480]
#### Describe the bug
I'm using PHPStorm, laravel-ide-helper, and Laravel idea... and my IDE sees inconsistency in Doc blocs and therefore shows an error when in fact there isn't really an error.  This is not really a breaking bug, just a minor annoyance for those who are using IDEs that scan everything and compare doc blocks

#### Steps to reproduce
Use PhpStorm + laravel idea (laravel-ide-helper may be needed too)
Follow the "Getting Started" documentation.  Once you get to this part:

![gettingstarted](https://user-images.githubusercontent.com/9354830/90542482-30c4e780-e152-11ea-85a8-4d11f5f8c439.png)

The error says:

`Model::callStatic(method: string, parameters: array)' must be compatible with 'Tenant->callStatic(method: string, parameters: array)`

Upon further inspection I can see that my IDE is sensing the __callStatic docblock that exists in both the Tenant Contract and the base Model, and seeing that they are conflicted.  (not sure how to resolve this)

#### Expected behavior
I don't see an error while doing the Getting Started tutorial.

#### Your setup
 - Laravel version: 7.25.0
 - stancl/tenancy version: v3.1.6
 - Storage driver: mysql

**Comment by stancl** [comment]
Does making the annotation `static` resolve this?

```php
* @method static __callStatic(string $method, array $parameters) IDE support. This will be a model.
```

**Comment by isaackearl** [comment]
@stancl yes.  When I add static to the annotation in Contracts/Tenant, it resolves the issue.

**Comment by stancl** [comment]
Resolved in latest commit.
