### ISSUE TITLE
Calls to initialize with a non object value only works the first time it's called

### ISSUE THREAD

**Issue by lcdss** [archtechx/tenancy#481]
#### Describe the bug
The new feature to initialize the tenant manuall,  passing a string or int, only works the first time it's called. Subsequent calls will throw an error as $tenant->getTenantKey() does not exist.

https://github.com/stancl/tenancy/blob/1ff82fb2a09dd0ee545fd13679aa739ea589dfed/src/Tenancy.php#L34-L36

#### Steps to reproduce
Access the laravel console and try to initialize the tenancy more than once for the same or different tenant by its id:

```php
tenancy()->initialize('tenant1');
tenancy()->initialize('tenant2');
```

#### Expected behavior
The new tenant context would be loaded without throwing an error. In case of the id belongs to the current tenant, nothing should happen.

#### Your setup
 - Laravel version: 7.25.0
 - stancl/tenancy version: 3.1.7

**Comment by stancl** [comment]
Hey,

Can you try doing

```
composer require stancl/tenancy:fix-initialize
```

and testing if this is fixed?

Thanks!
