### ISSUE TITLE
How could I access to tenant assets by using path identification?

### ISSUE THREAD

**Issue by johnyang90** [archtechx/tenancy#483]
I am using path identification for tenancy. Example: http://localhost:8000/api/{tenant_id}/{api_path}
When I use asset helper to return tenancy images or file, it return http://localhost:8000/tenancy/assets/{image_path}, since I am using path identification, so from the image url, it couldn't recognize which tenant is.

Could you provide more documentation about the accessing assets in path identification?

**Comment by stancl** [comment]
You'll need a custom path. You can change the TenancyAssetController's middleware by changing a static property, and then you can create a custom route that uses that controller in your route group prefixed with /{tenant}/.

**Comment by jwktje** [comment]
@johnyang90 @stancl 

I stumbled upon this issue and tried fixing it like you mentioned. 
I can't get it to work logically. 

In a controller method inside my tenant I store a file like so; 
```
if($request->file('company_logo')) {
            $newPath = Storage::disk('public')->put('logos',$request->file('company_logo'));
            $this->settings->put('company_logo', $newPath);
}
```

Then in my Blade template I output the URL for testing like so:
```
@dump(asset($settings['company_logo']))
```

This gives me: 
```
https://laravel.test/tenancy/assets/logos/CwPRwG0OoIoAcwnK88GSKzTvG8hum3xVLXiSU2qL.jpg
```

Then I updated the static property on the TenantAssetsController like so:
```
TenantAssetsController::$tenancyMiddleware = InitializeTenancyByPath::class;
```

And then I added  a custom path like so:
```
Route::group([
    'prefix' => '/{tenant}',
    'middleware' => [ExcludeNovaFromTenantMatching::class, InitializeTenancyByPath::class, SetDefaultTenantForUrls::class],
], function () {
    Route::get('/tenancy/assets/logos/{logo}',function($logo) {
        $assetController = new TenantAssetsController();
        return $assetController->asset('logos/' . $logo);
    });
});
```

The only way I can get the image to show is by manually crafting this URL:
```
https://laravel.test/tenant_1/tenancy/assets/logos/CwPRwG0OoIoAcwnK88GSKzTvG8hum3xVLXiSU2qL.jpg
```

Ideally I would just use the `asset()` function and have it return an URL that includes the Tenant path prefix, and that the router would understand which storage directory to use, based on this tenant URL. What can I do to make that work?

**Comment by johnyang90** [comment]
I end up create a custom helper function to get tenancy asset path.
I placed all my tenancy storage folder inside storage/app/public/{tenant_id}

if (!function_exists('tenancy_asset')) {
    function tenancy_asset($path)
    {
        $tenant_id = tenant('id');
        return url('storage/' . $tenant_id . '/' . $path);
    }
}
