### ISSUE TITLE
 Observation period issues

### ISSUE THREAD

**Issue by youyingxiang** [archtechx/tenancy#484]
#### Describe the bug
Why can't tenants use observers?

#### Steps to reproduce
![image](https://user-images.githubusercontent.com/28653285/91291416-9c98f700-e7c7-11ea-95d3-36988b300b62.png)
![image](https://user-images.githubusercontent.com/28653285/91291510-bfc3a680-e7c7-11ea-8c37-6d29d010062a.png)
![image](https://user-images.githubusercontent.com/28653285/91291600-dff36580-e7c7-11ea-83c5-962a8157f903.png)

#### Your setup
 - Laravel version: [e.g.7.24]
 - stancl/tenancy version: [e.g.3.1]
 - Storage driver: [e.g.mysql]

**Comment by stancl** [comment]
That's strange. Events work completely fine. Can you try using events in `booted()`?

If events work, observers should work too.
