### ISSUE TITLE
Logout from all Subdomain

### ISSUE THREAD

**Issue by cix99** [archtechx/tenancy#490]
In many cases, multi-tenant apps use a central login with redirection to the single tenant (can be multiple tenants).
The single users are just **Synced between tenants** and the central app impersonates the user in the tenant.

This is like SSO. One of the most common protocols used for SSO is SAML 2.0
The central app acts as an Identity Provider, where you can pick the tenant to open. The tenant, on the other hand, would act as a Service Provider. And tenancy works just like this, while logging in.

However, there's one feature that would be great to add, and that is the Single Logout. This feature exists in SAML 2.0. However, for just one single app, multi-tenant but still the same app, would be painful to add the SAML configuration, and would be fantastic to do everything in laravel and tenancy.

**Comment by stancl** [comment]
Hey,

Yeah, this is planned. When I'll be writing the code for the [central (SSO-like) auth](https://sponsors.tenancyforlaravel.com/central-sso-like-authentication), I'll be doing single-logout as well.

**Comment by stancl** [comment]
Hey,

Yeah, this is planned. When I'll be writing the code for the [central (SSO-like) auth](https://sponsors.tenancyforlaravel.com/central-sso-like-authentication), I'll be doing single-logout as well.

**Comment by vahidalvandi** [comment]
or how i can login to all sub domains ?
