### ISSUE TITLE
Usage with Jetstream

### ISSUE THREAD

**Issue by obrunsmann** [archtechx/tenancy#496]
I created a new Jetstream Project with Teams today and tried integrating tenancy with jetstream.

I think it could be quite easy with using the Jetstream actions on one hand and implementing just a custom middleware which sync the current jetstream team with the tenancy tenant.

But: The default team already extends the `JetstreamTeam` Base Model so I am not able to extend to the `Tenant` as well. Maybe it could be solved with creating a trait in addition to the Tenant base model?

**Comment by stancl** [comment]
Hey,

I'll be building a Jetstream integration soon.

You don't need to extend the base tenant model, you just have to implement the interface.

There's no need to create new traits, because the base model is already composed from traits, and has very little custom stuff.

**Comment by saade** [comment]
Hey @obrunsmann i can't get login and registration on the tenant domain to work. I'm using the same setup as yours, but the users are created in the central database instead of the tenant one. Can u help me setup mine?

**Comment by obrunsmann** [comment]
@saademotion In fact it was relatively easy.. I just used Fortify's `Team` Model as Tenant Model and wrote a custom identification middleware:

```
    public function handle(Request $request, Closure $next)
    {
        if (auth()->user()) {
            tenancy()->initialize(auth()->user()->currentTeam);
        }

        return $next($request);
    }
``` 


That's all. I putted all my routes in web.php instead of tenant.php.

**Comment by victorelec14** [comment]
is broken on on Laravel 8 with tenancy 3.4 ?

It happens to me when I try to login / register in a tenant:

```
Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'maindomain.users' doesn't exist (SQL: select * from `users` where `email` = xxxx.xxx@example.net limit 1)

```

SESSION_DRIVER=database

"laravel/framework": "^8.12",
        "laravel/jetstream": "^2.0",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.0",
        "stancl/tenancy": "^3.4"

**Comment by sefaYavuz** [comment]
> is broken on on Laravel 8 with tenancy 3.4 ?
> 
> It happens to me when I try to login / register in a tenant:
> 
> ```
> Illuminate\Database\QueryException
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'maindomain.users' doesn't exist (SQL: select * from `users` where `email` = xxxx.xxx@example.net limit 1)
> ```
> 
> SESSION_DRIVER=database
> 
> "laravel/framework": "^8.12",
> "laravel/jetstream": "^2.0",
> "laravel/sanctum": "^2.6",
> "laravel/tinker": "^2.5",
> "livewire/livewire": "^2.0",
> "stancl/tenancy": "^3.4"

This also happens to me, any idea? @stancl

**Comment by victorelec14** [comment]
Related #547

**Comment by suleodu** [comment]
> is broken on on Laravel 8 with tenancy 3.4 ?
> 
> It happens to me when I try to login / register in a tenant:
> 
> ```
> Illuminate\Database\QueryException
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'maindomain.users' doesn't exist (SQL: select * from `users` where `email` = xxxx.xxx@example.net limit 1)
> ```
> 
> SESSION_DRIVER=database
> 
> "laravel/framework": "^8.12",
> "laravel/jetstream": "^2.0",
> "laravel/sanctum": "^2.6",
> "laravel/tinker": "^2.5",
> "livewire/livewire": "^2.0",
> "stancl/tenancy": "^3.4"

i am having the same issue what is the clear solution to this ?

**Comment by jeremiahsherrill** [comment]
Any news or updates?  I am also having this issue

**Comment by ClaudioEyzaguirre** [comment]
@victorelec14  In order to integrate stancl/tenancy with Jetstream you need to make the followings  changes:

1. Open the `config/database.php` file and add a tenant connection:
```php
'connections' => [
    'tenant' => [
        'driver' => 'mysql',
        'url' => env('DATABASE_URL'),
        'host' => env('DB_HOST', '127.0.0.1'),
        'port' => env('DB_PORT', '3306'),
        'database' => null,
        'username' => env('DB_USERNAME', 'forge'),
        'password' => env('DB_PASSWORD', ''),
        'unix_socket' => env('DB_SOCKET', ''),
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => '',
        'prefix_indexes' => true,
        'strict' => true,
        'engine' => null,
        'options' => extension_loaded('pdo_mysql') ? array_filter([
            PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
        ]) : [],
    ],
],
```
2. Open the `config/tenancy.php` file, find the `database.central_connection` option and set to `env('DB_CENTRAL_CONNECTION', 'central')`. Then find the `database.template_tenant_connection` and replace `null` with `env('DB_CONNECTION', 'tenant')`.
3. Open your `.env` file and set `DB_CONNECTION` to `tenant`. **This tells Jetstream that the default connection is tenant, not central**.
4. Finally, open the `config/fortify.php` and change `middleware` option to this:
```php
use Stancl\Tenancy\Middleware\InitializeTenancyByDomain;
use Stancl\Tenancy\Middleware\PreventAccessFromCentralDomains;

...

'middleware' => [
    'web',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
],
```

Please let me now if this works for you

**Comment by ClaudioEyzaguirre** [comment]
> @victorelec14 In order to integrate stancl/tenancy with Jetstream you need to make the followings changes:
> 
> 1. Open the `config/database.php` file and add a tenant connection:
> 
> ```
> 'connections' => [
>     'tenant' => [
>         'driver' => 'mysql',
>         'url' => env('DATABASE_URL'),
>         'host' => env('DB_HOST', '127.0.0.1'),
>         'port' => env('DB_PORT', '3306'),
>         'database' => null,
>         'username' => env('DB_USERNAME', 'forge'),
>         'password' => env('DB_PASSWORD', ''),
>         'unix_socket' => env('DB_SOCKET', ''),
>         'charset' => 'utf8mb4',
>         'collation' => 'utf8mb4_unicode_ci',
>         'prefix' => '',
>         'prefix_indexes' => true,
>         'strict' => true,
>         'engine' => null,
>         'options' => extension_loaded('pdo_mysql') ? array_filter([
>             PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
>         ]) : [],
>     ],
> ],
> ```
> 
> 2. Open the `config/tenancy.php` file, find the `database.central_connection` option and set to `env('DB_CENTRAL_CONNECTION', 'central')`. Then find the `database.template_tenant_connection` and replace `null` with `env('DB_CONNECTION', 'tenant')`.
> 3. Open your `.env` file and set `DB_CONNECTION` to `tenant`. **This tells Jetstream that the default connection is tenant, not central**.
> 4. Finally, open the `config/fortify.php` and change `middleware` option to this:
> 
> ```
> use Stancl\Tenancy\Middleware\InitializeTenancyByDomain;
> use Stancl\Tenancy\Middleware\PreventAccessFromCentralDomains;
> 
> ...
> 
> 'middleware' => [
>     'web',
>     InitializeTenancyByDomain::class,
>     PreventAccessFromCentralDomains::class,
> ],
> ```
> 
> Please let me now if this works for you

A simpler solution is follow step 4 and add `protected $connection = 'tenant';` to `User` model.

**Comment by zupolgec** [comment]
Managed to use Jetstream with Tenancy v3

https://github.com/zupolgec/fortitenant

Main changes:
- set `['web', 'universal', InitializeTenancyByDomain::class]` as middlewares in both config/fortify.php, config/livewire.php and config/livewire.php (if using Livewire)
- added @jhoopes suggestion from https://github.com/archtechx/tenancy/issues/702, just customised and cleaned
