### ISSUE TITLE
TenantDatabaseAlreadyExistsException message issue

### ISSUE THREAD

**Issue by GENL** [archtechx/tenancy#497]
![image](https://user-images.githubusercontent.com/36866702/93884999-83f30280-fcdb-11ea-8652-afa3c7aad30e.png)

The reason does not display the database.

I receive
![image](https://user-images.githubusercontent.com/36866702/93885363-f5cb4c00-fcdb-11ea-9bc7-41fcfd30a460.png)

The code at the line 23 should come before `parent::__construct();` so the reason message can display the database in the text.

Just to be noted. It is quite difficult to test with multi-db. The documentation must be clear on (Refresh the database, delete the created database,). I'm still stuck on this

**Comment by stancl** [comment]
Hey,

Nice catch! Can you submit a PR adding this line?

What do you mean by "difficult to test with multi-db"? The testing setup in boilerplate/sponsor docs works very well https://sponsors.tenancyforlaravel.com/frictionless-testing-setup

I will also be making some improvements to it, to clean up databases better and to use transactions inside the tenant DB for even better performance.
