### ISSUE TITLE
Tenant not initialized on asset() and tenant_asset() urls

### ISSUE THREAD

**Issue by Dontorpedo** [archtechx/tenancy#500]
Hi 

I am using your saas-boilerplate and didn't made big changes in the app,

i am trying to download a file which i saved in the tenant folder using Storage::....

but when i use the asset or tenant_asset helper and use the url like: 

tenanturl.com/tenancy/assets/tmp/filename.pdf or any else i get two errors:

Tenant could not be identified on domain tenant1.myurl.com {"exception":"[object] (Stancl\\Tenancy\\Exceptions\\TenantCouldNotBeIdentifiedOnDomainException(code: 0):

and

Route [central.landing] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [central.landing] not defined. at /var/www/invernos.at/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:420) 

thanks for help

**Comment by stancl** [comment]
Hey, this is not a bug related to the package. I'm trying to keep things organized please.

If you have a support question, you can:
- contact support if it's part of your license (Enterprise)
- ask on our Discord server.

Thanks.

**Comment by GENL** [comment]
Need the discord link please,
