### ISSUE TITLE
Schedule Run support

### ISSUE THREAD

**Issue by renege** [archtechx/tenancy#502]
#### Description
Now it is not possible to have Command to be scheduled in the Kernel. 

#### Why this should be added
Or am I wrong and is this already working? Still my  `php artisan schedule:run` insn't Tenant-aware

**Comment by stancl** [comment]
This shouldn't be solved by the package.

How would it know what tenants to run for? How would it know what jobs are central and what jobs are tenant?

If you need to do something in the tenant context, loop through the tenants and `run()` in the handle method of the job.

**Comment by renege** [comment]
@stancl 
But I tried this:

 ```
protected function schedule(Schedule $schedule)
    {
        foreach (Tenant::all() as $tenant) {
            $schedule->command('tenants:run foobar --tenants=' . $tenant->id)->everyFourHours();
        }
}
```

And this is not running my `foobar`-command Tenant aware.

**Comment by stancl** [comment]
I said use `$tenant->run()` inside `handle()`, not loop through tenants in the `schedule()` method. That can't possibly work.

**Comment by ctf0** [comment]
@renege try
```php
$schedule->command('tenants:run foobar' . $this->getTenants())->everyFourHours();
```

```php
protected function getTenants()
{
    return Cache::remember('tenants-ids', now()->addHour(), function () {
        $str = '';
        foreach (Tenant::get()->pluck('id')->all() as $id) {
            $str .= " --tenants='{$id}'";
        }

        return $str;
    });
}
```

**Comment by stancl** [comment]
Please don't abuse artisan commands when you can use `$tenant->run()`.

**Comment by ctf0** [comment]
this is mostly for the external packages cmnds

**Comment by stancl** [comment]
Why would `$tenant->run()` not work there?

**Comment by stancl** [comment]
Ah, you mean commands like `artisan foobar`.

Still, I don't think it's a good idea to run commands like that. I'd just loop through tenants, initialize tenancy using `run()`, and use `Artisan::call()`.

**Comment by ctf0** [comment]
am facing this with `spatie/laravel-backup` where am scheduling the cmnd to run daily, without the above i either 
- create a job and inside it run the db backup cmnd
- or override the original cmnd

**Comment by Fuhrmann** [comment]
@ctf0 this is my approach:

```
<?php

namespace App\Jobs;

use App\Models\Tenant;

abstract class TenantsJob extends BaseJob
{
    /**
     * Execute
     */
    public function handle()
    {
        $tenants = Tenant::where('active', 1)->get();
        tenancy()->runForMultiple($tenants, function ($tenant) {
            $this->execute($tenant);
        });
    }

    /**
     * Execute the job for the specific tenant.
     *
     * @param  Tenant  $tenant
     */
    abstract public function execute(Tenant $tenant);
}
```

Then you create your job:

```
<?php

namespace App\Jobs;

use App\Jobs\TenantsJob;
use App\Models\Tenant;

class DeleteTemporaryFiles extends TenantsJob
{
   
    public function execute(Tenant $tenant)
    {
      // do something with $tenant
    }
}

```

And your Kernel.php file you define the schedule job:

```
$schedule->job(new DeleteTemporaryFiles)->daily()->at('01:00');
```

**Comment by aneeskhan47** [comment]
@renege 
@Fuhrmann 
@ctf0 

for those who want to run their custom artisan command tenant aware (for each tenant):

![image](https://user-images.githubusercontent.com/30714223/133605899-d9bd95b0-2990-4c71-aa46-e884525e37e9.png)
