### ISSUE TITLE
Favicons returned by tenancy

### ISSUE THREAD

**Issue by colinmackinlay** [archtechx/tenancy#503]
#### Description
Return a favicon bespoke to the tenancy
#### Why this should be added
Nice to have for  branding for individual  clients but really useful if someone has multiple clients for different organisations within their company and wants to see something to differentiate between them in the browser tabs

Low priority of course but a nice little puzzle!

A starting point could be https://github.com/beyondcode/laravel-favicon which returns modified favicons according to environment variable

**Comment by CristianTudorache** [comment]
This can be achieved right now. The package offers you everything you need to find if tenancy is initialized and get current tenant. After this you are free to play with favicon as you wish (get icon from config or database etc.)
something like `tenant('data.favicon') ?? default_favicon` should do the job.

**Comment by stancl** [comment]
Yeah. This sounds like a nice feature, but I don't think it needs to be part of the core. There's nothing in the package that needs to be changed to allow you to do this.
