### ISSUE TITLE
Migrations Laravel 8 Passport 10v Wrong db connection

### ISSUE THREAD

**Issue by Nizari** [archtechx/tenancy#505]
#### Describe the bug
Since updating to laravel 8 the seeders seem to break for Passport.

#### Steps to reproduce

Put your passport migrations inside the tenant-directory.
Create a Tenant.

```
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Laravel\Passport\Client;

class TenantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Client::create([
            'name'                   => config('app.name') . ' Password Grant Client',
            'secret'                 => 'secret',
            'redirect'               => config('app.url'),
            'password_client'        => true,
            'personal_access_client' => false,
            'revoked'                => false,
        ]);
    }
}
```

Then run:
`a tenants:seed --tenants tenant-id --class TenantSeeder`

This returned
```
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud_tenancy.oauth_clients' doesn't exist (SQL: insert into `oauth_clients` (`name`, `secret`, `redirect`, `password_client`, `personal_access_client`, `revoked`, `updated_at`, `created_at`) values (Cloud API Password Grant Client, secret, http://cloud-api.app.test, 1, 0, 0, 2020-10-02 20:13:54, 2020-10-02 20:13:54))
```

#### Expected behavior
It should go to the cloud_tenant_{tenant_id} database but instead goes to the master branch.

#### Your setup
 - Laravel version: v8.7.1
 - stancl/tenancy v3.2.1
 - Storage driver: mysql 5.7

**Comment by JapSeyz** [comment]
Don't know if it's the same bug, but both migrations and seeders seems broken to me in L8.

**Comment by Nizari** [comment]
> Don't know if it's the same bug, but both migrations and seeders seems broken to me in L8.

Depends. For my standard models it works just fine and gets seeded ok. But it's specifically for laravel passport it seems. I'm using Laravel passport v10. Weird thing is that it looks like before the query gets executed the target database seems ok, but then I still get an error were it tries to connect to the main database...

**Comment by Nizari** [comment]
OMG!!! I found it! Starting laravel passport 10 they've added a config('passport.storage.connection.driver'). This is not updated by tenancy and was the reason the database connection is never to the tenant!

Hopefully this can safe other people lots of stress.

```php
<?php

return [

   ....
    /*
    |--------------------------------------------------------------------------
    | Passport Storage Driver
    |--------------------------------------------------------------------------
    |
    | This configuration value allows you to customize the storage options
    | for Passport, such as the database connection that should be used
    | by Passport's internal database models which store tokens, etc.
    |
    */

    'storage' => [
        'database' => [
            'connection' => 'tenant', // This was env('DB_CONNECTION', 'mysql')
        ],
    ],

];
```

**Comment by stancl** [comment]
@Nizari Does it work if you make the connection `null`?

**Comment by Nizari** [comment]
@stancl this also seem to work. Even better :)

**Comment by devsergioraar** [comment]
Hi @Nizari 
I did it. It did not work.

```
 InvalidArgumentException

  Database connection [tenant] not configured.
```

**Comment by ashraful19** [comment]
Hi,
anyone finally solved this issue ?
`'connection' => 'tenant'` is giving error `Database connection [tenant] not configured.`
`'connection' => null` is taking the central db connection

If anyone solved the issue, please help.

**Comment by ashraful19** [comment]
To anyone who face this problem, here is the solution,
```
'storage' => [
        'database' => [
            'connection' => null,
        ],
    ],
```
it is the right value.
The problem is `auth` middleware is getting higher priority than the middleware we are using to determine the tenant and switch db connection. So for example if you are using `Stancl\Tenancy\Middleware\InitializeTenancyByDomain` middleware to identify tenant and switch db connection, then go to `app/Http/Kernel.php` file, find the `protected $middlewarePriority` array, and insert  `\Stancl\Tenancy\Middleware\InitializeTenancyByDomain::class` before `\App\Http\Middleware\Authenticate::class`

This will solve the issue. 
If you are using a different middleware than `InitializeTenancyByDomain`, just make sure to put that one in this priority array before the `Authenticate` middleware.

**Comment by stancl** [comment]
@abrardev99 
1. Try to reproduce the issue
2. Try the fix above — setting it to `null` as I commented

**Comment by pepijndik** [comment]
is it an idea to automatically change the database connection for passport. So that it's also still able to use passport in just the central app and in the tenant?

**Comment by abrardev99** [comment]
@stancl I reproduced the error and the reported error is correct. Passport tries to connect to central DB. The provided suggestion works fine. Setting the connection to null in passport config works fine for me. 
```
'storage' => [
    'database' => [
        'connection' => null,
    ],
],
```

Looks like the [Docs page](https://tenancyforlaravel.com/docs/v3/integrations/passport) already mentioned it.

**Comment by stancl** [comment]
So this is pretty much resolved? The docs fully cover the needed integration steps?

**Comment by abrardev99** [comment]
> So this is pretty much resolved?

Yes. 

> The docs fully cover the needed integration steps?

Yes. Docs are good enough.

**Comment by stancl** [comment]
Thanks the testing :)
