### ISSUE TITLE
Tenancy with "multi-apps"

### ISSUE THREAD

**Issue by DaGLiMiOuX** [archtechx/tenancy#506]
Hi there.

I don't know if you have any other ways/channels to request some assitance/support information about your product. I've been testing some functions to see how your package works with tenants and I'm really impressed.

Today, I was thinking in the project im currently working on and how to implement Tenancy into it to upgrade our application and offer it as SaaS.

I mostly like to keep things separated like login informations (tenants), dashboard ("main" page with some links to different apps) and the apps itself in subdomains. I will explain myself with an example:

https://myapp.com -> Main site with information about the software and a link to login
|
|- User clicks in login and gets redirected
https://login.myapp.com -> Tenants information (simple app, probably with tenancy integrated to manage databases)
|
|- User logs in using his tenant account. After login, redirects user to myapp.com with UID stored somewhere, like in cookies
https://myapp.com -> Now shows the dashboard of the user. Access to the user/company specific database to show some info
|
|- User clicks in one of our apps to get redirected into the app
https://app1.myapp.com -> Loads as a site with all the information from that user/company specific database

Is there a way to communicate all these sites instead to have all the tenancy in a single app? I mean, I don't care if I have to install the tenancy package in all these sites to keep things in harmony and synced, but I don't know if that is possible. Probably all these sites will be in different servers and databases probably will be in AWS. Im still studying if this case is possible (talking only about tenancy and syncing as Im kinda new on it) and any suggestion will be appreciated.

Thanks in advance.

Br,
Diego.

**Comment by stancl** [comment]
Why would you want them to be separate apps? I can see why you'd want `myapp.com` to serve a landing page separately, but for everything else, if I understand correctly `login.myapp.com` and `app1.myapp.com` will just store stuff and do a redirect?

Also, if you want `myapp.com` to serve both the landing page and the app, you lose **all** of the benefits of having a landing page separately. Use `app.myapp.com`.

If you need further assistance - our Discord is the right place to ask support questions.

Thanks.
