### ISSUE TITLE
when asset_helper_tenancy is set to false, tenant_asset doesn't respect ASSET_URL config option as described in documentation

### ISSUE THREAD

**Issue by isaackearl** [archtechx/tenancy#508]
#### Describe the bug
I have an app that uses Livewire and Laravel Vapor for deployment.  I found that because of the way those packages internally use the asset() helper I had to disable the 'asset_helper_tenancy' configuration option in tenancy.php.  I then started using tenant_asset when I want to explicitly use a tenant specific asset... in the documentation it says 

> If config('app.asset_url') has been set, it will simply append tenant$id to the end of the configured asset URL. This is useful if you use Laravel Vapor

The behavior that I would expect would be that if I set asset_url, and I have the asset helper tenancy disabled, I would still be able to use tenant_asset() in order to take advantage of the asset_url configuration above... however it doesn't work.  

The actual result is that it appends the file to /tenancy/assets/<myfile> and routes it to the controller to handle it (asset_url is completely ignored while using tenant_asset in this case).

it's possible that I'm just confused about how this should work.  If so, then let me know and close this up.  Thanks

#### Steps to reproduce

1. set 'asset_helper_tenancy' to false
2. set asset_url to some url like 'http://myapp.test'
3. 
```
$tenant = Tenant::first();
tenancy()->initialize($tenant);

tenant_asset('file.txt');
```

the expected output would be http://myapp.test/tenant+tenantId/file.txt

but the actual output is http://myapp.test/tenancy/assets/file.txt

#### Your setup
 - Laravel version: v8.9.0
 - stancl/tenancy version: v3.2.1
 - Storage driver: local

**Comment by isaackearl** [comment]
So i realized I can make my own helper if I really want it to work that way.  This probably isn't that very critical/important.  To me it feels like it should work that way after reading the documentation, but I can also see the argument against it as well.

**Comment by stancl** [comment]
I'll change how the asset helpers work in v4

**Comment by masiorama** [comment]
Hi @isaackearl what would you do to implement the helper to make it work that way? I'm trying to achieve the same result and I'm still learning how things should be implemented the right way. Can you point me in the right direction? 
Thanks!

**Comment by stancl** [comment]
Closing this since the docs now mention that `tenant_asset()` always creates paths to the `TenantAssetController`. We'll add some option to make `tenant_asset()` generate paths that respect the `ASSET_URL` in v4.
