### ISSUE TITLE
Drop tenant databases

### ISSUE THREAD

**Issue by glupeksha** [archtechx/tenancy#509]
#### Description
A command to drop all tenant databases

#### Why this should be added
If I run php artisan migrate:fresh, then all the tables with links to databases will drop. So when I create a new tenant with the same name, it wont allow me because the database already existing. So it will be a lot easier if there is a command to delete all the tenant databases in the development environment

**Comment by ctf0** [comment]
add the below to cmnd and run it anytime u want to clear old dbs

```php
foreach (DB::select('SHOW DATABASES LIKE "tenant%"') as $db) {
    $db = array_values((array) $db)[0];

    DB::select("DROP DATABASE `$db`");
}
```
