### ISSUE TITLE
Auth Session visibility

### ISSUE THREAD

**Issue by alsahlawi** [archtechx/tenancy#510]
#### Case
This might not be a bug rather than concept understanding. I have used this package to create a multi-tenant app with single database tenancy in the app, where the SaaS provider manages the application by accessing `web.php` routes. In the other side I want my tenants will access their routes that lies in `tenant.php`. 
I am using path identification method for the tenants 'www.example.com/tenant'.

I have used Laravel/ui to publish auth view, controllers and middlewares and created the login at the central domain level. 

Now, I am having trouble when I authenticating a tenant user, and redirect him to his tenant path i.e. "www.example.com/user_tenant/dashboard", the Auth::user() is returning null. 

Note: at the tenant.php I am able to test this `Auth::loginUsingId(user_id)` and it is showing the authenticated user normally.

Last, the question is is this an issue with my concept or did I miss something here. 

####  routes/tenant.php
```
Route::group([
    'middleware' => ['web'],
    'prefix' => '/{vendor}',
    'middleware' => [InitializeTenancyByPath::class],
], function () {
    Route::get('/dashboard', function () {
        dd(Auth::user());
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });
```

for that, I am getting null.

**Comment by stancl** [comment]
If you need support, please use our Discord. GitHub is for tracking genuine bugs and this is making it noisy.

Your code never specifies the `auth` middleware, but you expect `Auth::user()` to work. How would it work when auth was not used? I suggest reading the Laravel auth docs.

Also, you're setting `'middleware'` twice in the array. Which overrides the value. See how PHP arrays work.
