### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is preseant on the requested resourc

### ISSUE THREAD

**Issue by kenytux** [archtechx/tenancy#513]
Hello,

I'm using "Tenancy" with subdomains. I've got this error when I'm getting data from subdomain and from my ftontend (Angular)

I'm using https://github.com/fruitcake/laravel-cors for the cors handling.

Thank you in advance

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. I'm afraid this is not a bug with the package, seems to be related to your setup. I may be wrong though, could you provide more information?

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks

**Comment by kenytux** [comment]
thank you @stancl 

After installation of fruitcake(Cors), 

I create a route in routes/tenant.php

```
Route::middleware([
    'cors',
    'web',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::get('/', function () {
        dd(\App\User::all());
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });
});
```

But there's still this error:

```
No 'Access-Control-Allow-Origin' header is preseant on the requested resourc
```
But for main domain is working, I've got the data
 ``

**Comment by kenytux** [comment]
Hello @stancl 

I also put in app/Kernel.php

```
    protected $middleware = [
        // \App\Http\Middleware\TrustHosts::class,
        \Fruitcake\Cors\HandleCors::class,

```

Any idea wil be welcome!

**Comment by stancl** [comment]
Hey. As I said - community support is handled on Discord.

**Comment by kenytux** [comment]
@stancl 

Thanks

**Comment by Mohammed-800** [comment]
@kenytux 
Do you found any solve?
