### ISSUE TITLE
Jobs subsequent to Jobs\CreateDatabase, doesn't respect tenany_create_database = false

### ISSUE THREAD

**Issue by tamkeen-tms** [archtechx/tenancy#514]
#### Describe the bug
In the TenancyServiceProvider, the job pipeline for "`Events\TenantCreated`" event is as follows:
```php
JobPipeline::make([
    Jobs\CreateDatabase::class,
    Jobs\MigrateDatabase::class,
    Jobs\SeedDatabase::class
]);
```
When `tenanct_create_database` set to FALSE (when adding a new tenant), the first event "`Jobs\CreateDatabase`" will skip database creation (as instructed in line 34 inside Jobs/CreateDatabase), but the following jobs wont respect this, the `MigrateDatabase` job will try to migrate the database (that wasn't created in the first place!)

#### Steps to reproduce
Create a new tenant with the internal key "tenanct_create_database" set to FALSE.

#### Expected behavior
The subsequent jobs (migration and seeding) should be skipped too, if the database creation itself was skipped.

#### Your setup
 - Laravel version:7.25.0
 - stancl/tenancy version: 3.1
 - Storage driver: DB

**Comment by lokreybe** [comment]
Hello @tamkeen-tms 
For solving it you have two options.
1. Inactive the Jobs\CreateDatabase::class, , Jobs\MigrateDatabase::class, and Jobs\SeedDatabase::class, from the TenancyServiceProvider.
2.  Edit the CreateDatabase class like this
`    public function handle(DatabaseManager $databaseManager)
    {
        event(new CreatingDatabase($this->tenant));

        if ($this->tenant->getInternal('create_database') !== false && config('tenancy.create_database') == true) {
            $databaseManager->ensureTenantCanBeCreated($this->tenant);
            $this->tenant->database()->makeCredentials();
            $this->tenant->database()->manager()->createDatabase($this->tenant);

            event(new DatabaseCreated($this->tenant));
        }
    }`

Edit in the MigrateDatabase::class 
`    public function handle()
    {

        if ($this->tenant->getInternal('migrate_after_creation') !== false && config('tenancy.migrate_after_creation') == true) {
            Artisan::call('tenants:migrate', [
                '--tenants' => [$this->tenant->getTenantKey()],
            ]);
        }
        
    }`

**Comment by stancl** [comment]
Thanks for reporting this.

Hmm, I don't like the idea of accessing `tenant_create_database` from the other jobs because that mixes things up too much. Maybe we could return `false` from the job and check for this in the pipeline?

**Comment by stancl** [comment]
Actually, that would need a small change because there might be a job unrelated to the DB. So you'd need two job pipelines

```php
Tenant\Created::class => [
    JobPipeline::make([
        Jobs\CreateDatabase::class,
        Jobs\MigrateDatabase::class,
        Jobs\SeedDatabase::class,
    ]),

    JobPipeline::make([
        CreateS3Bucket::class,
        SeedStorageWIthImages::class,
    ]),    
]
```

**Comment by stancl** [comment]
@tamkeen-tms can you try running `composer require stancl/tenancy:dev-terminating-pipelines`? does that fix it for you?

I'll add tests tomorrow, thanks!
