### ISSUE TITLE
Configuring VaporFile/VaporImage w/ Nova over Vapor

### ISSUE THREAD

**Issue by MikeCraig418** [archtechx/tenancy#516]
I was having some issues w/ Laravel Vapor and Nova. The overall setup was cake (Thanks Stancl!) but I noticed my file uploads were failing. I had trouble getting the User Policy to load. I created [this issue](https://github.com/laravel/nova-issues/issues/3001) but soon found out I needed some additional https://github.com/stancl/tenancy/ configuration.

**Solution:** 

Add `Route::post('/vapor/signed-storage-url', '\Laravel\Vapor\Http\Controllers\SignedStorageUrlController@store');` to the web portion of the tenant.php route file.

**~/routes/tenant.php**
```
Route::middleware([
    'web',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::get('/', function () {
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });

    Route::post('/vapor/signed-storage-url', 
        '\Laravel\Vapor\Http\Controllers\SignedStorageUrlController@store'); // 👈 Add this

});
```

Then simply create a **UserPolicy** w/ a uploadFiles() method, or create a Gate and add it to your AuthServiceProvider.

Ex:

```
        Gate::define('uploadFiles', function ($user, $post) {
            return true;
        });
```

Voila. Hopefully this helps someone save a few hours.

**Comment by nenads** [comment]
What do you do if you have file system separated and tmp is global ?

**Comment by MikeCraig418** [comment]
@nenads,

Currently there is one file system in s3. It holds the /tmp folder, and then moves the finalized file to the appropriate path within the same s3 bucket.

Assuming you are using a single s3 bucket, then I think it should just "work". 

What are you experiencing?

**Comment by bsormagec** [comment]
> @nenads,
> 
> Currently there is one file system in s3. It holds the /tmp folder, and then moves the finalized file to the appropriate path within the same s3 bucket.
> 
> Assuming you are using a single s3 bucket, then I think it should just "work".
> 
> What are you experiencing?

It can't handle tmp directory on my example @949mac it returns "File not found at path: tmp/51054911-b35a-415c-be9d-44970c78cd27" do you have any idea how to fix this ?

**Comment by pmreyes** [comment]
Hi @949mac,

Thanks for providing the configuration solution for Vapor! 
I'm also having the same issue of mentioned by @bsormagec "File not found at path: tmp/521......" Has anyone resolved this? I get this error message upon submitting the form.

I also checked in the s3 tenant/tmp folder that the image was correctly uploaded.
