### ISSUE TITLE
Identifying tenant in error views

### ISSUE THREAD

**Issue by zek** [archtechx/tenancy#518]
#### Describe the bug

I need two different 404 pages for both central & tenant. Somehow tenancy is not initialized for error pages such as 404, 500.

#### Your setup
 - Laravel version: 8
 - stancl/tenancy version: 3.2
 - Storage driver: DB

**Comment by zek** [comment]
My current workaround is as following:

I moved `InitializeTenancyByDomain` middleware from `routes/tenant.php` to global middleware in `Kernel.php` and it works. 

However this breaks central app.

**Comment by stancl** [comment]
https://laravel.com/docs/8.x/errors#custom-http-error-pages

I think you can either override the 404 error handling in `App\Exception\Handler` or use a single 404.blade.php file and @include the right file based on whether `tenancy()->initialized` is true or false.
