### ISSUE TITLE
add --path to tenants:run

### ISSUE THREAD

**Issue by Dontorpedo** [archtechx/tenancy#519]
#### Description
php artisan tenants:run migrate --path

i would like to run a specific migration like adding columns to a existing table for tenants.. but --path says:

`  The "--path" option does not exist.  
`

thanks

**Comment by stancl** [comment]
`tenants:run` usage is described in the docs.

And for running migrations, you shouldn't be using this. Specify the path in migration_paths config, or use `tenants:migrate --path`
