### ISSUE TITLE
can not use validation

### ISSUE THREAD

**Issue by shaahindeveloper** [archtechx/tenancy#520]
when i use validation in /pages/store , redirect to "/" route in tenant

```
$request->validate([
            'mobile' => 'required|unique:users',
        ]);
```

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks

**Comment by shaahindeveloper** [comment]
Thanks for answer , fixed

**Comment by henryeticom** [comment]
> Thanks for answer , fixed

How did you fix this please?
