### ISSUE TITLE
`--tenants` argument incorrectly defined to receive arrays

### ISSUE THREAD

**Issue by dylanharbour** [archtechx/tenancy#521]
Tenancy for Laravel docs refer to using multiple `--tenants=<...> ` options when running a command for multiple tenants explicitly: https://tenancyforlaravel.com/docs/v3/console-commands 

However, the command input is not defined correctly to receive arrays. 
https://laravel.com/docs/7.x/artisan#input-arrays
https://github.com/stancl/tenancy/blob/f273ed4f1eef3f036de4fb4052d39fb43ad45072/src/Commands/Run.php#L24

I'll create a PR to fix this, together with a [current] failing test

**Comment by stancl** [comment]
Why is that wrong? You do `--tenants=foo --tenants=bar`

**Comment by dylanharbour** [comment]
@stancl The `*` is missing, so Laravel does not expect multiple values (i.e. array input)
https://github.com/stancl/tenancy/pull/522

**Comment by stancl** [comment]
Ah, I see, thanks!

**Comment by ctf0** [comment]
@stancl can we make `--tenants=` accept multiple ids separated by `,` instead of writing it like `--tenants=foo --tenants=bar` which is not the standard for cli ?

**Comment by stancl** [comment]
`--tenants=foo --tenants=bar` is completely standard for the CLI.

We're not even using any custom feature, this is the artisan way to do it https://laravel.com/docs/8.x/artisan#input-arrays

**Comment by ctf0** [comment]
i meant [`php artisan queue:work --queue=high,default`](https://laravel.com/docs/8.x/queues#connections-vs-queues)

**Comment by stancl** [comment]
🤷🏻‍♂️  We use the standard way for custom commands to accept multiple argument values
