### ISSUE TITLE
When checking the existence of the tenant database with databaseExists() it fails

### ISSUE THREAD

**Issue by mindtrust** [archtechx/tenancy#523]
#### Describe the bug
I’m using PostgreSQL schema separation. I called the databaseExists() method. Naturally, the tenant database was created first.

$tenant->database()->manager()->databaseExists($database))

I faced with the following problem:

Stancl\Tenancy\Exceptions\TenantDatabaseDoesNotExistExceptionDatabase tenantfoo does not exist

#### Code fix
I found that the following modifications were needed.

PostgreSQLSchemaManager

public function databaseExists(string $name): bool
{
      return (bool) $this->database()->statement("SELECT schema_name FROM information_schema.schemata WHERE schema_name = '$name'");
}

#### Your setup
- Laravel 7.28.4
- stancl/tenancy version: 3.2.1
- PostgreSQL 11 schema separation

**Comment by rizkyarlin** [comment]
using `statement` will always return true

**Comment by rizkyarlin** [comment]
can you confirm that the schema is really existed by cli or db client app?

**Comment by mindtrust** [comment]
Yes, I confirm that the schema as the following cli. But the databaseExists('tenantfoo') returns that it doesn't exist.

```
# SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'tenantfoo';
 schema_name
-------------
 tenantfoo
(1 row)
```

**Comment by mindtrust** [comment]
I found the cause of the problem. When creating a tenant, it only happens when Queue is set to asynchronous, not when it is synchronous.

This will only happen if shouldBeQueued is true in TenancyServiceProvider, not if it's false.

TenancyServiceProvider
```
shouldBeQueued(true), // `false` by default, but you probably want to make this `true` for production.
```

This is because we made the tenant's database asynchronous, so databaseExists() is called before the database is created.

It only occurs in the following code under the following conditions: 

1) PostgreSQL schema separation
2) The above shouldBeQueued(true) 
3) If APP_ENV in .env is 'local'

This is caused by the following code

stancl/Bootstraps/DatabaseTenancyBootstrapper 
```   
 public function bootstrap(Tenant $tenant)
    {
        /** @var TenantWithDatabase $tenant */

        // Better debugging, but breaks cached lookup in prod
        if (app()->environment('local')) {
            $database = $tenant->database()->getName();
            if (!$tenant->database()->manager()->databaseExists($database)) {
                throw new TenantDatabaseDoesNotExistException($database);
            }
            // ddd($database);
        }

        $this->database->connectToTenant($tenant);
    }
```

**Comment by mindtrust** [comment]
I've found the cause and have closed it. Thank you !!
