### ISSUE TITLE
Customisable tenant ID column

### ISSUE THREAD

**Issue by kmcluckie** [archtechx/tenancy#524]
#### Description
Include in the tenancy config an option to customise the `BelongsToTenant::$tenantIdColumn` property.

#### Why this should be added
I am using an existing database that uses `organisation_id` as the tenant ID field. The `BelongsToTenant` trait has a hard-coded `$tenantIdColumn` property, which cannot be overridden in models which `use` the trait.

I have had to duplicate the `BelongsToTenant` trait in order to use `organisation_id` (as well as the `TenantScope` class also). This is not ideal as future updates to `BelongsToTenant` won't be reflected in my version. It would be good if this could be added as a config option.

And thanks for the package!

**Comment by stancl** [comment]
The reason why it's a public static property is so that you can do:

```php
// appserviceprovider

BelongsToTenant::$tenantIdColumn = 'organization_id';
```

in v3 I refactored a lot of config keys into static properties, because it makes the individual parts more self-contained

**Comment by kmcluckie** [comment]
Don't know why I didn't think of that! Thanks for the help.
