### ISSUE TITLE
Central routes without Route::domain() to allow for route names even when using multiple central domains

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#530]
#### Description

Scope central routes using another mechanism than `Route::domain()` to allow for using route names with multiple central domains.

#### Why this should be added

Right now only one central domain can be used when using route names for central routes (due to the change made to route SP [here](https://tenancyforlaravel.com/docs/v3/quickstart#central-routes))

**Comment by chrillep** [comment]
`->name("{$domain}.") ?`

**Comment by stancl** [comment]
Closing as we have a PR open for this in the v4 repo
