### ISSUE TITLE
rename column tenant_id to custom_id

### ISSUE THREAD

**Issue by kertahayu** [archtechx/tenancy#535]
Argument 1 passed to Stancl\Tenancy\Resolvers\Contracts\CachedTenantResolver::invalidateCache() must implement interface Stancl\Tenancy\Contracts\Tenant, null given, called in /Users/dele/Documents/GitHub/ad-meal/vendor/stancl/tenancy/src/Database/Concerns/InvalidatesTenantsResolverCache.php on line 29

I combine the tenant model with the affiliate model or the default is the user model.

I changed this tenant_id to affiliate_id. so are migrations.
```
    public function domains()
    {
        return $this->hasMany(config('tenancy.domain_model'), 'affiliate_id');
    }
```

when I run `migration --seed` I got the message.

I hope someone can help me solve this.

**Comment by stancl** [comment]
Are you using single DB tenancy?

**Comment by stancl** [comment]
When asking support questions using the "bug" issue template, please at least fill it out properly.

**Comment by kertahayu** [comment]
> Are you using single DB tenancy?

I don't use multi / single databases, I don't use databases for tenants. I only use the tenant model feature which is combined with the user model and the domain model only.

if the column names are not changed, everything works fine. default `tenant_id`.

the point is I just want to change the column names to match my other tables.

**Comment by stancl** [comment]
> I don't use multi / single databases, I don't use databases for tenants

Then you use single db tenancy.

You may have to change this https://github.com/stancl/tenancy/blob/b176481cdfa6cf07d7c8b1c648d0baeca4305dea/src/Database/Concerns/BelongsToTenant.php#L15
