### ISSUE TITLE
laravel translate file for every  tenancy

### ISSUE THREAD

**Issue by hizone** [archtechx/tenancy#539]
#### Description
**make a json laravel translate file for every tenancy
and commend to get auto translate tag from blade**

**Comment by stancl** [comment]
Can you elaborate?

Having a translate _file_ per tenant wouldn't be true multi-tenancy. Multi-tenancy shouldn't change your filesystem for a tenant.

Also, these things can be easily implemented yourself in a way that works for you. I'm not sure to what degree the package should be adding features that only a small amount of people need, and everyone needs implemented in a different way.
