### ISSUE TITLE
Getting 404 when trying to reach a model binded url

### ISSUE THREAD

**Issue by franckdpt** [archtechx/tenancy#545]
#### Describe the bug
I have a 404 when trying to reach an url with a model binding like "/contacts/{contact}/edit" with an ID for the binding.

#### Steps to reproduce
**I'm in tenant routes here.**
Route returning a 404 :
`Route::get('contacts/{contact}/edit')->name('contacts.edit')->uses('ContactsController@edit');`
url : ` /contacts/32/edit` is 404

FYI : 
`Route::get('contacts')->name('contacts')->uses('ContactsController@index');`
url : ` /contacts` is ok (200)

I tried to put that into the TenancyServiceProvider.php 's boot  : 
```
Route::bind('contact', function ($value) {
            dd(\App\Contact::all());
        });
```
=> Returning an empty collection. (Contacts table is not empty)
I'm pretty sure I missed something. I can't find what. Thanks for your help!

================

TenancyServiceProvider.php 's boot : 

```

public function boot()
{
        $this->bootEvents();
        $this->mapRoutes();
        $this->makeTenancyMiddlewareHighestPriority();

        \Stancl\Tenancy\Middleware\InitializeTenancyByDomain::$onFail = function () {
            return redirect(env('APP_URL'));
        };
}

```

RouteServiceProvider.php 's boot : 
```

public function boot()
    {
        parent::boot();
    }

```

#### Expected behavior
I expect to get a 200 response with the correct model object in my Controller.
Thanks a lot for your help

#### Your setup
 - Laravel version: [6.18.11]
 - stancl/tenancy version: [3.3.0]
 - Storage driver: [DB]
 - I use InertiaJS: [0.2.5]

**Comment by stancl** [comment]
Hey,

Thanks for bringing this to my attention. I think this is related to https://tenancyforlaravel.com/docs/v3/early-identification/

Assuming it is, route model binding is not and can't be supported. This should be documented, so I'm changing the label to `documentation`.

**Comment by franckdpt** [comment]
Thank you a lot for your response.
Actually I'm afraid to not understand how you don't get a 404 on the documentation example : 

Route::get('/post/{post}/edit', 'PostController@edit');
```

class PostController
{
    public function edit(Request $request, Post $post, Cloudinary $cloudinary)
    {
        if ($request->has('image')) {
            $post->image_url = $cloudinary->store($request->file('image'));
        }
    }
}

```
Did I miss something ?

**Comment by stancl** [comment]
I think that the page mentions that the code is just an example,  but yeah it shouldn't use model binding there either if it doesn't work.

Just use ids in the routes.

**Comment by franckdpt** [comment]
Thank you for your help.
For those who want a solution, this works : 

```

Route::get('contacts/{contact}/edit')->name('contacts.edit')->uses('ContactsController@edit');

public function edit($contact_id)
{
$contact = Contact::find($contact_id);

...
}

```

**Comment by listermatrix** [comment]
> I think that the page mentions that the code is just an example, but yeah it shouldn't use model binding there either if it doesn't work.
> 
> Just use ids in the routes.

i used id but still not working....**i used tenant identification by path**.  what i see happening is that when you pass a route paramter of $id it picks  the tenant prefix as parameter and pass it to the controller ...therefore the model search returns **null** 

Route::group(['prefix' => '/{**tenant**}', 'middleware' => [**InitializeTenancyByPath**::class,'auth']], function () {
.....

Route::resource('system_user', SystemUserController::class);

...

http://localhost:8000/admin/ **new** /system_user/ **7**

 public function show(Request $request,$id)
    {
        dd($id);
  $user = User::query()->find($id);
...........

so instead of passing the id of **7** to the controller its rather passing **new**.    the **new** is the prefix of the tenant


any help ??

**Comment by listermatrix** [comment]
> > I think that the page mentions that the code is just an example, but yeah it shouldn't use model binding there either if it doesn't work.
> > Just use ids in the routes.
> 
> i used id but still not working....**i used tenant identification by path**. what i see happening is that when you pass a route paramter of $id it picks the tenant prefix as parameter and pass it to the controller ...therefore the model search returns **null**
> 
> Route::group(['prefix' => '/{**tenant**}', 'middleware' => [**InitializeTenancyByPath**::class,'auth']], function () {
> .....
> 
> Route::resource('system_user', SystemUserController::class);
> 
> ...
> 
> http://localhost:8000/admin/ **new** /system_user/ **7**
> 
> public function show(Request $request,$id)
> {
> dd($id);
> $user = User::query()->find($id);
> ...........
> 
> so instead of passing the id of **7** to the controller its rather passing **new**. the **new** is the prefix of the tenant
> 
> any help ??

okay i fixed it by doing this 

1. Created a middle and removed the tenant parameter  in the request 
then I added it to the kernel.php 

<img width="661" alt="Screenshot 2021-04-05 at 2 51 18 AM" src="https://user-images.githubusercontent.com/29496455/113531991-cdd97100-95b9-11eb-9113-8819f1ac574d.png">
 now everything works fine

**Comment by tmsperera** [comment]
@stancl but route model binding works when testing.

**Comment by stancl** [comment]
v4 — https://github.com/stancl/tenancy/issues/652#issuecomment-841331170

**Comment by Jaspur** [comment]
@stancl is this issue solved that you closed it?

**Comment by stancl** [comment]
It will be fixed by the new approach added in v4.

**Comment by heshamabdallah** [comment]
I developed a very simple solution, you just need to ensure you initialized the tenancy before `SubstituteBindings` middleware. The `api` middleware group has the following middlewares:

```php
protected $middlewareGroups = [
    // Other middleware groups

    'api' => [
        'throttle:api',
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
    ],
];
```

## How to fix
1. Add a new `api-company` middleware group ( feel free to change it )
```php
protected $middlewareGroups = [
    // Other middleware groups

    'api' => [
        'throttle:api',
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
    ],

    'api-company' => [
        'throttle:api',

        /*
        |-----------------------------------------------------
        | Early identification issue
        |-----------------------------------------------------
        |
        | We need to initialize tenancy before subtituting bindings, we do this
        | to fix early model identification for the tenant models.
        | When `/products/{product}` is used, the `resolveRouteBinding` methods tries
        | to get the model from the central database because the tenant wasn't
        | initialized yet, that's why we need to initialize it first!
        |
        | @see: https://tenancyforlaravel.com/docs/v3/early-identification
        */

        \App\Http\Middleware\InitializeTenancyManuallyMiddleware::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
    ],
];
```

2. Add new middleware `InitializeTenancyManuallyMiddleware`
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class InitializeTenancyManuallyMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param  \Closure(\Illuminate\Http\Request): (\Illuminate\Http\Response)  $next
     * @return \Illuminate\Http\Response
     */
    public function handle(Request $request, Closure $next)
    {
        // Write your logic to initialize the tenant
        tenancy()->initialize($tenant);

        return $next($request);
    }
}
```

3. Wrap your tenant routes with the `api-company` 
- You can do that from the  `app/Providers/RouteServiceProvider.php` file
```php
/**
 * Define your route model bindings, pattern filters, and other route configuration.
 *
 * @return void
 */
public function boot()
{
    $this->configureRateLimiting();

    $this->routes(function () {
        Route::middleware('api-company')
            ->group(base_path('routes/company.php'));
    });
}
```
- Or you can wrap your tenant routes with a middleware group
```php

Route::middleware('api-company')->group(function () {
    //
});
```
