### ISSUE TITLE
Laravel Jetstream with Inertia tenants 302 to login

### ISSUE THREAD

**Issue by svenvanhees** [archtechx/tenancy#549]
#### Describe the bug
When using Jetstream with Inertia on the central and tenant domains, navigation to the user/profile pages results in a 302 redirect to /login. This only happens on the tenant routes, when using the central route, the navigation works just fine.

#### Steps to reproduce
**New laravel project:** `composer create-project --prefer-dist laravel/laravel .`
**All steps from:** `https://tenancyforlaravel.com/docs/v3/quickstart`
**Install Jetstream as per their documentation:**
`composer require laravel/jetstream`
`php artisan jetstream:install inertia`
`npm install && npm run dev`
`php artisan migrate`
`php artisan vendor:publish --tag=jetstream-views`
`npm run dev`

**All steps from:** `https://tenancyforlaravel.com/docs/v3/features/universal-routes/`

Add the universal and InitializeTenancyByDomain middleware to the  config/fortify.php
`'middleware' => [
        'web',
        'universal',
        InitializeTenancyByDomain::class
    ],`

Modify the routes/tenant.php to include the dashboard and auth:sanctum middleware.
```
Route::middleware([
    'web',
    'universal',
    'auth:sanctum',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::get('/dashboard', function () {
        return Inertia\Inertia::render('Dashboard');
    })->name('dashboard');
});
```

**Central Tenant**
Go to http://localhost/register and create an account.
It redirects to the dashboard.
Now use the top right profile dropdown to navigate to the users profile.
Every thing works..

**Foo Tenant**
Go to http://foo.localhost/register and create an account. It redirects to the dashboard and by dd(Auth::check()) it seems the user is authenticated.

Now use the top right profile dropdown to navigate to the users profile.

3 navigation events happen.
```
GET user/profile 302 FOUND
GET login 302 FOUND
GET dashboard 200 OK
```

It seems the user is not authorised to visit user/profile.

#### Expected behavior
I expect the authentication to work on the tenant, just as it does on the central domain, but can't seem to figure out how to solve it.

#### Your setup
 - Laravel version: 8.17.2
 - stancl/tenancy version: 3.4.0
 - Storage driver: DB
- Laravel/Jetstream version: 1.6.3

**Comment by svenvanhees** [comment]
Found a solution. Apparently, you can define a middleware stack inside the Laravel Jetstream configuration.

When I added this to the config/jetstream.php config file, the auth sessions working.

```
 'middleware' => [
        'web',
        'universal',
        InitializeTenancyByDomain::class
    ],
```

**Comment by maspireone** [comment]
Hi @svenvanhees 

Thank you for your sharing on the top. It gave me a good start point. However, I stuck in the middle that I cannot find a solution to. 

**Challenge:**
I tried to put the middleware without the universal. (I don't need login and register function in the central app)

**Setup**
I have tried to add middleware both in fortify.php and jetstream.php like you mentioned above.
'middleware' => [
        'web',
        InitializeTenancyByDomain::class
    ],

The following is my route in routes/tenant.php
Route::middleware([
    'web',
    'auth:sanctum',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::get('/dashboard', function () {
        return \Inertia\Inertia::render('Dashboard');
    })->name('dashboard');
});

**Error**
After login, I got "error 419" too many redirect between login and dashboard. (ERR_TOO_MANY_REDIRECTS)
Around 10 repetitive navigation events happen like the following

GET login 302 FOUND
GET dashboard 302 FOUND
GET login 302 FOUND
GET dashboard 302 FOUND
......

Would you mind to share your latest working setup? Do you put middleware in both fortify.php and jetstream.php?
Do I need to adjust anything else?

**Comment by maggz69** [comment]
@stancl This problem is still valid on projects making use of Jetstream and Fortify. This is even after adding the middleware stack in jetstream.php. 

The tenant tries to redirect to login on the central domains scope which (might) already have been authenticated and thus the central domain scope redirects back to login thus furthering the cycle of MANY_REDIRECTS.

**Comment by maggz69** [comment]
@maspireone  This was posted as a resolution to this problem on the discord chat. Linking it here as navigation in discord took me a while.

![image](https://user-images.githubusercontent.com/20341115/104853322-ba96fd80-5908-11eb-97a2-5d960f63b24d.png)

**Comment by maspireone** [comment]
@maggz69 Perfect. Thank you for sharing. I have stuck for a while. This is exactly what I am looking for. You save my day.

**Comment by mo3auya91** [comment]
> Found a solution. Apparently, you can define a middleware stack inside the Laravel Jetstream configuration.
> 
> When I added this to the config/jetstream.php config file, the auth sessions working.
> 
> ```
>  'middleware' => [
>         'web',
>         'universal',
>         InitializeTenancyByDomain::class
>     ],
> ```

I did the same thing you did, but still have the same problem
config/jetstream.php 
```
'middleware' => [
        'web',
        'universal',
        InitializeTenancyByDomain::class
    ],
```
config/fortify.php 
```
'middleware' => [
        'web',
        'universal',
        InitializeTenancyByDomain::class
    ],
```
config/tenancy.php
```
'features' => [
        // Stancl\Tenancy\Features\UserImpersonation::class,
        // Stancl\Tenancy\Features\TelescopeTags::class,
        Stancl\Tenancy\Features\UniversalRoutes::class,
        // Stancl\Tenancy\Features\TenantConfig::class, // https://tenancyforlaravel.com/docs/v3/features/tenant-config
        Stancl\Tenancy\Features\CrossDomainRedirect::class, // https://tenancyforlaravel.com/docs/v3/features/cross-domain-redirect
    ],
```

routes/tenant.php

```
Route::middleware([
    'web',
    'universal',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::get('/', function () {
        return Inertia::render('Welcome');
        //return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    })->name('welcome');

    Route::middleware(['auth:sanctum', 'verified'])
        ->get('/dashboard', function () {
            return Inertia::render('Dashboard');
        })->name('dashboard');
});

```

the problem is the user isa registred in the tenant database users table, but the `auth:sanctum` middleware has a poblem with redirecting.
this is how it looks in the console log
<img width="1440" alt="Screenshot 2021-01-22 at 14 21 21" src="https://user-images.githubusercontent.com/6853643/105490252-2ab4d300-5cbd-11eb-951b-cb6546ea8020.png">

**Comment by mo3auya91** [comment]
> @maspireone This was posted as a resolution to this problem on the discord chat. Linking it here as navigation in discord took me a while.
> 
> ![image](https://user-images.githubusercontent.com/20341115/104853322-ba96fd80-5908-11eb-97a2-5d960f63b24d.png)

@maggz69 @maspireone 
how did you solve this problem?
did you create diffrent model for tenant users? If so, how did you did that?
-------------------
**UPDATE**:
### problem solved by setting the session drive to **`redis`**

**Comment by karnash** [comment]
some solution.???

**Comment by stancl** [comment]
Jetstream will be supported in v4.

**Comment by zupolgec** [comment]
Managed to use Jetstream/Fortify with Tenancy v3

https://github.com/zupolgec/fortitenant

Main changes:
- set `['web', 'universal', InitializeTenancyByDomain::class]` as middlewares in both config/fortify.php and config/livewire.php (if using Livewire)
- added @jhoopes suggestion from https://github.com/archtechx/tenancy/issues/702, just customised and cleaned

**Comment by siva-20011** [comment]
this problem solution

step 1:
file: .env

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file //change this
SESSION_LIFETIME=120
SESSION_SECURE_COOKIE=false //Add this

step 2:
file: config/session.php

'driver' => env('SESSION_DRIVER', 'file'), //change this

**Comment by tahseen9** [comment]
TenancyServiceProvider should be loaded before fortify and jetstream

bootstrap/providers.php  (This file is automatically generated by Laravel, just change the sequence as below) 
return [
    App\Providers\TenancyServiceProvider::class,
    App\Providers\AppServiceProvider::class,
    App\Providers\FortifyServiceProvider::class,
    App\Providers\JetstreamServiceProvider::class,
];

I am using laravel 11.x with stancl/tenancy 3.8.3
