### ISSUE TITLE
Livewire: Invalid  Route Action

### ISSUE THREAD

**Issue by CNSam** [archtechx/tenancy#562]
#### Describe the bug
Laravel 8 instance returning:
> Invalid route action: [App\Http\Controllers\App\Http\Livewire\Something]. 

when navigating to a full-page Livewire component even though route is defined in tenant.php with Universal middleware. Route renders fine when in web.php

#### Steps to reproduce
1. Create a new livewire component
2. Add route param to tenant.php
3. Try to go navigate to tenant.php route
4. error presents itself.

#### Expected behavior
Livewire component should render and not throw respective error?

#### Your setup
 - Laravel version: 8.12.1
 - stancl/tenancy version:3.4

**Comment by CNSam** [comment]
Update: I believe this may have something to do with the Route::namespace set within TenancyServiceProvider.

As of Laravel 8 I believe the namespace defaults back to null in RouteServiceProvider line 29?

Changing it to null in TenancyServiceProvider now renders the component...

**Comment by stancl** [comment]
> I believe this may have something to do with the Route::namespace set within TenancyServiceProvider

Yeah, that's what the routes use.

**Comment by stancl** [comment]
I updated this in the core since the new syntax is probably more common now for new apps than the old one. Also added a static property to make things more understandable.
