### ISSUE TITLE
Tennancy domain not detected when accesed with www.

### ISSUE THREAD

**Issue by SebastianBotez** [archtechx/tenancy#563]
#### Describe the bug
I have created a store generator: main-domain.com and I registered a new domain https://domain.com pointed the nameservers, all good when we acces the domain with non www url.

If we try to access it by www like so, www.domain.com the package is not detecting it and redirects the user to main-domain.com

#### Expected behavior
It should load the store domain.com not redirect to main-domain.com

Any ideea how to fix this?
Thanks.

**Comment by stancl** [comment]
www.foo != foo

If you use both, create domain records for both

**Comment by travnettech** [comment]
@stancl I am having the same problem. When we add example.com and issue the certificate it works fine with the same domain. But www.example.com does not load the site (It shows 404 error). When I add www.example.com in the portal the domain load, but without SSL. Whenever I request SSL for the same domain, both sites (example.com and www.example.com) do not load. It shows a security issue.
