### ISSUE TITLE
whereIn with single-database tenancy overwrites tenacy scope

### ISSUE THREAD

**Issue by Reflic** [archtechx/tenancy#569]
#### Describe the bug
```
foreach ($days as $d) {
            $dbDates[] = $d->format('Y-m-d');
        }

        $data = Order::whereIn('date', [$dbDates])->get();
        dump($data);
```

When trying to get all orders with the date in *$dbDates* the query seems to be formed wrong...
![image](https://user-images.githubusercontent.com/1646074/102823699-b2b46e00-43db-11eb-9e27-34e231e989c8.png)

#### Steps to reproduce
1. Initalize the single database tenancy.
2. Try a whereIn Query on a model which belongs to tenant.

#### Expected behavior
I expect a correct query with right bindings. And not overwriting the tenancy scope with my provided date.

#### Your setup
 - Laravel version: 8.17.2
 - stancl/tenancy version: 3.4.0

**Comment by stancl** [comment]
https://github.com/stancl/tenancy/blob/3.x/src/Database/TenantScope.php#L20

It uses `where('tenant_id', tenant('id'))` basically. Are you sure you didn't make any changes to that logic? Such as the tenant primary key.
