### ISSUE TITLE
Livewire error with pagination

### ISSUE THREAD

**Issue by cavajr** [archtechx/tenancy#573]
#### Describe the bug
In the central domain environment, pagination works perfectly using the WithPagination trait;

But when entering the tenant, when changing pages one tries to connect to the database of the central domain instead of remaining in the database of the current tenant.

Displays the following error:
Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'toolconsig.bank' doesn't exist (SQL: select count(*) as aggregate from `bank`)

#### Expected behavior

Paging using the same connection as the current tenant.
Any solution to this problem?

#### Your setup
 - Laravel version: 7.29
 - stancl/tenancy version: 3.4.0

**Comment by stancl** [comment]
Hey. Thanks for reporting this.

Can you create a simple reproduction repository? I'd take a look at that.

Thanks!

**Comment by cavajr** [comment]
Hi.

First of all, thanks for responding quickly.

Below is the link to the repository https://github.com/cavajr/toolconfig-pagination

Thanks again

**Comment by stancl** [comment]
Why is the table `bank`?

You only have a [`banco` table](https://github.com/cavajr/toolconfig-pagination/blob/main/database/migrations/tenant/2020_12_29_091309_create_banco_table.php) and the [model uses it as well](https://github.com/cavajr/toolconfig-pagination/blob/main/app/Models/Banco.php#L11)

**Comment by cavajr** [comment]
Then perform the migrations and seeds. The tables of users and banks in the tenants will be created.

If you insert records in the 'banks' table, when you click the link to change the page you will see the error.

**Comment by stancl** [comment]
I'm asking about the table name though. The error says `bank` but you only have a `banco` table.

**Comment by cavajr** [comment]
The table's name is Bank. I started to implement a crud with this bank table in a tenant and this error occurred.

**Comment by stancl** [comment]
I don't get it. The code you sent doesn't have any table named `bank` and the error says that there's no table named `bank`.

How is the table not named `banco`? It's literally all over the code.

**Comment by cavajr** [comment]
Yes. In App/Models/Banco.php. In portuguese.

Sorry for my English.

**Comment by stancl** [comment]
I don't get what the problem is. If you have a _correct_ reproduction repo and a link to a Flare exception, I can take a look at it.

**Comment by keisto** [comment]
@cavajr I made my own tenant system, and I was looking here for a solution... anyways I figured it out.

You should just need to run `php artisan livewire:publish` and enter whichever tenant middleware that sets your database connection into the `middleware_group` in the `config/livewire.php`

Mine was `'middleware_group'  => ['web', 'tenant'],` and it works now!

**Comment by stancl** [comment]
https://tenancyforlaravel.com/docs/v3/integrations/livewire
