### ISSUE TITLE
filesystem.suffix_base not present on TenantCreated

### ISSUE THREAD

**Issue by johans** [archtechx/tenancy#574]
#### Describe the bug
I have  a value set for `filesystem.suffix_base` but it seems this has not been loaded when I use the example  `CreateFrameworkDirectoriesForTenant` on https://tenancyforlaravel.com/docs/v3/realtime-facades
It still uses the default "tentant" at this stage. Later when running the application `storage_path` returns the correct suffix_base from the config.

#### Steps to reproduce
Set a value for `filesystem.suffix_base`
Add `CreateFrameworkDirectoriesForTenant` to your `TenantCreated` job pipeline like shown on https://tenancyforlaravel.com/docs/v3/realtime-facades

#### Expected behavior
Should use the value from tenancy-config.

#### Your setup
 - Laravel version: 8.20.0
 - stancl/tenancy version: 3.4.0

**Comment by stancl** [comment]
> I have a value set for filesystem.suffix_base

What's the reason for that?

**Comment by johans** [comment]
Sorry, it works as expected. I was using an old tinker session.
