### ISSUE TITLE
Tenant is null in AppServiceProvider and AuthServiceProvider

### ISSUE THREAD

**Issue by rodrigoalexandrino** [archtechx/tenancy#575]
#### Describe the bug
Hello, I'm trying to use this package for an application with many databases.
I followed the documentation correctly, but I have a problem with the AppServiceProvider and AuthServiceProvider files.
The application does not identify the tenant and tries to query the central database, which does not contain any of the data

In the AppServiceProvider class, some variables are shared throughout the application and now it is not possible, since the tenant is null.
In the AuthServiceProvider class I cannot identify the user who is logged in, consequently his permissions.

#### Steps to reproduce
1. Configure for multiple databases
2. Try to access some information from the database in the AppServiceProvider or AuthServiceProvider classes

#### Expected behavior
The application should identify which tenant is being used and return the data correctly

#### Your setup
 - Laravel version: 8.30.0
 - stancl/tenancy version: 3.4

**Comment by stancl** [comment]
Not a bug, providers are executed before middleware, and as such, before the tenancy middleware.

Providers tell the app what middleware to use, so it wouldn't make sense for the tenant to be accessible in them.

If you need to use the tenant, use the `TenancyInitialized` event.

**Comment by rodrigoalexandrino** [comment]
Got it, thanks for the explanation.
@stancl In that case can you tell me how do I use these variables that are globally shared in the application? (AppServiceProvider)
`
view()->share('calendario', Instituicao::find(1)->calendario);
`

And in the case of AuthServiceProvider, how can I identify the tenant?

`

public function boot()
    {
        $this->registerPolicies();
            $permissions = Permission::with('roles')->get();
            foreach ($permissions as $permission) {
                Gate::define($permission->nome, function (User $user) use ($permission) {
                    return $user->acesso_admin ? true : $user->hasPermission($permission);
                });
            }
            Gate::before(function (User $user, $ability) {
                if ($user->hasAnyHoles('adm')) {
                    return true;
                }
            });
    }

`

**Comment by ctf0** [comment]
@rodrigoalexandrino try https://tenancyforlaravel.com/docs/v3/event-system/#tenancy

> You want to use the bootstrapped event if you want to execute something after the app has been transitioned to the tenant context
