### ISSUE TITLE
Return value of Stancl\Tenancy\Resolvers\DomainTenantResolver::resolveWithoutCache() must implement interface Stancl\Tenancy\Contracts\Tenant, null returned

### ISSUE THREAD

**Issue by ctf0** [archtechx/tenancy#580]
#### Describe the bug

this started to happen when i added `['web', 'universal', 'InitializeTenancyBySubdomain']` to the auth routes.
if i used only `web` it works but after auth i either get
>  - a loop of redirection between login & dashboard which have the middlewares of `['web', 'universal', 'InitializeTenancyBySubdomain', 'auth']` because now the session is saved under central db not the tenant
>  - or remove `InitializeTenancyBySubdomain` from dashboard route & redirect correctly but get error of not found db table, because the applied context is central not tenant

- tenant model

```php
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\Concerns\HasDomains;
use Stancl\Tenancy\Database\Concerns\HasDatabase;
use Stancl\Tenancy\Database\Concerns\MaintenanceMode;
use Stancl\Tenancy\Database\Models\Tenant as BaseTenant;

class Tenant extends BaseTenant implements TenantWithDatabase
{
    use HasDatabase,
        HasDomains,
        MaintenanceMode;
}
```

- current config

```php
<?php

declare(strict_types = 1);

use Modules\Tenant\Model\Domain;
use Modules\Tenant\Model\Tenant;

return [
    'tenant_model' => Tenant::class,
    'id_generator' => Stancl\Tenancy\UUIDGenerator::class,
    'domain_model' => Domain::class,

    'central_domains' => [
        env('APP_DOMAIN'), // abc.test
    ],
   
    'bootstrappers' => [
        Stancl\Tenancy\Bootstrappers\DatabaseTenancyBootstrapper::class,
        Stancl\Tenancy\Bootstrappers\CacheTenancyBootstrapper::class,
        Stancl\Tenancy\Bootstrappers\FilesystemTenancyBootstrapper::class,
        Stancl\Tenancy\Bootstrappers\QueueTenancyBootstrapper::class,
        Stancl\Tenancy\Bootstrappers\RedisTenancyBootstrapper::class,
    ],

    // ...

    'features' => [
        Stancl\Tenancy\Features\UserImpersonation::class,
        Stancl\Tenancy\Features\UniversalRoutes::class,
        Stancl\Tenancy\Features\CrossDomainRedirect::class,
    ],
];
```

#### Steps to reproduce

- create a universal `auth & dashboard` routes that works in both central & tenant context
- use session db driver & migrate the table for both 
- add the middlewares `['web', 'universal', 'InitializeTenancyBySubdomain']` for both (+ `auth` for dashboard)
- create a demo table with some data on tenant side to test the db context after login
  - we can use something like below to differ the data fetch between central and tenant
    ```php
    protected function isCentralDomain()
    {
        return in_array(request()->getHost(), config('tenancy.central_domains', []));
    }
    ```
- now u should get one of the 3 errors mentioned above

#### Expected behavior

login should work according to the host as expected

#### Your setup

- Laravel version: [e.g. 8.2.0] **8.22.1**
- stancl/tenancy version: [e.g. 3.1.0] **v3.4.0**

**Comment by stancl** [comment]
What's `'InitializeTenancyBySubdomain'`? Why is it a string?

**Comment by ctf0** [comment]
**update**

changing the domain name to the full host name `bla.abc.test` got me past the auth but now am stuck at the app not using the tenant context and showing error of `cant find db table`

**Comment by ctf0** [comment]
> What's 'InitializeTenancyBySubdomain'? Why is it a string?

```php
'InitializeTenancyBySubdomain' => \Stancl\Tenancy\Middleware\InitializeTenancyBySubdomain::class,
```
& its string because am using it in several middlewars

**Comment by stancl** [comment]
This seems like a usage issue because you're trying to implement auth which is a complex feature. If you could make a minimal reproducible example that shows exactly what in the tenancy package works differently than expected, I could take a look at that.

**Comment by ctf0** [comment]
why closed ? what about the pkg not applying the tenant context ?

**Comment by ctf0** [comment]
finally solved it.

for anyone who also got this issue.

1. using `InitializeTenancyBySubdomain` wont work as expected, not sure why yet.
2. use `InitializeTenancyByDomain` instead & make sure the domain name in the db is saved as full host name ex`bbb.abc.test`
3. make sure the `InitializeTenancyByDomain` mw comes after `web` directly so the tenant context is applied as early as possible.
4. for any route that is going to be universal, use `['web', 'universal', 'InitializeTenancyByDomain']` for mw
    - `web` if we need sessions (aka.not api)
    - `universal` to bypass the next `InitializeTenancyByDomain` mw error of not being on a tenant uri
    - `InitializeTenancyByDomain` to apply the tenant context (if we are under one)

5. to fix wrong tenant uri not firing exception, [docs](https://tenancyforlaravel.com/docs/v3/features/universal-routes/#universal-routes)
    - comment out `Stancl\Tenancy\Features\UniversalRoutes::class,`
    - under `TenancyServiceProvider@boot` add
      ```php
      \Stancl\Tenancy\Middleware\InitializeTenancyByDomain::$onFail = function ($exception, $request, $next) {
          return (new UniversalRoutes())->routeHasMiddleware($request->route(), 'universal') && $this->isCentralDomain()
              ? $next($request)
              : abort(404, $exception->getMessage());
      };
      ```

now the app will work as expected without much changes to the routes or actions, simply use 
```php
protected function isCentralDomain()
{
    return in_array(request()->getHost(), config('tenancy.central_domains', []));
}
```

in any action that is going to serve both tenant & central to show different logic/views/etc... ex.`auth controller`
