### ISSUE TITLE
have bug in migration central domain upgrade "doctrine/dbal": "^2.10",

### ISSUE THREAD

**Issue by vahidalvandi** [archtechx/tenancy#586]
#### Describe the bug
please upgrade "doctrine/dbal": "^2.10"
to
`"doctrine/dbal": "^3.0" `
 Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

#### Your setup
 - Laravel version: [e.g. 8.2.0]
 - stancl/tenancy version: [e.g. 3.1.0]

**Comment by stancl** [comment]
Okay, this is a permanent ban.

https://github.com/stancl/tenancy/issues/587#issuecomment-762431830
