### ISSUE TITLE
multi path in migration

### ISSUE THREAD

**Issue by vahidalvandi** [archtechx/tenancy#587]
i have multi database path 
in config do i can set multi path like bellow

    'migration_parameters' => [
        '--force' => true, // This needs to be true to run migrations in production.
        '--path' => [database_path('migrations/tenant'),base_path('vendor/xcf/base/src/database/migrations')],
        '--realpath' => true,
    ],

**Comment by stancl** [comment]
Please don't spam this repository with issues that:
- don't follow issue templates
- deceptively use the wrong template (e.g. asking a support question as a bug report)

Next time I'm issuing a block.
