### ISSUE TITLE
have bug in web Group middleware

### ISSUE THREAD

**Issue by webactor724** [archtechx/tenancy#591]
#### Describe the bug
hello
I had already made a package  it contain multi middleware like bellow after i configure laravel with subdomain all thing is good but this define to web group is not work 

` app('router')->pushMiddlewareToGroup('web', \mymodule\base\http\middleware\setLocale::class);
`
 but this work fine

` app('router')->aliasMiddleware('FaNumToEn',\mymodule\base\http\middleware\FaNumToEn::class);
`

#### Your setup
 - Laravel version: 7
 - stancl/tenancy version: 3.4.1

**Comment by stancl** [comment]
Doesn't seem related to the package. If you can show how the tenancy package is breaking this, I can reopen.

**Comment by webactor724** [comment]
i dont now how this package breaking this , if you add this in boot AppProvider You see it does not work 

app('router')->pushMiddlewareToGroup('web', \mymodule\base\http\middleware\setLocale::class);
