### ISSUE TITLE
When deleting a tenant with a single database throws an exception

### ISSUE THREAD

**Issue by khatabwedaa** [archtechx/tenancy#596]
#### Describe the bug
When deleting a tenant with a single database throws an exception, it deletes the tenant and throws this exception.

![Screenshot from 2021-01-31 20-20-31](https://user-images.githubusercontent.com/38974561/106393895-3c575280-6402-11eb-9bad-fcbacce98552.png)

#### Steps to reproduce
I configured the pack as a single database setup and this how I delete my tenant.
```php
public function destroy(Tenant $tenant)
{
    $tenant->domains()->delete();

    $tenant->delete();
    
    session()->flash('success', 'Deleted');

    return redirect()->route('tenants.index');
}
```

#### Your setup
 - Laravel version: [e.g. 8.12.0]
 - stancl/tenancy version: [e.g. 3.4.0]

**Comment by stancl** [comment]
Remove the job that deletes tenant databases from the job pipeline that listens to TenantDeleted in EventServiceProvider
