### ISSUE TITLE
flysystem-aws-s3-v3

### ISSUE THREAD

**Issue by serdartaylan** [archtechx/tenancy#597]
#### Describe the bug
It is necessary to use flysystem-aws-s3-v3 v2.x.
however, stancl / tenancy dependencies include flysystem-aws-s3-v3 "~ 1.0"

#### Expected behavior
composer.json update "league/flysystem-aws-s3-v3": "^2.0",

#### Your setup
 - Laravel version: [e.g. 8.0]
 - stancl/tenancy version: [e.g. 3.2]

**Comment by stancl** [comment]
Are you sure? It's in dev dependencies, I don't think that should interfere with your dependencies
