### ISSUE TITLE
Laravel User Authentication In Tenant

### ISSUE THREAD

**Issue by fazalm13** [archtechx/tenancy#602]
I'm able to login from the central app but not able to login from the tenant app in my local.
My tenant login page shows the following error:

**Target class [Auth\LoginController] does not exist.**

I have also configured the universal setting from the documentation: https://tenancyforlaravel.com/docs/v3/features/universal-routes
Also read the issue: #427  
Following Is my tenant route code with the help of the above links:
```
Route::group(['middleware'=>['web',InitializeTenancyByDomain::class,PreventAccessFromCentralDomains::class]
],function () {
	Route::middleware(['universal'])->group(function () {
	    Auth::routes();
	});
	
	Route::middleware(['auth'])->group(function () {
	    Route::get('/', function () {
	        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
	    });
	});
});
```

#### Your setup
 - Laravel version: [6.2.0]
 - stancl/tenancy version: [3.1.0]

**Comment by stancl** [comment]
That's not a bug with the package but a broken import/wrong route namespace/some such thing. "Target class ... does not exist" is a PHP error.

**Comment by fazalm13** [comment]
Yes exactly but then why is it working for the central app and just giving error on the tenant app?
