### ISSUE TITLE
Database connection [tenant] not configured

### ISSUE THREAD

**Issue by aronquiray** [archtechx/tenancy#606]
#### Describe the bug
What seems to be the problem:
I’m using tenancyforlaravel (with multiple database).
Fetching of data doesn’t have any problem. Loading it via livewire components does work.
But whenever I add the
wire:click=""
I noticed that on the tenant side, it uses a “tenant” connection instead of “central”

I can load the products correctly on tenants subdomain, but whenever I click the button with livewire on it. 
![Screenshot_899](https://user-images.githubusercontent.com/13714092/109432945-a5a1a400-7a48-11eb-857b-b3d49e56c70c.png)

#### Steps to Reproduce:
Basic setup of tenancyforlaravel
added the basic “counter” functionality" of livewire on docs (just for a test)

Are you using the latest version of Livewire: yes
![Screenshot_897](https://user-images.githubusercontent.com/13714092/109432887-58bdcd80-7a48-11eb-9ecd-8f2c0008bcc6.png)

#### Expected behavior
Expected behavior should just fire the increment of livewire.

#### Your setup
 - Laravel version: Latest
 - stancl/tenancy version: Latest

**Comment by stancl** [comment]
> I noticed that on the tenant side, **it uses a “tenant” connection** instead of “central”
> 
> I can load the products correctly **on tenants subdomain**, but whenever I click the button with livewire on it.

So what's the issue?

**Comment by aronquiray** [comment]
Not sure if this is an issue or a misconfiguration of mine. 
whenever I fire the wire:click of livewire. 
it's looking for a "tenant" template db instead of automatically looking it via "central" database.

**Comment by stancl** [comment]
Why would it look for central if you're on a tenant domain?

**Comment by aronquiray** [comment]
https://user-images.githubusercontent.com/13714092/109433377-f914f180-7a4a-11eb-93bd-03bde4732ef9.mp4

**Comment by aronquiray** [comment]
not really sure why that is happening. all the products came from correct db though.

**Comment by stancl** [comment]
> Steps to Reproduce:
> Basic setup of tenancyforlaravel
> added the basic “counter” functionality" of livewire on docs (just for a test)

Seems like you haven't followed our docs for configuring Livewire 

> not really sure why that is happening. all the products came from correct db though.

The first render is not handled by Livewire, only subsequent actions are. So your Livewire is broken, not just a part of it. Again, likely you didn't do the steps to configure it for tenancy

**Comment by aronquiray** [comment]
oh! I get it now. sorry. there was a configuration for livewire. works now. thanks.

**Comment by cardentey** [comment]
> oh! I get it now. sorry. there was a configuration for livewire. works now. thanks.

I have the same error, can you tell me how you solved it?
Thank you.

**Comment by aronquiray** [comment]
> > oh! I get it now. sorry. there was a configuration for livewire. works now. thanks.
> 
> I have the same error, can you tell me how you solved it? Thank you.

I think this is having the "universal" enabled. 
and the tenancy config. 

completely forgot this bro as i dont encounter this since
