### ISSUE TITLE
Unexpected T_STRING error on fresh install

### ISSUE THREAD

**Issue by AbrahamBrookes** [archtechx/tenancy#607]
#### Describe the bug
I am running though the quick start guide and have required the package and installed via artisan. When I run `php artisan migrate` I get a `syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)` in TenancyServiceProvider.php line 19:

```
class TenancyServiceProvider extends ServiceProvider
{
    // By default, no namespace is used to support the callable array syntax.
    public static string $controllerNamespace = '';
                  ^^^^^^
```
I am running PHP 7.3.22 in a docker container. Is that syntax just incompatible with my PHP version?

#### Steps to reproduce
`composer require stancl/tenancy`
`php artisan tenancy:install`
`php artisan migrate`

#### Expected behavior
I expect the migrations to run

#### Your setup
 - Laravel version: 6.18.5
 - stancl/tenancy version: ^3.4

**Comment by stancl** [comment]
Yeah, that code requires PHP 7.4

Either remove the type hint or upgrade (preferable).

**Comment by isaacdarcilla** [comment]
```
In TenancyServiceProvider.php line 19:

  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)  

```

I have the same error, I'm using Laravel 8 and PHP7.4
