### ISSUE TITLE
Cannot run PHPUnit tests - lack of info?

### ISSUE THREAD

**Issue by cecilymiller** [archtechx/tenancy#609]
#### Describe the bug
Cannot run PHPUnit tests.
`Database already exists`

I think the main problem here is the lack of info in the docs

#### Steps to reproduce
Install new laravel project & tenancy package

#### Expected behavior
Should be able to run tests.
I've read https://sponsors.tenancyforlaravel.com/frictionless-testing-setup as well and using the setup

#### Your setup
 - Laravel version: 8.30.1
 - stancl/tenancy version: 3.4.1

Testing env
```
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=project
```

`TenantTestCase` & `TestCase` files identical with https://sponsors.tenancyforlaravel.com/frictionless-testing-setup

**Example test**
```
<?php

namespace Tests\Feature;

use App\Models\User;
use Tests\TenantTestCase;

class ExampleTest extends TenantTestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $this->assertCount(0, User::all());
        User::factory()->create();
        $this->assertCount(1, User::all());
    }
}
```

**Error**
`Tenant cannot be created. Reason: Database test_tenantid already exists.`

**Comment by cecilymiller** [comment]
@stancl Can you update the docs and/or provide a simple (working) test example? Behind a paywall, if you prefer.

No offense (I appreciate your work), but is it kinda ironic that in the docs, where you compare your package against others, you highlight "Very high testability" - while the package cannot run tests out of the box / no docs for working tests setup?

I'm not saying the package is not testable, but a working example would be appreciated.

**Comment by stancl** [comment]
How does the described setup not work? The boilerplate uses exactly the described setup and there are no issues with it.

> Database test_tenantid already exists

Are you cleaning up your databases? In boilerplate tests we don't use pre-made databases, we create databases as needed in the tests. With random names.

**Comment by cecilymiller** [comment]
Thanks for your response!

> In boilerplate tests we don't use pre-made databases, we create databases as needed in the tests. With random names.

Where does this happen?

I can't find anything like that from:
https://tenancyforlaravel.com/docs/v3/testing
https://sponsors.tenancyforlaravel.com/frictionless-testing-setup

Also, the setup is identical to the docs. Expect traits (I think), since the docs do not show which one is used.

Traits used:
`DatabaseMigrations` on the `TenantTestCase` &
`CreatesApplication` + `RefreshDatabase` (tried with & without) on the `TestCase`


Hmm, feels like I'm missing something obvious here

**Comment by stancl** [comment]
<img width="470" alt="Screen Shot 2021-03-09 at 13 12 08" src="https://user-images.githubusercontent.com/33033094/110468803-1300a500-80d9-11eb-9d34-911c49a73db1.png">

<img width="524" alt="Screen Shot 2021-03-09 at 13 11 08" src="https://user-images.githubusercontent.com/33033094/110468811-1562ff00-80d9-11eb-85e9-daa3e447c5d1.png">

<img width="512" alt="Screen Shot 2021-03-09 at 13 10 51" src="https://user-images.githubusercontent.com/33033094/110468820-198f1c80-80d9-11eb-9030-d3acb585b0d8.png">

Seems like we use the traits for central tests and no traits for tenant tests

**Comment by cecilymiller** [comment]
@stancl  Makes no difference.

1) https://sponsors.tenancyforlaravel.com/frictionless-testing-setup has `DatabaseMigrations` on `TenantTestCase` class

2) When a tenant is created using the `createTenant` method in `TestCase` - `TenantCreated` event is triggered that causes the database creation etc - and since the database is not cleaned anywhere, the app tries to create a database that already exists.

All of my own solutions has been **very** slow ~2 seconds per test - I was hoping you could share a simplest example to make it work with MySQL or sqlite with a decent speed

**createTenant method**
```
protected function createTenant(array $data = [], string $domain = null, bool $createStriperCustomer = null): Tenant
    {
        $tenant = Tenant::create(array_merge([
            'id' => 'uniq-id',
        ], $data));

        $tenant->domains()->create(['domain' => $domain ?? 'domain.test']);

        return $tenant;
    }
```

**NOTE:**
I've followed https://sponsors.tenancyforlaravel.com/frictionless-testing-setup - is it outdated?

>  In boilerplate tests we don't use pre-made databases, we create databases as needed in the tests. With random names.

I guess the `createTenant` uses random string as a `id` then? Also, do you mean by `In boilerplate tests` the pointed docs?

**Comment by cecilymiller** [comment]
If a random string is used as an ID, how the DB cleaning is handled?

Also, why this is not included in the docs? Not even the one behind the paywall? Looks like the `frictionless testing setup` is not that frictionless after all :grin:

**Comment by cecilymiller** [comment]
Maybe I'm ruined by spoon-feeding type-of-docs like Laravel's official docs and can't figure things out on my own if the docs missing critical parts.

Anyway, I'm just looking for a solution to run my tests faster and was hoping for an example 🙏

**Comment by Zboru** [comment]
@cecilymiller can you share your TestCase and TenantTestCase file, im fighting kinda similar problem, maybe we can solve it together.

**Comment by stancl** [comment]
Did you customize your tenant logic in any way or are you using a fresh install?

Your error is:

> Database test_tenantid already exists

The docs mention using `test_tenant` as the DB name prefix. If the error in your case is `test_tenantid` then it means that you're creating a tenant with an id of `'id'`. Why? Can you post your `CreateTenantAction` class?

**Comment by cecilymiller** [comment]
@stancl Thanks for getting back!

I don't have `CreateTenantAction` class - in the docs, it says

> So in your case, call Tenant::create() and anything else that your app needs

You can see my `createTenant` method above.

I did pass in a tenant ID and that caused the existed DB error, so now the error is gone but it never cleans up the DB so it creates a new DB on each test. The previous DB would be good to delete.

Below is numbered list of Qs to keep questions/answers more organized.

1) Should I do the DB deletion on my own? - If so, can you share an example

2) Do you use MySQL, sqlite, or something else?

3) Do you use custom DB settings to run it faster, perhaps? E.g is SQLite with :memory: DB ideal?


I know DB driver/settings vary a lot between projects but examples would be highly appreciated

**Comment by stancl** [comment]
> You can see my createTenant method above

It specifies a tenant id, and as the docs say, databases are created based on the tenant id. So when you're getting an error saying that the database already exists, it means this.

1. If you want. Or you can use sqlite w/ .gitignore, tmpfs docker containers, or you can have pre-made databases.
2. Up to you
3. See the tmpfs example

**Comment by cecilymiller** [comment]
@stancl and where can I find this `tmpfs` example?

**Comment by stancl** [comment]
search in the issues and discussions for that, it was discussed I believe

**Comment by cecilymiller** [comment]
@stancl Any chance to update the docs to cover cleaning the database?

Now I handle the database deletion on my own but when running close to 100 tests, it throws `failed to open stream: Too many open files`, I'm using `:memory:` env variable, but it still uses files on SQLite, it seems.

I follow the sponsored docs on the testing setup. But on top of that, I have this `tearDown` method in `TenantTestCase` class

```php
protected function tearDown(): void
{
    parent::tearDown(); // TODO: Change the autogenerated stub

    (new SQLiteDatabaseManager)->deleteDatabase($this->tenant);
}
```

As far as I understood, it is possible to use :memory: sqlite, right?

**Comment by stancl** [comment]
You can't use :memory:, I think that's mentioned in the docs

**Comment by cecilymiller** [comment]
@stancl Hmm, yes you're right. On my current setup, the tenant connection uses a file but the central used the memory DB - interestingly enough, it works fine. However, is there something I should be aware of? For example, issues when using `:memory:` for central DB, but file for tenants?
