### ISSUE TITLE
Tenancy documentation and can it do the requested

### ISSUE THREAD

**Issue by moneya** [archtechx/tenancy#61]
@stancl 
I stumbled upon your blog post, I will say i am really impressed by your package, I would say it remove 99% time meant for the development of multi-tenancy app.
But i hit a  snag because i could not get the complete documentation.
I would love it if you could write more tutorials on how to build a panel/control dashboard to create, delete and suspend a tenant app.
Preferably continuing from your  [Tutorial](https://stancl.github.io/blog/how-to-make-any-laravel-app-multi-tenant-in-5-minutes/).
I have an app which i am working which allow user's to send emails On the free plan and Limited number of  SMS on the pro plan.
Currently i use hard coded variables for that. Something like  this in my controller 
 `$use_sms = true;
if($use_sms === true){
//Function to send SMS
}`
How do i do such using your package..

Thanks.
**Moneya**

**Comment by stancl** [comment]
Hi. If I understand your question correctly, you're asking about how to store data about tenants, such as whether their plan includes the ability to send SMS?

I think you're looking for `tenancy()->set()` and `tenancy()->get()`. [This part](https://github.com/stancl/tenancy#storing-custom-data) of the documentation covers that.

In your registration process, when creating a tenant, you could do something like this:

```php
$uuid = tenant()->create('example.domain');
tenancy()->put('plan', 'free', $uuid);
```

And then, in your controller, this:

```php
if (tenancy()->get('plan') === 'free') {
   $use_sms = false;
}

// ...

if ($use_sms) {
    // send SMS
}
```

Thanks for the feedback. I will add more real-life examples to the documentation and write a few more practical tutorials.

**Comment by moneya** [comment]
Thanks for your prompt reply.
I still have some more questions.
In my former web.php route file, i use some function from my DB.
$domain = config('site.domain');
$client = App\Client::where('name',$doman)->first();
To make some routes accessible based the client status.
i use the below codes
`if($client->status === 'active'){
//Show the allowed active routes
}
elseif($client->status === 'suspended'){
// Allow routes only
}
`
Using your package now, how do i use it in the tenants.php routes.

And in my controller called DashboardController.php Which i want to use for Tenants CRUD (For creating tenants , update and delete) Which will also work as the master dashboard.... 

At the TOP of the Controller where we add class we use with our controllers (Model, Packages) check the Image below for what i meant.
`use App\User;`
![image](https://user-images.githubusercontent.com/7353773/60807059-90457b00-a17c-11e9-9149-f9ef82faccb9.png)
Then we go to our public function and use our users model like this 
` public function index()
    {
   $users = User::all();
}`
How do i use your php package in Controller.
Do i go direct in my Controller

` public function index()
    {
   $tenants = tenant()->all();
}`


Thanks for your support.
**Moneya**

**Comment by stancl** [comment]
> To make some routes accessible based the client status.

This logic shouldn't be done in the routes file.

Put all the tenant routes in `tenant.php` and your tenant CRUD routes into `web.php`. If you want to allow only some tenants to access a certain route, I recommend doing that in the controllers, i.e.

```php
// some controller method
if (tenant()->get('status') === 'suspended') { // alternatively, tenant('status') === 'suspended'
    return redirect()->route('home')->with('error', 'This page is not available, because your account is suspended.');
}

// ...
```

`AppServiceProvider::boot()` could also work for this, but I'm not sure if you can access `tenancy()` in there.

> `public function index() { $tenants = tenant()->all(); }`

Yes, that's the correct way to get all tenants. Note that it doesn't return User models, but arrays with data about tenants -- there's an example in the README.

**Comment by moneya** [comment]
Once again thanks for your prompt reply..
How do i get all blog posts of all clients in my dashboard for example 
here is what i am think of doing..
`
// for all posts from all tenents
$posts = Post::all()->orderBy('created_at', 'desc')->toArray();
//so to get all posts from all tenents
$tenants = tenant($posts)->all();
//for all posts from a single tenent.
$posts = Post::all()->orderBy('created_at', 'desc')->toArray();
//get all posts from a single tenent with uuid (dbe0b330-1a6e-11e9-b4c3-354da4b4f339).
tenant($posts)->getTenantById('dbe0b330-1a6e-11e9-b4c3-354da4b4f339');
`
Is this the right way?
Thanks 
**Moneya**

**Comment by stancl** [comment]
Trying to get all blog posts of all clients is hard with multi-database tenancy. If you need to do a lot of stuff similar to this, consider the single-database model instead.

In your dashboard, you're connected to your central, non-tenant database. The posts for each tenant are stored in his database.

If you really need to do this, you can do this:

```php
// get list of all tenants
$tenants = tenant()->all();

$posts = [];
foreach ($tenants as $tenant) {
    // initialize tenany for each tenant
    tenancy()->init($tenant['domain']);
    $posts[] = Post::all();
}

// tenancy()->disconnectDatabase(); // READ NOTE BELOW
```

Few things:
1. If you do many things like this, use a single database setup.
2. If you don't use a single database setup, **cache the result**.
3. The last line of my snippet shows `tenancy()->disconnectDatabase()`. This will switch the database back to the central, non-tenant database. **However**, this will not switch the Redis, cache and filesystem back. I will add that functionality in the next minor release.

**Comment by moneya** [comment]
Thanks bro, You are the best...  💯  👍  🥇 .
**If you do many things like this, use a single database setup.**
Can that be done using your tenancy package,  if yes How?

**Comment by stancl** [comment]
[This video](https://www.youtube.com/watch?v=nCiNqboYFVQ) might help with implementing single-database tenancy.

**Comment by moneya** [comment]
Thanks

**Comment by stancl** [comment]
You're welcome.

> Can that be done using your tenancy package, if yes How?

This package is strictly for multi-database tenancy. Single-database and multi-database tenancy are two very different concepts to implement. I might create a package for single-database tenancy in the future, but right now, you're probably best off implementing it yourself with the help of internet.

Good luck.

**Comment by moneya** [comment]
Thanks, You have been so helpful
