### ISSUE TITLE
Tenant Subdomain showing data from central database

### ISSUE THREAD

**Issue by sirhB** [archtechx/tenancy#610]
This tenant, `boof`, has the database `tnt_boof` that it should be connecting to, but it is retrieving data from the central database.

My route looks like this for tenants:
```
Route::middleware([
    'web',
    'auth',
    InitializeTenancyBySubdomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::get('/events', 'EventController@displayEvents')->name('events');
    // other routes here
});
```

I added this __construct function to my EventController (after calling `use App\Models\Event, ...`):
```
public function __construct(Event $events, User $users)
    {
        $this->users = $users;
        $this->events = $events;
    }
```
I have a function within the controller that checks the user role. Instead of attempting to do this query on `tnt_boof`, it is attempting the query on `landlord`.
```
 public function roleCheck()
    {
        $user = $this->users->find(Auth::id());
        if($user->hasAnyRole('Super Administrator', 'Administrator'))
        {
            return 'admin';
        }
        elseif($user->hasAnyRole('Client'))
        {
            return 'client';
        }
        else
        {
            return false;
        }
    }
```
Here is the Flare of the error. 
http://flareapp.io/share/17Dn3k9m

_Originally posted by @sirhB in https://github.com/stancl/tenancy/issues/558#issuecomment-791802877_

**Comment by sirhB** [comment]
@stancl

**Comment by morloderex** [comment]
It might be that the relation model you are trying to get does not have it's default connection set to tenant.. Which means it would always get data from the central connection by default.. That's would be my assumtion atleast.
