### ISSUE TITLE
Cannot install package with fresh installation Laravel

### ISSUE THREAD

**Issue by sawirricardo** [archtechx/tenancy#612]
#### Describe the bug
<img width="1792" alt="Screen Shot 2021-03-10 at 08 58 04" src="https://user-images.githubusercontent.com/37329575/110564239-15b5d580-817f-11eb-93f8-3991f12bc83a.png">
 In the middle of package installation, exactly this line: @php artisan package:discover --ansi
 
 This error appears:
  An argument with name "class" already exists.

#### Steps to reproduce
1. composer create-project laravel
2. composer require stancl/tenancy

#### Expected behavior
It should install

#### Your setup
 - Laravel version: v8.5.13
 - stancl/tenancy version: ^3.4

**Comment by stancl** [comment]
See the PR that was just opened. I'll be looking at that in the morning.

Righty now you can simply use a previous version of Laravel (as in a lower minor version number)

**Comment by sawirricardo** [comment]
Right, thank you for the confirmation @stancl
