### ISSUE TITLE
Tenant migrations are applied on central DB

### ISSUE THREAD

**Issue by mrneatly** [archtechx/tenancy#613]
#### Describe the bug
I have a multi-database tenancy installation, but when executing a `php artisan tenants:migrate` command, all migrations are being applied on central DB instead.

This unexpected behaviour started happening after I transferred (copy-pasted) my code to another physical machine. I didn't do any changes in my code after that. On an old machine, all migrations were being applied on proper databases. I cleared all app caches, but it did no impact on the situation.

I suppose this may not be a bug, but rather an issue in a configuration. Where should I look to fix that?

#### Steps to reproduce
- Set up a new project;
- Install `stancl/tenancy` package;
- Set up a multi-database tenancy app;
- Move code to another machine by `ctrl+c`-ing source to another computer;
- Run app and tenant migrations;

#### Expected behavior
Tenant migrations should apply on tenant databases, not central one.

#### Your setup
 - Laravel version: 8.26.1
 - stancl/tenancy version: 3.4.1

**Comment by stancl** [comment]
Can you test this on an older Laravel 8 release?

**Comment by mrneatly** [comment]
Tested on Laravel 8.0.3 - same story.

**Comment by mrneatly** [comment]
I made a clear Laravel v8.0.3 setup with a `stancl/tenancy` package, created two tenants via laravel tinker and ran their migrations (at first, corresponding databases have been automatically created and filled by migrations for each tenant, but I truncated these databases and applied migrations manually) - works as intended.
