### ISSUE TITLE
Allow custom lookup fields for Resolver(s)

### ISSUE THREAD

**Issue by devjack** [archtechx/tenancy#615]
Instead of requiring a custom PathTenantResolver, it would be convenient to configure a field on the Tenant model that can be used to 'resolve' it.

For example; I prefer auto incrementing ID's on all models/resources, and uuid's or 'slugs' for anything public; this naturally assumes a unique constraint on the uuid (e.g. it's 'key') or the identifying field (e.g. it's 'slug').

I *think* this is the simplest place to make the change:
https://github.com/stancl/tenancy/blob/411d486282517956ae32976cabe2cda07ad887ab/src/Resolvers/PathTenantResolver.php#L32

This would allow you to customise both the $tenantParameterName, and, as an example the config('model_field_identifier').

Opening an issue for discussion/feedback before looking to implement/PR. :)

**Comment by stancl** [comment]
https://github.com/stancl/tenancy/blob/411d486282517956ae32976cabe2cda07ad887ab/src/Tenancy.php#L101-L104

I think you should be able to change the `getTenantKeyName()` to do what you want here.

**Comment by devjack** [comment]
Ah right you are, I was too head in the weeds and missed that. Cheers!
