### ISSUE TITLE
Authentication with LoginAs via Dusk Test does not authenticate

### ISSUE THREAD

**Issue by nakab** [archtechx/tenancy#616]
#### Describe the bug

When creating a test using Dusk and the LoginAs() authentication method, the user is not authenticated.

#### Steps to reproduce

Creating a test below:

```
$this->browse(function (Browser $browser) {

    $browser->loginAs(User::find(1))
            ->assertAuthenticated();
});
```
The result is:

The user is not authenticated.

#### Expected behavior

The user is authenticated

#### Your setup
 - Laravel version: 8.26.1
 - stancl/tenancy version: 3.4.0

**Comment by stancl** [comment]
This depends entirely on your testing setup. I recommend asking in the discussions or on our Discord, since this isn't really related to the package, as the package does nothing to your tests or say anything about Dusk in the docs.

**Comment by chrillep** [comment]
@stancl started https://github.com/archtechx/tenancy/discussions/918
