### ISSUE TITLE
Can't add other columns tenant migrations

### ISSUE THREAD

**Issue by abeer93** [archtechx/tenancy#622]
#### Describe the bug

Hello,
I have a model called company model and each company must has a tenant. 
So, I tried to add company_id column in tenant migration.
But I faced and issue when trying to create new tenant.
I received a database error saying that company_id has no default value I wondered as I already added company id value in array passed to create function.
#### Steps to reproduce
1- add company_id filed to tenant migration
2- add protected $fillable array to tenant model.
`protected $fillable = ['id', 'company_id', 'data'];
![stancl1](https://user-images.githubusercontent.com/16510751/112178470-6fe47b00-8c02-11eb-9501-4bdc9708f082.png)
![stancl2](https://user-images.githubusercontent.com/16510751/112178472-707d1180-8c02-11eb-8877-bb78cb941e6e.png)

`
3- trying to create new tenant with `Tenant::create([]);`
4- this the error appeared to me
> SQLSTATE[HY000]: General error: 1364 Field 'company_id' doesn't have a default value (SQL: insert into `tenants` (`id`, `data`, `updated_at`, `created_at`) values (my_company, {\"company_id\":8}, 2021-03-23 14:43:29, 2021-03-23 14:43:29)

#### Expected behavior
Company_id inserted 
#### Your setup
 - Laravel version: [e.g. 8.2.0]
 - stancl/tenancy version: [e.g. 3.1.0]

**Comment by stancl** [comment]
Did you read the documentation page about custom columns?

**Comment by abeer93** [comment]
@stancl Thanks for your reply.
if you mean this page [https://tenancyforlaravel.com/docs/v3/tenants/#custom-columns](url), yes I read it before posting this issue and after your comment, I read it again.
I understand that if I want to add custom columns to the tenant model I should add them to the JSON data filed through `getCustomColumns` function.

But I have another problem which is retrieving company relation with tenant model and vice versa in company model (retrieving tenant relation inside company object).

**Comment by stancl** [comment]
If you have a support question I recommend posting on our Discord. If there's no bug here I'm closing this.
