### ISSUE TITLE
PHP Error:  Class 'Tenant' not found 

### ISSUE THREAD

**Issue by isaacdarcilla** [archtechx/tenancy#630]
I'm following the quickstart guide at [https://tenancyforlaravel.com/docs/v3/quickstart](https://tenancyforlaravel.com/docs/v3/quickstart).

But, when I'm at creating tenant using Tinker command.

```
$ php artisan tinker
>>> $tenant1 = Tenant::create(['id' => 'foo']);
```

It shows.
```
PHP Error:  Class 'Tenant' not found 
```

I already created Tenant model, nothing happens. Any help?

Setup
 - Laravel versio 8.2.0
 - stancl/tenancy version 3.1.0

**Comment by peter-brennan** [comment]
Sounds like a namespace issue. I placed my Tenant model in app/Models folder so when using tinker my call is:

$tenant1 = App\Models\Tenant::create(['id' => 'foo']);

**Comment by stancl** [comment]
Hey. If you have support questions, our Discord server is the best place for that.

**Comment by joshuacadman01** [comment]
I have found the same issue after following the documentation

**Comment by stancl** [comment]
Just import the model with the full namespace.

**Comment by stancl** [comment]
Former: I said import your model, not two classes with the same name

Latter: You're not importing your model

If you cannot debug this on your own or notice that of the things you tried you haven't actually done what I said, it might be wise to put building multi-tenant applications on hold and get some general PHP experience first.
