### ISSUE TITLE
Cannot use InitializeTenancyByPath middleware with laravel/ui Auth routes

### ISSUE THREAD

**Issue by pippos44** [archtechx/tenancy#634]
#### Describe the bug
Im trying to setup mutli-tenancy using Path Tenant Identification. I don't know if this is something obvious but I couldn't get the InitializeTenancyByPath middleware to work with the preconfigured Laravel Authentication routes

#### Steps to reproduce
Based on the example of how to use **Path identification** I have placed in the tenant.php route file the below code
https://tenancyforlaravel.com/docs/v3/tenant-identification/
```
Route::group([
    'prefix' => '/{tenant}',
    'middleware' => [
        'web',
        InitializeTenancyByPath::class
        ],
    ], function () {
        Auth::routes(['verify' => true]);
});  
```
But I got the below exception which clearly says that a parameter is required.

`Illuminate\Routing\Exceptions\UrlGenerationException
Missing required parameter for [Route: login] [URI: {tenant}/login] [Missing parameter: tenant]`

I can fix this by making optional the `{tenant?}` parameter. Is there any other way of doing this without affecting all routes?

#### Expected behavior
Predefine authentication routes should load fine under tenant context.

#### Your setup
 - Laravel version: [8.28.1]
 - stancl/tenancy version: [3.4.2]

**Comment by stancl** [comment]
Hey, this doesn't seem to be an actual bug in tenancy, but rather 3rd party library support. So it's more of a support question, and the best place to ask those is our Discord server. Thanks
