### ISSUE TITLE
NotFoundHttpException in api request and Illegal offset type in isset or empty in route:list command

### ISSUE THREAD

**Issue by EVNIKHIL** [archtechx/tenancy#641]
Hi I have recently read about tenancy. Great work team.
I have a application with Angular on front end and want use tenancy, so using the api route.
For the time being I am trying to use tenancy with Path Identification method. following the https://tenancyforlaravel.com/docs/v3/tenant-identification this documentation. added the same sample route and when I try to hit the link in Post man 'localhost:8000/api/test1' then the error 'Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException'
route not found error raised. Then I tried to check how route is listed but route:list command, it raised an error like below
 
`ErrorException 
  Illegal offset type in isset or empty
  at vendor/laravel/framework/src/Illuminate/Routing/Router.php:1267
    1263▕ 
    1264▕         foreach ($middleware as $value) {
    1265▕             $key = \is_object($value) ? \spl_object_id($value) : $value;
    1266▕ 
  ➜ 1267▕             if (! isset($seen[$key])) {
    1268▕                 $seen[$key] = true;
    1269▕                 $result[] = $value;
    1270▕             }
    1271▕         }`
 

My current route tenent file is 

`<?php

declare(strict_types=1);

use Illuminate\Support\Facades\Route;
use Stancl\Tenancy\Middleware\InitializeTenancyByDomain;
use Stancl\Tenancy\Middleware\PreventAccessFromCentralDomains;

Route::middleware([
    'web',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::get('/', function () {
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });
});

Route::middleware([
    'prefix' => '/{tenant}',
    'middleware' => [InitializeTenancyByPath::class],
])->group(function () {
    Route::get('/', function () {
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });
});
`
And my current RouteServiceProvider.php

`<?php

namespace App\Providers;

use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{
    public const HOME = '/home';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        $this->configureRateLimiting();
        $this->mapWebRoutes();
        $this->mapApiRoutes();
    }

    /**
     * Configure the rate limiters for the application.
     *
     * @return void
     */
    protected function configureRateLimiting()
    {
        RateLimiter::for('api', function (Request $request) {
            return Limit::perMinute(60)->by(optional($request->user())->id ?: $request->ip());
        });
    }

    protected function mapWebRoutes()
    {
        foreach ($this->centralDomains() as $domain) {
            Route::middleware('web')
                ->domain($domain)
                ->namespace($this->namespace)
                ->group(base_path('routes/web.php'));
        }
    }

    protected function mapApiRoutes()
    {
        foreach ($this->centralDomains() as $domain) {
            Route::prefix('api')
                ->domain($domain)
                ->middleware('api')
                ->namespace($this->namespace)
                ->group(base_path('routes/api.php'));
        }
    }

    protected function centralDomains(): array
    {
        return config('tenancy.central_domains');
    }
}
`

Can you please where is I am wrong?

**Comment by stancl** [comment]
Please use the correct channels for support questions.

**Comment by EVNIKHIL** [comment]
post the same in discussion is fine right?
