### ISSUE TITLE
Laravel Octane with TenantConfig Feature

### ISSUE THREAD

**Issue by robean01** [archtechx/tenancy#649]
#### Describe the bug
When using Laravel Octane with the TenantConfig feature enabled, the configuration is always from the previous request

#### Steps to reproduce
- Enable TenantConfig feature
- Map tenant id to app.name
- Print app.name in a view

#### Expected behavior
When visiting tenant a, tenant a should appear, and the same for tenant b.

#### Your setup
 - Laravel version: 8.40
 - stancl/tenancy version: 3.4.3

**Comment by stancl** [comment]
Octane isn't officially supported yet, I'll be focusing on that in v4.

**Comment by dorep** [comment]
Found this thread on google, very happy using this package in our application, keep up the good work. I hope octane support comes too 👍 👍
