### ISSUE TITLE
Authenticated user can request data from all tenants

### ISSUE THREAD

**Issue by andre-zago** [archtechx/tenancy#653]
Hello, first of all, thank you for all the good work done with this package. I have set up a multi-database tenancy by using path identification following the steps in the stancl/tenancy docs. Everything works fine but when I was doing security tests I have noticed that since a user is authenticated, he is able to request data from all tenants (routes protected by auth:sanctum middleware). 
I am using a Laravel 8 API with Laravel Sanctum. How could I prevent that? I have already tested changing the middleware to domain identification, subdomain identification but the problem persists.
I have read the docs exhaustively; I have searched in the Discord Community of the package and I cannot figure out how to avoid showing data from users in other databases. 
For example, a tenant called 'foo' authenticates in its own database. If he, evil-minded, tries to request data from another tenant he can return the data from another database/ tenant by simply changing the parameters (uri) to a required known tenant id. As I understood, it can cause several security issues by exposing a potentially leakage of confidential information. Am I doing it wrong, or this is really a bug?

Here's my tenant.php file.

```
Route::group([
    'prefix' => '/{tenant}',
    'middleware' => [InitializeTenancyByPath::class, 'web'],
    PreventAccessFromCentralDomains::class,
], function () {
    
    Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
        return $request->user();
    });
    
    Route::post('/auth/login', [\App\Http\Controllers\Auth\LoginController::class, 'authenticate'])->name('auth.login');
});
```

Here's my LoginController with the "autentication function".

```
class LoginController extends Controller
{
    public function authenticate(Request $request)
    {
        $validation = $request->validate([
           'email' => 'required|string|email',
           'password' => 'required|string|min:8'
        ]);

        $attempt = Auth::attempt($validation);

        if ($attempt) {
            $request->session()->regenerate();
            return response()
                ->json([
                   'status' => true,
                   'user' => Auth::user(),
                ], 202);
        }

        return response()
            ->json([
                'status' => false,
                'message' => 'Credentials do not match',
            ], 401);
}
```

When, for example, the tenant 'foo' authenticates, if he requests the route of another tenant like 'bar' (mydomain.com/bar/user), it returns its data normally, even though that user lives on completely different databases, so I understood that since a user is logged in, he is gaining access to all tenants. Am I wrong? Am I doing something wrong? How can I prevent that?

#### My Setup
 - Laravel Framework 8.41.0
-  Laravel Sanctum 2.11
 - Stancl/tenancy 3.4

**Comment by stancl** [comment]
> If he, evil-minded, tries to request data from another tenant he can return the data from another database/ tenant by simply changing the parameters (uri) to a required known tenant id. As I understood, it can cause several security issues by exposing a potentially leakage of confidential information. Am I doing it wrong, or this is really a bug?

This is one of the pains of multi-tenant auth in general.

I think the issue is that Laravel stores "user with id 1 is logged in". This is encrypted using the app key, which is usually the same for all tenants.

If you'd use domain identification and the default auth, you'd have session scoped to individual domains, so this wouldn't happen. With a single API and/or path identification it's important to separate the user sessions in another way.

Can you try applying this middleware? https://github.com/stancl/tenancy/blob/3.x/src/Middleware/ScopeSessions.php

**Comment by stancl** [comment]
See this: https://tenancyforlaravel.com/docs/v3/session-scoping

**Comment by andre-zago** [comment]
Hello, Stancl. Thank you very much for your support. Using Laravel's default auth with the ScopeSessions middleware worked just fine. Best Regards!
