### ISSUE TITLE
Queue not processing jobs

### ISSUE THREAD

**Issue by bhagdave** [archtechx/tenancy#657]
#### Describe the bug
I have a Welcome email to be sent on creating an account withinh the tenant setting and I switched to move this to be queued.  This attempts to add a job to a jobs table on the tenant database - which does not exist.  

#### Steps to reproduce
Run 
`php artisan queue:table`
`php artisan migrate`
Set the queue config to use database
Run
`php artisan queue:work`

The code runs the following when a user is created:-
`\Mail::to($user)->queue((new Welcome($resetUrl))->onConnection('database'));`
This reports:-
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tenantfoo.jobs' doesn't exist

If I leave off the onConnection then the job gets placed in the central jobs table fine. But the queue worker does not process it or increase the attempts field or add it to the failed_jobs table and there is no errors shown in the logs.

#### Expected behavior
I expected the mail to be added to the job queue in the central database and processed.

#### Your setup
 - Laravel version: 8.12
 - stancl/tenancy version: 3.4

**Comment by stancl** [comment]
I think you misconfigured the queue. It's looking for the jobs table on the tenant connection. Re-read the docs for that and if you need help you can join our Discord 👍🏻

**Comment by bhagdave** [comment]
It was indeed a mis-configure.  Apologies.

**Comment by Angelo-TR** [comment]
Hello, I want to be part of your discord group, I have problems with stancl/tenancy queues when I send mail with queues

**Comment by stancl** [comment]
https://archte.ch/discord

**Comment by zohaibcrewlogix** [comment]
Hi @stancl , I am dispatching all the jobs in central db connection in jobs table. but when i run php artisan queue:listen no one job gets processed. i have attached SS. please have a look into it.
![laravel queued jobs](https://user-images.githubusercontent.com/102576962/211486271-52283157-340a-4a81-a240-fe6f9f400b9b.PNG)
