### ISSUE TITLE
SSL issue with www domain.

### ISSUE THREAD

**Issue by travnettech** [archtechx/tenancy#660]
#### Describe the bug

I am having the same problem. When we add example.com and issue the certificate it works fine with the same domain. But www.example.com does not load the site (It shows a 404 error). When I add www.example.com in the portal the domain load, but without SSL. Whenever I request SSL for the same domain, both sites (example.com and www.example.com) do not load. It shows a security issue.

#### Steps to reproduce
1. Create an account and add a domain.
2. Point domain to the IP (ex. example.com to the server IP). and Point domain with www to the main domain (ex. cname www.example.com to example.com)
3. Issue an SSL certificate for the domain in the portal. For example, the domain is **example.com**
4. Now access the domain it works. But when we access the domain with www.example.com, it shows a 404 error.
5. If I add the domain www.example.com in the portal and issue another certificate. Both domains stop working.

#### Expected behavior
Both domains: example.com and www.example.com should work under an SSL certificate. In fact, when we issue an SSL using Ploi API we should issue SSL for both domains together as one.

#### Your setup
 - Laravel version: 7
 - stancl/tenancy version: 3

**Comment by stancl** [comment]
This doesn't seem specific to the package. Have you resolved this?
