### ISSUE TITLE
JobPipeline is not stringable, causing TenancyServiceProvider::bootEvents() to fail

### ISSUE THREAD

**Issue by roelofr** [archtechx/tenancy#661]
#### Describe the bug
In [TenancyServerProvider.stub.php](https://github.com/archtechx/tenancy/blob/54a33f93a85a5e0a4d53ac48fabacd8ebb716eec/assets/TenancyServiceProvider.stub.php#L111-L116), a call is made to `array_unique` on the list of events, which works as long as there's no `Stancl\JobPipeline\JobPipeline` in the list, or there `Stancl\JobPipeline\JobPipeline` instance is the only item in the list.

However, as soon as a second item is added to an event list with `Stancl\JobPipeline\JobPipeline`, or an `Stancl\JobPipeline\JobPipeline` instance is added, `array_unique` fails:

```
   Error 

  Object of class Stancl\JobPipeline\JobPipeline could not be converted to string

  at app/Providers/TenancyServiceProvider.php:115
    111▕         dump("Registering events");
    112▕ 
    113▕         foreach ($this->events() as $event => $listeners) {
    114▕             $count = 0;
  ➜ 115▕             foreach (array_unique($listeners) as $listener) {
    116▕                 if ($listener instanceof JobPipeline) {
    117▕                     $listener = $listener->toListener();
    118▕                 }
    119▕ 

  1   app/Providers/TenancyServiceProvider.php:115
      array_unique()

  2   app/Providers/TenancyServiceProvider.php:103
      App\Providers\TenancyServiceProvider::bootEvents()
```

#### Steps to reproduce

1. Install Stancl (`composer require stancl/tenancy` and `php artisan tenancy:install`)
2. Add the `App\Providers\TenancyServiceProvider::class` to your `config/app.php`
3. Add a second item to the `App\Providers\TenancyServiceProvider::events()` array, where a JobPipeline is present, for example at `Events\TenantCreated::class`.
4. Start `php artisan tinker` or open the application.

#### Expected behavior

The application properly starts, and both jobs run (in order) when the event is invoked,

#### Your setup
 - Laravel version: 8.42.1
 - stancl/tenancy version: 3.4.4

**Comment by stancl** [comment]
What do you mean by "second item"? Can you share actual code?

**Comment by roelofr** [comment]
Yeah sure,

Full steps to reproduce in a testing environment.

1. `composer create-project laravel/laravel tenancy-test`
2. cd `tenancy-test`
2. `composer require stancl/tenancy`
3. `php artisan tenancy:install`
4. Add `App\Providers\TenancyServiceProvider::class,` to `config/app.php`
5. `php artisan make:listener --event='Stancl\Tenancy\Events\TenantCreated' SendMailOnTenantCreatedListener`
6. Update `app/Providers/TenancyServiceProvider.php` with code below
7. `php artisan`, error now shows

Code to modify

```diff
 class TenancyServiceProvider extends ServiceProvider
 {
 …
     public function events()
     {
         return [
             // Tenant events
             Events\CreatingTenant::class => [],
             Events\TenantCreated::class => [
+                \App\Listeners\SendMailOnTenantCreatedListener::class,
                 JobPipeline::make([
                     Jobs\CreateDatabase::class,
 …
```

I just tried this locally and the error showed up, so it should work.

Edit 2021-05-27: Replaced the job with a listener, the problem is still the same.

**Comment by stancl** [comment]
Right, well jobs can't be used as listeners well, so you should create another pipeline and pass the single job to it.

**Comment by roelofr** [comment]
I updated the comment to use a listener instead, but the problem still has the same origin (`array_unique`). 

It doesn't happen when there are only jobs added to _a single JobPipeline_, but as soon as you add a second JobPipeline or mix a JobPipeline and a string, the error shows.

---

For more examples, the code below would trigger **the same error**.

```diff
 class TenancyServiceProvider extends ServiceProvider
 {
 …
     public function events()
     {
         return [
             // Tenant events
             Events\CreatingTenant::class => [],
             Events\TenantCreated::class => [
+                JobPipeline::make([
+                    \App\Jobs\SendMessageToAdmin::class,
+                    \App\Jobs\RequestTlsCertificate::class,
+                ]),
                 JobPipeline::make([
                     Jobs\CreateDatabase::class,
 …
```

**Comment by stancl** [comment]
Right, I can reproduce this. I think the array_unique() was relevant in the past with different code, but now it's probably useless. Can you make a PR to remove it?

**Comment by stancl** [comment]
I think really just removing the `array_unique()` call fixes this

**Comment by roelofr** [comment]
I'll get to creating a PR this afternoon.

**Comment by roelofr** [comment]
That wasn't exactly "this afternoon", sorry about that.
