### ISSUE TITLE
Weird behaviour when using view()->render inside of a $tenant->run()

### ISSUE THREAD

**Issue by kajgiesbersflavour** [archtechx/tenancy#662]
#### Describe the bug
Hello all,

I am trying to show the users login information in the navbar of the central domain when they are logged in in a tenant. 
I am using a multidatabase setup and the users are not synced, they are tenant only.
I might be going about this the wrong way but I am seeing some unexpected behavour with the following code:
`
        $tenantNavigation = "";
        $tenant = \App\Http\Controllers\TenantController::getTenant();
        if($tenant)
        {
            $tenant->run(function () use(&$tenantNavigation) {
                $tenantNavigation = view('partials.nav')->render();
            });
        }
`

__Actual behavior__
Within this view:
- tenant() returns the tenant as expected
- the central database is still being used when accessing @Auth or Auth::user()

__Expected behavior__
Within this view:
- tenant() returns the tenant as expected
- the tenant database should be used and @Auth::user() should return the currently logged in user on the tenant.

#### Your setup
 - Laravel version: ^6.0
 - stancl/tenancy version: ^3.4

**Comment by stancl** [comment]
Can you make a simple example that reproduces this without view logic and the controllers?

Also, what is the use case for this? This is generally not what tenant run is meant for.

**Comment by kajgiesbersflavour** [comment]
Thanks for your response! I will make something simple to show the problem.

While testing I found out that actually it is just Auth::user() which doesn't seem to return the correct user within the tenant->run().

Simple example case:
Controller:
```
        $user = null;
        \App\Tenant::first()->run(function () use(&$user) {
            $user = auth()->user();
        });
        return $user;
```
This will return the central user instead of the tenant's user. 

Don't forget to replace \App\Tenant with the correct model location.



As for the use case, we are trying to make an app that uses different tenants for different regions people can be in. We want a central website where people from every region can go and it should be seemlessly integrated with the tenant. If people click the login button on this central app, they will be automatically redirected to the correct tenant. If they log in and return to the central app page, it should not show a login button anymore but instead a button that redirects them to their profile page on the tenant.

Everything else is already setup and working but I am still trying to find a way to get access to the user that is currently logged in on a specific tenant from the central app.

Is there any other way we can find the logged in user on a specific tenant?

Kind regards,

Kaj

**Comment by stancl** [comment]
> This will return the central user instead of the tenant's user.

Well yes, because auth is a thing of the current request, and in the current request there's a central user authenticated. `run()` only switches the context to tenant DB, but it won't change what's already bound.

**Comment by kajgiesbersflavour** [comment]
I just realized that your login is saved in the session which is retrieved trough the cookies which are of course domain specific. 

Is there anyway to somehow share the session if they are on the same domain but a different subdomain?

Either way,  there is no bug here then and I will close the issue shortly.

Thanks for your responses!

Kaj

**Comment by stancl** [comment]
I think you can set the session domain in the config. Check the Laravel docs
