### ISSUE TITLE
abc.maindomain.com redirect too many times and Sessions stored into the central domain database instead of storing tenants database 

### ISSUE THREAD

**Issue by binodgtm** [archtechx/tenancy#663]
#### Describe the bug

Hello , I got an issue "redirected you too many times" after adding auth middleware to tenant.php.
This issue only appears in the subdomains(tenants) and main domain working properly.

I am using XAMPP server on local and have created virtual host 
maindomain.com
abc.maindomain.com
xyz.maindomain.com

in the maindomain.com every thing working properly and other subdomain are not.
But login and register pages are working fine in every domain. After login user to tenant(xyz.maindomain.com) shows the the issue "redirected you too many times".

And one thing if i remove auth middleware from tenant.php it working properly but my authenticated routes are exposed to outer users.

I don't know why it is not working or something i missing from the package documentation.....

my tenant.php looks like
Route::group(['prefix'=>'/admin','middleware' =>['web','auth',PreventAccessFromCentralDomains::class]], function () {

Route::resource('deleteduser','DeletedUserController');
});
#### Your setup
 - Laravel version: [e.g. 7.24]
 - stancl/tenancy version: [e.g. 3.4]

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks
