### ISSUE TITLE
Laravel passport authentication

### ISSUE THREAD

**Issue by Jimmy-kiarie8** [archtechx/tenancy#664]
Hello, I am using tenancyforlaravel package to beild my saas application. I am trying to create an api using laravel passport but when I run the request `http://foo.myapp.test/oauth/token` I get this error. `Table 'tenants.oauth_clients' doesn't exist`. But when I run an API route `http://foo.myapp.test/api/test` I get the desired output. I have created a config file on config/passport.php but I can't figure out how to solve this.

passport.php

<?php

return [

    'storage' => [
        'database' => [
            'connection' => null,
        ],
    ],
    'key_path' => env('OAUTH_KEY_PATH', 'storage')

];

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks
