### ISSUE TITLE
Call to undefined method Stancl\Tenancy\Database\Models\Tenant::domains()

### ISSUE THREAD

**Issue by usman-ali-sarwar** [archtechx/tenancy#665]
I am new and i followed interaction according to your quick start butt i am facing the that issue when i am try access sub domain.
Call to undefined method Stancl\Tenancy\Database\Models\Tenant::domains()

![image](https://user-images.githubusercontent.com/21079029/119899475-91444900-bf5c-11eb-8153-dbc0b4c3d583.png)

**Comment by MeshackNzuki** [comment]
sorry for answering wile closed
in config tenancy.php configure 
'tenant_model' => \App\Models\Tenant::class,
your model may not be vissible

**Comment by nezaboravi** [comment]
same here
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/1515172/157734271-d8c46a7d-6f21-4d77-aae7-eb87ec63f109.png">

**Comment by crytos** [comment]
Hi @MeshackNzuki and @nezaboravi did you resolve this? Im also stuck here please?

**Comment by dinhhuy258** [comment]
> Hi @MeshackNzuki and @nezaboravi did you resolve this? Im also stuck here please?

The issue is that the default tenant model does not include domains table (domains is an optional feature).
You should define your own Tenant model and add the HasDomain trail there.

For more information, you can find here https://tenancyforlaravel.com/docs/v3/tenants

**Comment by briavers** [comment]
Using v3 with valet and 1 database my issue was that i didn't place my central domain correct in `config/tenancy.php`
```php
 'central_domains' => [
        '127.0.0.1',
        'localhost',
        'myapp.test' //<-- you need to add your xxx.test url
    ],
```

**Comment by mfeeee** [comment]
I actually defined my own Tenant model and added the HasDomain trail, also placed my central domain correctly but it still doesn't work
