### ISSUE TITLE
how to fetch data from tenant in tenant mode and make globally available in all view files.

### ISSUE THREAD

**Issue by amitgwachha** [archtechx/tenancy#668]
#### Describe the bug
I used to fetch data in serviceProvider and make it available globally in all view files. But now using this tenancy package, it only return data from central database. So to fetch data from own tenant database, how can we achieve. 
Using from the middleware, is not working, since it also returns data from central database

#### Your setup
 - Laravel version: [e.g. 7.0]
 - stancl/tenancy version: [e.g. 3.4]

**Comment by lcdss** [comment]
The tenant can only be accessed if it was identified before (in the middleware specified in the TenancyServiceProvider). I think you are making the request to a central domain (localhost or 127.0.0.1) and therefore, there're no tenant available.

**Comment by stancl** [comment]
Please respect the issue templates.
