### ISSUE TITLE
Tenant database creation requires an existent database name in the database server

### ISSUE THREAD

**Issue by lcdss** [archtechx/tenancy#669]
#### Describe the bug
After a tenant is created, the tenant connection template is used to check if the database server already  has a database with the same name and throws an error if the database name specified in the tenant template connection doesn't exist in the server. For while I'm defining `postgres` as it'll always exist on my setup. I also tried to use the internal postgresql databases but it didn't work.

```php
// Stancl\Tenancy\TenantDatabaseManagers\PostgreSQLDatabaseManager:44
public function databaseExists(string $name): bool
{
        return (bool) $this->database()->select("SELECT datname FROM pg_database WHERE datname = '$name'");
}
```

#### Steps to reproduce
1. Define a custom tenant connection template
2. Specify in the database key of the connection, the value null or any database name that doesn't exists in the database server.
3. Create a new tenant

```php
// config/tenancy.php
return [
    'database' => [
        'template_tenant_connection' => 'tenant-default',
    ]
];

// config/database.php
return [
    'connections' => [
        'tenant-default' => [
            // ...
            // If omitted: <warning>PHP Warning:  Undefined array key "database" in /app/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php on line 76</warning>
            'database' => 'anything', // database "anything" does not exist
            // "database" => null, database "port=5432" does not exist
        ]
    ]
];
```

#### Expected behavior
The tenant connection template should be just a template, therefore the database key should be omitted or be null and the tenant's database should still be created.

I'm aware Laravel uses PDO and it requires a valid database name to establish a connection with the database server, but I still think something should be done to improve this scenario.

**Comment by stancl** [comment]
Is this related to #656?

**Comment by lcdss** [comment]
> Is this related to #656?

No, it's not the same problem. I test his changes and this problem persists. This issue is more about a PDO limitation, that requires an existent database to make any request to the database server. So when we check if already exists a database for the tenant we are creating, the query fails, as there are no databases yet to use in the database connection configuration.

**Comment by lcdss** [comment]
> Is this related to #656?

No, it's not the same problem. I tested his changes and this problem persists. This issue is more about a PDO limitation, that requires an existent database to make any request to the database server. So when we check if already exists a database for the tenant we are creating, the query fails, as there are no databases yet to use in the database connection configuration.

**Comment by stancl** [comment]
I see. Maybe the bug fix should be part of that PR too, since the issues overlap a bit.

If I understand things correctly, #656 makes the package use the correct connection for creating tenant DBs, because currently the package ignores `tenancy_db_host` in the tenant data when creating the DB for the first time.

And this other issue relates to PDO needing to connect to at least _some_ database to create a new one?

Actually not sure if that can even be solved in PHP. If PDO needs to connect to _some_ database, I don't see how the package could do anything there. It should just be assumed that connections should be fully qualified, even if they're template connections I guess.

> I also tried to use the internal postgresql databases but it didn't work

So the package *needs to know* the name of some existing database. Again, don't think there's any way to solve this. Maybe just mention this in the documentation.

**Comment by lcdss** [comment]
Adding to the documentation should be enough and this can happen even if the central e tenant database host are the same, in case the tenant connection template has an invalid database name defined. ON PostgresSQL, using `postgres` worked for me and on MySQL/MariaDB should be the same (`mysql` database name). Not sure about SQLite.

**Comment by stancl** [comment]
SQLite doesn't need a connection to create a DB, we just create a new file iirc

**Comment by lgcshy** [comment]
Hello, how can I set up each（connect） tenant's database on a different server? I mean  tenant's db connection template from tenants table,the tenant's db config is dynamic .Can someone give me some suggestions on this issue?

**Comment by lcdss** [comment]
> Hello, how can I set up each（connect） tenant's database on a different server? I mean tenant's db connection template from tenants table,the tenant's db config is dynamic .Can someone give me some suggestions on this issue?

I think your looking for https://tenancyforlaravel.com/docs/v3/customizing-databases
