### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by PasiDaniele** [archtechx/tenancy#671]
#### Description
Can we add a MongoDB support?
Yesterday I tried to install this package and I added jenssegers/mongodb to use mongo DB.
Then I added a DatabaseManager in config
```
'managers' => [
            'sqlite' => Stancl\Tenancy\TenantDatabaseManagers\SQLiteDatabaseManager::class,
            'mysql' => Stancl\Tenancy\TenantDatabaseManagers\MySQLDatabaseManager::class,
            'pgsql' => Stancl\Tenancy\TenantDatabaseManagers\PostgreSQLDatabaseManager::class,
            'mongodb' => \App\TenantDatabaseManagers\MongoDatabaseManager::class,
]
```
Then I extended Tenant model with Jenssegers\Mongodb\Eloquent\Model and copied Stancl\Tenancy\Database\Models\Tenant code in my Tenant Model to have all features of your Tenant model
With this settings, Mongo DB is populated, migrations work... and it seems to run.
I have an error when it tries to create a new tenant db, because with Mongo is different, but with a manual db creation with correct name and this trick in MongoDatabaseManger
```
public function databaseExists(string $name): bool
{
        return true;
}
```
it seems to be fixed.
I was wondering if official integration was possible for Mongo DB or Hybrid situation ( Mongo + mySql) 
 

#### Why this should be added
To manage central and tenant on mongo db

**Comment by alrisha** [comment]
I try to detail better my context.
Central database on mysql, tenant database on mongo.
This in my composer
````
"require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "jenssegers/mongodb": "^3.8",
        "laravel/framework": "^8.40",
        "laravel/jetstream": "^2.3",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.0",
        "stancl/tenancy": "^3.4"
    },
````
This is my config/tenantcy.php
````
'managers' => [
            'sqlite' => Stancl\Tenancy\TenantDatabaseManagers\SQLiteDatabaseManager::class,
            'mysql' => Stancl\Tenancy\TenantDatabaseManagers\MySQLDatabaseManager::class,
            'pgsql' => Stancl\Tenancy\TenantDatabaseManagers\PostgreSQLDatabaseManager::class,
            'mongodb' => \App\TenantDatabaseManagers\MongoDatabaseManager::class,
````
Where MongoDatabaseManager is a copy of other Manager, but commenting job to create new database the only function that seems to be used is makeConnectionConfig
````
'database' => [
        'template_tenant_connection' => 'mongodb',
````
Then i have commented in TenancyServiceProvider this jobs because database creation is different on mongo
````
Events\TenantCreated::class => [
                JobPipeline::make([
//                    Jobs\CreateDatabase::class,
//                    Jobs\MigrateDatabase::class,
                    // Jobs\SeedDatabase::class,

                    // Your own jobs to prepare the tenant.
                    // Provision API keys, create S3 buckets, anything you want!

                ])->send(function (Events\TenantCreated $event) {
                    return $event->tenant;
                })->shouldBeQueued(false), // `false` by default, but you probably want to make this `true` for production.
            ],
````

My Tenant model is the same as in you guide.
Then all other model that have to go on mongo extend this model TenantMongo

````
<?php

namespace Src\Models;

use Jenssegers\Mongodb\Eloquent\Model;
use Stancl\Tenancy\Contracts\Tenant as BaseTenantContract;
use Stancl\Tenancy\Database\Concerns\HasInternalKeys;
use Stancl\Tenancy\Database\Concerns\TenantRun;

class TenantMongo extends Model implements BaseTenantContract
{

    use HasInternalKeys;
    use TenantRun;

    protected $collection = 'products';

    public function getTenantKeyName(): string
    {
        return '_id';
    }

    public function getTenantKey()
    {
        return $this->getAttribute($this->getTenantKeyName());
    }

}
````

Whit this changes, Do you think that there will be any problem?
For now i tried to write and read on mongo passing through subdomain tenant identification.. and it seems to work

Regards and congratulations on the package, it's really useful ^_^

**Comment by stancl** [comment]
Laravel doesn't have a native MongoDB driver, so the package won't include one either. This should probably be done as a separate community package.

**Comment by HamzaAlayed** [comment]
Hi @stancl 
Laravel added MongoDB to their official documentation https://laravel.com/docs/11.x/mongodb#main-content
