### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by brenjt** [archtechx/tenancy#675]
#### Describe the bug
When changing the Tenant JobPipeline to `shouldQueue(true)` I get this error: `Serialization of 'Closure' is not allowed`

#### Steps to reproduce
I am using the default service provider that Tenancy creates and then changed `shouldQueue(true)` param to true

    Events\TenantCreated::class => [
        JobPipeline::make([
            TenancyJobs\CreateDatabase::class,
            TenancyJobs\MigrateDatabase::class,
            TenancyJobs\SeedDatabase::class,

            // Your own jobs to prepare the tenant.
            // Provision API keys, create S3 buckets, anything you want!

        ])->send(function (Events\TenantCreated $event) {
            return $event->tenant;
        })->shouldBeQueued(  true  ), // `false` by default, but you probably want to make this `true` for production.
    ],

#### Expected behavior
I'd expect this to just work and do its normal thing but it looks like its breaking here:

    public function toListener(): Closure
    {
        return function (...$args) { // <------- Is crying because of this closure
            $executable = $this->executable($args);

            if ($this->shouldBeQueued) {
                dispatch($executable);
            } else {
                dispatch_now($executable);
            }
        };
    }

#### Your setup
 - Laravel version: 8.45.1
 - stancl/tenancy version: 3.4.4

Am I missing? I assume I've done something wrong. I am using redis for my queues.

**Comment by stancl** [comment]
I think Closure serialization is related to your server setup. Make sure that it's allowed in PHP
