### ISSUE TITLE
The database remain after delete tenant

### ISSUE THREAD

**Issue by ksuwa55** [archtechx/tenancy#678]
Hi, I followed the tutorial below to get started with Tenancy, and once I succeeded in creating two tenants. 
https://tenancyforlaravel.com/docs/v3/quickstart

However, when I deleted the tenant (or rather, deleted the project) and tried to create a new tenant with the same name again in a new project with the same name, I got the following error message and could not create the tenant.

"Stancl\Tenancy\Exceptions\TenantDataTableAlreadyExistsException with message 'Tenant cannot be created. Reason: Database tenantfoo already exists.'"

I assume this is because the database that I made before delete the previous project still exists, so that,
1) How can I delete the remaining database?
2) How can I check the list of remaining databases?
Could you tell me please?

 - Laravel version: [8.47.0]
 - stancl/tenancy version: [3.4.4]

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks
