### ISSUE TITLE
Bug schedule run onOneServer

### ISSUE THREAD

**Issue by PedroCM-git** [archtechx/tenancy#681]
#### Describe the bug
I'm running into a problem when scheduling jobs in my application using the Schedule feature: onOneServer(), the job just get scheduled for one tenant and the others get skipped.

#### Steps to reproduce
1. Create an schedule command using the feature onOneServer()

#### Expected behavior
The command should run for each one of the tenants, however it only runs in one tenant.

The output is something like the following:

```
Tenant: tenant1
Running scheduled command: App\Domain\Process\Jobs\MyJob
Tenant: tenant2
Skipping command (has already run on another server): App\Domain\Process\Jobs\MyJob
```

I´ve been looking into it an the problem is that onOneServer has a key which is used to prevent that the same command is executed multiple times in other servers. 

So I wonder if the command should be scoped in some way with the tenants.

#### Your setup
 - Laravel version: 8.48.1
 - stancl/tenancy version: v3.4.4 
 - redis cluster cache: 5.0.6

**Comment by stancl** [comment]
Jobs aren't meant to be scheduled for multiple tenants. All tenancy logic should happen inside the jobs. See the docs
