### ISSUE TITLE
Create Domain

### ISSUE THREAD

**Issue by raphaelramos** [archtechx/tenancy#687]
#### Describe the bug
executing $tenant->domains()->create() returns an error.

Argument 1 passed to Stancl\Tenancy\Jobs\CreateDatabase::__construct() must be an instance of Stancl\Tenancy\Contracts\TenantWithDatabase, instance of Stancl\Tenancy\Database\Models\Tenant given, called in E:\Projetos\api-test\vendor\stancl\jobpipeline\src\JobPipeline.php on line 61

#### Steps to reproduce
`Route::get('/tentant', [TenantController::class, 'createTenant'])->name('createTenant');`

```
<?php

namespace App\Http\Controllers;

use Stancl\Tenancy\Database\Models\Tenant;

class TenantController extends Controller
{
    function createTenant(){
        $company = 'teste';
        
        $tenant = Tenant::create([
            'id' => $company,
            'plan' => 'trial'
        ]);

        $tenant->domains()->create([
            'domain' => $company
        ]);
    }
}
```

```
<?php

namespace App\Models;

use Stancl\Tenancy\Database\Models\Tenant as BaseTenant;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\Concerns\HasDatabase;
use Stancl\Tenancy\Database\Concerns\HasDomains;

class Tenant extends BaseTenant implements TenantWithDatabase
{
    use HasDatabase, HasDomains;
}
```

 - Laravel version: 8.40
 - stancl/tenancy version: 3.4

**Comment by raphaelramos** [comment]
Problem solved.

Needed to change model use Stancl\Tenancy\Database\Models\Tenant; to use \App\Models\Tenant;

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks

**Comment by stancl** [comment]
Yes, seems to be that you didn't change the model in the config file as the docs suggest.
