### ISSUE TITLE
PHP Parse error: Syntax error, unexpected T_DOUBLE_ARROW on line 1

### ISSUE THREAD

**Issue by dhsont** [archtechx/tenancy#69]
I am getting  error while while creating tenent in tinker
```
>>> tenant()->create('tenant1.localhost')
=> [
     "uuid" => "e5611150-9a9e-11e9-8315-b9eb127de2b8",
     "domain" => "tenant1.localhost",
   ]
```

Error
```
PHP Parse error: Syntax error, unexpected T_DOUBLE_ARROW on line 1
```

I tried on different projects , different php versions bu no luck.

I was following this article
https://stancl.github.io/blog/how-to-make-any-laravel-app-multi-tenant-in-5-minutes/

Thanks for this incredible package.

**Comment by stancl** [comment]
Have you pasted just `tenant()->create('tenant1.localhost')` or also this?

```php
=> [
     "uuid" => "e5611150-9a9e-11e9-8315-b9eb127de2b8",
     "domain" => "tenant1.localhost",
   ]
```

You should call just `tenant()->create()`. The array is the output of that call.
