### ISSUE TITLE
central app data access from tenant

### ISSUE THREAD

**Issue by abhinay1435** [archtechx/tenancy#690]
#### Description

Need to access Central App Data from Tenant Domain

tenancy()->central(function($tenant) {
 return User::all();
});

this is a great helper but what when i need to pass arguments to this like
tenancy()->central(function($id) {
 return User::find($id);
});

Then this doesnot works
#### Why this should be added

Example:- 
If I need global data from central database using some ID
$admin_fuel_type_details = FuelType::find($id);

**Comment by TomHermsen** [comment]
Since you're not passing parameters to the function but rather want to use an existing variable, you should use the variable.
If you do this it should work:
```
tenancy()->central(function() use ($id){ 
    return User::find($id);
});
```

**Comment by abhinay1435** [comment]
@TomHermsen 
It is a real help sir.
It worked
Thanks for you unexpected quick reply.
