### ISSUE TITLE
Tenancy for Laravel & Laravel Sail

### ISSUE THREAD

**Issue by alexjustesen** [archtechx/tenancy#691]
#### Description
In the docs I suggest making a note that if someone is using Laravel Sail to make sure they're using the `root` user when connecting to their database instance in their `.env` file.

#### Why this should be added
The default `sail` user doesn't have the permissions needed to create databases.

**Comment by artworkad** [comment]
Sh into mysql container:

    docker exex -it mysql sh

Start mysql console:

    mysql -u root -p

Grant privileges:

```
GRANT ALL PRIVILEGES ON *.* TO 'default'@'%';
FLUSH PRIVILEGES;
```

**Comment by stancl** [comment]
@abrardev99 Please test this locally (that the issue exists by default, and that the `GRANT` above fixes it), and PR a new page to the tenancy docs.

**Comment by eskiesirius** [comment]
> Sh into mysql container:
> 
> ```
> docker exex -it mysql sh
> ```
> 
> Start mysql console:
> 
> ```
> mysql -u root -p
> ```
> 
> Grant privileges:
> 
> ```
> GRANT ALL PRIVILEGES ON *.* TO 'default'@'%';
> FLUSH PRIVILEGES;
> ```

i tried this but i got this error
```
Illuminate\Database\QueryException with message 'SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'sail'@'%' to database 'tenantbar' (SQL: GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `tenantbar`.* TO `5GBFOl6FEQPh62RL`@`%`)'
```

**Comment by cdterry87** [comment]
I ran the following:
```
docker exec -it name-of-mysql-container sh
```
then:
```
mysql -u root -p
```
and finally:
```
GRANT ALL PRIVILEGES ON *.* TO 'sail'@'%';
FLUSH PRIVILEGES;
```

And afterward, the tenant database would be created after `Tenant::create()` is called. However, for me it results in an additional error shown below:
```
$tenant1 = App\Models\Tenant::create(['id' => 'foo']);
BadMethodCallException with message 'Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database()'
```

**Comment by abrardev99** [comment]
> Please test this locally (that the issue exists by default, and that the GRANT above fixes it), and PR a new page to the tenancy docs.

I've tested it, and yes, the `sail` user can not create databases. I found the two workarounds. 

Change the `DB_USERNAME` from `sail` to `root`. Or grant access to the `sail` user. For granting access, the following commands works for me:

login as root user
`mysql -u root -p`

grant create access
`grant create on *.* to 'sail'@'%';`

**Comment by abrardev99** [comment]
@eskiesirius above solution might help you.

**Comment by stancl** [comment]
Changing it to use `root` is definitely the worse solution. If `sail` has its own user, we should respect that.

Also, you granted permissions to create databases. Can you test if this works for **deleting** databases too? Eg when tenants get deleted.

**Comment by abrardev99** [comment]
> Can you test if this works for deleting databases too? Eg when tenants get deleted.

Yes, this permission does delete the tenant database too.

**Comment by abrardev99** [comment]
Closing this issue because PR got merged https://github.com/stancl/tenancy-docs/pull/182.

**Comment by eskiesirius** [comment]
```grant create on *.* to 'sail'@'%';``` produce this error in laravel sail, jetstream
```
Illuminate\Database\QueryException with message 'SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'sail'@'172.23.0.7' for table 'migrations' (SQL: select `migration` from `migrations` order by `batch` asc, `migration` asc)'
```
so I used ```GRANT ALL PRIVILEGES on *.* to 'sail'@'%';``` and it worked well..

**Comment by stancl** [comment]
@abrardev99 Could you look into that?

**Comment by abrardev99** [comment]
> grant create on *.* to 'sail'@'%'; produce this error in laravel sail, jetstream

Looks like it is working fine for me. 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/54532330/184627752-47c9fb10-5f7c-473f-a776-e92063de92c4.png">

While reproducing this issue, I've noticed a few things. 

- `sail` user missing only **create** database permission (which the above command fixed) and it has all other permissions like delete and read. 
- `sail` user does not have any permission like read to newly created databases even after granting `create` permission. 

So I think @eskiesirius is facing an issue on a newly created database that which `sail` user does not have permission to read. 

@stancl I think the `GRANT ALL PRIVILEGES on *.* to 'sail'@'%';` is a good solution. Why because it grants [all permissions](https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_all) to sail user, including current database and future creating databases.

**Comment by stancl** [comment]
So you mean that the solution we PR'd to the docs only works with the central DB and for **creating** tenant DBs, but it doesn't actually let the user **manage** the tenant DBs, as in the content inside them?

And using `GRANT ALL PRIVILEGES on *.* to 'sail'@'%';` would fix that.

If that's the case, you can open a PR to update this in the docs.

**Comment by abrardev99** [comment]
> So you mean that the solution we PR'd to the docs only works with the central DB and for creating tenant DBs, but it doesn't actually let the user manage the tenant DBs, as in the content inside them?

Yes. And I'll send the PR.
