### ISSUE TITLE
Central app error with Laravel Nova (NotASubdomainException)

### ISSUE THREAD

**Issue by WillyReyno** [archtechx/tenancy#694]
#### Describe the bug
Hello, I'm not 100% sure if this is considered a bug, if not, feel free to redirect me to where I should report this!

I am trying to set Laravel Nova in both my central & tenants domain, I want the following: 
* `website.localhost/nova` → handling tenants & its own users
* `test.website.localhost/nova` → handling its own users and other resources

I tried following the documentation and successfully installed Nova, however I'm getting a weird behavior on the central domain.

Following the documentation, I added this to my config `nova.middleware`  : 
```php 
    'middleware' => [
        InitializeTenancyByDomainOrSubdomain::class, 
        'web',
        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],
```

When I hit my subdomain ` test.website.localhost/nova` everything works fine, and I can access nova and see the tenant's users. 

When I hit my central app `website.localhost/nova` I get a `NotASubdomainException` with error: 
```
Hostname website.localhost does not include a subdomain.
 ```

#### Steps to reproduce

* Install Laravel 8 with tenancy
* Set central to be `website.localhost`
* Install Laravel Nova
* Follow configuration steps from https://tenancyforlaravel.com/docs/v3/integrations/nova/

#### Expected behavior

I expect to reach nova from my central app and be able to see its own users & tenants.

#### Your setup
 - Laravel version: 8.52.0
 - Laravel Nova version: 3.27.0
 - stancl/tenancy version: 3.4.4

**Comment by WillyReyno** [comment]
I'm closing this issue!

The solution was to declare nova routes as [Universal Routes](https://tenancyforlaravel.com/docs/v3/features/universal-routes/) : 

Added `universal` to `nova.php` middleware list, before the `InitializeTenancyByDomainOrSubdomain` : 
```
'middleware' => [
        'universal',
        InitializeTenancyByDomainOrSubdomain::class,
        'web',
        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],
```

Thanks to @morloderex !

**Comment by asanchez19** [comment]
Hey, I'm trying to do the same thing, the docs are very poor when it comes to install nova. I was wondering if you have any kind of guide? 
Right now I'm getting the ERR_TOO_MANY_REDIRECTS error on my browser when I try to access https://localhost.test/nova/login

Thanks in advance.

**Comment by slimani-dev** [comment]
i'm having the same problem @stancl

**Comment by osaz-delyork** [comment]
> Hey, I'm trying to do the same thing, the docs are very poor when it comes to install nova. I was wondering if you have any kind of guide? Right now I'm getting the ERR_TOO_MANY_REDIRECTS error on my browser when I try to access https://localhost.test/nova/login
> 
> Thanks in advance.

Getting the same Error,  i think this issue should be reopened

**Comment by Mahdi-Sahib** [comment]
Getting the same Error when trying to access In the tenant app

http://foo.localhost/nova

**Comment by isaacdarcilla** [comment]
Same error, getting ERR_TOO_MANY_REDIRECTS

**Comment by DC-Sebastian** [comment]
Unfortunately, I also get the error message ERR_TOO_MANY_REDIRECTS when I follow these instructions https://tenancyforlaravel.com/docs/v3/integrations/nova/

**Comment by stancl** [comment]
Nova is already integrated in this repo, so there's no need to follow that guide.

As for the `ERR_TOO_MANY_REDIRECTS` — that has to be something related to your setup. We regularly use this boilerplate on multiple setups and don't face the issue when following the installation guide step by step.

**Comment by imorad87** [comment]
Any solutions yet? I am facing too many redirects issues when adding universal to nova.middleware and removing it results in an error "Tenant could not be identified on domain localhost" when accessing Nova from the central domain

**Comment by jacklc-1** [comment]
Hi all, I found a fix, as this doesn't seem to be working. I created a new Middleware with the following code:

```php
/**
     * Handle an incoming request.
     *
     * @param  \Closure(\Illuminate\Http\Request): (\Symfony\Component\HttpFoundation\Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        if ($this->isSubdomain($request->getHost())) {
            return app(InitializeTenancyBySubdomain::class)->handle($request, $next);
        }

        return $next($request);
    }

    protected function isSubdomain(string $hostname): bool
    {
        return !in_array($hostname, config('tenancy.central_domains'));
    }
``` 

Then placed that inside the middleware array in nova.php, seems to work
