### ISSUE TITLE
Exclude `www` Subdomain from tenants list

### ISSUE THREAD

**Issue by ousid** [archtechx/tenancy#695]
#### Description
First thanks @stancl  For this awesome package, it's a pretty good one!
When I deployed my application I notice when I access into for example `www.domain-name.tld`,  It shows an error telling you that there's no tenant called `www`.

#### Why this should be added
I searched on the documentation and in some forums, discussions, and we can trick this with some `if statment` in the tenant routes, but I don't think it's the best practice here.

**Comment by stancl** [comment]
What identification middleware do you use and what are the exact hostnames?

**Comment by gregupton** [comment]
I am curious about this myself, what if you wanted to have docs.example.com or support.example.com? Is there a way to blacklist certain subdomains from being created as tenants and exempt them from being routed to the tenant routes?

**Comment by morloderex** [comment]
> I am curious about this myself, what if you wanted to have docs.example.com or support.example.com? Is there a way to blacklist certain subdomains from being created as tenants and exempt them from being routed to the tenant routes?

@gregupton I believe this is an application specific issue you should prevent whatever data you deems invalid for your application from entering your application.

**Comment by ousid** [comment]
@stancl  Everything Set the default, except some Event & Jobs I created for certain functionality in the app.

**Comment by ousid** [comment]
@morloderex Can you, please  give us an example?

**Comment by gregupton** [comment]
> > I am curious about this myself, what if you wanted to have docs.example.com or support.example.com? Is there a way to blacklist certain subdomains from being created as tenants and exempt them from being routed to the tenant routes?
> 
> @gregupton I believe this is an application specific issue you should prevent whatever data you deems invalid for your application from entering your application.

Yes I understand that from the tenant creation side, even if I blocked them from being created with a validation rule, wouldn't the InitializeTenancyByDomain and PreventAccessFromCentralDomains middleware still come into play? 

For instance, if I had a statamic section of my app that I wanted routed to the docs.example.com subdomain, wouldn't the middleware try to initialize a tenant and fail?

**Comment by gregupton** [comment]
> > > I am curious about this myself, what if you wanted to have docs.example.com or support.example.com? Is there a way to blacklist certain subdomains from being created as tenants and exempt them from being routed to the tenant routes?
> > 
> > 
> > @gregupton I believe this is an application specific issue you should prevent whatever data you deems invalid for your application from entering your application.
> 
> Yes I understand that from the tenant creation side, even if I blocked them from being created with a validation rule, wouldn't the InitializeTenancyByDomain and PreventAccessFromCentralDomains middleware still come into play?
> 
> For instance, if I had a statamic section of my app that I wanted routed to the docs.example.com subdomain, wouldn't the middleware try to initialize a tenant and fail?

or am I miss-understanding the route lifecycle?

**Comment by Nischal-shrestha** [comment]
Have you tried configuring the config/tenancy.php ?
In the `"central_domains"` key add your central domains `"yourdomain.tld,www.yourdomain.tld"`
```php

config/tenancy.php

/**
  * The list of domains hosting your central app.
  *
  * Only relevant if you're using the domain or subdomain identification middleware.
  */
  'central_domains' => explode(',','yourdomain.tld,www.yourdomain.tld'),

```

**Comment by Nischal-shrestha** [comment]
> #### Description
> First thanks @stancl For this awesome package, it's a pretty good one!
> When I deployed my application I notice when I access into for example `www.domain-name.tld`, It shows an error telling you that there's no tenant called `www`.
> 
> #### Why this should be added
> I searched on the documentation and in some forums, discussions, and we can trick this with some `if statment` in the tenant routes, but I don't think it's the best practice here.

Have you tried configuring the config/tenancy.php ?
In the `"central_domains"` key add your central domains `"yourdomain.tld,www.yourdomain.tld"`
```php

config/tenancy.php

/**
  * The list of domains hosting your central app.
  *
  * Only relevant if you're using the domain or subdomain identification middleware.
  */
  'central_domains' => explode(',','yourdomain.tld,www.yourdomain.tld'),

```
