### ISSUE TITLE
Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database()

### ISSUE THREAD

**Issue by narendraraghuwanshi** [archtechx/tenancy#698]
#### Describe the bug
Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database()

#### Steps to reproduce
When I want to create new tenant this error occur

#### Your setup
 - Laravel version: [ 8.2.0]
 - stancl/tenancy version: [ 3.1.0]
![image](https://user-images.githubusercontent.com/26792935/128600542-c2fa5b0a-62e8-4eb5-8700-3e41f96ccfec.png)

**Comment by stancl** [comment]
Follow the installation instructions and please use the issue templates correctly

**Comment by narendraraghuwanshi** [comment]
> Follow the installation instructions and please use the issue templates correctly

I Tried Multiple Time But got same Error

**Comment by Elikar-KM** [comment]
> #### Describe the bug
> Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database()
> 
> #### Steps to reproduce
> When I want to create new tenant this error occur
> 
> #### Your setup
> * Laravel version: [ 8.2.0]
> * stancl/tenancy version: [ 3.1.0]
>   ![image](https://user-images.githubusercontent.com/26792935/128600542-c2fa5b0a-62e8-4eb5-8700-3e41f96ccfec.png)

I had the same issue, and it was solved for me by the laravel command : php artisan optimize

**Comment by stancl** [comment]
That's just clearing cache and re-caching everything. Will lead to more issues once code changes again. I'd avoid using code cache in development.
