### ISSUE TITLE
Better tenant-specific assets

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#7]
Code like this is problematic:

```php
public static function productImage($product_id)
{
    return asset("storage/images/products/$product_id.png");
}
```

```php
\Image::make($image)
    ->resize(750, 750, $constraint)//->resizeCanvas(750, 750)
    ->save(storage_path("app/public/images/products/{$product->id}.png"))
    ->resize(300, 300, $constraint)//->resizeCanvas(300, 300)
    ->save(storage_path("app/public/images/products/thumbnails/{$product->id}.png"));
```

But code like this seems to work (= doesn't delete the image, since the code above put it in the wrong directory):

```php
if (\Helper::imageExists($product->id) && $image_deleted) {
    Storage::delete("public/images/products/{$product->id}.png");
    Storage::delete("public/images/products/thumbnails/{$product->id}.png");
}
```

- [x] Try to fix `storage_path()` and `asset()`
    - [x] `app()->useStoragePath(app()->storagePath() . $path)`
    - [x] `app('url')->forceRootUrl(asset('') . $url)`
- [x] <strike>Add a class for global (non-suffixed) Storage (unrelated to this issue, but it might be a useful feature)</strike> #8

**Comment by stancl** [comment]
`storage_path()` is fixed now, but `asset()` is problematic.

```php
asset("storage/images/products/$product_id.png");
```

This shows that any tenant can access any other tenant's files in the public storage. Therefore, a controller is likely necessary. Changing the symlink wouldn't work because there would be issues if two users were connected to two different tenant sites at the same time.

**Comment by tamkeen-tms** [comment]
Using a controller fixes the issue, but consider this: if one of these assets is the tenant's logo, now you require to call that controller also when the logo is requested, which will be at least one time on the page! This means that the whole app will run at least twice, one for the requested controller, and another for the logo itself! Which I think isn't efficient.

My solution is to separate files like this into a global (public) disk, where "logos" (in this scenario) is stored all together, and each tenant's logo is requested by its id.

```php
		/**
		 * @return string
		 */
		public static function logo(){
			return \Storage::disk('app-public')->url('tenants/logos/' . tenant()->id . '.png');
		}
```

What do you think?

**Comment by stancl** [comment]
That's a good point, I'll add something like that to docs.

**Comment by stancl** [comment]
https://github.com/stancl/tenancy-docs/commit/cffbb8d1cb0242ed32db5d19f65d3bc5670dfb71
