### ISSUE TITLE
Problem to use Larave Scout with Meilisearch driver

### ISSUE THREAD

**Issue by ronaldtorrez** [archtechx/tenancy#701]
Hello, I'm using MeiliSearch in Docker and when I try to use "Laravel Scout" with MeiliSearch driver, the data no index in the Tenant.

For example, I'm using a Tenant called "bar" [_id=bar, domain=bar_] . After to install and setting "Laravel Scout", I'm using the **scout:import** command

```
php artisan tenants:run scout:import --tenants=bar --argument="model=App\Models\User" 
```

![Command](https://user-images.githubusercontent.com/60638820/128808329-6c1b1cdb-7e9e-42f3-87fb-f5dd34cb0d8f.png)

> But when I use MeiliSearch UI in browser, the data no exist

![MeiliSearch in Tenant](https://user-images.githubusercontent.com/60638820/128808231-aea3ce7c-205c-4313-b40a-99779168a1fd.png)

> I'm using this setting to "Laravel Scout"

```
SCOUT_DRIVER=meilisearch
SCOUT_QUEUE=true
SCOUT_DELETE=true

MEILISEARCH_HOST=http://localhost:7700
MEILISEARCH_KEY=masterKey
```

> This is my setting to MeiliSearch Docker with Laradock

![Laradock MeiliSearch](https://user-images.githubusercontent.com/60638820/128811097-c3549d1c-9382-4c89-8974-28699b35ad87.png)

When I try to get a search

```
dump(\App\Models\User::search('Whitney')->get());
```
... I have this error

![Error to connection](https://user-images.githubusercontent.com/60638820/128808230-6adc144b-2442-4d1e-8558-6f09a81c94e1.png)

I tried changing the "**MEILISEARCH HOST**" setting to http://bar.localhost:7700

```
MEILISEARCH_HOST=http://bar.localhost:7700
```

... throws me another error

![Error 6](https://user-images.githubusercontent.com/60638820/128812705-e9ff8e99-f7bf-4861-aaa0-fccc07a61992.png)

#### My setup
 - Laravel version: 8.51
 - stancl/tenancy version: 3.4
 - laravel/scout version: 9.2

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks
