### ISSUE TITLE
Fortify Doesn't work with Tenancy Auth not getting user. 

### ISSUE THREAD

**Issue by jeremiahsherrill** [archtechx/tenancy#702]
#### Describe the bug

Setup route middleware with 
`    InitializeTenancyByDomain::class,
    'web',
    'universal',
    'auth',
    'verify',
    PreventAccessFromCentralDomains::class,`

After login,  session data is stored in both the central database and the tenant database, but it is not getting the auth user, returns null.   So if it attempts to visit any route that requires verify, it just redirects back to {tenant}.{domain}/  route as an auth user doesn't exist.  Spent the last couple days on discord, following instruction on there I was able to get registration, and login working great, everything stores, but so far what information on discord is kind of a jumbled mess and nobody can't quite figure out to make fortify work and if they have, they don't post their solution.  

I know this laravel fortify issue has been talked about, and everyone always gets sent to discord, but since there is no set answer in discord we need to address this here.  Fortify is integral part of the Laravel ecosystem.   If we can't get this working correctly, what other auth system can we use that just works with tenancy.  A multi-tenant system that doesn't auth, kind of pointless.  

#### Steps to reproduce
Install laravel/fortify
Install Tenancy
Setup tenant routes
Make sure to 

use Stancl\Tenancy\Middleware\InitializeTenancyByDomain;
use Stancl\Tenancy\Middleware\PreventAccessFromCentralDomains;

in the proper locations

#### Expected behavior
I create the tenant in the backend of the central app, create a default user, user points their domain to {tenant}.{domain}/myadmin and they are presented with a login screen that logs them in to their admin.   

#### Your setup
 - Laravel version: [e.g. 8.4.7]
 - stancl/tenancy version: [e.g. 3.4.^]

**Comment by stancl** [comment]
> I know this laravel fortify issue has been talked about, and everyone always gets sent to discord, but since there is no set answer in discord we need to address this here. Fortify is integral part of the Laravel ecosystem.

This is not a bug, a bug would be something that works differently than described in the docs.

The issue with Fortify is that [it uses constructor DI](https://github.com/search?q=__construct+repo%3Alaravel%2Ffortify+path%3Asrc%2FHttp%2FControllers&type=Code&ref=advsearch&l=&l=) which the [docs say isn't supported](https://tenancyforlaravel.com/docs/v3/early-identification/#not-using-constructor-di).

In version 4 I might try to find a way to improve this, but currently everything is working as described, so this is still a support question.

You can try opening a PR in laravel/fortify to change all instances of controller constructor DI to route action DI. I don't think Fortify should have to change this to support other packages, but practically it's just a few lines of code so they might be open to it for better compatibility with the ecosystem.

> If we can't get this working correctly, what other auth system can we use that just works with tenancy.

There are many auth systems. laravel/ui, Breeze, Jetstream, and many more. The first two should work with tenancy perfectly.

> A multi-tenant system that doesn't auth, kind of pointless.

Nothing's stopping you from using auth. You just can't use constructor DI or packages that use constructor DI.

I personally wouldn't be using packages for this, I'd just make a simple Livewire component and implement auth as needed for each project individually.

**Comment by jhoopes** [comment]
Hey @stancl , yep, this is an issue with the constructor DI:

For anyone else, because we use the domain/subdomain tenancy initialization with sanctum and fortify, this is what we did to get around this issue for now.

Basically just need to override how Fortify binds the `StatefulGuard` class into the container through its own register function.


```php
<?php declare(strict_types=1);

namespace App\Providers;

use Illuminate\Contracts\Auth\StatefulGuard;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Laravel\Fortify\Fortify;
use Illuminate\Support\ServiceProvider;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Support\Facades\RateLimiter;
use Stancl\Tenancy\Exceptions\NotASubdomainException;
use Stancl\Tenancy\Resolvers\DomainTenantResolver;
use Stancl\Tenancy\Tenancy;
use Exception;

class FortifyServiceProvider extends ServiceProvider
{

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(StatefulGuard::class, function () {
            /** @var Request $request */
            $request = app('request');

            $tenantDomain = $request->getHost();
            if ($this->isSubdomain($request->getHost())) {
                $tenantDomain = $this->makeSubdomain($request->getHost());

                if($tenantDomain instanceof Exception) {
                    throw $tenantDomain;
                }
            }

            /** @var Tenancy $tenancy */
            $tenancy = app(Tenancy::class);
            /** @var DomainTenantResolver $tenantResolver */
            $tenantResolver = app(DomainTenantResolver::class);


            if($tenancy->initialized) {
                return Auth::guard(config('fortify.guard', null));
            }

            $tenancy->initialize(
                $tenantResolver->resolve(
                    $tenantDomain
                )
            );

            return Auth::guard(config('fortify.guard', null));
        });
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        // usual fortify overrides
    }


    /** Copy tenancy functions for usage with building fortify guard */

    /**
     * The index of the subdomain fragment in the hostname
     * split by `.`. 0 for first fragment, 1 if you prefix
     * your subdomain fragments with `www`.
     *
     * @var int
     */
    public static int $subdomainIndex = 0;


    protected function isSubdomain(string $hostname): bool
    {
        return Str::endsWith($hostname, config('tenancy.central_domains'));
    }

    /** @return Exception|string */
    protected function makeSubdomain(string $hostname)
    {
        $parts = explode('.', $hostname);

        $isLocalhost = count($parts) === 1;
        $isIpAddress = count(array_filter($parts, 'is_numeric')) === count($parts);

        // If we're on localhost or an IP address, then we're not visiting a subdomain.
        $isACentralDomain = in_array($hostname, config('tenancy.central_domains'), true);
        $notADomain = $isLocalhost || $isIpAddress;
        $thirdPartyDomain = ! Str::endsWith($hostname, config('tenancy.central_domains'));

        if ($isACentralDomain || $notADomain || $thirdPartyDomain) {
            return new NotASubdomainException($hostname);
        }

        return $parts[static::$subdomainIndex];
    }
}

```

Because some of the tenant resolving and domain resolving code isn't available to be called outside of their own respective classes, some of that code was copied into here.  This doesn't feel the greatest, but, it is only generally called first when Fortify is building it's controller constructors.  If tenancy is already initialized, it just continues on building up the guard without re-initializing.  

Not sure if there's a better way other than modifying how Laravel's first party packages are doing things, but this at least makes it work on the sanctum, fortify side.


Edit:  I should also note that this code is not accounting for 'universal' routes, so it's essentially binding fortify routes that build the statefull guard with DI to the tenant context vs the central one.  So, another solution of sorts would need to be worked out if the fortify routes are needed in both central and tenant

**Comment by stancl** [comment]
Thanks a lot for sharing that @jhoopes. I wanted to write the usual explanation of why this is an issue with route level MW and that global MW solves this (but doesn't work well with non-domain identification), but I realized that in v4 it'd probably be best to add our own way of affecting the app. Something like middleware, but implemented a bit differently.

Basically we want to hook between routing and route action instantiation (controller constructor DI) and run tenancy there. I'll check the routing lifecycle in the Laravel codebase and find a way to implement this.

**Comment by matt-breeden** [comment]
I know this is closed, and don't expect anything from you until version 4 (crosses fingers), but I've been playing around and trying to get API auth to work with Sanctum and Tenancy. I noticed this in Laravel\Sanctum\SanctumServiceProvider  and I wonder if it's the cause of a lot of these headaches:

`        $kernel->prependToMiddlewarePriority(EnsureFrontendRequestsAreStateful::class);
`

**Comment by sicaboy** [comment]
Thanks @jhoopes Do we have an official solution for this? 
When `StatefulGuard` DI is in any controller's  `__construct`, it is reading session from central, even though the route is under tenant middleware.

**Comment by stancl** [comment]
The issue is pretty much what's described on the Early Identification page of v3 docs. We're in the process of finishing the early identification logic in the upcoming v4 version.

**Comment by freziertz** [comment]
Is there any schedule for version 4 release?

**Comment by yusufkaracaburun** [comment]
When can we expect version 4?

**Comment by stancl** [comment]
It's been mostly stable for a few months, we're working on adding some final features now. Hope to have everything done within Q1.

**Comment by yusufkaracaburun** [comment]
Is it possible get early access, because I really need it? I can always update it with the new features.

**Comment by stancl** [comment]
Yes, early access has been available for a long time. See the [announcement](https://discord.com/channels/976506366502006874/976506996201230416/1047644771587469312) on [our Discord](https://archte.ch/discord) (you need to join first for the announcement link to work).

**Comment by tahseen9** [comment]
TenancyServiceProvider should be loaded before fortify and jetstream

bootstrap/providers.php  (This file is automatically generated by Laravel, just change the sequence as below) 
return [
    App\Providers\TenancyServiceProvider::class,
    App\Providers\AppServiceProvider::class,
    App\Providers\FortifyServiceProvider::class,
    App\Providers\JetstreamServiceProvider::class,
];

I am using laravel 11.x with stancl/tenancy 3.8.3

**Comment by sicaboy** [comment]
@tahseen9 thanks, but modifying an auto-generated file is not an option for anyone

**Comment by stancl** [comment]
In L11 those files aren't autogenerated and can be modified (this was a bit unclear in early L11 iirc). Either way, v3 doesn't properly support Jetstream/Fortify.

**Comment by tahseen9** [comment]
You are right, I had to do another change to run it properly, but i am not sure where its gonna break next.

according to L11 doc I did change the sequence

![image](https://github.com/archtechx/tenancy/assets/108788946/957312f2-8daf-4158-b172-ed8eb32ee17f)

bootstrap/providers.php (This file is automatically generated by Laravel, just change the sequence as below)
return [
App\Providers\TenancyServiceProvider::class,
App\Providers\AppServiceProvider::class,
App\Providers\FortifyServiceProvider::class,
App\Providers\JetstreamServiceProvider::class,
];

and in my app service providers boot method:

public function boot(): void
    {
        $domainIsTenant = (new Domain)->where('domain', \request()->getHost());

        if($domainIsTenant->exists()){
            $tenancy = app(Tenancy::class);
            $tenantResolver = app(DomainTenantResolver::class);
            $tenancy->initialize(
                $tenantResolver->resolve(
                    \request()->getHost()
                )
            );
        }
    }

With this i am able to get the right db connection injected in Database Session Handler

![image](https://github.com/archtechx/tenancy/assets/108788946/252214ab-12e5-4a17-838c-342647c05df1)

**Comment by MuhammadSulman** [comment]
I performed the above actions but did not work for me. facing the same issue, login works correctly as soon as I click further link then get the error, DB is not correct. 

Laravel version 10, inertia JS, vite and react js.

**Comment by SuperDJ** [comment]
https://github.com/archtechx/tenancy/issues/564 is related

**Comment by SuperDJ** [comment]
@stancl are there any updates on using Fortify with this package? I'm noticing several issues with this combination and so far none of the above solutions has helped. 

Issues:
- When logging in the user of the central database is used where the ID matches that of the user in a tenant;
- When requesting a password reset a tenant email is not found;

Solutions that didn't help:
- Changing the order of [*ServiceProviders](https://github.com/archtechx/tenancy/issues/702#issuecomment-2119005925);
- Changing the [FortifyServiceProvider](https://github.com/archtechx/tenancy/issues/702#issuecomment-914438547) `register` method, and adding `dd( resolve( StatefulGuard::class ) );` after the change will result in a `Target class [cache] does not exist.` error;
- Changing the [AppServiceProvider](https://github.com/archtechx/tenancy/issues/702#issuecomment-2119637543) `boot` method, will thrown an error for not finding routes;
- Changing the Fortify config [middleware](https://github.com/archtechx/tenancy/issues/496#issuecomment-808938508);

Or is it possible to use the [`Bootstrappers\Integrations\FortifyRouteBootstrapper::class`](https://tenancy-v4.pages.dev/configuration/#bootstrappers-section) from v4 in v3 unfortunately I can't find it in the the [master](https://github.com/archtechx/tenancy/tree/master/src/Bootstrappers/Integrations) branch.

**Comment by joepages** [comment]
I have successfully managed to implement Fortify ( * v1.24.5
)  and Tenancy ( stancl/tenancy": "^3.8) with this thanks to @jhoopes  comment and suggestion: 

```
<?php

namespace App\Providers;

use App\Actions\Fortify\CreateNewUser;
use App\Actions\Fortify\ResetUserPassword;
use App\Actions\Fortify\UpdateUserPassword;
use App\Actions\Fortify\UpdateUserProfileInformation;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Contracts\Auth\StatefulGuard;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Str;
use Laravel\Fortify\Fortify;
use Stancl\Tenancy\Tenancy;
use Stancl\Tenancy\Resolvers\DomainTenantResolver;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class FortifyServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        $this->app->bind(StatefulGuard::class, function () {
            /** @var Request $request */
            $request = app('request');
            $host = $request->getHost();

            // If we're on the central domain, return the default guard
            if (in_array($host, config('tenancy.central_domains'))) {
                return Auth::guard(config('fortify.guard', null));
            }

            // If tenancy is already initialized, return the guard
            /** @var Tenancy $tenancy */
            $tenancy = app(Tenancy::class);
            if ($tenancy->initialized) {
                return Auth::guard(config('fortify.guard', null));
            }

            try {
                // Initialize tenancy for tenant domain
                /** @var DomainTenantResolver $tenantResolver */
                $tenantResolver = app(DomainTenantResolver::class);
                $tenant = $tenantResolver->resolve($host);

                if ($tenant) {
                    $tenancy->initialize($tenant);
                }

                return Auth::guard(config('fortify.guard', null));
            } catch (\Exception $e) {
                Log::error('Fortify tenant resolution failed', [
                    'host' => $host,
                    'error' => $e->getMessage()
                ]);

                // Fallback to default guard if tenant resolution fails
                return Auth::guard(config('fortify.guard', null));
            }
        });
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Fortify::createUsersUsing(CreateNewUser::class);
        Fortify::updateUserProfileInformationUsing(UpdateUserProfileInformation::class);
        Fortify::updateUserPasswordsUsing(UpdateUserPassword::class);
        Fortify::resetUserPasswordsUsing(ResetUserPassword::class);

        RateLimiter::for('login', function (Request $request) {
            $throttleKey = Str::transliterate(Str::lower($request->input(Fortify::username())) . '|' . $request->ip());
            return Limit::perMinute(5)->by($throttleKey);
        });

        RateLimiter::for('two-factor', function (Request $request) {
            return Limit::perMinute(5)->by($request->session()->get('login.id'));
        });
    }
}
```

**Comment by claudio-pandolfi** [comment]
Hi everyone

The Fortify routes isn`t declare in the files in your app and don`t use the same middleware configured. The Tenancy needs to inicialize and needs to include some middlewares.

A simple solution, that worked for me, was add the Tenancy`s middlewares in the Fortify config file.

Open the `config/fortify.php` file and replace the line:

```
'middleware' => ['web', InitializeTenancyByDomain::class, PreventAccessFromCentralDomains::class],
```

Don`t forget to add the classes at the begin of file:


```
use Stancl\Tenancy\Middleware\InitializeTenancyByDomain;
use Stancl\Tenancy\Middleware\PreventAccessFromCentralDomains;
```

**Comment by hemant17** [comment]
thanks @claudio-pandolfi  you saved my hours
