### ISSUE TITLE
HasDomains trait doesn't use the Global tenantIdColumn

### ISSUE THREAD

**Issue by JohnRoux** [archtechx/tenancy#708]
#### Describe the bug
https://tenancyforlaravel.com/docs/v3/single-database-tenancy/#customizing-the-column-name

Those docs show how you can set your own custom tenantIdColumn

But the HasDomains trait doesn't look for that column name, it only looks for `tenant_id`
This means that anyone who wants to have a custom tenant ID column both needs to override the BelongsToMany variable and also make their own HasDomains trait

Following from the design pattern in the BelongsToTenant trait, it would be good to also have a public static variable in the HasDomains model.

Such that then the override in the docs can simply be to add both
` BelongsToTenant::$tenantIdColumn = 'custom_id';
and 
` HasDomains::$tenantIdColumn = 'custom_id';`
to the service provider.

#### Expected behavior
Consistent overrides for the $tenantIdColumn property on the HasDomains Trait

#### Your setup
 - Laravel version: 8.40
 - stancl/tenancy version: 3.4

**Comment by JohnRoux** [comment]
Example of the change requested (Sorry, this should really be a PR)
```
trait HasDomains
{
    public static $tenantIdColumn = 'tenant_id';

    public function domains()
    {
        return $this->hasMany(config('tenancy.domain_model'), HasDomains::$tenantIdColumn);
    }

    public function createDomain($data): Domain
    {
        $class = config('tenancy.domain_model');

        if (! is_array($data)) {
            $data = ['domain' => $data];
        }

        $domain = (new $class)->fill($data);
        $domain->tenant()->associate($this);
        $domain->save();

        return $domain;
    }
}

```

**Comment by JohnRoux** [comment]
One could instead do it in the Domain model, since that would also have to change actually.
Not suuuper clean:

```public function tenant()
    {
        return $this->belongsTo(config('tenancy.tenant_model'), HasDomains::$tenantIdColumn);
    }
```

**Comment by stancl** [comment]
This is not a bug.

You linked to https://tenancyforlaravel.com/docs/v3/single-database-tenancy/#customizing-the-column-name which relates to **single database tenancy**. Database setup and tenant identification are separate things.

> But the HasDomains trait doesn't look for that column name, it only looks for tenant_id
This means that anyone who wants to have a custom tenant ID column both needs to override the BelongsToMany variable and also make their own HasDomains trait

Why do they need to make their own trait? The trait contains:

```php
public function domains()
{
    return $this->hasMany(config('tenancy.domain_model'), 'tenant_id');
}
```

The developer can simply override this method. It's much more straightforward than adding static properties.
