### ISSUE TITLE
Running command in tenancy->run returns null

### ISSUE THREAD

**Issue by allestaire** [archtechx/tenancy#711]
#### Describe the bug
The `$tenancy->run()` executed properly but when I tried to run command or querying it does not return any, instead it still uses the central databases.

#### Steps to reproduce
1. `php artisan tinker`
2. `Tenant::first()->run(function () { User::all(); })`

#### Expected behavior
Running command inside `tenancy->run` should return results that is available on the tenant database.

#### Your setup
 - Laravel version: 7
 - stancl/tenancy version: 3

**Comment by stancl** [comment]
Can you provide more context? This seems like a usage issue.

**Comment by ccchapman** [comment]
You can use [manual initialization](https://tenancyforlaravel.com/docs/v3/manual-initialization/#manual-initialization) inside Tinker instead.
