### ISSUE TITLE
Integrating with artesaos/seotools package

### ISSUE THREAD

**Issue by thanhtoan1196** [archtechx/tenancy#713]
#### Description
Integrating with artesaos/seotools package.

#### Why this should be added
To optimize SEO for multi-tenant web.

**Comment by stancl** [comment]
Please use more detail when opening feature requests. If you can explain well what should be done to support this, in what way is it not supported yet, and exactly why this package should be a focus, I'll reopen.

**Comment by KatiaSishost** [comment]
Hi, @thanhtoan1196  it's easy... use for example:

use Artesaos\SEOTools\Facades\SEOMeta;

$data=WebsiteSetting::select('site_title','site_logo','site_description','theme')->where('id', 1)->get();

foreach($data as $dat)
        {
            Theme::uses($dat->theme);
            SEOMeta::setTitle($dat->site_title);
            SEOMeta::setDescription($dat->site_description);
            SEOMeta::setCanonical($request->getHost());
            SEOMeta::addKeyword(['key1', 'key2', 'key3']);
            SEOMeta::addMeta('article:section', 'asd', 'property');
    
        }

u need a table in your database with this data... this load when u enter to site... and save it in cache view.

**Comment by thanhtoan1196** [comment]
ok, thanks
