### ISSUE TITLE
Share session value between central app & tenants #712

### ISSUE THREAD

**Issue by ousid** [archtechx/tenancy#714]
I'm building an app using @stancl  Multi tenancy package with multiple languages, but I notice.

When I store a session value (Lang value for instance) it does not take effect in the tenants and returns a `null` value, but in the central does.

Is there's any idea on how to store session values on the tenant domains?

## Steps to Produce

```php
# Tenant
session()->put('lang', 'fr');
dd(session('lang');
// output: null;

# Central
session()->put('lang', 'fr');
dd(session('lang');
// output: fr
```

#### Your setup
 - Laravel version: [e.g. 8.4.0]
 - stancl/tenancy version: [e.g. 3.4.0]

**Comment by stancl** [comment]
```php
>>> $tenant = App\Models\Tenant::create()
=> App\Models\Tenant {#3504
     id: "78e87ff6-dc4b-416a-a4d8-2d015c8390f4",
     updated_at: "2021-09-02 20:34:05",
     created_at: "2021-09-02 20:34:05",
     data: null,
   }
>>> session()->put('foo', 'bar')
=> null
>>> session('foo')
=> "bar"
>>> tenancy()->initialize($tenant)
=> null
>>> session()->put('abc', 'def')
=> null
>>> session('abc')
=> "def"
```

Sessions themselves work. If this is related to a specific setup, please provide more context and reproduction steps that actually reproduce the issue.

**Comment by ousid** [comment]
Hey, @stancl 

Sorry to not provide the full implementation.

I'm trying to make my app `multi-language` and this seems to not going to work on tenant domains.

##  Steps to Produce

In the `route` file, I make shared file for both tenants & central domain:

```php
/....
Route::get('lang/switch/{lang}', LanguageController::class)
   ->name('language.switcher');
/....
```

In the `Language Controller`

```php
class LanguageController extends Controller
{
    public function __invoke($lang, Request $request)
    {
        $languages = ['en', 'fr'];

        if (in_array($lang, $languages)) {

            $locale = session()->put('lang', $lang);

            App::setLocale(session('lang') ?? 'fr');

        }

        return back(302);
    }
}
```
I created a `middleware` to determine if there is a session or not with the tenant existence

```php
    public function handle(Request $request, Closure $next)
    {

        $subdomain = Arr::first(explode('.', $request->getHost()));

        if (
            $tenant = tenancy()->find(strtolower($subdomain))
        ) {
            tenancy()->initialize($tenant);
        }

        $this->switchLanguage();

        return $next($request);
    }

    private function switchLanguage()
    {
        if (session()->has('lang')) {
            app()->setLocale(session()->get('lang'));
        }

        if (!session()->has('lang')) {
            app()->setLocale(config('app.locale'));
            session()->put('lang', config('app.locale'));
        }
    }
```

## The Problem
Let's say you accessed `https://domain.ltd/lang/switch/fr` to get the French version, and in the `central domain` this process working nicely, but in the `tenants` I can see the value of the `session`but the `local` seems it has no change.

Hope this make sense.
