### ISSUE TITLE
Skip creating tenant database if already exists

### ISSUE THREAD

**Issue by kyleferguson** [archtechx/tenancy#716]
We have a use case where we only want the database to be created if it doesn't already exist. For production there's an ops process that bootstraps everything for a particular deployment of the app. Kind of weird and probably fringe case but it's essentially a multi-tenant deployment of the multi-tenant Laravel app.

In that environment we don't want to give each individual deployment permissions to create databases on a shared instance so they're made beforehand along with locked down user grants. We've just modified our own database manager to add `IF NOT EXISTS` on `createDatabase`, but was wondering if you'd be open to a PR adding this to the default managers?

Thanks for the package, works great!

**Comment by stancl** [comment]
https://github.com/archtechx/tenancy/blob/54a33f93a85a5e0a4d53ac48fabacd8ebb716eec/src/Jobs/CreateDatabase.php#L35

You can set the `tenancy_create_database` attribute to `false` if the DB already exists (based on some check of yours)

**Comment by kyleferguson** [comment]
Even better, thanks!
