### ISSUE TITLE
Creating a new model on a tenant with resource syncing can cause a duplicate entry error

### ISSUE THREAD

**Issue by chillbram** [archtechx/tenancy#717]
I'm using resource syncing on my User model and when creating a new User from a tenant it will sometimes throw the following error `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2' for key 'central_users.PRIMARY' (SQL: insert into 'central_users' ('name', 'email', 'password', 'global_id', 'id') values (test, test@test.com, asdasdasd, ee2bab73-708e-486b-b715-91909b0c0b5c, 2))`

Because I use a regular incrementing id and not the global_id as the primary key for the User and CentralUser databases, Tenancy also tries to sync the primary key when creating a new Central instance from a new tenant model. 

The following code causes the problem, because it tries to sync all model attributes regardless of the columns put into `User::getSyncedAttributeNames()`: https://github.com/archtechx/tenancy/blob/3.x/src/Listeners/UpdateSyncedResource.php#L61-L63.

#### Your setup
 - Laravel version: 8.59
 - stancl/tenancy version: 3.4.4

**Comment by stancl** [comment]
Isn't there an issue already open for this?

**Comment by chillbram** [comment]
I couldn't find an issue or PR. There have been multiple reports of this bug on the Discord though, but none with a fix/solution

**Comment by stancl** [comment]
Maybe #658 is similar? Just want to keep things tidy for when I get to working on the v4

**Comment by chillbram** [comment]
Ah yes, different error but the same issue. The current code forces the SyncMaster to have all columns that the Syncable model has as well, which causes a problem when using tenant-specific columns as well as when using a non-uuid primary key. Feel free to close this issue if you want to keep everything in #658

**Comment by stancl** [comment]
Cool, I'll see that this was mentioned so I'll read both issues when fixing this. Thanks!
