### ISSUE TITLE
Ensure Laravel Vapor is supported

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#74]

**Comment by drfraker** [comment]
I'm building an app now for which I plan to use this pacakge and Laravel Vapor. I'll let you know if we run into any issues and submit PR's whenever possible.

**Comment by stancl** [comment]
@drfraker

Thanks a lot! I really appreciate it.

Few things regarding Vapor:
- I did some work to ensure that the asset URL is injected properly, but I haven't tested it, since I don't have a Vapor subscription. Should be OK though.
- Just a heads up: Multiple second level domains are not supported and when I reached out to Vapor support, they responded with: "we have no plans for it at the moment."

**Comment by drfraker** [comment]
>  Multiple second level domains are not supported

To make sure I'm clear on this. That means we can't do something like acme.app.example.com, right?

**Comment by stancl** [comment]
You can have an (I think) unlimited amount of subdomains on *your* domain, so `client1.yourapp.com`, but you can't use multiple second level domains (`yourapp.client1.com`).

**Comment by drfraker** [comment]
I have recently deployed my app to staging on Laravel Vapor. Other than a few issues around the asset helper everything seems to be working well. I'll add notes here if I run into anything tricky or impossible, but so far it looks really promising and straightforward.

**Comment by stancl** [comment]
Thanks for letting me know, I appreciate it.

> a few issues around the asset helper

Is there anything I can do to make the package handle this better?

**Comment by stancl** [comment]
BTW It's worth mentioning, for those unaware, that you can now have unlimited second level domains on Vapor projects. But I think there is a limit of SSL certificates per load balancer, so that's something you need to deal with.

**Comment by JGamboa** [comment]
@drfraker  did you have problem with the queue and cli ? were they tenant aware?

**Comment by simonmaass** [comment]
@drfraker a quick question... are you able to sub-subdomain on vapor?

like:
next.service-name.domain.com
test.service-name.domain.com

**Comment by drfraker** [comment]
> @drfraker a quick question... are you able to sub-subdomain on vapor?
> 
> like:
> next.service-name.domain.com
> test.service-name.domain.com

I have not tried this.

**Comment by drfraker** [comment]
@JGamboa
> @drfraker did you have problem with the queue and cli ? were they tenant aware?

I am not having a problem with queues or cli. Seem to be working fine. Debugging is a bit hard, you'll def. want telescope and a bug tracker like Flare or Bugsnag. I am using a jumpbox and table plus to view databases as well as medis to view redis cache stuff.

**Comment by devoncmather** [comment]
I've been using this package on Vapor for over a month now without any specific issues related to this package. I think this issue could be closed ✌🏻

**Comment by stancl** [comment]
Fair point, thanks everyone for the feedback. Closing :)

**Comment by isaackearl** [comment]
@stancl I realize this is closed,

But I'm trying to deploy to laravel vapor and I'm having issues with assets, as well as Livewire loading... Should I make a new issue to track problems/solutions?

**Comment by stancl** [comment]
@isaackearl If you have support questions, the Discord server is the ideal place to ask.

**Comment by lovecoding-git** [comment]
@devoncmather 
Did you solve SSL issue too for custom domain?
