### ISSUE TITLE
Add a class for global (non-suffixed) Storage

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#8]
TODO: Add some method/class that would use the config stored in this variable:

https://github.com/stancl/tenancy/blob/6473806d0de4c8b1f10e781a814e78dce4d46761/src/Traits/BootstrapsTenancy.php#L7

**Comment by stancl** [comment]
Creating a disk and not putting it in `tenancy.filesystem.disks` config can be used to achieve this.

**Comment by genesiscz** [comment]
This is still a real need in 2026. We ended up building exactly what this issue describes — a `CacheService` with `getGlobally()`/`putGlobally()`/`rememberGlobally()` methods that use `app('cache.store')` to bypass the tenant-aware `CacheManager`.

The problem surfaces heavily with queue workers + Telescope + Horizon: any `Cache::` or `cache()` call outside tenant context crashes with `getTenantKey() on null` (see #870, which keeps getting new comments despite being closed).

Having an official `GlobalCache` or `CentralCache` facade/helper in the package would save every user from building this workaround independently.

**Comment by stancl** [comment]
@genesiscz I don't understand your comment here. I see a seemingly reasonable report here https://github.com/archtechx/tenancy/issues/870#issuecomment-3995362224 but I don't understand the crossposts across the other threads.

What's the relation between our *Storage disk* prefixing logic and `CacheManager`?

And what do you mean by "This is still a real need in 2026"? My comment above says how to achieve what this issue talks about.
