### ISSUE TITLE
Let the user to set the database name

### ISSUE THREAD

**Issue by carlos-mora** [archtechx/tenancy#84]
by including the name as an optional argument in the create() call. If it is not set, it should be solved as usual (prefix + uuid + sufix)

**Comment by stancl** [comment]
Sounds useful.

I'm not sure if this is possible with the current API of TenantManager, I'll take a look at it.

A good implementation of this in v2 could be to let developers set tenant data in `TenantManager::create()`, like this:

```php
tenant()->create('example.com', [
    'database' => 'example_com',
    'plan' => 'free'
]);
```

**Comment by carlos-mora** [comment]
As you said, it should be included in the create() method of TenantManager,
because it is creating the database immediatly. Given the significance of
the field, I would promote it to a field.
I think it will suffice to change the TenantManager:getDatabaseName()
method.

**Comment by stancl** [comment]
The issue with doing that in v1 is that it's kind of a breaking change, because I would be changing the `create()` method's signature.

TenantManager is bound into the service container by its class name. I'll check if the package's users can override the instance.

**Comment by stancl** [comment]
I added this to the 1.7.0 milestone. If this is not possible in 1.x, I'll change the milestone to 2.0.0.
