### ISSUE TITLE
Issue w/ redis->scan() in getAllTenants logic.

### ISSUE THREAD

**Issue by Mbein03** [archtechx/tenancy#96]
I've noticed an issue w/ the logic in the getAllTenants() function inside of RedisStorageDriver.php. It has to do w/ the redis->scan() function. It results in an error w/ "php artisan tenant:list". After there are more than five tenants in the system, the command often becomes unreliable, as it does not always return the total number of tenants in the system. I've tried substituting keys() for scan(), which fixes the problem, but I realize that is not a viable solution for production. I have temporarily fixed the issue by inserting "10000" as the third parameter in the scan() function - 

$all_keys = $this->redis->scan(null, $redis_prefix . 'tenants:*', 10000);

I know that is a bit hacky, so I wanted to bring this to your attention, and see if you had any thoughts/ideas.

**Comment by stancl** [comment]
Hi.

Thanks for reporting this. Are you using predis or phpredis?

`scan()` is a bit problematic, see this thread: https://github.com/laravel/ideas/issues/1756

**Comment by Mbein03** [comment]
Using phpredis, as I thought is was required for the package to work properly (Note: You must use phpredis if you want mutli-tenant Redis...).

**Comment by stancl** [comment]
Right. Originally only phpredis was supported but I added support for predis if you don't need multi-tenant Redis in your application code and just need Redis to store the tenant data.

`scan` apparently also [accepts a count option](https://redis.io/commands/scan#the-count-option). I'll see if there's anything wrong with just using a huge number for this, like you did.

Thanks.

**Comment by Mbein03** [comment]
Thanks so much for the quick response!

**Comment by stancl** [comment]
I would normally make a bugfix release as I already fixed another bug, but I also added a ton of new features so I'll add this to the 1.7.0 feature release. Should be released in less than a week. You can keep this replaced in the vendor files and the next time you run `composer update`, just do `y` on `The package has modified files. Discard changes [y,n,v,s,?]?`

**Comment by Mbein03** [comment]
Sounds good, thanks again for the help!

**Comment by stancl** [comment]
Using `scan` instead of `keys` is considered a best practice, but [apparently](https://stackoverflow.com/questions/32603964/scan-vs-keys-performance-in-redis) the only difference is that `scan` lets you use chunking, whereas `keys` just returns everything at once.

Redis docs on `keys`:

> **Warning:** consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using SCAN or sets.

I don't think anyone is going to have a million tenants, so for now, I'll just change `scan` to `keys`.

I might implement some chunking logic at some point in the future.

**Comment by Mbein03** [comment]
Yeah, I did similar research on KEYS versus SCAN, and several threads I was browsing warned against using it b/c it may cause performance issues (https://stackoverflow.com/questions/32603964/scan-vs-keys-performance-in-redis). I'm very unfamiliar w/ Redis, so I thought it best to pass along the info.

**Comment by stancl** [comment]
The performance issues come from the fact that Redis is single-threaded and the `KEYS` operation can take a long time in some cases, so it would block all other requests. Whereas with `SCAN` you can get the first chunk, let Redis process other requests in queue, and ask for the next chunk.
